objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cvent_Account_ID__c</fullName>
        <description>Please separate account id's by ;</description>
        <label>NA Cvent Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <formula>Account.Id</formula>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cvent_Account_ID__c</fullName>
        <formula>Account.Cvent_Account_ID__c</formula>
        <label>NA Cvent Account ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Id__c.object
<CustomObject>
    <description>This will store the Id of the Contact which needs to be deleted according to the criteria.</description>
    <label>Contact Id</label>
    <nameField>
        <displayFormat>Con-{0000000}</displayFormat>
        <label>Contact Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Ids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>Text Field -18 digit id the account associated with the contact</description>
        <label>Account ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <description>Text Field - 18 digit id of the contact associated with user (#11123550)</description>
        <label>Contact ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PreChatFormControllerTest.cls
@IsTest
public class PreChatFormControllerTest
{
    static testMethod void myUnitTestFirst()
    {
        Account instofAcc = TestUtil.createAccount('Test Account','Biz_Ac');
        instofAcc.Cvent_Account_ID__c = 'NBAK12';
        insert instofAcc;
        Contact instOfCon = TestUtil.createContact(String.valueOf(instofAcc.Id));
        instOfCon.Phone = '1241142534';
        insert instOfCon;
        
        User instUsr = TestUtil.CreateDeploymentUser();
        instUsr.Account_ID__c = instofAcc.Id;
        instUsr.Contact_ID__c = instOfCon.Id;
        insert instUsr;
        
        system.runAs(instUsr)
        {
            PreChatFormController pre = new PreChatFormController();
        }
    }

}