objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_ARA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>All changes on this field should be approved by ARA Team #11203260</description>
        <inlineHelpText>Indicates active At Risk Account (ARA)</inlineHelpText>
        <label>Active ARA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <formula>Year(Today())</formula>
        <label>Current Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Prospect Lead</fullName>
                </value>
                <value>
                    <fullName>Fit Lead</fullName>
                </value>
                <value>
                    <fullName>Active Lead</fullName>
                </value>
                <value>
                    <fullName>Passive Win</fullName>
                </value>
                <value>
                    <fullName>Imp Win</fullName>
                </value>
                <value>
                    <fullName>Live Win</fullName>
                </value>
                <value>
                    <fullName>End Business</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/ARA__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ARAs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Associate this ARA to the largest renewal opportunity of those at risk, if renewal is less than 365 days out, otherwise leave blank.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>ARAs/Escalations</relationshipLabel>
        <relationshipName>ARAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Positive Progress</fullName>
                </value>
                <value>
                    <fullName>Negative Progress</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Escalated (to VP/Executive level)</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>On Ice</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Pending</fullName>
                </value>
                <value>
                    <fullName>Closed Lost - Pending</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed-Resolved</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Closed-Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ARA/Escalation</label>
    <nameField>
        <displayFormat>ARA/E-{000000}</displayFormat>
        <label>ARA/Escalation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ARAs/Escalations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EB_Agent_Profile__c.object
<CustomObject>
    <label>EB/CC Agent Profile</label>
    <nameField>
        <label>EB Agent Profile</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EB/CC Agent Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>CrowdCompass</fullName>
        <active>true</active>
        <label>CrowdCompass</label>
    </recordTypes>
</CustomObject>

objects/Implementation_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementation Surveys</relationshipLabel>
        <relationshipName>Implementation_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implementation Surveys</relationshipLabel>
        <relationshipName>Implementation_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Did_this_deal_use_the_Mid_Year_Promo__c</fullName>
        <inlineHelpText>Please check this box if this deal included 10-20% off, a free EB or ABP, and/or 50% off Cvent CONNECT registration as part of the official Mid-Year Promotion</inlineHelpText>
        <label>Did this deal use the Mid-Year Promo?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Mobile_Event_Date__c</fullName>
        <label>First Mobile Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Mobile_Event_Launch_Date__c</fullName>
        <label>First Mobile Event Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>K_has_mult_Bill_to_or_Ship_to_addresses__c</fullName>
        <inlineHelpText>Does this contract have multiple bill-to or ship-to addresses? 
If Yes, you are required to attach the excel file outlining the different bill-to or ship-to addresses on this implementation survey record within the notes &amp; attachments.</inlineHelpText>
        <label>Multiple Bill To/Ship To?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile_Delivery_Date__c</fullName>
        <label>Mobile Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AttendeeHub</fullName>
                </value>
                <value>
                    <fullName>Self-Publishing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Implementation Surveys</relationshipLabel>
        <relationshipName>Implementation_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This identifies the person who will be receiving the welcome email.</inlineHelpText>
        <label>Welcome Email Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implementation Surveys (Primary User)</relationshipLabel>
        <relationshipName>Primary_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provide_Cvent_Account_ID_If_Applicable__c</fullName>
        <inlineHelpText>If a Cvent Account ID is not applicable, please write Not Applicable or N/A</inlineHelpText>
        <label>Provide Cvent Account ID (If Applicable)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Implementation Surveys</relationshipLabel>
        <relationshipName>Implementation_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rush_Request__c</fullName>
        <inlineHelpText>If &lt;60 days, select Yes</inlineHelpText>
        <label>Rush Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation Survey</label>
    <nameField>
        <displayFormat>IMS-{0000}</displayFormat>
        <label>Implementation Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Event_Cloud</fullName>
        <active>true</active>
        <label>Event Cloud</label>
    </recordTypes>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Complexity__c</fullName>
        <label>Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Complexity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Associated__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created as per requirement of Data Services. This will be auto populated based on Opportunity Contact associated.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>CrowdCompass</fullName>
        <active>true</active>
        <label>CrowdCompass</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
</CustomObject>

objects/Professional_Services_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PSGs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PSPs</relationshipLabel>
        <relationshipName>PSPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>of_EB__c</fullName>
        <label># of EB</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>(List of all Additional Services)</description>
    <label>PSP</label>
    <nameField>
        <displayFormat>PSPs-{YYYY} #{0000}#</displayFormat>
        <label>PSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Complexity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Medium</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Complex</fullName>
    </customValue>
    <masterLabel>Complexity</masterLabel>
</GlobalValueSet>

classes/CreatePSPOnOppLineItem_TrigAct_Test.cls
/*****************************************************************
* Author : Sandeep Kumar
* Date : 12 April, 2017
* Description : It tests below mentioned classes
* 1) CreatePSPOnOppLineItemInsertion_TrigAct
* 2) EBProjectUpdatePendingHrsForCompletion
* 3) EBProjectAssignmentRollup_TrigAct
*******************************************************************/
@isTest(seeAllData= true)
public class CreatePSPOnOppLineItem_TrigAct_Test {    
    private static Opportunity opp;
    private static Account acc; 
    private static Contact con;
    private static User testUser;
    private static List<User> userList;
    private static SBQQ__Quote__c testQuote;
    private static Implementation_Survey__c impSurvey;
    private static Professional_Services_Project__c PSP;    
    private static List<EB_Agent_Profile__c> eBAgentProfileList;
    private static List<PricebookEntry> pbeList;
    private static User depUser = [Select Id, ProfileId from User where Name = 'CRM Deployment User'];
    private static Id userProfieId = UserProfileUtil.getProfileIDByName('Customer Care Rep - Product Consultant EB Team');    
    
    public static void setupData(){
        // Create Contact Record.
        con = TestUtil.createContact(acc.id);
        insert con;
        
        userList = new List<User>();
        // Create Salesforce Users for which will be assigned to EB Agent Profile later.
        User usr1 = TestUtil.createUser(userProfieId);
        usr1.username= 'CreatePSPOnOppLineItem_TrigAct_Test@test.com';
        //usr1.ContactId = con.Id;
        usr1.FederationIdentifier = 'F8ECWVJWT98C';
        userList.add(usr1);
        
        User usr2 = TestUtil.createUser(userProfieId);
        usr2.username= 'CreatePSPOnOppLineItem_TrigAct_Test2@test.com';
        //usr1.ContactId = con.Id;
        usr1.FederationIdentifier = 'F8ECWVJWT98D';
        userList.add(usr2);
        
        User usr3 = TestUtil.createUser(userProfieId);
        usr3.username= 'CreatePSPOnOppLineItem_TrigAct_Test3@test.com';
        //usr1.ContactId = con.Id;
        usr1.FederationIdentifier = 'F8ECWVJWT98E';
        userList.add(usr3);
        
        User usr4 = TestUtil.createUser(userProfieId);
        usr4.username= 'CreatePSPOnOppLineItem_TrigAct_Test4@test.com';
        //usr1.ContactId = con.Id;
        usr1.FederationIdentifier = 'F8ECWVJWT98F';
        userList.add(usr4);
        
        User usr5 = TestUtil.createUser(userProfieId);
        usr5.username= 'CreatePSPOnOppLineItem_TrigAct_Test5@test.com';
        //usr1.ContactId = con.Id;
        usr1.FederationIdentifier = 'F8ECWVJWT98G';
        userList.add(usr5);
        
        User usr6 = TestUtil.createUser(userProfieId);
        usr6.username= 'CreatePSPOnOppLineItem_TrigAct_Test6@test.com';
        //usr1.ContactId = con.Id;
        usr1.FederationIdentifier = 'F8ECWVJWT98H';
        userList.add(usr6);
        
        User usr7 = TestUtil.createUser(userProfieId);
        usr7.username= 'CreatePSPOnOppLineItem_TrigAct_Test7@test.com';
        //usr1.ContactId = con.Id;
        usr1.FederationIdentifier = 'F8ECWVJWT98I';
        userList.add(usr7);
        
        insert userList;  
        
        eBAgentProfileList = new List<EB_Agent_Profile__c>();
        // Create EB Agent Profile Records.   
        EB_Agent_Profile__c EBAgentProfile1 = TestUtil.createEBAgentProfile('Profile 1',userList[0].Id,'Low - 1');
        eBAgentProfileList.add(EBAgentProfile1);
        EB_Agent_Profile__c EBAgentProfile2 = TestUtil.createEBAgentProfile('Profile 2',userList[1].Id,'Med - 2');
        eBAgentProfileList.add(EBAgentProfile2);
        EB_Agent_Profile__c EBAgentProfile3 = TestUtil.createEBAgentProfile('Profile 3',userList[2].Id,'Top - 3');
        eBAgentProfileList.add(EBAgentProfile3);
        EB_Agent_Profile__c EBAgentProfile4 = TestUtil.createEBAgentProfile('Profile 4',userList[3].Id,'ARA - Inactive');
        eBAgentProfileList.add(EBAgentProfile4);
        EB_Agent_Profile__c EBAgentProfile5 = TestUtil.createEBAgentProfile('Profile 5',userList[4].Id,'ARA - Active');
        eBAgentProfileList.add(EBAgentProfile5);
        EB_Agent_Profile__c EBAgentProfile6 = TestUtil.createEBAgentProfile('Profile 6',userList[5].Id,'Enterprise Project1');
        eBAgentProfileList.add(EBAgentProfile6);
        EB_Agent_Profile__c EBAgentProfile7 = TestUtil.createEBAgentProfile('Profile 7',userList[6].Id,'Event Quarterback Project');        
        eBAgentProfileList.add(EBAgentProfile7);        
        insert eBAgentProfileList;          
                        
        // Create Product Record.
        List<Product2> products =  TestUtil.createProducts(
            new List<String>{
                'Event Builder(s) - Simple',
                    'Event Builder(s) - Medium',
                    'Event Builder(s) - Complex',
                    'Event Builder(s) - Advanced',
                    'Event Builder Rush Services – Simple',
                    'Event Builder Rush Services – Medium',
                    'Event Builder Rush Services – Complex',
                    'Event Builder Rush Services – Advanced',
                    'App Build',
                    'CrowdCompass Mobile App'
                    }
        );
        
        products[8].Family = 'CrowdCompass';
        products[9].Family = 'CrowdCompass';
        insert products;
        
        pbeList = new List<PricebookEntry>();        
        PricebookEntry pbe1 =  TestUtil.createPricebookEntry(products[0],200);
        pbeList.add(pbe1);
        PricebookEntry pbe2 =  TestUtil.createPricebookEntry(products[1],400);
        pbeList.add(pbe2);
        PricebookEntry pbe3 =  TestUtil.createPricebookEntry(products[2],200);
        pbeList.add(pbe3); 
        PricebookEntry pbe4 =  TestUtil.createPricebookEntry(products[3],200);
        pbeList.add(pbe4);
        PricebookEntry pbe5 =  TestUtil.createPricebookEntry(products[4],400);
        pbeList.add(pbe5);
        PricebookEntry pbe6 =  TestUtil.createPricebookEntry(products[5],200);
        pbeList.add(pbe6);
        PricebookEntry pbe7 =  TestUtil.createPricebookEntry(products[6],200);
        pbeList.add(pbe7);
        PricebookEntry pbe8 =  TestUtil.createPricebookEntry(products[7],400);
        pbeList.add(pbe8);
        PricebookEntry pbe9 =  TestUtil.createPricebookEntry(products[8],200);
        pbeList.add(pbe9); 
        PricebookEntry pbe10 =  TestUtil.createPricebookEntry(products[9],200);
        pbeList.add(pbe10);
        insert pbeList;   
        
        Opportunity o1 = TestUtil.createOpportunity('testOpp','Event','Bid Phase');
        o1.Contact_Associated__c = con.Id;
        o1.AccountId = acc.Id;
        o1.Event_Planner_Name__c = 'test User';
        o1.Event_Planner_Email__c = 'testuser@cvent.com';
        o1.Contract_Implemented__c = false;
        o1.CloseDate = Date.today().addDays(80);
        insert o1;
        
        testQuote = new SBQQ__Quote__c();
        testQuote.SBQQ__Opportunity2__c = o1.id;
        testQuote.Contract_Term_Years__c = '2';
        testQuote.SBQQ__Type__c = 'Amendment';
        testQuote.Current_Year__c = 2;
        testQuote.Contract_Executed__c = true;
        testQuote.SBQQ__StartDate__c = System.today().addYears(-1);
        testQuote.SBQQ__EndDate__c = System.today();
        //testQuote.createdFromLegacyContract__c = true;
        // testQuote.statusCheckCount__c = 0;
        insert testQuote;
        
        impSurvey = new Implementation_Survey__c();
        impSurvey.Account__c = acc.Id;
        impSurvey.Contact__c = con.Id;
        impSurvey.Opportunity__c = o1.Id;
        impSurvey.Primary_User__c = con.Id;
        impSurvey.Quote__c = testQuote.Id;
        impSurvey.Rush_Request__c = 'Yes';        
        impSurvey.Mobile_Delivery_Date__c = 'AttendeeHub';
        impSurvey.Additional_Comments__c = 'Test Comments';        
        impSurvey.First_Mobile_Event_Date__c = Date.today();
        impSurvey.First_Mobile_Event_Launch_Date__c = Date.today();
        impSurvey.Did_this_deal_use_the_Mid_Year_Promo__c = 'Yes';
        impSurvey.K_has_mult_Bill_to_or_Ship_to_addresses__c = 'Yes';
        impSurvey.Provide_Cvent_Account_ID_If_Applicable__c = 'Test';
        impSurvey.RecordtypeId = Schema.SObjectType.Implementation_Survey__c.getRecordTypeInfosByDeveloperName().get('Event_Cloud').getRecordTypeId();
        insert impSurvey;
        
        OpportunityLineItem oli1 = TestUtil.createOpportunityLineItems(o1,pbe1);
        oli1.Quantity = 3;
        OpportunityLineItem oli2 = TestUtil.createOpportunityLineItems(o1,pbe2);
        oli1.Quantity = 3;
        OpportunityLineItem oli3 = TestUtil.createOpportunityLineItems(o1,pbe3);
        oli1.Quantity = 3;
        OpportunityLineItem oli4 = TestUtil.createOpportunityLineItems(o1,pbe4);
        oli1.Quantity = 3;
        
        // Rush Request - Simple,Medium,Advanced and Complex opportunity products 
        OpportunityLineItem oli5 = TestUtil.createOpportunityLineItems(o1,pbe5);
        OpportunityLineItem oli6 = TestUtil.createOpportunityLineItems(o1,pbe6);
        OpportunityLineItem oli7 = TestUtil.createOpportunityLineItems(o1,pbe7);
        OpportunityLineItem oli8 = TestUtil.createOpportunityLineItems(o1,pbe8);
        
        // create crowdcompass opportunity products
        OpportunityLineItem oli9 = TestUtil.createOpportunityLineItems(o1,pbe9);
        oli9.Complexity__c = 'Standard';        
        OpportunityLineItem oli10 = TestUtil.createOpportunityLineItems(o1,pbe9);
        oli10.Complexity__c = 'Medium';        
        OpportunityLineItem oli11 = TestUtil.createOpportunityLineItems(o1,pbe9);
        oli11.Complexity__c = 'Advanced';        
        OpportunityLineItem oli12 = TestUtil.createOpportunityLineItems(o1,pbe9);
        oli12.Complexity__c = 'Complex';        
        OpportunityLineItem oli13 = TestUtil.createOpportunityLineItems(o1,pbe10); 
        
        insert new List<OpportunityLineItem>{oli1,oli2,oli3,oli4,oli5,oli6,oli7,oli8,oli9,oli10,oli11,oli12,oli13};
            
            opp = o1;//[Select Id, Amount From Opportunity where Id =:o1.Id];
    }
    
    // Creates new PSP record in Salesforce.
    static testMethod void createNewEBSBProjectsOnOppClosure(){
        System.runAs(depUser){
            // Create Account Record.
            acc = TestUtil.createAccount('EB Account', 'Biz_Ac');
            acc.BillingCountry = 'US';
            insert acc;           
            // Call SetupData Method
            setupData();
            System.debug('===createNewEBSBProjectsOnOppClosure====>>>>Before'+LIMITS.getLimitQueries());
            Test.startTest();            
            opp.StageName = 'Closed Won';
            opp.Contract_Implemented__c = true;
            opp.Contract_Number_New__c = '123456';
            update opp;
            System.debug('===createNewEBSBProjectsOnOppClosure====>>>>After'+LIMITS.getLimitQueries());
            Test.stopTest();  
        }      
    }
    
    // create new PSP and EBSB Project for ARA Account
    static testMethod void createEBSBProjectsOnOppClosure(){
        System.runAs(depUser){
            OpportunityTrgHelperCls_Version_2.isComingfromTestHandler1=true;         
            // create Account Record.
            acc = TestUtil.createAccount('EB Account 1', 'Biz_Ac');
            acc.Active_ARA__c = true;
            acc.BillingCountry = 'US';
            insert acc;
             
            // create ara record
            ARA__c araObj = new ARA__c();
            araObj.Account__c =acc.Id;
            araObj.Status__c = 'Open';
            insert araObj;
            
            // create PSP record.
            PSP = new Professional_Services_Project__c();
            PSP.Account__c = acc.Id;
            PSP.of_EB__c = 2;
            insert PSP;  
            
            // call SetupData Method
            setupData();
             System.debug('===createEBSBProjectsOnOppClosure====>>>>Before'+LIMITS.getLimitQueries());
                     
            opp.StageName = 'Closed Won';
            opp.Contract_Number_New__c = '123456';
            opp.Contract_Implemented__c = false;
            Test.startTest(); 
            //update opp;
             System.debug('===createEBSBProjectsOnOppClosure====>>>>After'+LIMITS.getLimitQueries());
            Test.stopTest();  
        }      
    }   
    
    // Updates exisitng PSP record in Salesforce.
    static testMethod void updateExistingEBSBProjectsOnOppClosure(){
        System.runAs(depUser){  
            OpportunityTrgHelperCls_Version_2.isComingfromTestHandler1=true;          
            // create Account Record.
            acc = TestUtil.createAccount('EB Account 1', 'Biz_Ac');
            acc.Active_ARA__c = true;
            acc.BillingCountry = 'US';
            insert acc;
            
            // create ara record            
            ARA__c araObj = new ARA__c();
            araObj.Account__c =acc.Id;
            araObj.Status__c = 'Open';
            insert araObj;
            
            // create PSP record.
            PSP = new Professional_Services_Project__c();
            PSP.Account__c = acc.Id;
            PSP.of_EB__c = 2;
            insert PSP;       
            
            System.debug('===updateExistingEBSBProjectsOnOppClosure====>>>>Before'+LIMITS.getLimitQueries());
            // call SetupData Method
            setupData();
                     
            opp.StageName = 'Closed Won';
            opp.Contract_Number_New__c = '123456';
            opp.Contract_Implemented__c = true;
            Test.startTest();   
            //update opp;
            System.debug('===updateExistingEBSBProjectsOnOppClosure====>>>>After'+LIMITS.getLimitQueries());
            Test.stopTest();  
        }      
    }     
}