objects/Account.object
<CustomObject>
    <fields>
        <fullName>EBS_Account_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise
Exclude from field purging exercise</description>
        <label>EBS Account ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Tier__c</fullName>
        <description>This will show the quality of service we will provide to the customer according to the Annual Contract Value.</description>
        <label>Service Tier (Hospitality Cloud)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account to which this Additional Address record is related.
This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <inlineHelpText>The Account to which this Additional Address record is related.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Additional_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Remittance</fullName>
                    <default>true</default>
                    <label>Remittance</label>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Primary POC</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Contact Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SMM_Implementations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SMM_Implementations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>SA Managed Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Implementation_Status__c</fullName>
        <label>Implementation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scoped for Sales</fullName>
                </value>
                <value>
                    <fullName>Pending Assignment</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending Close Out Call</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Stalled</fullName>
                </value>
                <value>
                    <fullName>No IMP - SA Managed</fullName>
                </value>
                <value>
                    <fullName>No IMP - Transition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_Lanyon__c</fullName>
        <label>Legacy Lanyon</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Tier__c</fullName>
        <formula>Account__r.Service_Tier__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Tier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Original</fullName>
                </value>
                <value>
                    <fullName>Original - Addl Instance</fullName>
                </value>
                <value>
                    <fullName>Original - No IMP</fullName>
                </value>
                <value>
                    <fullName>Event Quarterback</fullName>
                </value>
                <value>
                    <fullName>Re-Engagement</fullName>
                </value>
                <value>
                    <fullName>Venue Sourcing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation &amp; CS Team</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>SMM Implementations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation &amp; CS Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>SMM_Implementation</fullName>
        <active>true</active>
        <label>SMM Implementation</label>
    </recordTypes>
</CustomObject>

classes/SendOrderToEBSTest.cls
/**
*    
*   Author: Mohsin Siddiqui
*   Date Added : 08-02-2019
*   This class tests the functionality of SendOrderToEBS.
* 
*/
@istest
public class SendOrderToEBSTest 
{
	  public static testmethod void testCreateServiceOrder()
      {
          Account acc = new Account();
          acc.Name = 'Biz Test Acc 1';   
          acc.EBS_Account_ID__c = '46465464';     
          acc.BillingCountry = 'US'; 
          acc.BillingState = 'AK';
          acc.BillingCity = 'AKat';
          acc.BillingStreet = '172 Palm Ave Apt 2';
          acc.BillingPostalCode='4654';
          acc.Service_Tier__c = 'Gold';
          insert acc;
          
          SMM_Implementations__c smm = new SMM_Implementations__c();
          smm.RecordTypeId = Schema.SObjectType.SMM_Implementations__c.getRecordTypeInfosByDeveloperName().get('SMM_Implementation').getRecordTypeId();
          smm.Contract_Status__c = 'Active';
          smm.Child_Account__c = 'No';
          smm.Type__c = 'Original';
          smm.Implementation_Status__c = 'Completed';
          smm.Legacy_Lanyon__c = 'Yes';
          smm.Account__c = acc.Id;
          insert smm;
          
          smm.Legacy_Lanyon__c = 'No';
          update smm;
          
          Contact con = new Contact();
          con.LastName = 'Test Con 1';
          con.AccountId = acc.Id;
          con.EBS_Account_Id__c = '464654';
          insert con;
          
          List<Address__c> addressList = new List<Address__c>();
          Address__c address = new Address__c();
          address.Type__c = 'Billing';
          address.Account__c = acc.Id;
          address.Country__c = 'US';
          address.State__c = 'NY';
          address.Postal_Code__c = '10001';
          
          Address__c sAddress = new Address__c();
          sAddress.Type__c = 'Shipping';
          sAddress.Account__c = acc.Id;
          
          addressList.add(address);
          addressList.add(SAddress);
          insert addressList;
          Opportunity opp = new Opportunity();
          opp.Name = 'Test Opp 1';
          opp.AccountId = acc.Id;
          opp.StageName = 'Closed Won';
          opp.CloseDate = System.today()+ 30;
          opp.Contact_Associated__c = con.Id;
          opp.Contact_Role__c = 'Influencer';
          opp.ContractReceived__c = System.today()-7;
          opp.Bill_To_Address__c = addressList[0].Id;
          opp.Ship_To_Address__c = addressList[1].Id;
          opp.SF_Org_ID__c = '00Df0000002HJcq';
          
          insert opp;
          test.startTest();
          	SendOrderToEBS.createCustomerAndServiceOrder(opp.Id);
          test.stopTest();
      }
}