objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Acct_Status__c</fullName>
        <label>CC Acct Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                    <default>true</default>
                    <label>Untouched</label>
                </value>
                <value>
                    <fullName>Working/No traction yet</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Progress_Values__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This is used in the TopAccount Vf Page.</description>
    <label>Account Progress Values</label>
</CustomObject>

objects/Current_Status__c.object
<CustomObject>
    <fields>
        <fullName>Account_Progress__c</fullName>
        <label>Event Core Account Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Engaged buyer</fullName>
                </value>
                <value>
                    <fullName>Presentation scheduled</fullName>
                </value>
                <value>
                    <fullName>Correct Contacts Identified</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Price Quote/Proposal</fullName>
                </value>
                <value>
                    <fullName>Negotiation</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Using Competitor/Keeping in Touch</fullName>
                </value>
                <value>
                    <fullName>No Opportunity / Not a Fit</fullName>
                </value>
                <value>
                    <fullName>Active Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Parent</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Parent &amp; Subsidiary</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Sourcing</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Subsidiary</fullName>
                </value>
                <value>
                    <fullName>Completely Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - CT</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in CSN</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in Event</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in Mobile</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch -  Interested in SMM</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                    <default>true</default>
                    <label>No Contact</label>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BCP_Status__c</fullName>
        <label>Progress Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CC_Acct_Status__c</fullName>
        <label>Mobile Solutions Account Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                    <default>true</default>
                    <label>Untouched</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Engaged buyer</fullName>
                </value>
                <value>
                    <fullName>Presentation scheduled</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Assigned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>A_c_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Progress_Details__c</fullName>
        <label>CC Progress Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Days_Since_CC_Acct_Status_Change__c</fullName>
        <formula>NOW() - CC_Acct_Status_Change_Time_Capture__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since CC Acct Status Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_Since_Status_Change__c</fullName>
        <formula>NOW() - Status_Change_Time_Capture__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since Status Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Current_Status</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>A/c Status</label>
    <nameField>
        <displayFormat>CS{0000}</displayFormat>
        <label>Current Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>A/c Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Top_Accounts</fullName>
        <active>true</active>
        <label>Top Accounts</label>
    </recordTypes>
</CustomObject>

classes/TopAccountExtension.cls
/**
** Author: Shanu Aggarwal
** Test class: TopAccountExtensionTest
**/
public with sharing class TopAccountExtension {
    Id accountId;
    private String accountProgress;
    public Boolean showSection{get;set;}
    Public Current_Status__c accountRec{get;set;}
    List<Current_Status__c> accountList;
    public TopAccountExtension(ApexPages.StandardController controller) {
        showSection=false;
        RecordType instRecTypeThir = [SELECT Id FROM RecordType WHERE SobjectType='Current_Status__c' And IsActive = true And DeveloperName = 'Top_Accounts' ];
        accountList=new List<Current_Status__c>();
        accountId=ApexPages.currentPage().getParameters().get('id');
        System.debug('accountId===>>>>'+accountId);
        if(accountId!=null){
            accountList = [Select c.Parent_Account__r.Name,CC_Acct_Status__c,CC_Assigned_User__c,CC_Progress_Details__c,Days_Since_CC_Acct_Status_Change__c,c.Days_Since_Status_Change__c,c.Parent_Account__c, c.BCP_Status__c, c.Account_Progress__c From Current_Status__c c where Parent_Account__c = :accountId and RecordTypeId=:instRecTypeThir.Id LIMIT 1];  
            System.debug('accountList******'+accountList);
            if(accountList.size()>0){
                showSection=true;
                accountRec = new Current_Status__c();
                //accountRec.RecordTypeId = instRecTypeThir.Id;
                accountRec=accountList[0];   
                accountProgress =  accountRec.Account_Progress__c ;
                System.debug('accountRec**********'+accountRec);
            }
        } 
    }
    public List<SelectOption> typeOptions {
        get {
            if (typeOptions == null) {
                typeOptions = new List<SelectOption>();
                //typeOptions.add(new SelectOption('', '--None--'));
                DescribeFieldResult d = Current_Status__c.Account_Progress__c.getDescribe();
                for(PicklistEntry e : d.getPicklistValues()) {
                    if (e.isActive()) {
                        typeOptions.add(new SelectOption(e.getValue(), e.getLabel()));
                    }
                }
            }
            return typeOptions;
        }
        set;
    }
    
    
    
    public List<SelectOption> getaccountProgressList() {
        List<SelectOption> options = new List<SelectOption>();
        Map<string,Account_Progress_Values__c> mapCodes = Account_Progress_Values__c.getAll();
        if(accountList.size()>0){
            if(accountRec.Account_Progress__c!=null)
                options.add(new SelectOption(accountRec.Account_Progress__c,accountRec.Account_Progress__c));
            else
                options.add(new SelectOption('--None--','--None--'));
            For(Integer i=1;i<=50;i++){
                if(mapCodes.containsKey(String.ValueOf(i)))
                {
                    String code = Account_Progress_Values__c.getInstance(String.ValueOf(i)).Value__c; 
                    if(code != accountRec.Account_Progress__c)
                        options.add(new SelectOption(code ,code ));
                    //listString.add(code);
                }
                else
                    break;
            }
        }
        return options;
    }
    public String getAccountProgress() {
        return accountProgress;
    }
    public void setAccountProgress(String accountProgress) {
        this.accountProgress = accountProgress;
    }
    
    public void Save(){
        
        accountRec.Account_Progress__c = accountProgress;
        update accountRec;
    }
}