objects/Account.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Name__c</fullName>
        <label>Affiliate Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Case</label>
        <referenceTo>BillingCase__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CVII_ID__c</fullName>
        <description>Unique Customer ID - only for finance and SF
Exclude from field purging exercise</description>
        <label>NA CVII ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
</CustomObject>

objects/BillingCase__c.object
<CustomObject>
    <fields>
        <fullName>CVII_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>CVII ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Case</label>
    <nameField>
        <label>Billing Cases</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Primary POC</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Buyer_Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Contact Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Reviewing__c.object
<CustomObject>
    <fields>
        <fullName>Acc_Reviewer_Comments_Hybrid__c</fullName>
        <label>Acc Reviewer Comments (Hybrid)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Accounting_Hybrid_Review_Ok__c</fullName>
        <label>Accounting (Hybrid)Review Ok?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Error Correct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Reviewer__c</fullName>
        <label>Contract Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Harish Arora</fullName>
                </value>
                <value>
                    <fullName>Deepshikha Sharma</fullName>
                </value>
                <value>
                    <fullName>Akash Tiwari</fullName>
                </value>
                <value>
                    <fullName>Bishnu Singh</fullName>
                </value>
                <value>
                    <fullName>Vishav Garg</fullName>
                </value>
                <value>
                    <fullName>Akriti Puri</fullName>
                </value>
                <value>
                    <fullName>Poshali Gauba</fullName>
                </value>
                <value>
                    <fullName>Lalit Rawat</fullName>
                </value>
                <value>
                    <fullName>Dimple Kocher</fullName>
                </value>
                <value>
                    <fullName>Lalit Kashyap</fullName>
                </value>
                <value>
                    <fullName>Tushar Gautam</fullName>
                </value>
                <value>
                    <fullName>Ankit Pandey</fullName>
                </value>
                <value>
                    <fullName>Vishal Sharma</fullName>
                </value>
                <value>
                    <fullName>Prachi Tanwar</fullName>
                </value>
                <value>
                    <fullName>Tushar Vats</fullName>
                </value>
                <value>
                    <fullName>Vishal Gandhi</fullName>
                </value>
                <value>
                    <fullName>Gaurav Singh</fullName>
                </value>
                <value>
                    <fullName>Himanshi Chawla</fullName>
                </value>
                <value>
                    <fullName>Samridhi Rathi</fullName>
                </value>
                <value>
                    <fullName>Aman Singla</fullName>
                </value>
                <value>
                    <fullName>Aastha Dagdi</fullName>
                </value>
                <value>
                    <fullName>Vikas Arora</fullName>
                </value>
                <value>
                    <fullName>Anurag Singh</fullName>
                </value>
                <value>
                    <fullName>Manisha Parti</fullName>
                </value>
                <value>
                    <fullName>Shrishti Singh</fullName>
                </value>
                <value>
                    <fullName>Pradeep Deoli</fullName>
                </value>
                <value>
                    <fullName>Swati Gautam</fullName>
                </value>
                <value>
                    <fullName>Mohd Suhail</fullName>
                </value>
                <value>
                    <fullName>Kritika Singh</fullName>
                </value>
                <value>
                    <fullName>Shivangi Gupta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal_Year__c</fullName>
        <formula>TEXT(Opportunity__r.Deal_Year__c)</formula>
        <label>Deal Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Contract__c</fullName>
        <formula>Opportunity__r.Contract_Number_New__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Contract #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contract Reviews</relationshipLabel>
        <relationshipName>Contract_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Review</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Contract Reviewing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FeatureSet__c.object
<CustomObject>
    <fields>
        <fullName>FeatureSet__c</fullName>
        <label>FeatureSet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This is used in the Year1 opportunity Project. This will store the feature set picklist value and is used in the class"billingCaseCreate_Opp_handler" to match.</description>
    <label>Feature Set</label>
</CustomObject>

objects/HybridPicklistValue__c.object
<CustomObject>
    <fields>
        <fullName>HybridValue__c</fullName>
        <label>HybridValue</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>It is used in Tract</description>
    <label>HybridPicklistValue</label>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Adelaide</fullName>
                </value>
                <value>
                    <fullName>Akron</fullName>
                </value>
                <value>
                    <fullName>Alabama Gulf Coast</fullName>
                </value>
                <value>
                    <fullName>Albuquerque</fullName>
                </value>
                <value>
                    <fullName>Alexandria</fullName>
                </value>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Anaheim</fullName>
                </value>
                <value>
                    <fullName>Anchorage</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ashville</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Atlantic City</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Barcelona</fullName>
                </value>
                <value>
                    <fullName>Baton Rouge</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bergen County</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Birmingham</fullName>
                </value>
                <value>
                    <fullName>Bloomington</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Bridgewater</fullName>
                </value>
                <value>
                    <fullName>Brisbane</fullName>
                </value>
                <value>
                    <fullName>Brussels</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Associated__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created as per requirement of Data Services. This will be auto populated based on Opportunity Contact associated.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
</CustomObject>

objects/RRATracker__c.object
<CustomObject>
    <fields>
        <fullName>RoundRobinId__c</fullName>
        <label>RoundRobinId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>It stores the Id of corresponding user</description>
        <label>UserId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>It is used in tracker to assign contract  in Round Robin manner</description>
    <label>RoundRobinAssingmentTracker</label>
</CustomObject>

classes/billingCaseCreate_Opp_Test.cls
@isTest(seeAllData=false)
public class billingCaseCreate_Opp_Test{
    Private static User u;
    Private static void createUser(string roleName,integer id ){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Finance - Management']; 
        String s = '%' + roleName + '%'; 
        USerrole testroleId=[select id from userRole where name like :s limit 1];
        u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                     EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, userRoleId=testroleId.id,
                     TimeZoneSidKey='America/Los_Angeles', UserName=id+'deploymentuser@cvent.com');
        
    }
    
    Static testmethod void oppAutomationYear1_Methodtest(){
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.CVII_ID__c='11;12;23';
            acc.Affiliate_Name__c ='Curio Collection';
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            insert acc;
            //acc.Billing_Case__c=billingObj.Id;
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            opp.Contract_Number_New__c='123';
            opp.Contract_Implemented__c=false;
            opp.Deal_Year__c='1';
            opp.AccountId=acc.id;
            opp.ContractReceived__c=system.today();
            opp.ContractStartDate__c=system.today();
            opp.Chain_Deal__c='Bulk Purchase By Management Company';
            opp.Case_Received_Date__c=System.today();
            opp.Implementation_Response__c='1';
            opp.Contract_Number_New__c ='1';
            opp.Contact_Associated__c= con.Id;
            opp.Deal_Closed_by__c=u.Id;
            //opp.Manager__c='testManager@test.com';
            
            opp.Contact_Role__c='Primary User & Signer';
            opp.Pricebook2Id = pbEntry.Pricebook2Id;
            opp.NBB_Renewal__c ='Renewal';
            opp.Early_Contract__c='Not Early';
            opp.ContractStartDate__c= system.today()-1;
            
            date dt1 = date.newInstance(2018, 1, 1);
            date dt2 = date.newInstance(2018, 5, 1);
            opp.RenewalDate__c=dt2;
            opp.ContractReceived__c = dt1;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            insert opp;
            //system.debug('cviiId test'+opp.CVII_ID__c);
            
            
            
            HybridPicklistValue__c hybrid=new HybridPicklistValue__c();
            hybrid.Name='2Test';
            hybrid.HybridValue__c='Attendee Hub';
            insert hybrid;
            
            RRATracker__c RR = new RRATracker__c();
            RR.RoundRobinId__c=0;
            RR.UserId__c=u.id;
            rr.Name='0';
            RR.User_Name__c ='test user';
            insert RR;
            
            
            opportunity oppquery = [select Id,accountId,CVII_ID__c,Contract_Number_New__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            update oppquery;
            
            Contract_Reviewing__c conRev = new Contract_Reviewing__c();
            conRev.Accounting_Hybrid_Review_Ok__c='Yes';
            conRev.Contract_Reviewer__c=u.Id;
            conRev.Opportunity__c =oppquery.Id;
            //conRev.Opportunity_Contract__c =123;
            insert conRev;
            
            
            
            //system.debug('cviiId test update'+oppquery.CVII_ID__c);
            //system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            

            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            
            
            Contract_Reviewing__c ContractNum =[select Id,Accounting_Hybrid_Review_Ok__c,
                                                Opportunity__c,Contract_Reviewer__c,Opportunity_Contract__c
                                                from Contract_Reviewing__c where Opportunity__c=:oppquery.Id];
            billingCaseCreate_Opp_handler.oppAutomationYear1_Method(opplist);
            system.assertEquals(oppquery.ContractReceived__c, oppquery.CloseDate);
        }
    }
    Static testmethod void oppAutomationYear1_MethodtestNOOLI(){
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Affiliate_Name__c ='';
            insert acc;
            //acc.Billing_Case__c=billingObj.Id;
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            opp.Contract_Number_New__c='123';
            opp.Contract_Implemented__c=false;
            opp.Deal_Year__c='1';
            opp.AccountId=acc.id;
            opp.ContractReceived__c=system.today();
            opp.ContractStartDate__c=system.today();
            opp.Chain_Deal__c='Bulk Purchase By Management Company';
            opp.Case_Received_Date__c=System.today();
            opp.Implementation_Response__c='1';
            opp.Contract_Number_New__c ='1';
            opp.Contact_Associated__c= con.Id;
            opp.Deal_Closed_by__c=u.Id;
            opp.Chain_Name__c='Accor';
            opp.Brand_Name__c='Accor';
            //opp.Manager__c='testManager@test.com';
            
            opp.Contact_Role__c='Primary User & Signer';
            //opp.Pricebook2Id = pbEntry.Pricebook2Id;
            opp.NBB_Renewal__c ='Renewal';
            opp.Early_Contract__c='Not Early';
            opp.ContractStartDate__c= system.today()-1;
            
            date dt1 = date.newInstance(2018, 1, 1);
            date dt2 = date.newInstance(2018, 5, 1);
            opp.RenewalDate__c=dt2;
            opp.ContractReceived__c = dt1;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            insert opp;
            //system.debug('cviiId test'+opp.CVII_ID__c);
            
            
            
            HybridPicklistValue__c hybrid=new HybridPicklistValue__c();
            hybrid.Name='2Test';
            hybrid.HybridValue__c='Attendee Hub';
            insert hybrid;
            
            RRATracker__c RR = new RRATracker__c();
            RR.RoundRobinId__c=0;
            RR.UserId__c=u.id;
            rr.Name='0';
            RR.User_Name__c ='test user';
            insert RR;
            
            
            opportunity oppquery = [select Id,accountId,CVII_ID__c,Contract_Number_New__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            oppquery.MYD_Deal__c='MYD';
            update oppquery;
            
            Contract_Reviewing__c conRev = new Contract_Reviewing__c();
            conRev.Accounting_Hybrid_Review_Ok__c='Yes';
            conRev.Contract_Reviewer__c=u.Id;
            conRev.Opportunity__c =oppquery.Id;
            //conRev.Opportunity_Contract__c =123;
            insert conRev;
            
            
            
            //system.debug('cviiId test update'+oppquery.CVII_ID__c);
            //system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            

            insert pbEntry;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            
            
            Contract_Reviewing__c ContractNum =[select Id,Accounting_Hybrid_Review_Ok__c,
                                                Opportunity__c,Contract_Reviewer__c,Opportunity_Contract__c
                                                from Contract_Reviewing__c where Opportunity__c=:oppquery.Id];
            billingCaseCreate_Opp_handler.oppAutomationYear1_Method(opplist);
            //system.assertEquals(oppquery.ContractReceived__c, oppquery.CloseDate);
        }
    }
    static testmethod void billingCasemethod4()
    { 
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        
        insert u;
        
        system.runAs(u)
        {
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.Affiliate_Name__c ='Autograph Collection';
            insert acc;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            opp.Deal_Closed_by__c= u.Id;
            date dt1 = date.newInstance(2018, 1, 1);
            date dt2 = date.newInstance(2018, 5, 1);
            opp.RenewalDate__c=dt2;
            opp.ContractReceived__c = dt1;
            opp.MYD_Deal__c='MYD';
            insert opp;
            system.debug('oppformutil'+opp.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(opp);
            billingCaseCreate_opp_handler.oppAutomationYear1_Method(opplist);
            //billingCaseCreate_opp_handler.billingCaseCreate_Method(opplist);
        }
        test.stopTest();  
    }
    static testmethod void billingCasemethod5()
    { 
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            BillingCase__c billingObj = new BillingCase__c();
            billingObj.CVII_Number__c='123';
            billingObj.Name='testbilling';
            insert billingObj;
            
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            acc.Billing_Case__c=billingObj.Id;
            
            insert acc;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            
            insert opp;
            system.debug('cviiId test'+opp.CVII_ID__c);
            opportunity oppquery = [select Id,accountId,CVII_ID__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            update oppquery;
            system.debug('cviiId test update'+oppquery.CVII_ID__c);
            system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            //billingCaseCreate_opp_handler.oppAutomationYear1_Method(opplist);
            billingCaseCreate_opp_handler.billingCaseCreate_Method(opplist);
            
            
        }
        test.stopTest();  
    }
    static testmethod void billingCasemethod5BillingAddress()
    { 
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            BillingCase__c billingObj = new BillingCase__c();
            billingObj.CVII_Number__c='123';
            billingObj.Name='testbilling';
            insert billingObj;
            
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            acc.Billing_Case__c=billingObj.Id;
            
            insert acc;
            address__c address = testutil.createAccountAddress(acc.Id,'Billing');
            insert address;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            
            insert opp;
            system.debug('cviiId test'+opp.CVII_ID__c);
            opportunity oppquery = [select Id,accountId,CVII_ID__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            //oppquery.Bill_To_Contact__c=con.Id;
            oppquery.Bill_To_Address__c=address.Id;
            update oppquery;
            system.debug('cviiId test update'+oppquery.CVII_ID__c);
            system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            //billingCaseCreate_opp_handler.oppAutomationYear1_Method(opplist);
            billingCaseCreate_opp_handler.billingCaseCreate_Method(opplist);
            
            
        }
        test.stopTest();  
    }
    static testmethod void billingCasemethodElsePart()
    { 
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            BillingCase__c billingObj = new BillingCase__c();
            billingObj.CVII_Number__c='11;12;23';
            billingObj.Name='testbilling';
            insert billingObj;
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Billing_Case__c=billingObj.Id; // commented  it for the billing case else part
            
            insert acc;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            
            insert opp;
            system.debug('cviiId test'+opp.CVII_ID__c);
            opportunity oppquery = [select Id,accountId,CVII_ID__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            update oppquery;
            system.debug('cviiId test update'+oppquery.CVII_ID__c);
            system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            //billingCaseCreate_opp_handler.oppAutomationYear1_Method(opplist);
            billingCaseCreate_opp_handler.billingCaseCreate_Method(opplist);
            
            
        }
        test.stopTest();  
    }
    static testmethod void billingCasemethodElsePartBillAddress()
    { 
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            BillingCase__c billingObj = new BillingCase__c();
            billingObj.CVII_Number__c='11;12;23';
            billingObj.Name='testbilling';
            insert billingObj;
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Billing_Case__c=billingObj.Id; // commented  it for the billing case else part
            address__c address = testutil.createAccountAddress(acc.Id,'Billing');
            address.City__c=' TestCity';
            insert address;
            insert acc;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            
            insert opp;
            system.debug('cviiId test'+opp.CVII_ID__c);
            opportunity oppquery = [select Id,accountId,CVII_ID__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            //oppquery.Bill_To_Contact__c=con.Id;
            oppquery.Bill_To_Address__c=address.Id;
            update oppquery;
            system.debug('cviiId test update'+oppquery.CVII_ID__c);
            system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            //billingCaseCreate_opp_handler.oppAutomationYear1_Method(opplist);
            billingCaseCreate_opp_handler.billingCaseCreate_Method(opplist);
        }
        test.stopTest();  
    }
    static testmethod void billingCasemethodbillToAddressElse298()
    { 
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Billing_Case__c=billingObj.Id;
            
            insert acc;
            address__c address = testutil.createAccountAddress(acc.Id,'Billing');
            insert address;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            
            insert opp;
            system.debug('cviiId test'+opp.CVII_ID__c);
            opportunity oppquery = [select Id,accountId,CVII_ID__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            //oppquery.Bill_To_Contact__c=con.Id;
            oppQuery.Bill_To_Address__c= address.Id;
            update oppquery;
            system.debug('cviiId test update'+oppquery.CVII_ID__c);
            system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            //billingCaseCreate_opp_handler.oppAutomationYear1_Method(opplist);
            billingCaseCreate_opp_handler.billingCaseCreate_Method(opplist);
            
            
        }
        test.stopTest();  
    }
    
    static testmethod void billingCasemethodbillTocontactElse298()
    { 
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Billing_Case__c=billingObj.Id;
            
            insert acc;
            address__c address = testutil.createAccountAddress(acc.Id,'Billing');
            insert address;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            
            insert opp;
            system.debug('cviiId test'+opp.CVII_ID__c);
            opportunity oppquery = [select Id,accountId,CVII_ID__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            //oppQuery.Bill_To_Address__c= address.Id;
            update oppquery;
            system.debug('cviiId test update'+oppquery.CVII_ID__c);
            system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            //billingCaseCreate_opp_handler.oppAutomationYear1_Method(opplist);
            billingCaseCreate_opp_handler.billingCaseCreate_Method(opplist);
            
            
        }
        test.stopTest();  
    }
    Static testmethod void createContractReviewTestMethod(){
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Billing_Case__c=billingObj.Id;
            
            insert acc;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            opp.Contract_Number_New__c='123';
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            insert opp;
            //system.debug('cviiId test'+opp.CVII_ID__c);
            
            
            
            HybridPicklistValue__c hybrid=new HybridPicklistValue__c();
            hybrid.Name='2Test';
            hybrid.HybridValue__c='Attendee Hub';
            insert hybrid;
            
            RRATracker__c RR = new RRATracker__c();
            RR.RoundRobinId__c=0;
            RR.UserId__c=u.id;
            rr.Name='0';
            RR.User_Name__c ='test user';
            insert RR;
            
            
            opportunity oppquery = [select Id,accountId,CVII_ID__c,Contract_Number_New__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            update oppquery;
            
            Contract_Reviewing__c conRev = new Contract_Reviewing__c();
            conRev.Accounting_Hybrid_Review_Ok__c='Yes';
            conRev.Contract_Reviewer__c=u.Id;
            conRev.Opportunity__c =oppquery.Id;
            //conRev.Opportunity_Contract__c =123;
            insert conRev;
            
            
            
            //system.debug('cviiId test update'+oppquery.CVII_ID__c);
            //system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            
            
            Contract_Reviewing__c ContractNum =[select Id,Accounting_Hybrid_Review_Ok__c,
                                                Opportunity__c,Contract_Reviewer__c,Opportunity_Contract__c
                                                from Contract_Reviewing__c where Opportunity__c=:oppquery.Id];
            
            map<id,Boolean> mapcontractReview = new map<id,Boolean>();
            mapcontractReview.put(oppquery.Id,true);
            billingCaseCreate_Opp_handler.createContractReview(opplist,mapcontractReview);
            
        }
    }
    Static testmethod void createContractReviewTestMethodElsePart(){
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Billing_Case__c=billingObj.Id;
            
            insert acc;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            opp.Contract_Number_New__c='123';
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            insert opp;
            //system.debug('cviiId test'+opp.CVII_ID__c);
            
            
            
            HybridPicklistValue__c hybrid=new HybridPicklistValue__c();
            hybrid.Name='2Test';
            hybrid.HybridValue__c='Attendee Hub';
            insert hybrid;
            
            RRATracker__c RR = new RRATracker__c();
            RR.RoundRobinId__c=0;
            RR.UserId__c=u.id;
            rr.Name='0';
            RR.User_Name__c ='test user';
            insert RR;
            
            
            opportunity oppquery = [select Id,accountId,CVII_ID__c,Contract_Number_New__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            update oppquery;
            
            Contract_Reviewing__c conRev = new Contract_Reviewing__c();
            conRev.Accounting_Hybrid_Review_Ok__c='Yes';
            //conRev.Contract_Reviewer__c=u.Id;
            conRev.Opportunity__c =oppquery.Id;
            //conRev.Opportunity_Contract__c =123;
            insert conRev;
            
            
            
            //system.debug('cviiId test update'+oppquery.CVII_ID__c);
            //system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            oppquery.Contract_Implemented__c=true;
            oppquery.Event_Name__C='Cvnet';
            update oppquery;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            
            
            Contract_Reviewing__c ContractNum =[select Id,Accounting_Hybrid_Review_Ok__c,
                                                Opportunity__c,Contract_Reviewer__c,Opportunity_Contract__c
                                                from Contract_Reviewing__c where Opportunity__c=:oppquery.Id];
            ContractNum.Accounting_Hybrid_Review_Ok__c='No';
            ContractNum.Acc_Reviewer_Comments_Hybrid__c ='test comment';
            update ContractNum;
            map<id,Boolean> mapcontractReview = new map<id,Boolean>();
            mapcontractReview.put(oppquery.Id,true);                                            
            
            /* for else if part */
            billingCaseCreate_Opp_handler.createContractReview(opplist,mapcontractReview);
        }
    }
    Static testmethod void createContractReviewTestMethodISHybridloop(){
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Billing_Case__c=billingObj.Id;
            
            insert acc;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            //opp.Contract_Number_New__c=123;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            insert opp;
            //system.debug('cviiId test'+opp.CVII_ID__c);
            
            
            
            HybridPicklistValue__c hybrid=new HybridPicklistValue__c();
            hybrid.Name='2Test';
            hybrid.HybridValue__c='Attendee Hub';
            insert hybrid;
            
            RRATracker__c RR = new RRATracker__c();
            RR.RoundRobinId__c=0;
            RR.UserId__c=u.id;
            RR.name='test';
            RR.User_Name__c = u.name;
            insert RR;
            
            
            opportunity oppquery = [select Id,accountId,CVII_ID__c,Contract_Number_New__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            update oppquery;
            //system.debug('cviiId test update'+oppquery.CVII_ID__c);
            //system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            map<id,Boolean> mapcontractReview = new map<id,Boolean>();
            mapcontractReview.put(oppquery.Id,true);
            billingCaseCreate_Opp_handler.createContractReview(opplist,mapcontractReview);
        }
    }
    Static testmethod void createContractReviewTestMethodISHybridloopFalse(){
        test.startTest();
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        system.runAs(u)
        {
            
            Account acc= testutil.createAccount('name', 'Biz_Ac');
            acc.BillingCountryCode = 'US';
            acc.BillingState = 'TX';
            acc.CVII_ID__c='11;12;23';
            //acc.Billing_Case__c=billingObj.Id;
            
            insert acc;
            system.debug('accountIDformutil'+acc.Id);
            Contact con= testutil.createContact('firstName', 'lastName', 'email@test.com', acc.Id);
            insert con;
            system.debug('contactformutil'+con.Id);
            opportunity opp = testutil.createOpportunity('theName', 'Event', 'Closed');
            opp.AccountId= acc.Id;
            //opp.Contract_Number_New__c=123;
            //opp.Deal_Closed_by__c= u.Id;
            //opp.CVII_ID__c='1;2;3';
            insert opp;
            //system.debug('cviiId test'+opp.CVII_ID__c);
            
            
            
            HybridPicklistValue__c hybrid=new HybridPicklistValue__c();
            hybrid.Name='2Test';
            hybrid.HybridValue__c='Attendee Hub';
            insert hybrid;
            
            RRATracker__c RR = new RRATracker__c();
            RR.RoundRobinId__c=0;
            RR.UserId__c=u.id;
            RR.name='test';
            RR.User_Name__c = u.name;
            insert RR;
            
            
            opportunity oppquery = [select Id,accountId,CVII_ID__c,Contract_Number_New__c from opportunity where accountId=:acc.Id limit 1][0];
            system.assertEquals('11;12;23', oppquery.CVII_ID__c);
            oppquery.Date_Assigned__c=system.today();
            oppquery.Bill_To_Contact__c=con.Id;
            update oppquery;
            //system.debug('cviiId test update'+oppquery.CVII_ID__c);
            //system.debug('oppformutil---'+opp.Id+'oppqueryID>>>>'+oppquery.Id);
            
            // custom setting
            FeatureSet__c fCustomSetting= new FeatureSet__c();
            fCustomSetting.Name='1test';
            //fCustomSetting.FeatureSet__c='Attendee Hub';
            fCustomSetting.FeatureSet__c='Product X';
            insert fCustomSetting;
            
            Id pricebookId = Test.getStandardPricebookId();
            Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X',isActive = true);
            insert prod;
            
            //Create pricebook entry
            PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId,Product2Id = prod.Id,UnitPrice = 100.00,
                                                        IsActive = true);
            insert pbEntry;
            OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = opp.Id,
                                                              PricebookEntryId = pbEntry.Id,
                                                              quantity=4, 
                                                              totalprice=200);
            insert oli;
            list<opportunity> opplist = new list<opportunity>();
            opplist.add(oppquery);
            map<id,Boolean> mapcontractReview = new map<id,Boolean>();
            mapcontractReview.put(oppquery.Id,False);
            billingCaseCreate_Opp_handler.createContractReview(opplist,mapcontractReview);
        }
    }
}