objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/Account_Shut_Down_Details__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments_Description__c</fullName>
        <label>Why did we lose this Customer?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Did_we_Lose_to_a_Competitor__c</fullName>
        <label>Did we Lose to a Competitor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Did_we_Lose_to_an_Internal_System__c</fullName>
        <label>Did we Lose to an Internal System?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <label>Primary Lost Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Opportunity_Lost_On__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Champion Left</fullName>
                </value>
                <value>
                    <fullName>Company dissolved/Was acquired</fullName>
                </value>
                <value>
                    <fullName>Complexity</fullName>
                </value>
                <value>
                    <fullName>Contract renegotiated with cvent</fullName>
                </value>
                <value>
                    <fullName>Decreased number of Events</fullName>
                </value>
                <value>
                    <fullName>Didn't get Org-Wide Adoption</fullName>
                </value>
                <value>
                    <fullName>Didn't See Value</fullName>
                </value>
                <value>
                    <fullName>Failed To Launch</fullName>
                </value>
                <value>
                    <fullName>In Legal/Billing Settlement</fullName>
                </value>
                <value>
                    <fullName>Leadership change</fullName>
                </value>
                <value>
                    <fullName>Lost Internal Support for Project (too busy)</fullName>
                </value>
                <value>
                    <fullName>Main user changed roles/Left the company</fullName>
                </value>
                <value>
                    <fullName>Missing A Feature</fullName>
                </value>
                <value>
                    <fullName>Moved to Another Product</fullName>
                </value>
                <value>
                    <fullName>Moved to HQ System</fullName>
                </value>
                <value>
                    <fullName>Needed additional Functionality</fullName>
                </value>
                <value>
                    <fullName>No more Events</fullName>
                </value>
                <value>
                    <fullName>One Time Sale</fullName>
                </value>
                <value>
                    <fullName>Payment Terms</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Realized Value in creating similar Software</fullName>
                </value>
                <value>
                    <fullName>Too Expensive</fullName>
                </value>
                <value>
                    <fullName>Usability</fullName>
                </value>
                <value>
                    <fullName>Using for Ad-Hoc One-Time Surveys, Event</fullName>
                </value>
                <value>
                    <fullName>Wanted Custom App</fullName>
                </value>
                <value>
                    <fullName>Went Out of Business</fullName>
                </value>
                <value>
                    <fullName>Service Fees Too High</fullName>
                </value>
                <value>
                    <fullName>Signing Bonus Insufficient</fullName>
                </value>
                <value>
                    <fullName>Good Candidate for Self Serve</fullName>
                </value>
                <value>
                    <fullName>Persistent Tech issues</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Lost_On__c</fullName>
        <label>Primary Lost Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Adoption</fullName>
                </value>
                <value>
                    <fullName>Adoption/Low Usage</fullName>
                </value>
                <value>
                    <fullName>Budgetary Issues</fullName>
                </value>
                <value>
                    <fullName>Company Reorganization</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Customer Business Process</fullName>
                </value>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Customer Turnover</fullName>
                </value>
                <value>
                    <fullName>Economics/Pricing</fullName>
                </value>
                <value>
                    <fullName>Events Changed</fullName>
                </value>
                <value>
                    <fullName>Lack of Need</fullName>
                </value>
                <value>
                    <fullName>Lack of ROI</fullName>
                </value>
                <value>
                    <fullName>Market Conditions</fullName>
                </value>
                <value>
                    <fullName>Migrating to Cvent</fullName>
                </value>
                <value>
                    <fullName>Moved In-House</fullName>
                </value>
                <value>
                    <fullName>Need</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive Customer</fullName>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                </value>
                <value>
                    <fullName>Onboarding/Training</fullName>
                </value>
                <value>
                    <fullName>One-Time Sale</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Oversold</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Property Operations &amp; Management</fullName>
                </value>
                <value>
                    <fullName>Property Reflag</fullName>
                </value>
                <value>
                    <fullName>PSG</fullName>
                </value>
                <value>
                    <fullName>Radio Silent</fullName>
                </value>
                <value>
                    <fullName>Reallocation of Funds</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <label>Opportunity Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Closed Lost Details</relationshipLabel>
        <relationshipName>Account_Shut_Down_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Please_Specify_the_Competitors_Name__c</fullName>
        <label>Please Specify the Competitors Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>168Tickets</fullName>
                </value>
                <value>
                    <fullName>Ace Ticket</fullName>
                </value>
                <value>
                    <fullName>Acteva</fullName>
                </value>
                <value>
                    <fullName>Active networks</fullName>
                </value>
                <value>
                    <fullName>Agile Ticketing Solutions</fullName>
                </value>
                <value>
                    <fullName>Akkroo</fullName>
                </value>
                <value>
                    <fullName>à la Reg</fullName>
                </value>
                <value>
                    <fullName>Al Brooks Theatre Ticket Agency</fullName>
                </value>
                <value>
                    <fullName>All Access Tickets</fullName>
                </value>
                <value>
                    <fullName>Alliance</fullName>
                </value>
                <value>
                    <fullName>Aloud.com</fullName>
                </value>
                <value>
                    <fullName>Amazing Tickets</fullName>
                </value>
                <value>
                    <fullName>Ask A Ticket</fullName>
                </value>
                <value>
                    <fullName>AtEvent</fullName>
                </value>
                <value>
                    <fullName>Atrient</fullName>
                </value>
                <value>
                    <fullName>AttendStar</fullName>
                </value>
                <value>
                    <fullName>AudienceView Ticketing</fullName>
                </value>
                <value>
                    <fullName>Aventi and Socio</fullName>
                </value>
                <value>
                    <fullName>AXS.com</fullName>
                </value>
                <value>
                    <fullName>Barry's Tickets Service</fullName>
                </value>
                <value>
                    <fullName>Bedouk</fullName>
                </value>
                <value>
                    <fullName>beTicketing</fullName>
                </value>
                <value>
                    <fullName>Blackbaud</fullName>
                </value>
                <value>
                    <fullName>BrownPaperTickets</fullName>
                </value>
                <value>
                    <fullName>Brushfire Software</fullName>
                </value>
                <value>
                    <fullName>CC/CT - Active</fullName>
                </value>
                <value>
                    <fullName>CC/CT - Aloompa</fullName>
                </value>
                <value>
                    <fullName>CC/CT - Applitite LLC</fullName>
                </value>
                <value>
                    <fullName>CC/CT - ATV's Event Pilot</fullName>
                </value>
                <value>
                    <fullName>CC/CT - Core-Apps</fullName>
                </value>
                <value>
                    <fullName>E - Active.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closed Lost Details</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Account Shut Down Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closed Lost Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Event_Renewal</fullName>
        <active>true</active>
        <label>Event Renewal</label>
    </recordTypes>
</CustomObject>

classes/ClosedLostDetailsTriggerHelperTest.cls
@isTest
public class ClosedLostDetailsTriggerHelperTest 
{
    public testmethod static void testMethod1()
    {
        Account instofAcc = TestUtil.createAccount('Test Account','Biz_Ac');
        instofAcc.BillingCountryCode='US';
        instOfAcc.BillingStateCode='TX';
        insert instOfAcc;
        
        Contact instofCon = TestUtil.createContact(instofAcc.id);
        instOfCon.Email = 'Test987654321@test.com';
        instOfCon.Phone = '8877665544';
        insert instofCon;
        
        Opportunity instOpp=TestUtil.createOpportunity('Test Opp','Event','Qualified');
        instOpp.AccountId = instOfAcc.Id;
        instOpp.StageName ='Verbal';
        instOpp.Deal_Year__c ='1';
        instOpp.NBB_Renewal__c = 'NBB';
        instOpp.Parent_Upsell__c = 'Primary';
        instOpp.CloseDate = system.today().addmonths(12);
        instOpp.pricebook2id=Test.getStandardPricebookID();
        instOpp.Contact_Associated__c=instofCon.id; 
        insert instOpp;
        
        Id recordTypeId = RecordTypeUtil.getRecordTypeIDByDevName('Account_Shut_Down_Details__c','Event_Renewal');
        Account_Shut_Down_Details__c closedLostRec = new Account_Shut_Down_Details__c();
        closedLostRec.RecordTypeId = recordTypeId;
        closedLostRec.Opportunity_Lost_On__c = 'Product';
        closedLostRec.Lost_Reason__c = 'Usability';
        closedLostRec.Did_we_Lose_to_a_Competitor__c = 'Yes';
        closedLostRec.Please_Specify_the_Competitors_Name__c = 'E - Active.com';
        closedLostRec.Did_we_Lose_to_an_Internal_System__c = 'Yes';
        closedLostRec.Additional_Comments_Description__c = 'testing testing testing';
        closedLostRec.Opportunity_Stage__c = 'At Risk';
        closedLostRec.Opportunity__c = instOpp.Id;
        insert closedLostRec;
        
        closedLostRec.Opportunity_Stage__c = 'Closed Lost';
        update closedLostRec;
    }
}