objects/Account.object
<CustomObject>
    <fields>
        <fullName>EBS_Account_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise
Exclude from field purging exercise</description>
        <label>EBS Account ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account to which this Additional Address record is related.
This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <inlineHelpText>The Account to which this Additional Address record is related.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Additional_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Site_Use_ID__c</fullName>
        <description>EBS Integration field
This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <externalId>true</externalId>
        <label>EBS Site Use ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>Used to track Canadian or other country's province data.</description>
        <inlineHelpText>This is required if Country = Canada.</inlineHelpText>
        <label>Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Remittance</fullName>
                    <default>true</default>
                    <label>Remittance</label>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
</CustomObject>

objects/ByPassTrigger__c.object
<CustomObject>
    <fields>
        <fullName>Enable_EBS_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for selectively enabling EBS Integration for users.</description>
        <inlineHelpText>Used for selectively enabling EBS Integration for users.</inlineHelpText>
        <label>Enable EBS Sync?</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Use to Bypass all triggers for data migration</description>
    <label>ByPass Trigger</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CountryCode__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Country Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Country Codes</label>
</CustomObject>

objects/EBS_Integration__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Map__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Map</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validate</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>EBS Integration</label>
</CustomObject>

objects/EBS_Order_Sync_Framework__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links to the Closed Won Opportunity which is to be sent over to EBS</description>
        <label>Opportunity (Related Order)</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EBS Order Sync Framework</relationshipLabel>
        <relationshipName>EBS_Order_Sync_Framework</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>This object would be used to control the Opportunity (Order) Sync process with EBS by ensuring that all dependencies like Account (new customer), associated  Addresses, Contacts and Contact Addresses have a valid EBS Id and if not, sync them with EBS first before pushing the Order. It does this by generating and queuing multiple Integration Queue records.</description>
    <label>EBS Order Sync Framework</label>
    <nameField>
        <displayFormat>OS-{00000000}</displayFormat>
        <label>Order Sync Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Order Sync Framework</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EBS_Orders__c.object
<CustomObject>
    <fields>
        <fullName>EBS_Header_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <externalId>true</externalId>
        <label>EBS Header ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EBS_Order_Number__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Order_Status__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Order Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Quote_Number__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Quote Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EBS Orders</relationshipLabel>
        <relationshipName>EBS_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBS-{00000}</displayFormat>
        <label>EBS Orders</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Enable_EBS_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to control if any inserts/updates made by this user would trigger a sync with EBS (integration queue)</description>
        <inlineHelpText>Flag to control if any inserts/updates made by this user would trigger a sync with EBS (integration queue)</inlineHelpText>
        <label>Enable EBS Sync?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/IntegrationAddressTest.cls
/**
*    
*   Author: Shanu Aggarwal
*   Date Added : 23-05-2017
*   This class tests the functionality of IntegrationAddress
* 
*/
@istest
public class IntegrationAddressTest{
    
   @testsetup
   public static void CreateTestData(){
        
        Test.startTest();
        
        //enable sync
        ByPassTrigger__c bp = new ByPassTrigger__c();
        bp.SetupOwnerId = UserInfo.getUserId();
        bp.Enable_EBS_Sync__c =true;
        insert bp;
        
        //Inserting User...............
        /*Profile p = [SELECT Id FROM Profile WHERE Name='Finance - Management']; 
    
        USerrole[] testroleId=[select id from userRole where name ='AM (Event)' OR name ='Pre Sales - Special Projects' limit 2];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Sops', LanguageLocaleKey='en_US', FirstName='TestUser',
        LocaleSidKey='en_US', ProfileId = p.Id, userRoleId=testroleId[0].id,
        TimeZoneSidKey='America/Los_Angeles', UserName='Test'+'deploymentuser@cvent.com');*/
       
        User u = [Select Id From User Where Name like '%deployment%' limit 1];
        
        CountryCode__c country = new CountryCode__c();
        country.Name = 'US';
        country.Code__c  = 'US';
        insert country;
            
        CountryCode__c country2 = new CountryCode__c();
        country2.Name = 'United States';
        country2.Code__c  = 'US';
        insert country2;
            
        CountryCode__c country3 = new CountryCode__c();
        country3.Name = 'CA';
        country3.Code__c  = 'CA';
        insert country3;
        
        
        system.runAs(u){
            
           Account acc = new Account();
           acc.Name = 'Biz Account Test 1';
           acc.Phone = '(604)440-3665';
           acc.Website = 'https://testWebsite.com/test.jsp?hello=\'asdf\'&test=1';
           acc.BillingStreet = '123';
           acc.BillingCity = 'San Diego';
           acc.BillingCountry = 'US';
           acc.BillingPostalCode = '90210';
           acc.BillingState = 'CA';
           acc.EBS_Account_Id__c='99999';      
           insert acc;
           
           Contact con = new Contact();
           con.LastName = 'Test Con 1';
           con.AccountId = acc.Id;
           insert con;
           
           Address__c address = new Address__c();
           address.Type__c = 'Billing';
           address.Account__c = acc.Id;
           address.City__c='Burnaby';
           address.Province__c='BC';
           address.Country__c='CA';
           address.EBS_Site_Use_Id__c=null;
           address.CountryCode__c = 'US';
           insert address;
           
           Address__c sAddress = new Address__c();
           sAddress.Type__c = 'Shipping';
           sAddress.Account__c = acc.Id;
           saddress.City__c='Burnaby';
           saddress.Province__c='BC';
           saddress.Country__c='CA';
           saddress.EBS_Site_Use_Id__c=null;
           saddress.CountryCode__c = 'US';
           insert sAddress;
           
           Opportunity opp = new Opportunity();
           opp.Name = 'Test Opp 1';
           opp.AccountId = acc.Id;
           opp.StageName = 'Opp Identified';
           opp.CloseDate = System.today()+ 30;
           opp.Contact_Associated__c = con.Id;
           opp.Bill_To_Address__c = address.Id;
           opp.Ship_To_Address__c = sAddress.Id;
           insert opp;
           
           
           List<EBS_Orders__c> orderList = new List<EBS_Orders__c>();
           //Order 1
           EBS_Orders__c order1 = new EBS_Orders__c();
           order1.Opportunity__c = opp.Id;
           order1.EBS_Order_Number__c = 'OR-54564';
           order1.EBS_Order_Status__c = 'New';
           order1.EBS_Quote_Number__c = 'QA-154455';
           order1.EBS_Header_ID__c = '646546';
           order1.Product_Line__c = 'Event';
           
         
           
           //Order 2
           EBS_Orders__c order2 = new EBS_Orders__c();
           order2.Opportunity__c = opp.Id;
           order2.EBS_Order_Number__c = 'OR-54565';
           order2.EBS_Order_Status__c = 'New';
           order2.EBS_Quote_Number__c = 'QA-154456';
           order2.EBS_Header_ID__c = '21311';
           order2.Product_Line__c = 'Event';
           
           orderList.add(order1);
           orderList.add(order2);
           
           //insert orderList;
           
           EBS_Order_Sync_Framework__c frameWork = new EBS_Order_Sync_Framework__c();
           framework.Opportunity__c  = opp.Id;
           insert frameWork;
           
           EBS_Integration__c eIntegration = new EBS_Integration__c();
           eIntegration.Name = 'Address Integration';
           eIntegration.Object__c = 'Address__c';
           eIntegration.Map__c =true;
           eIntegration.Field__c = 'City__c';
           eIntegration.Validate__c=true;
           insert eIntegration;
           
       }
       
       Test.stopTest();
       
   }
   
   //This method test Handle New Accounts, Resync Accounts
   
   public static testmethod void testAddress(){
       
        
        Id accId = [Select Id From Account Limit 1].Id;
        
        CountryCode__c country = new CountryCode__c();
        
        country.Name = 'Canada';
        country.Code__c  = 'CA';
        insert country;
        
        CountryCode__c country2 = new CountryCode__c();
        
        country2.Name = 'PU';
        country2.Code__c  = 'PU';
        insert country2;
        
        Address__c aad=new Address__c(City__c='Burnaby',Province__c='BC',Country__c='CA',Account__c=accId,CountryCode__c='US'); //Name='Test',Address__c='1',
        insert aad;
        
        aad.Province__c='USA';
        aad.City__c='Texas';
        update aad;
        
        aad.Country__c='PU';
        aad.City__c='Sintra';
        aad.EBS_Site_Use_Id__c = '465464';
        update aad;
        
        
        IntegrationAddress.handleUpdatedAddresses(new List<Address__c>{aad},new Map<Id,Address__c>{aad.Id=>aad});
        IntegrationAddress.resyncAddress(aad.Id);
        
        delete aad; 
   }


    
}