objects/Account.object
<CustomObject>
    <fields>
        <fullName>Seed_Expiration_Date__c</fullName>
        <label>Seed Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Seed_Owner_Name__c</fullName>
        <label>Seed Owner Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SeedOwnerControllerTest.cls
// ===============================
// AUTHOR     : Shanu Aggarwal    
// CREATED DATE     : 28/04/2016
// PURPOSE     :  Test Class for Seed Owner fields on Account
// CLASS COVERED:   SeedOwnerController
// ===============================
@istest
public class SeedOwnerControllerTest{

    static testmethod void createSeedOwner(){
    
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Seed_Expiration_Date__c = Date.Today()+1;
        acc.Seed_Owner_Name__c = 'CRM User';
        insert acc;
        
        ApexPages.StandardController ctr = new ApexPages.StandardController (acc);
        SeedOwnerController sController= new SeedOwnerController(ctr);
        
        sController.Save();
        sController.cancel();
    
    }
    
}