objects/Account.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Name__c</fullName>
        <label>Affiliate Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CVII_ID__c</fullName>
        <description>Unique Customer ID - only for finance and SF
Exclude from field purging exercise</description>
        <label>NA CVII ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Status__c</fullName>
        <inlineHelpText>It is status of supplier profile on CVII.</inlineHelpText>
        <label>Supplier Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Duplicate/Not Visible</fullName>
                </value>
                <value>
                    <fullName>Not Visible</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Reflagged</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>CVENT TEST SUPPLIER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <formula>Account.Id</formula>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Id__c.object
<CustomObject>
    <fields>
        <fullName>ContactId__c</fullName>
        <label>ContactId</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This will store the Id of the Contact which needs to be deleted according to the criteria.</description>
    <label>Contact Id</label>
    <nameField>
        <displayFormat>Con-{0000000}</displayFormat>
        <label>Contact Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Ids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DeletedAccountId__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <description>Account Id which needs to be deleted</description>
        <label>Account Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Account Id which needs to be deleted.</description>
    <label>DeletedAccountId</label>
    <nameField>
        <displayFormat>DA-{00000000}</displayFormat>
        <label>DeletedAccountId Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeletedAccountIds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactDeletionBatchSchedulerTest.cls
/**=====================================================================
 * Cvent
 * Name: ContactDeletionBatchSchedulerTest
 * Description: Test Class for "ContactDeletionBatch" , "ScheduledContactDeletionBatch" ,"ContactIdDeletionBatch" , "ScheduledContactIdDeletionBatch","AccountDeletionBatch"
                 "ScheduledAccountDeletionBatch","AccountRecordDeletionBatch","ScheduledAccountRecordDeletionBatch"
 * Created Date: [10/05/2016]
 * Created By: Hemant Rana
 * 
 * Date Modified                Modified By                  Description of the update
 * [MON DD, YYYY]               [FirstName LastName]         [Short description for changes]
 =====================================================================*/ 
@isTest
public class ContactDeletionBatchSchedulerTest
{
  
    static String CRON_EXP = '0 0 0 15 3 ? 2022';
    
    static testMethod void validateScheduledContactDeletionBatch() {
        
        Account instAccount=TestUtil.createAccount('TestAccount','Biz_Ac');  // call by test util [kumud]
        instAccount.CVII_ID__c='1'; 
        instAccount.Affiliate_Name__c='Autograph Collection';
        instAccount.Supplier_Status__c = 'Not Visible';
        instAccount.BillingCountryCode='US';
        instAccount.BillingState='TX';
        insert instAccount;
        
        Test.setCreatedDate(instAccount.Id, DateTime.newInstance(2000,10,10));
       
        Contact con=TestUtil.createContact(instAccount.id);// call by test util [kumud]
        insert con;
        Test.setCreatedDate(con.Id, DateTime.newInstance(2000,10,10)); 
        
        
        Contact_Id__c conIdObj = new Contact_Id__c();
        conIdObj.ContactId__c = con.Id;
        insert conIdObj;
        
        // Add by kumud on 9 march 2018
        DeletedAccountId__c instDelAcc=new DeletedAccountId__c(Account_Id__c=instAccount.id);
        insert instDelAcc;
        
        Test.setCreatedDate(conIdObj.Id, DateTime.newInstance(2000,10,10)); 
        
       Test.StartTest();
       // Schedule the ScheduledDeleteLeadBatch
       System.schedule('ScheduledDeleteContactBatch',CRON_EXP,new ScheduledContactDeletionBatch());
       System.schedule('ScheduledContactIdDeletionBatch',CRON_EXP,new ScheduledContactIdDeletionBatch());
       System.schedule('ScheduledAccountDeletionBatch',CRON_EXP,new ScheduledAccountDeletionBatch());
       System.schedule('ScheduledAccountRecordDeletionBatch',CRON_EXP,new ScheduledAccountRecordDeletionBatch());
        Test.stopTest(); 
    }
}