objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Prospect Lead</fullName>
                </value>
                <value>
                    <fullName>Fit Lead</fullName>
                </value>
                <value>
                    <fullName>Active Lead</fullName>
                </value>
                <value>
                    <fullName>Passive Win</fullName>
                </value>
                <value>
                    <fullName>Imp Win</fullName>
                </value>
                <value>
                    <fullName>Live Win</fullName>
                </value>
                <value>
                    <fullName>End Business</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Type__c</fullName>
        <label>Supplier Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>Unique Venue</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/CRM_Project__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Release__c</fullName>
        <label>Release</label>
        <referenceTo>ResourceProject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>CRM_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ready_for_UAT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for UAT?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business User who originally requested for this project</description>
        <inlineHelpText>Business User who originally requested for this project</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Requirements</fullName>
                </value>
                <value>
                    <fullName>Waiting for Response</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deferred - Requirements Changed</fullName>
                </value>
                <value>
                    <fullName>Deferred - Dev Incomplete</fullName>
                </value>
                <value>
                    <fullName>Deferred - UAT Incomplete</fullName>
                </value>
                <value>
                    <fullName>Ready For UAT</fullName>
                </value>
                <value>
                    <fullName>UAT Sign Off Received</fullName>
                </value>
                <value>
                    <fullName>Deployed</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Requirement Complete</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
                <value>
                    <fullName>Dependancy on Refactoring</fullName>
                </value>
                <value>
                    <fullName>Partially Deployed - Data Updates Still Pending</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Ready for QA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UAT_Start_Date__c</fullName>
        <formula>CRM_Release__r.UAT_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UAT Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Project #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CRM_Project_Item__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Project__c</fullName>
        <description>Module/Project this work item is associated to</description>
        <inlineHelpText>Module/Project this work item is associated to</inlineHelpText>
        <label>CRM Project</label>
        <referenceTo>CRM_Project__c</referenceTo>
        <relationshipName>CRM_Project_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Clarification</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Configuration</fullName>
                </value>
                <value>
                    <fullName>Reports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Work Item</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>Project Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CRM_Timecard__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date for this week. Inclusive</description>
        <inlineHelpText>Start Date for this week. Inclusive</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Identifies the status of a timecard throughout the lifecycle</description>
        <inlineHelpText>Identifies the status of a timecard throughout the lifecycle</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Represents monthly effort for a team member</description>
    <label>Timecard</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Timecard #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CRM_Timecard_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>CRM_Project_Work_Item__r.CRM_Project__r.Project_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Represents the type of work</description>
        <inlineHelpText>Represents the type of work</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cases</fullName>
                    <default>true</default>
                    <label>Cases</label>
                </value>
                <value>
                    <fullName>Support/Transactional Work</fullName>
                </value>
                <value>
                    <fullName>Projects</fullName>
                </value>
                <value>
                    <fullName>Others - Dev Related</fullName>
                </value>
                <value>
                    <fullName>Others - Admin Related</fullName>
                </value>
                <value>
                    <fullName>Others - Meetings</fullName>
                </value>
                <value>
                    <fullName>On Duty - Travel</fullName>
                </value>
                <value>
                    <fullName>On Duty - CU</fullName>
                </value>
                <value>
                    <fullName>On Duty - Team Building</fullName>
                </value>
                <value>
                    <fullName>Innovation/Ideation</fullName>
                </value>
                <value>
                    <fullName>Proof of Concept/Demo</fullName>
                </value>
                <value>
                    <fullName>Training/KT</fullName>
                </value>
                <value>
                    <fullName>PTO/Holiday</fullName>
                </value>
                <value>
                    <fullName>CPQ Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Represents one entry under a given timecard</description>
    <label>Timecard Entry</label>
    <nameField>
        <label>Entry #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timecard Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ResourceProject__c.object
<CustomObject>
    <fields>
        <fullName>Deployment_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deployment Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deployment_Date__c</fullName>
        <label>Deployment Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deployment_Initiated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deployment Initiated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Release Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ready_for_UAT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for UAT?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requirements_Cut_Off_Date__c</fullName>
        <label>Requirements Cut Off Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SignOff_Reminder_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UAT Sign Off Reminder Sent ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UAT_Sign_Off_Date__c</fullName>
        <label>UAT Sign Off Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UAT_Start_Date__c</fullName>
        <label>UAT Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_ReleaseManagement2_0.cls
/* Test coverage for the Release Management and Cvent Email Notification modules */
@isTest
class Test_ReleaseManagement2_0 {
    
    
    @testsetup
    static void createTestData(){
        
        ResourceProject__c crmRelease = new ResourceProject__c();
        crmRelease.Name = 'Test Release';
        crmRelease.Project_Name__c = 'Test Release';
        crmRelease.Requirements_Cut_Off_Date__c = System.today();
        crmRelease.UAT_Sign_Off_Date__c = system.today();
        crmRelease.UAT_Start_Date__c = System.today();
        crmRelease.Deployment_Date__c = System.today();        
        insert crmRelease;
       
        List<CRM_Project__c> projectList = new List<CRM_Project__c>();
        
        CRM_Project__c project = new CRM_Project__c();
        project.CRM_Release__c = crmRelease.Id;
        project.Project_Name__c = 'Test';
        project.Requestor__c = UserInfo.GetUserId();
        project.Status__c = 'Ready For UAT';
        
        CRM_Project__c project2 = new CRM_Project__c();
        project2.CRM_Release__c = crmRelease.Id;
        project2.Project_Name__c = 'Test';
        project2.Requestor__c = UserInfo.GetUserId();
        project2.Status__c = 'UAT Sign Off Received';
        
        projectList.add(project);
        projectList.add(project2);
        
        insert projectList; 
            
        crmRelease.Ready_for_UAT__c = true;
        crmRelease.Deployment_Initiated__c = true;
        crmRelease.Deployment_Complete__c = true;
        crmRelease.SignOff_Reminder_Sent__c=true;
        update crmRelease;
    
    }
    
    static testmethod void testCase1()
    {
    
        Id releaseId = [Select Id From ResourceProject__c Limit 1 ].Id; 
        
        CRM_EmailComponentController cntl = new CRM_EmailComponentController();
        cntl.setReleaseIdCtrl(releaseId);
        cntl.getReleaseIdCtrl();
        cntl.setRequestorIdCtrl(UserInfo.GetUserId());
        cntl.getRequestorIdCtrl();
        cntl.setReadyForUATCtrl(true);
        cntl.getReadyForUATCtrl();
        cntl.setProjectStatusCtrl('New');
        cntl.getProjectStatusCtrl();
        cntl.getProjects();
        cntl.getCRMRelease();
        
        System.debug('**** releaseId *** ' + releaseId);
    } 

    static testmethod void testCase2()
    {
        
        CRM_EmailComponentController cntl = new CRM_EmailComponentController();
        cntl.setRequestorIdCtrl(UserInfo.GetUserId());
        cntl.getRequestorIdCtrl();
        cntl.getProjects();

    }    
    
    static testmethod void testCaseTimeCards1()
    {
        
        RecordType rtType = [SELECT r.SobjectType, r.DeveloperName,r.IsActive FROM RecordType r WHERE SobjectType='Account' AND DeveloperName='Biz_Ac' And IsActive = true];

        Account instofAcc = new Account();
        instofAcc.Supplier_Type__c = 'Venue';
        instofAcc.Venue_Type__c = 'CVB';
        instofAcc.RecordTypeId = rtType.id;
        instofAcc.Name = 'Test';
        insert instofAcc;
    
        Contact instContact = new Contact();
        instContact.LastName = 'Test';
        instContact.AccountId = instofAcc.Id;
        instContact.CT_Contact_Status__c= 'Open Opportunity';
        instContact.Event_Contact_Status__c = 'Open Opportunity';
        instContact.TM_Contact_Status__c = 'Open Opportunity';
        instContact.LeadSource = 'WEB-Chat (CrowdCompass)';
        insert instContact;
    
        Id projectId = [Select Id From CRM_Project__c Limit 1 ].Id;
        
        CRM_Project_Item__c cItem = new CRM_Project_Item__c();
        cItem.CRM_Project__c =  projectId;
        cItem.Subject__c = 'Test';
        cItem.Estimated_Effort_Hours__c = 15;
        //cItem.Requestor__c  = instContact.Id ;
        insert cItem;
              
        
        CRM_Timecard__c t = new CRM_Timecard__c();
        t.Team_Member__c = UserInfo.getUserId();
        t.Approver_Email__c = 'test@testcvent.com';
        t.Start_Date__c = System.today() - 7;
        t.End_Date__c = System.today();
        t.Description__c = 'Test';
        insert t;
        
        CRM_Timecard_Entry__c cEntry = new CRM_Timecard_Entry__c();
        cEntry.CRM_Project_Work_Item__c = cItem.Id ;
        cEntry.User__c = UserInfo.getUserId();
        cEntry.Type__c = 'Cases';
        cEntry.CRM_Timecard__c = t.Id ;
        insert cEntry;
        
            
        CRM_MyTimeCardController cntl = new CRM_MyTimeCardController(new ApexPages.StandardController(t));
        cntl.selectedTimecardId = t.Id;
        cntl.refreshDropDowns();
        cntl.getSelectedTimecardId();
        cntl.reloadCurrentTimecard();
        cntl.selectTimecardAction();
        cntl.addEntryAction();
        
        List<CRM_Timecard_Entry__c> entries = [select Id from CRM_Timecard_Entry__c where CRM_Timecard__c =: t.Id limit 1];
        cntl.selectedEntryId = entries[0].Id;
        
        cntl.repopulateTimecardEntries();
        cntl.getIsValidTimecard();
        cntl.getEntryTypeOptions();
        cntl.saveAction();
        cntl.refreshAutoEntriesAction();
        cntl.autoGenerateEntriesAction();
        //cntl.deleteAction();
        cntl.doNothing();
        cntl.submitApprovalAction();
        cntl.approveAction();
        cntl.rejectAction();
        cntl.selectEntryTypeAction();
        cntl.getRecordCount();
        
        delete cEntry;
    }      
}