objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/EB_SB_Builder__c.object
<CustomObject>
    <fields>
        <fullName>AccountCustom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EB SB Projects</relationshipLabel>
        <relationshipName>EB_SB_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N00000008IWSzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Title__c</fullName>
        <label>Event Title(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Complexity__c</fullName>
        <label>Project Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Simple</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>3-Advanced</fullName>
                </value>
                <value>
                    <fullName>4-Complex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Stage__c</fullName>
        <label>Project Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Information Received</fullName>
                </value>
                <value>
                    <fullName>Setup Call Scheduled</fullName>
                </value>
                <value>
                    <fullName>Setup Call Done</fullName>
                </value>
                <value>
                    <fullName>Working on First Draft</fullName>
                </value>
                <value>
                    <fullName>First Draft Completed</fullName>
                </value>
                <value>
                    <fullName>First Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>First Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Second Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Second Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Third Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Third Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Fourth Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Fourth Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Additional Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>All the Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Event Testing</fullName>
                </value>
                <value>
                    <fullName>Event Launched</fullName>
                </value>
                <value>
                    <fullName>Sign Off Done</fullName>
                </value>
                <value>
                    <fullName>Premium Services - Post Launch Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Status_del__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yet To Start</fullName>
                </value>
                <value>
                    <fullName>Information Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Post Launch Support</fullName>
                </value>
                <value>
                    <fullName>On Hold - Leadership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type_del__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abstract Management Build</fullName>
                </value>
                <value>
                    <fullName>Additional Changes</fullName>
                </value>
                <value>
                    <fullName>Affinity Partner Build</fullName>
                </value>
                <value>
                    <fullName>Affinity Partner Build - Premium</fullName>
                </value>
                <value>
                    <fullName>AllianceTech - EMT Build</fullName>
                </value>
                <value>
                    <fullName>Appointments Build</fullName>
                </value>
                <value>
                    <fullName>ARA - Active</fullName>
                </value>
                <value>
                    <fullName>ARA - Inactive</fullName>
                </value>
                <value>
                    <fullName>ARA Projects</fullName>
                </value>
                <value>
                    <fullName>Creative Services - EB</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Premium</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Regular</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Rush</fullName>
                </value>
                <value>
                    <fullName>Custom Pages</fullName>
                </value>
                <value>
                    <fullName>Custom Task</fullName>
                </value>
                <value>
                    <fullName>Daily/Monthly Report</fullName>
                </value>
                <value>
                    <fullName>Dedicated Support</fullName>
                </value>
                <value>
                    <fullName>Demo eMarketing</fullName>
                </value>
                <value>
                    <fullName>Demo Event</fullName>
                </value>
                <value>
                    <fullName>Demo Survey</fullName>
                </value>
                <value>
                    <fullName>EB Mentoring</fullName>
                </value>
                <value>
                    <fullName>EMT Build</fullName>
                </value>
                <value>
                    <fullName>Enterprise Project</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Express</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Premium</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Premium Rush</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Regular</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Rush</fullName>
                </value>
                <value>
                    <fullName>Event Builder - SU4</fullName>
                </value>
                <value>
                    <fullName>Event Quarterback Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Builder</fullName>
                    <default>true</default>
                    <label>Event Builder</label>
                </value>
                <value>
                    <fullName>Survey Builder</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Graphics</fullName>
                </value>
                <value>
                    <fullName>Demo Builder (for Harmeet's Team)</fullName>
                </value>
                <value>
                    <fullName>Creative Services</fullName>
                </value>
                <value>
                    <fullName>Scope Call</fullName>
                </value>
                <value>
                    <fullName>Internal Events</fullName>
                </value>
                <value>
                    <fullName>TPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains all EB/SB projects</description>
    <label>EB SB Project</label>
    <nameField>
        <displayFormat>Project-{YYYY}{MM}-{0000}</displayFormat>
        <label>EB/SB Builders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EB SB Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Legal Review – Procurement Contract</description>
    <label>Procurement</label>
    <nameField>
        <label>Procurement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PopulateTimerDataEBProject_TrigAct_Test.cls
/*************************************************
* Author : Sandeep Kumar
* Date : 21 Nov 2017
* Description : It tests below mentioned classes
* 1) PopulateTimerDataOnEBProject_TrigAct
**************************************************/
@isTest(seeAllData=false)
public class PopulateTimerDataEBProject_TrigAct_Test {
    private static Case caseObj,caseObj2;
    private static Account accObj; 
    private static AccountTeamMember atmObj;
    private static Contact conObj;
    private static EB_SB_Builder__c EBSBRec,EBSBRec2;
    private static List<Case> caseList;
    private static List<EB_SB_Builder__c> eBProjectList;
    private static User depUser = [Select Id, ProfileId from User where Name = 'CRM Deployment User'];  
    private static Id userProfieId = UserProfileUtil.getProfileIDByName('Customer Care Rep - Product Consultant EB Team');    
    
    public static void setupData(){        
        // Create Account Record.
        accObj = TestUtil.createAccount('EB Account 1', 'Biz_Ac');
        insert accObj;     
        
        atmObj = TestUtil.createATM(accObj.Id,depUser.Id);
        atmObj.TeamMemberRole = 'AM - Event';
        insert atmObj;
        
        // Create Contact Record.
        conObj = TestUtil.createContact(accObj.Id);
        insert conObj; 
        
        eBProjectList = new List<EB_SB_Builder__c>();
        // Create Eb Project.
        EBSBRec = new EB_SB_Builder__c();
        EBSBRec.Contact__c = conObj.Id;
        EBSBRec.AccountCustom__c = accObj.Id;                 
        EBSBRec.Project__c = 'Event Builder';
        EBSBRec.Project_Status_del__c = 'Yet To Start';            
        EBSBRec.Project_Stage__c = 'Information Received';
        EBSBRec.Project_Complexity__c = '1-Simple';
        EBSBRec.Project_Type_del__c = 'Event Builder - Regular';            
        EBSBRec.Event_Title__c = '';
        eBProjectList.add(EBSBRec);
        
        // Create Eb Project.
        EBSBRec2 = new EB_SB_Builder__c();
        EBSBRec2.Contact__c = conObj.Id;
        EBSBRec2.AccountCustom__c = accObj.Id;                 
        EBSBRec2.Project__c = 'Event Builder';
        EBSBRec2.Project_Status_del__c = 'Yet To Start';              
        EBSBRec2.Project_Stage__c = 'Information Received';
        EBSBRec2.Project_Complexity__c = '1-Simple';
        EBSBRec2.Project_Type_del__c = 'Additional Changes'; 
        eBProjectList.add(EBSBRec2);
        
        insert eBProjectList;
        
        caseList = new List<Case>();
        
        caseObj = new Case();
        caseObj.AccountId = accObj.Id;
        caseObj.SuppliedEmail = 'testcontact1@test.com';
        caseObj.RecordTypeId = RecordTypeUtil.getRecordTypeIDByDevName('Case','Eventbuilder');
        caseObj.Status = 'Open';
        caseObj.OwnerId = depUser.Id;
        caseObj.Priority = 'Medium';
        caseObj.Origin = 'Admin';
        caseObj.Client_Services_Category__c = 'Set-up Call';
        caseObj.Subject = 'Test Case for Timer Update 1.';
        caseObj.Description = 'Please refer the attached email for more information.'; 
        caseObj.Event_Survey_Builder__c = eBProjectList[0].Id;
        caseList.add(caseObj); 
        
        caseObj = new Case();
        caseObj.AccountId = accObj.Id;
        caseObj.SuppliedEmail = 'testcontact1@test.com';
        caseObj.RecordTypeId = RecordTypeUtil.getRecordTypeIDByDevName('Case','Eventbuilder');
        caseObj.Status = 'Open';
        caseObj.OwnerId = depUser.Id;
        caseObj.Priority = 'Medium';
        caseObj.Origin = 'Admin';
        caseObj.Client_Services_Category__c = 'Set-up Call';
        caseObj.Subject = 'Test Case for Timer Update 1.';
        caseObj.Description = 'Please refer the attached email for more information.'; 
        caseObj.Event_Survey_Builder__c = eBProjectList[0].Id;
        caseList.add(caseObj); 
        
        caseObj2 = new Case();
        caseObj2.AccountId = accObj.Id;
        caseObj2.SuppliedEmail = 'testcontact2@test.com';
        caseObj2.RecordTypeId = RecordTypeUtil.getRecordTypeIDByDevName('Case','Creative_Services');
        caseObj2.Status = 'Open';
        caseObj2.Priority = 'Medium';
        caseObj2.OwnerId = depUser.Id;
        caseObj2.Origin = 'Admin';
        caseObj2.Client_Services_Category__c = 'Set-up Call';
        caseObj2.Subject = 'Test Case for Timer Update 2.';
        caseObj2.Description = 'Please refer the attached email for more information.';   
        caseObj2.Event_Survey_Builder__c = eBProjectList[0].Id;
        caseList.add(caseObj2);
        
        caseObj2 = new Case();
        caseObj2.AccountId = accObj.Id;
        caseObj2.SuppliedEmail = 'testcontact2@test.com';
        caseObj2.RecordTypeId = RecordTypeUtil.getRecordTypeIDByDevName('Case','Creative_Services');
        caseObj2.Status = 'Open';
        caseObj2.Priority = 'Medium';
        caseObj2.OwnerId = depUser.Id;
        caseObj2.Origin = 'Admin';
        caseObj2.Client_Services_Category__c = 'Set-up Call';
        caseObj2.Subject = 'Test Case for Timer Update 2.';
        caseObj2.Description = 'Please refer the attached email for more information.';   
        caseObj2.Event_Survey_Builder__c = eBProjectList[0].Id;
        caseList.add(caseObj2);
        
        insert caseList;
        
        caseList[0].OwnerId = depUser.Id;
        caseList[1].OwnerId = depUser.Id;
        caseList[2].OwnerId = depUser.Id;
        caseList[3].OwnerId = depUser.Id;
        update caseList;
    }
    
    static testMethod void updateTimeOnEBSB(){
        Test.startTest();
        // Call below method to load test Data.
        setupData();
        // create Timing record for Case 1
        WorkIt2__Timing__c timingObj1 = new WorkIt2__Timing__c();
        timingObj1.WorkIt2__Case__c = caseList[0].Id;
        insert timingObj1;
        
        // create Time Entry record for the above Timing
        WorkIt2__Time_Entry__c timeEntryObj1 = new WorkIt2__Time_Entry__c();
        timeEntryObj1.WorkIt2__Timing__c = timingObj1.Id;
        timeEntryObj1.WorkIt2__Start__c = System.now().addHours(-10);
        timeEntryObj1.WorkIt2__Heartbeat__c = System.now().addHours(-9);
        insert timeEntryObj1;
        
        System.debug('Timing Record Cal 1 Before = '+[Select Id,WorkIt2__Time_In_Seconds__c From WorkIt2__Timing__c Where Id =:timingObj1.Id].WorkIt2__Time_In_Seconds__c);
        
        WorkIt2__Time_Entry__c timeEntryToUpdate = [Select Id From WorkIt2__Time_Entry__c Where Id =:timeEntryObj1.Id];
        // Update Timing Entry record
        timeEntryToUpdate.WorkIt2__Heartbeat__c = System.now().addHours(-8);
        update timeEntryToUpdate;
        
        System.debug('Timing Record Cal 1 After = '+[Select Id,WorkIt2__Time_In_Seconds__c From WorkIt2__Timing__c Where Id =:timingObj1.Id].WorkIt2__Time_In_Seconds__c);
        
        // create Timing record for Case 2
        WorkIt2__Timing__c timingObj2 = new WorkIt2__Timing__c();
        timingObj2.WorkIt2__Case__c = caseList[1].Id;
        TriggerAction.resetAllHasRun();
        insert timingObj2;
        
        // create Time Entry record for the above Timing
        WorkIt2__Time_Entry__c timeEntryObj2 = new WorkIt2__Time_Entry__c();
        timeEntryObj2.WorkIt2__Timing__c = timingObj2.Id;
        timeEntryObj2.WorkIt2__Start__c = System.now().addHours(-10);        
        timeEntryObj2.WorkIt2__Heartbeat__c = System.now().addHours(-9);
        insert timeEntryObj2;
        
        System.debug('Timing Record Cal 2 Before = '+[Select Id,WorkIt2__Time_In_Seconds__c From WorkIt2__Timing__c Where Id =:timingObj2.Id].WorkIt2__Time_In_Seconds__c);
        
        WorkIt2__Time_Entry__c timeEntryToUpdate2 = [Select Id From WorkIt2__Time_Entry__c Where Id =:timeEntryObj2.Id];
        // Update Timing Entry record
        timeEntryToUpdate2.WorkIt2__Heartbeat__c = System.now().addHours(-8);
        timeEntryToUpdate2.WorkIt2__Force_End__c = System.now().addHours(-7);
        update timeEntryToUpdate2;     
        
        System.debug('Timing Record Cal 2 After = '+[Select Id,WorkIt2__Time_In_Seconds__c From WorkIt2__Timing__c Where Id =:timingObj2.Id].WorkIt2__Time_In_Seconds__c);
        Test.stopTest();
    }
}