objects/Account.object
<CustomObject>
    <fields>
        <fullName>EBS_Account_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise
Exclude from field purging exercise</description>
        <label>EBS Account ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account to which this Additional Address record is related.
This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <inlineHelpText>The Account to which this Additional Address record is related.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Additional_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Remittance</fullName>
                    <default>true</default>
                    <label>Remittance</label>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EBS_Integration__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Map__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Map</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validate</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>EBS Integration</label>
</CustomObject>

objects/EBS_Order_Sync_Framework__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links to the Closed Won Opportunity which is to be sent over to EBS</description>
        <label>Opportunity (Related Order)</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EBS Order Sync Framework</relationshipLabel>
        <relationshipName>EBS_Order_Sync_Framework</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>This object would be used to control the Opportunity (Order) Sync process with EBS by ensuring that all dependencies like Account (new customer), associated  Addresses, Contacts and Contact Addresses have a valid EBS Id and if not, sync them with EBS first before pushing the Order. It does this by generating and queuing multiple Integration Queue records.</description>
    <label>EBS Order Sync Framework</label>
    <nameField>
        <displayFormat>OS-{00000000}</displayFormat>
        <label>Order Sync Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Order Sync Framework</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EBS_Orders__c.object
<CustomObject>
    <fields>
        <fullName>EBS_Header_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <externalId>true</externalId>
        <label>EBS Header ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EBS_Order_Number__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Order_Status__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Order Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Quote_Number__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Quote Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EBS Orders</relationshipLabel>
        <relationshipName>EBS_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EBS Order</label>
    <nameField>
        <displayFormat>EBS-{00000}</displayFormat>
        <label>EBS Orders</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CS_AccountTriggerHandlerTest.cls
/**
*    
*   Author: Shanu Aggarwal
*   Date Added : 23-05-2017
*   This class tests the functionality of CS_AccountTriggerHandler
* 
*/
@istest
public class CS_AccountTriggerHandlerTest {
   
   @testsetup
   public static void CreateTestData(){
        
        Test.startTest();
        //Inserting User...............
        Profile p = [SELECT Id FROM Profile WHERE Name='Finance - Management']; 
    
        USerrole[] testroleId=[select id from userRole where name ='AM (Event)' OR name ='Pre Sales - Special Projects' limit 2];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Sops', LanguageLocaleKey='en_US', FirstName='TestUser',
        LocaleSidKey='en_US', ProfileId = p.Id, userRoleId=testroleId[0].id,
        TimeZoneSidKey='America/Los_Angeles', UserName='Test'+'deploymentuser@cvent.com');
        
        
        system.runAs(u){
            
           Account acc = TestUtil.createAccount('Test Account','Biz_Ac');   
           insert acc;
           
           Contact con = new Contact();
           con.LastName = 'Test Con 1';
           con.AccountId = acc.Id;
           insert con;
           
           Address__c address = new Address__c();
           address.Type__c = 'Billing';
           address.Account__c = acc.Id;
           insert address;
           
           Address__c sAddress = new Address__c();
           sAddress.Type__c = 'Shipping';
           sAddress.Account__c = acc.Id;
           insert sAddress;
           
           Opportunity opp = new Opportunity();
           opp.Name = 'Test Opp 1';
           opp.AccountId = acc.Id;
           opp.StageName = 'Opp Identified';
           opp.CloseDate = System.today()+ 30;
           opp.Contact_Associated__c = con.Id;
           opp.Bill_To_Address__c = address.Id;
           opp.Ship_To_Address__c = sAddress.Id;
           insert opp;
           
           
           List<EBS_Orders__c> orderList = new List<EBS_Orders__c>();
           //Order 1
           EBS_Orders__c order1 = new EBS_Orders__c();
           order1.Opportunity__c = opp.Id;
           order1.EBS_Order_Number__c = 'OR-54564';
           order1.EBS_Order_Status__c = 'New';
           order1.EBS_Quote_Number__c = 'QA-154455';
           order1.EBS_Header_ID__c = '646546';
           order1.Product_Line__c = 'Event';
           
         
           
           //Order 2
           EBS_Orders__c order2 = new EBS_Orders__c();
           order2.Opportunity__c = opp.Id;
           order2.EBS_Order_Number__c = 'OR-54565';
           order2.EBS_Order_Status__c = 'New';
           order2.EBS_Quote_Number__c = 'QA-154456';
           order2.EBS_Header_ID__c = '21311';
           order2.Product_Line__c = 'Event';
           
           orderList.add(order1);
           orderList.add(order2);
           
           //insert orderList;
           
           EBS_Order_Sync_Framework__c frameWork = new EBS_Order_Sync_Framework__c();
           framework.Opportunity__c  = opp.Id;
           insert frameWork;
           
           EBS_Integration__c eIntegration = new EBS_Integration__c();
           eIntegration.Name = 'Account Integration';
           eIntegration.Object__c = 'Account';
           eIntegration.Map__c =true;
           eIntegration.Field__c = 'Name';
           eIntegration.Validate__c=true;
           insert eIntegration;
           
       }
       
       Test.stopTest();
       
   }
    
   //This method tests account address
   public static testmethod void testAccountAddress(){
       Account acc = [Select Id,Name,ShippingStreet,LastModifiedById,EBS_Account_ID__c from Account Limit 1 ];
       acc.ShippingStreet = 'CA';
       acc.BillingStreet = 'SA';
       
       update acc;
   }
   
   public static testMethod void testFake(){
       CS_AccountTriggerHandler.fakeMethod();
   }
    
}