objects/Account.object
<CustomObject>
    <fields>
        <fullName>Supplier_Type__c</fullName>
        <label>Supplier Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>Unique Venue</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue_Type__c</fullName>
        <label>Venue/Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Supplier_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Above- Property Account</fullName>
                </value>
                <value>
                    <fullName>Aquarium / Zoo</fullName>
                </value>
                <value>
                    <fullName>Arena / Stadium</fullName>
                </value>
                <value>
                    <fullName>AV / Production &amp; Design</fullName>
                </value>
                <value>
                    <fullName>Banquet Facility</fullName>
                </value>
                <value>
                    <fullName>Bar / Club</fullName>
                </value>
                <value>
                    <fullName>Boutique Hotel</fullName>
                </value>
                <value>
                    <fullName>Caterers / Food Services</fullName>
                </value>
                <value>
                    <fullName>Conference Center</fullName>
                </value>
                <value>
                    <fullName>Convention Center</fullName>
                </value>
                <value>
                    <fullName>Corporate Office Space</fullName>
                </value>
                <value>
                    <fullName>CVB</fullName>
                </value>
                <value>
                    <fullName>CVB/DMC</fullName>
                </value>
                <value>
                    <fullName>Educational Facility</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Entertainment Venue</fullName>
                </value>
                <value>
                    <fullName>Event hospitality &amp; entertainment Limited</fullName>
                </value>
                <value>
                    <fullName>Event Management / DMCs</fullName>
                </value>
                <value>
                    <fullName>Event Management Services</fullName>
                </value>
                <value>
                    <fullName>Event Rentals / Decor</fullName>
                </value>
                <value>
                    <fullName>Exposition Center</fullName>
                </value>
                <value>
                    <fullName>Gallery / Museum</fullName>
                </value>
                <value>
                    <fullName>Golf Course</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Internal Value</fullName>
                </value>
                <value>
                    <fullName>Luxury Hotel</fullName>
                </value>
                <value>
                    <fullName>Mail / Shipping Services</fullName>
                </value>
                <value>
                    <fullName>Movie Theatre</fullName>
                </value>
                <value>
                    <fullName>Printing / Marketing Services</fullName>
                </value>
                <value>
                    <fullName>Promotional Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/BillingCase__c.object
<CustomObject>
    <fields>
        <fullName>CVII_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>CVII ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomersAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer's Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Cases</relationshipLabel>
        <relationshipName>R00N00000006yN6SEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Case</label>
    <nameField>
        <label>Billing Cases</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WriteOff__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Value__c</fullName>
        <label>Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_TCV_To_Be_Moved__c</fullName>
        <label>New TCV To Be Moved</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office_Location__c</fullName>
        <label>Office Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>OA</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>UAE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CrowdCompass</fullName>
                </value>
                <value>
                    <fullName>CrowdTorch</fullName>
                </value>
                <value>
                    <fullName>CSN</fullName>
                </value>
                <value>
                    <fullName>Cvent CONNECT</fullName>
                </value>
                <value>
                    <fullName>Decision Street</fullName>
                </value>
                <value>
                    <fullName>Double Dutch</fullName>
                </value>
                <value>
                    <fullName>EMI</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Lanyon Events</fullName>
                </value>
                <value>
                    <fullName>Lanyon Group</fullName>
                </value>
                <value>
                    <fullName>Lanyon Meetings</fullName>
                </value>
                <value>
                    <fullName>Lanyon Passkey</fullName>
                </value>
                <value>
                    <fullName>Lanyon Transient</fullName>
                </value>
                <value>
                    <fullName>Lanyon Travel</fullName>
                </value>
                <value>
                    <fullName>OA-Enterprise</fullName>
                </value>
                <value>
                    <fullName>OA-Universal Leads</fullName>
                </value>
                <value>
                    <fullName>Onsite Solutions</fullName>
                </value>
                <value>
                    <fullName>Quick Mobile</fullName>
                </value>
                <value>
                    <fullName>SMM</fullName>
                </value>
                <value>
                    <fullName>Social Tables</fullName>
                </value>
                <value>
                    <fullName>SUFEVE</fullName>
                </value>
                <value>
                    <fullName>SUFMO1</fullName>
                </value>
                <value>
                    <fullName>SUFMOB</fullName>
                </value>
                <value>
                    <fullName>SUFSMM</fullName>
                </value>
                <value>
                    <fullName>SUFTPP</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>TPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shut_Down_Required__c</fullName>
        <label>Shut Down Required</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Contract_Billed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Contract Billed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Overage_Billed__c</fullName>
        <label>Total Overage Billed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tax_Billed__c</fullName>
        <label>Total Tax Billed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Cancellation__c</fullName>
        <label>Type of Cancellation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Cancellation Error</fullName>
                </value>
                <value>
                    <fullName>Cancellation post rebilling</fullName>
                </value>
                <value>
                    <fullName>Contract Processing Error</fullName>
                </value>
                <value>
                    <fullName>Forgiven/Settlement by Billing</fullName>
                </value>
                <value>
                    <fullName>Forgiven/Settlement by Sales Team</fullName>
                </value>
                <value>
                    <fullName>Future Billing Edit</fullName>
                </value>
                <value>
                    <fullName>Invoicing Error</fullName>
                </value>
                <value>
                    <fullName>Only Tax</fullName>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                </value>
                <value>
                    <fullName>Refund Request</fullName>
                </value>
                <value>
                    <fullName>Renegotiated Cancellation</fullName>
                </value>
                <value>
                    <fullName>Retroactive Cancellation</fullName>
                </value>
                <value>
                    <fullName>Revenue Accounting</fullName>
                </value>
                <value>
                    <fullName>Sales Error</fullName>
                </value>
                <value>
                    <fullName>Shopify Tax Cancellation</fullName>
                </value>
                <value>
                    <fullName>Technical Error</fullName>
                </value>
                <value>
                    <fullName>Update Rescheduling</fullName>
                </value>
                <value>
                    <fullName>Withhold Tax Cancellation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Shut_Down__c</fullName>
        <label>Type of Shut Down</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Blade/Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Write_Off_Status__c</fullName>
        <label>Write-Off Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initially Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Submitted for Review</fullName>
                </value>
                <value>
                    <fullName>Error with Canx Team</fullName>
                </value>
                <value>
                    <fullName>Error with AR team</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Write-Off</label>
    <nameField>
        <displayFormat>WO-{000}</displayFormat>
        <label>Case No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Write-Offs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CloneWriteOffObj_ControllerExt_Test.cls
@isTest
public class CloneWriteOffObj_ControllerExt_Test {   
    private Static Account accObj;
    private Static BillingCase__c billCaseObj;
    private Static WriteOff__c WrOffObj;
    private Static final RecordType recType = [SELECT r.SobjectType, r.DeveloperName,r.IsActive FROM RecordType r WHERE SobjectType='Account' And DeveloperName='Biz_Ac' And IsActive=true];
    
    //Create new Account Record
    private static Id insertAccount(){
        if(accObj == null){
            accObj = new Account();
            accObj.Name = 'Test';
            accObj.Supplier_Type__c = 'Venue';
            accObj.Venue_Type__c = 'CVB';
            accObj.RecordTypeId = recType.Id;
            insert accObj;
        }            
        return accObj.Id;
    }
    
    //Create new Account Record
    private static Id insertBillingCase(){
        if(billCaseObj == null){
            billCaseObj = new BillingCase__c();
            billCaseObj.CustomersAccount__c = insertAccount();
            billCaseObj.CVII_Number__c = '32323';
            billCaseObj.Name = 'Test';
            insert billCaseObj;
        }            
        return billCaseObj.Id;
    }
    
    //test data setup method
    public static void testData(){   
        //Create new Write-Off Record        
        WrOffObj = new WriteOff__c();
        WrOffObj.Type_of_Cancellation__c = 'Billing Error';
        WrOffObj.Product__c = 'Event';
        WrOffObj.Contract__c = '25512';
        WrOffObj.Write_Off_Status__c = 'Initially Approved';
        WrOffObj.New_TCV_To_Be_Moved__c ='Yes';
        WrOffObj.Total_Contract_Billed__c = 100.00;
        WrOffObj.Total_Tax_Billed__c = 100.00;
        WrOffObj.Total_Overage_Billed__c = 100.00;
        WrOffObj.Office_Location__c = 'Test Location';
        WrOffObj.Shut_Down_Required__c = 'No';
        WrOffObj.Type_of_Shut_Down__c = 'Feature';
        WrOffObj.Contract_Value__c = 38250.0;
        WrOffObj.Total_Paid__c = 12750.0;
        WrOffObj.Amount_to_be_Written_Off__c = 12750.0;
        WrOffObj.Currency_Conversion_Rate__c = 	1.0;
        WrOffObj.Customer_Name__c = insertBillingCase();
        insert WrOffObj;
    }
    // Method tests the "Save" button.
    public static testmethod void insertWriteOffRecPositiveTest(){
        Test.startTest();
        TestData();
        Test.setCurrentPage(Page.CloneWriteOffObj_Page);     
        System.currentPageReference().getParameters().put('id', WrOffObj.Id);         
        // Initialising StandardController Extension
        ApexPages.StandardController sC = new ApexPages.StandardController(WrOffObj);  
        CloneWriteOffObj_ControllerExt clnWrtOffController = new CloneWriteOffObj_ControllerExt(sC);
        WrOffObj = new WriteOff__c();
        WrOffObj.Type_of_Cancellation__c = 'Billing Error';
        WrOffObj.Product__c = 'Event';
        WrOffObj.Contract__c = '25512';
        WrOffObj.Write_Off_Status__c = 'Initially Approved';
        WrOffObj.New_TCV_To_Be_Moved__c ='Yes';
        WrOffObj.Customer_Name__c = insertBillingCase();
        clnWrtOffController.saveWriteOff();
        Test.stopTest();
    }
    // Method tests the "Save & New" button.
    public static testmethod void insertandCreateWriteOffRec(){
        Test.startTest();
        TestData();
        Test.setCurrentPage(Page.CloneWriteOffObj_Page);
        System.currentPageReference().getParameters().put('id', WrOffObj.Id);         
        // Initialising StandardController Extension
        ApexPages.StandardController sC = new ApexPages.StandardController(WrOffObj);  
        CloneWriteOffObj_ControllerExt clnWrtOffController = new CloneWriteOffObj_ControllerExt(sC);
        WrOffObj = new WriteOff__c();
        WrOffObj.Type_of_Cancellation__c = 'Billing Error';
        WrOffObj.Product__c = 'Event';
        WrOffObj.Contract__c = '25512';
        WrOffObj.Write_Off_Status__c = 'Initially Approved';
        WrOffObj.New_TCV_To_Be_Moved__c ='Yes';
        WrOffObj.Customer_Name__c = insertBillingCase();
        clnWrtOffController.saveAndNewWriteOff();
        Test.stopTest();        
    }
    // Negative test for the "Save & New" button.
    public static testmethod void insertWriteOffRecNegativeTest1(){
        Test.startTest();
        TestData();
        Test.setCurrentPage(Page.CloneWriteOffObj_Page);     
        System.currentPageReference().getParameters().put('id', WrOffObj.Id);         
        // Initialising StandardController Extension
        ApexPages.StandardController sC = new ApexPages.StandardController(WrOffObj);  
        CloneWriteOffObj_ControllerExt clnWrtOffController = new CloneWriteOffObj_ControllerExt(sC);
        WrOffObj = new WriteOff__c();
        WrOffObj.Type_of_Cancellation__c = 'Billing Error';
        // WrOffObj.Product__c = 'Event';
        WrOffObj.Contract__c = '25512';
        WrOffObj.Write_Off_Status__c = 'Initially Approved';
        // WrOffObj.New_TCV_To_Be_Moved__c ='Yes';
        WrOffObj.Customer_Name__c = insertBillingCase();
        clnWrtOffController.saveWriteOff();
        clnWrtOffController.saveAndNewWriteOff();
        Test.stopTest();
    }
    // Negative test for the "Save" button.
    public static testmethod void insertWriteOffRecNegativeTest2(){
        Test.startTest();
        TestData();
        Test.setCurrentPage(Page.CloneWriteOffObj_Page);     
        System.currentPageReference().getParameters().put('id', WrOffObj.Id);         
        // Initialising StandardController Extension
        ApexPages.StandardController sC = new ApexPages.StandardController(WrOffObj);  
        CloneWriteOffObj_ControllerExt clnWrtOffController = new CloneWriteOffObj_ControllerExt(sC);
        WrOffObj = new WriteOff__c();
        WrOffObj.Type_of_Cancellation__c = 'Billing Error';
        // WrOffObj.Product__c = 'Event';
        WrOffObj.Contract__c = '25512';
        WrOffObj.Write_Off_Status__c = 'Initially Approved';
        // WrOffObj.New_TCV_To_Be_Moved__c ='Yes';
        WrOffObj.Customer_Name__c = insertBillingCase();
        clnWrtOffController.saveAndNewWriteOff();
        clnWrtOffController.saveWriteOff();
        Test.stopTest();
    }
}