objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Acct_Status__c</fullName>
        <label>CC Acct Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                    <default>true</default>
                    <label>Untouched</label>
                </value>
                <value>
                    <fullName>Working/No traction yet</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Progress_Values__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This is used in the TopAccount Vf Page.</description>
    <label>Account Progress Values</label>
</CustomObject>

objects/Current_Status__c.object
<CustomObject>
    <fields>
        <fullName>Account_Progress__c</fullName>
        <label>Event Core Account Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Engaged buyer</fullName>
                </value>
                <value>
                    <fullName>Presentation scheduled</fullName>
                </value>
                <value>
                    <fullName>Correct Contacts Identified</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Price Quote/Proposal</fullName>
                </value>
                <value>
                    <fullName>Negotiation</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Using Competitor/Keeping in Touch</fullName>
                </value>
                <value>
                    <fullName>No Opportunity / Not a Fit</fullName>
                </value>
                <value>
                    <fullName>Active Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Parent</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Parent &amp; Subsidiary</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Sourcing</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Subsidiary</fullName>
                </value>
                <value>
                    <fullName>Completely Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - CT</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in CSN</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in Event</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in Mobile</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch -  Interested in SMM</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                    <default>true</default>
                    <label>No Contact</label>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Acct_Status__c</fullName>
        <label>Mobile Solutions Account Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                    <default>true</default>
                    <label>Untouched</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Engaged buyer</fullName>
                </value>
                <value>
                    <fullName>Presentation scheduled</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Current_Status</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>A/c Status</label>
    <nameField>
        <displayFormat>CS{0000}</displayFormat>
        <label>Current Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>A/c Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TopAccountExtensionTest.cls
/**
**  Class: TopAccountExtension
**/
@istest
public class TopAccountExtensionTest {
    
    public static testmethod void testaccountProgress(){
        
        Account_Progress_Values__c setting = new Account_Progress_Values__c();
        setting.Name = '1';
        setting.Value__c = 'Closed Won';
        insert setting;
                
		Id recTypeId = Schema.SObjectType.Current_Status__c.getRecordTypeInfosByName().get('Top Accounts').getRecordTypeId();

        Account Acc = new account (name = 'testname' );
        insert Acc;
        
        Current_Status__c c = new Current_Status__c (Account_Progress__c = 'Closed Won',Parent_Account__c= Acc.Id,CC_Acct_Status__c='Closed Won',RecordTypeId=recTypeId);
        insert c;
                
        Pagereference pgRef = Page.TopAccount;
        pgRef.getParameters().put('id',Acc.Id);
        test.setCurrentPageReference(pgRef);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(c);
        TopAccountExtension ext = new TopAccountExtension(controller);
        List<SelectOption> opt = ext.typeOptions;
        ext.getaccountProgressList();
        ext.getAccountProgress();
        ext.setAccountProgress('Closed Won');
        ext.Save();
        
    } 

}