objects/Account.object
<CustomObject>
    <fields>
        <fullName>Integration__c</fullName>
        <label>Integration</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hyatt Envision</fullName>
                </value>
                <value>
                    <fullName>Meeting Broker</fullName>
                </value>
                <value>
                    <fullName>Marriott SFA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bundle_Card__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bundle Cards</relationshipLabel>
        <relationshipName>Bundle_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oversold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post Purchase Concern</label>
        <type>Checkbox</type>
    </fields>
    <label>Bundle Card</label>
    <nameField>
        <displayFormat>BCard-{0000}</displayFormat>
        <label>Bundle Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Experiential_Survey_Invitation__c</fullName>
        <description>This field is used to capture the Last Experiential Survey that has been sent to Client</description>
        <label>Last Experiential Inquisium Invitation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <description>Created to get the profile of the CS Rep who is updating the mood. This is required so that we can check it in the workflow and make sure it does not send email laerts when mood is updated by Sales team.</description>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EB_SB_Builder__c.object
<CustomObject>
    <fields>
        <fullName>AccountCustom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EB SB Projects</relationshipLabel>
        <relationshipName>EB_SB_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N00000008IWSzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration__c</fullName>
        <label>Integration</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Crowd Compass</fullName>
                </value>
                <value>
                    <fullName>Crowd Compass – ABP</fullName>
                </value>
                <value>
                    <fullName>Marketo</fullName>
                </value>
                <value>
                    <fullName>Sales Force</fullName>
                </value>
                <value>
                    <fullName>Passkey</fullName>
                </value>
                <value>
                    <fullName>Concur</fullName>
                </value>
                <value>
                    <fullName>Eloqua</fullName>
                </value>
                <value>
                    <fullName>Membership Management</fullName>
                </value>
                <value>
                    <fullName>Appointments</fullName>
                </value>
                <value>
                    <fullName>Abstract Management</fullName>
                </value>
                <value>
                    <fullName>Lead Capture</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oversold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post Purchase Concern</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Complexity__c</fullName>
        <label>Project Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Simple</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>3-Advanced</fullName>
                </value>
                <value>
                    <fullName>4-Complex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yet to Start</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type_del__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abstract Management Build</fullName>
                </value>
                <value>
                    <fullName>Additional Changes</fullName>
                </value>
                <value>
                    <fullName>Affinity Partner Build</fullName>
                </value>
                <value>
                    <fullName>Affinity Partner Build - Premium</fullName>
                </value>
                <value>
                    <fullName>AllianceTech - EMT Build</fullName>
                </value>
                <value>
                    <fullName>Appointments Build</fullName>
                </value>
                <value>
                    <fullName>ARA - Active</fullName>
                </value>
                <value>
                    <fullName>ARA - Inactive</fullName>
                </value>
                <value>
                    <fullName>ARA Projects</fullName>
                </value>
                <value>
                    <fullName>Creative Services - EB</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Premium</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Regular</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Rush</fullName>
                </value>
                <value>
                    <fullName>Custom Pages</fullName>
                </value>
                <value>
                    <fullName>Custom Task</fullName>
                </value>
                <value>
                    <fullName>Daily/Monthly Report</fullName>
                </value>
                <value>
                    <fullName>Dedicated Support</fullName>
                </value>
                <value>
                    <fullName>Demo eMarketing</fullName>
                </value>
                <value>
                    <fullName>Demo Event</fullName>
                </value>
                <value>
                    <fullName>Demo Survey</fullName>
                </value>
                <value>
                    <fullName>EB Mentoring</fullName>
                </value>
                <value>
                    <fullName>EMT Build</fullName>
                </value>
                <value>
                    <fullName>Enterprise Project</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Express</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Premium</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Premium Rush</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Regular</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Rush</fullName>
                </value>
                <value>
                    <fullName>Event Builder - SU4</fullName>
                </value>
                <value>
                    <fullName>Event Quarterback Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Builder</fullName>
                    <default>true</default>
                    <label>Event Builder</label>
                </value>
                <value>
                    <fullName>Survey Builder</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Graphics</fullName>
                </value>
                <value>
                    <fullName>Demo Builder (for Harmeet's Team)</fullName>
                </value>
                <value>
                    <fullName>Creative Services</fullName>
                </value>
                <value>
                    <fullName>Scope Call</fullName>
                </value>
                <value>
                    <fullName>Internal Events</fullName>
                </value>
                <value>
                    <fullName>TPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Invitation_Sent__c</fullName>
        <label>Survey Invitation Sent</label>
        <type>DateTime</type>
    </fields>
    <description>Contains all EB/SB projects</description>
    <label>EB SB Project</label>
    <nameField>
        <displayFormat>Project-{YYYY}{MM}-{0000}</displayFormat>
        <label>EB/SB Builders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EB SB Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Mobile_Card__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Account_New__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CC_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oversold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post Purchase Concern</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Invitation_Sent__c</fullName>
        <label>Survey Invitation Sent</label>
        <type>DateTime</type>
    </fields>
    <description>Track Projects for Mobile App Builders in SF</description>
    <label>Mobile App</label>
    <nameField>
        <label>Mobile Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MobileAppNotificationUser__c.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>This list contains users which will be sent notification for mobile app if post purchase concern checkbox is true</description>
    <label>MobileAppNotificationUser</label>
</CustomObject>

objects/Onboarding__c.object
<CustomObject>
    <fields>
        <fullName>Oversold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post Purchase Concern</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Invitation_Sent__c</fullName>
        <label>Survey Invitation Sent</label>
        <type>DateTime</type>
    </fields>
    <label>Onboarding</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Onboarding</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Survey</fullName>
        <active>true</active>
        <label>Survey</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <formula>Profile.Name</formula>
        <label>Profile Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ChatterPostNotificationTest.cls
@isTest
public class ChatterPostNotificationTest 
{
    static testMethod void testMethod1()
    {
        Profile p = [SELECT Name FROM Profile WHERE Name = 'System Administrator']; 
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Sherlin', LastName='Lauren', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com');
        insert user1;
        
        User user2 = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Daniel', LastName='Shregg', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest1@testorg.com');
        insert user2;
        
        Account acc = new Account(Name='Test Account');
        Acc.BillingCountryCode='US';
        Acc.BillingState='TX';
        Acc.BillingStateCode ='TX';
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact',AccountId = acc.Id);
        insert con;
        
        AccountTeamMemberRoles__c atms = new AccountTeamMemberRoles__c();
        atms.Name = 'AM - Event Cloud';
        insert atms;
        
        MobileAppNotificationUser__c users = new MobileAppNotificationUser__c();
        users.Name = 'Test User';
        users.Type__c = 'MobileApp';
        users.Id__c = user1.Id;
        insert users;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = acc.Id;
        atm.TeamMemberRole = 'AM - Event Cloud';
        atm.UserId = user1.Id; 
        insert atm;
        
        Mobile_Card__c mobileCard = new Mobile_Card__c();
        mobileCard.Name = 'Test Mobile App 1';
        mobileCard.Oversold__c = true;
        mobileCard.Contract_Account_New__c = acc.Id;
        insert mobileCard;
        
        Mobile_Card__c mobileCard1 = new Mobile_Card__c();
        mobileCard1.Name = 'Test Mobile App 2';
        mobileCard1.Oversold__c = true;
        insert mobileCard1;
        
    }
    
    static testMethod void testMethod3()
    {
        Profile p = [SELECT Name FROM Profile WHERE Name = 'System Administrator']; 
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Sherlin', LastName='Lauren', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com');
        insert user1;
        
        User user2 = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Daniel', LastName='Shregg', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest1@testorg.com');
        insert user2;
        
        Account acc = new Account(Name='Test Account');
        acc.BillingCountryCode='US';
        acc.BillingState='TX';
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact',AccountId = acc.Id);
        insert con;
        
        AccountTeamMemberRoles__c atms = new AccountTeamMemberRoles__c();
        atms.Name = 'AM - Event Cloud';
        insert atms;
        
        MobileAppNotificationUser__c users = new MobileAppNotificationUser__c();
        users.Name = 'Test User';
        users.Type__c = 'MobileApp';
        users.Id__c = user1.Id;
        insert users;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = acc.Id;
        atm.TeamMemberRole = 'AM - Event Cloud';
        atm.UserId = user1.Id; 
        insert atm;
        
        Mobile_Card__c mobileCard1 = new Mobile_Card__c();
        mobileCard1.Name = 'Test Mobile App 2';
        mobileCard1.Oversold__c = true;
        insert mobileCard1;
    }
    
    static testMethod void testMethod4()
    {
        Profile p = [SELECT Name FROM Profile WHERE Name = 'System Administrator']; 
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Sherlin', LastName='Lauren', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com');
        insert user1;
        
        User user2 = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Daniel', LastName='Shregg', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest1@testorg.com');
        insert user2;
        
        Account acc = new Account(Name='Test Account');
        acc.BillingCountryCode='US';
        acc.BillingState='TX';
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact',AccountId = acc.Id);
        insert con;
        
        AccountTeamMemberRoles__c atms = new AccountTeamMemberRoles__c();
        atms.Name = 'AM - Event Cloud';
        insert atms;
        
        MobileAppNotificationUser__c users = new MobileAppNotificationUser__c();
        users.Name = 'Test User';
        users.Type__c = 'EB SB Project';
        users.Id__c = user1.Id;
        insert users;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = acc.Id;
        atm.TeamMemberRole = 'AM - Event Cloud';
        atm.UserId = user1.Id; 
        insert atm;
        
        EB_SB_Builder__c instOfEB =  new EB_SB_Builder__c();
        instOfEB.Project__c = 'Event Builder';
        instOfEB.Project_Status__c = 'Information Pending';
        instOfEB.Project_Type_del__c = 'Demo Event';
        instOfEB.Project_Complexity__c = '1-Simple';
        instOfEB.Integration__c = 'Marketo';
        instOfEB.AccountCustom__c = acc.Id;
        instOfEB.Contact__c = con.id;
        instOfEB.Oversold__c = true;
        insert instOfEB;
    }
    
    //This method covering Survey_Invitation_Sent__c for Mobile App, EBSB Project and Case Object
    static testMethod void testMethod5()
    {
        Profile p = [SELECT Name FROM Profile WHERE Name = 'System Administrator']; 
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Sherlin', LastName='Lauren', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com');
        insert user1;
        
        User user2 = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Daniel', LastName='Shregg', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest1@testorg.com');
        insert user2;
        
        Account acc = new Account(Name='Test Account');
        acc.BillingCountryCode='US';
        acc.BillingState='TX';
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact',AccountId = acc.Id,Last_Experiential_Survey_Invitation__c=system.today()+10/*,Profile_Name__c='temp profile'*/);
        insert con;
        
        AccountTeamMemberRoles__c atms = new AccountTeamMemberRoles__c();
        atms.Name = 'AM - Event Cloud';
        insert atms;
        
        MobileAppNotificationUser__c users = new MobileAppNotificationUser__c();
        users.Name = 'Test User';
        users.Type__c = 'MobileApp';
        users.Id__c = user1.Id;
        insert users;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = acc.Id;
        atm.TeamMemberRole = 'AM - Event Cloud';
        atm.UserId = user1.Id; 
        insert atm;
        
        Mobile_Card__c mobileCard1 = new Mobile_Card__c();
        mobileCard1.Name = 'Test Mobile App 2';
        mobileCard1.Primary_Contact__c = con.Id;
        mobileCard1.Survey_Invitation_Sent__c = system.today();
        mobileCard1.Oversold__c = true;
        insert mobileCard1;
        
        mobileCard1.Survey_Invitation_Sent__c = system.today()+5;
        update mobileCard1;
        
        EB_SB_Builder__c instOfEB =  new EB_SB_Builder__c();
        instOfEB.Project__c = 'Event Builder';
        instOfEB.Project_Status__c = 'Information Pending';
        instOfEB.Project_Type_del__c = 'Demo Event';
        instOfEB.Project_Complexity__c = '1-Simple';
        instOfEB.Integration__c = 'Marketo';
        instOfEB.AccountCustom__c = acc.Id;
        instOfEB.Contact__c = con.id;
        instOfEB.Survey_Invitation_Sent__c = system.today();
        insert instOfEB;
        
        instOfEB.Survey_Invitation_Sent__c = system.today()+5;
        update instOfEB;
        
        Case caseObj = new Case();
        caseObj.Status = 'Open';
        caseObj.Minutesoncase__c = 30; 
        caseObj.OwnerId = userInfo.getUserId();
        caseObj.AccountId=acc.Id;
        caseObj.subject='Test Hosp Cloud Implementation Survey';
        caseObj.Origin ='Email';       
        caseObj.description='The details of Francisco De Asis Grageras response are below.Dear Francisco De Asis Gragera,Thank you for completing the Hosp Cloud Implementation Survey! We appreciate the time you spent to provide us with the contract details. Given below is a snaphot of the survey response. Respondent Information Survey Title: Hosp Cloud Implementation Survey Response Number: 50104104 Total Score: 0.00/0.00 Start Date: 01/09/2017 1:07 PM Completion Date: 01/09/2017 1:25 PM Response Information Question Answer Score Contract Type CSN Bundle 0.00 Please provide the Salesforce link to the Contract Signer https://cvent.my.salesforce.com/'+acc.Id+' 0.00 Bundle Type Single Property Bundle 0.00 Salesforce Account Link: https://cvent.my.salesforce.com/00100000008DBY3 0.00';
        caseObj.Survey_Invitation_Sent__c = system.today();
        caseObj.ContactId = con.Id;
        caseObj.Date_Closed__c = system.today();
        insert caseObj;
        
        caseObj.Survey_Invitation_Sent__c = system.today()+5;
        caseObj.status = 'Pending for Closure Confirmation';
        update caseObj;
        caseObj.Survey_Invitation_Sent__c = system.today()+10;
        caseObj.status = 'Closed';
        //update caseObj;
        System.debug(caseObj.Status);
        
    }
    
     static testMethod void testMethod6()
    {
        Profile p = [SELECT Name FROM Profile WHERE Name = 'System Administrator']; 
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Sherlin', LastName='Lauren', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com');
        insert user1;
        
        User user2 = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Daniel', LastName='Shregg', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest1@testorg.com');
        insert user2;
        
        Account acc = new Account(Name='Test Account');
        acc.BillingCountryCode='US';
        acc.BillingState='TX';
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact',AccountId = acc.Id,Last_Experiential_Survey_Invitation__c=system.today()+10/*,Profile_Name__c='temp profile'*/);
        insert con;
        
        AccountTeamMemberRoles__c atms = new AccountTeamMemberRoles__c();
        atms.Name = 'AM - Event Cloud';
        insert atms;
        
        MobileAppNotificationUser__c users = new MobileAppNotificationUser__c();
        users.Name = 'Test User';
        users.Type__c = 'MobileApp';
        users.Id__c = user1.Id;
        insert users;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = acc.Id;
        atm.TeamMemberRole = 'AM - Event Cloud';
        atm.UserId = user1.Id; 
        insert atm;
        
         Case caseObj = new Case();
        caseObj.Status = 'Open';
        caseObj.Minutesoncase__c = 30; 
        caseObj.OwnerId = userInfo.getUserId();
        caseObj.AccountId=acc.Id;
        caseObj.subject='Test Hosp Cloud Implementation Survey';
        caseObj.Origin ='Email';       
        caseObj.description='The details of Francisco De Asis Grageras response are below.Dear Francisco De Asis Gragera,Thank you for completing the Hosp Cloud Implementation Survey! We appreciate the time you spent to provide us with the contract details. Given below is a snaphot of the survey response. Respondent Information Survey Title: Hosp Cloud Implementation Survey Response Number: 50104104 Total Score: 0.00/0.00 Start Date: 01/09/2017 1:07 PM Completion Date: 01/09/2017 1:25 PM Response Information Question Answer Score Contract Type CSN Bundle 0.00 Please provide the Salesforce link to the Contract Signer https://cvent.my.salesforce.com/'+acc.Id+' 0.00 Bundle Type Single Property Bundle 0.00 Salesforce Account Link: https://cvent.my.salesforce.com/00100000008DBY3 0.00';
        insert caseObj;
        
        caseObj.Oversold__c = true;
        update caseObj;
    }
    
     static testMethod void testMethod7()
    {
        Profile p = [SELECT Name FROM Profile WHERE Name = 'System Administrator']; 
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Sherlin', LastName='Lauren', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com');
        insert user1;
        
        User user2 = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Daniel', LastName='Shregg', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest1@testorg.com');
        insert user2;
        
        Account acc = new Account(Name='Test Account');
        acc.BillingCountryCode='US';
        acc.BillingState='TX';
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact',AccountId = acc.Id);
        insert con;
        
        AccountTeamMemberRoles__c atms = new AccountTeamMemberRoles__c();
        atms.Name = 'AM - Event Cloud';
        insert atms;
        
        MobileAppNotificationUser__c users = new MobileAppNotificationUser__c();
        users.Name = 'Test User';
        users.Type__c = 'EB SB Project';
        users.Id__c = user1.Id;
        insert users;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = acc.Id;
        atm.TeamMemberRole = 'AM - Event Cloud';
        atm.UserId = user1.Id; 
        insert atm;
        
        Onboarding__c onboardingObj = new Onboarding__c();
        onboardingObj.Account_Name__c = acc.Id;
        onboardingObj.Oversold__c = true;
        insert onboardingObj;
        
        Bundle_Card__c bundleCard = new Bundle_Card__c();
        bundleCard.Account__c = acc.Id;
        bundleCard.Oversold__c = true;
        insert bundleCard;
    }
    
    static testMethod void testMethod8()
    {
        Profile p = [SELECT Name FROM Profile WHERE Name = 'System Administrator']; 
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Sherlin', LastName='Lauren', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com');
        insert user1;
        
        User user2 = new User(Alias = 'standt', Email='standarduser1@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Daniel', LastName='Shregg', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest1@testorg.com');
        insert user2;
        
        Account acc = new Account(Name='Test Account');
        acc.BillingCountryCode='US';
        acc.BillingState='TX';
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact',AccountId = acc.Id,Last_Experiential_Survey_Invitation__c=system.today()+10/*,Profile_Name__c='temp profile'*/);
        insert con;
        
        AccountTeamMemberRoles__c atms = new AccountTeamMemberRoles__c();
        atms.Name = 'AM - Event Cloud';
        insert atms;
        
        MobileAppNotificationUser__c users = new MobileAppNotificationUser__c();
        users.Name = 'Test User';
        users.Type__c = 'MobileApp';
        users.Id__c = user1.Id;
        insert users;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = acc.Id;
        atm.TeamMemberRole = 'AM - Event Cloud';
        atm.UserId = user1.Id; 
        insert atm;
        
        Onboarding__c onboardingObj = new Onboarding__c();
        onboardingObj.Account_Name__c = acc.Id;
        insert onboardingObj;
        
        onboardingObj.Oversold__c = true;
        update onboardingObj;
        
        Bundle_Card__c bundleCard = new Bundle_Card__c();
        bundleCard.Account__c = acc.Id;
        insert bundleCard;
        
        bundleCard.Oversold__c = true;
        update bundleCard;
    }
    
}