objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <formula>Year(Today())</formula>
        <label>Current Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Term_Years__c</fullName>
        <description>Contract duration in years.</description>
        <inlineHelpText>Contract duration in years.</inlineHelpText>
        <label>Contract Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Duration</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Failed_Auto_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed Auto Renew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Multiple_Years_Commitment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Multiple Years Commitment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Contract_Term_Years__c</fullName>
        <formula>TEXT(Parent_Contract__r.Contract_Term_Years__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Contract Term (years)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Read/Write access granted to Finance CI Team for manual upload. Access will be revoked once we built the automated solution.</description>
        <label>Parent Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Child Contracts</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remaining_Master_Term__c</fullName>
        <formula>VALUE(Parent_Contract_Term_Years__c) - Current_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Parent Term (years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Creation_Date__c</fullName>
        <inlineHelpText>Date the renewal opportunity will be automatically created.</inlineHelpText>
        <label>Renewal Creation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Upcoming_Renewal_Type__c</fullName>
        <formula>IF( Remaining_Master_Term__c &gt; 0, "MYD Renewal", "Contract Renewal")</formula>
        <label>Upcoming Renewal Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CpqAudit__c.object
<CustomObject>
    <fields>
        <fullName>contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cpq Audit Records</relationshipLabel>
        <relationshipName>Cpq_Audit_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cpq Audit Records</relationshipLabel>
        <relationshipName>Cpq_Audit_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>statusCheckCount__c</fullName>
        <label>statusCheckCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CPQ Audit</label>
    <nameField>
        <label>CpqAudit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Audit Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Contract_Duration.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <description>Duration of the contract</description>
    <masterLabel>Contract Duration</masterLabel>
</GlobalValueSet>

classes/CventMyd_AutoRenewContractSched_Test.cls
@isTest
private class CventMyd_AutoRenewContractSched_Test {

    private static testMethod void test0() {
        
            //Insert Opp
            Opportunity opp = TestUtil.createOpportunity('Test Opp', 'Renewal', 'Closed Won');
                opp.CurrencyIsoCode  = 'USD';
                insert opp;
                
                //Account
                Account TestAccount = new Account();
                TestAccount.Name = 'Test Account';
                insert TestAccount;
                
                Id RecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Parent Contract').getRecordTypeId();
                Id ChildRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Child Contract').getRecordTypeId();
                
            //Parent Contract to have Parent_Contract_Term_Years__c, Upcoming_Renewal_Type__c, Parent_Contract_Term_Years__c
                Contract ParentCont = new Contract();
                ParentCont.AccountId = TestAccount.id;
                ParentCont.Contract_Term_Years__c = '1';
                ParentCont.RecordTypeId = RecordTypeId;
                ParentCont.SBQQ__Opportunity__c = opp.id;
                //ParentCont.Is_Legacy__c = true;
                ParentCont.SBQQ__RenewalQuoted__c = false;
                ParentCont.Failed_Auto_Renew__c = false;
                ParentCont.Renewal_Creation_Date__c = System.today().addYears(1);
                insert ParentCont;

                Test.setCreatedDate(ParentCont.Id,DateTime.newInstance(2015,1,1));
                
                //Child Contract
                Contract cont = new Contract();
                cont.RecordTypeId = ChildRecordTypeId;
                cont.AccountId = TestAccount.id;
                cont.Parent_Contract__c = ParentCont.id;
                //cont.Upcoming_Renewal_Type__c = 'Contract Renewal';
                cont.EndDate = System.today();
                //cont.Remaining_Master_Term__c = 0;
                cont.Current_Year__c = 1;
                //cont.Is_Legacy__c = true;
                cont.SBQQ__RenewalQuoted__c = false;
                cont.Failed_Auto_Renew__c = false;
                cont.Renewal_Creation_Date__c = Date.newInstance(2018,9,5); //System.today().addYears(1);
                insert cont;

                Test.setCreatedDate(cont.Id,DateTime.newInstance(2015,1,1));
                
            //Insert Quote
                SBQQ__Quote__c TestQuote = new SBQQ__Quote__c();
                TestQuote.SBQQ__Opportunity2__c = opp.id;
                TestQuote.Contract_Term_Years__c = '2';
                TestQuote.SBQQ__Type__c = 'Amendment';
                TestQuote.Current_Year__c = 2;
                TestQuote.Contract_Executed__c = true;
                TestQuote.SBQQ__StartDate__c = System.today().addYears(-1);
                TestQuote.SBQQ__EndDate__c = System.today();
                TestQuote.createdFromLegacyContract__c = true;
                //TestQuote.Multiple_Years_Commitment__c = true;
                TestQuote.statusCheckCount__c = 0;
                insert TestQuote;
                
                TestQuote.Multiple_Years_Commitment__c = true;
                update TestQuote;
            
                //Insert CPQ Audit record
                CpqAudit__c testAudit = new CpqAudit__c();
                testAudit.Name = 'Test Audit';
                testAudit.quote__c = TestQuote.id;
                testAudit.contract__c = ParentCont.id;
                insert testAudit;
                
                Test.startTest();
                
                //Run batch
                CventMyd_AutoRenewContractSchedulable BatchRun = new CventMyd_AutoRenewContractSchedulable();
                //CventMyd_QuoteSchedulable renewalQuoteSchedulable = new CventMyd_QuoteSchedulable(renewalQuoteMap.keySet(),renewalJobName,renewalJobAuditRecord.Id);
                //ID batchprocessid = Database.executeBatch(BatchRun,200);
                String sch = '0 0 23 * * ?';
                system.schedule('Test Run', sch, BatchRun);
                
                Test.stopTest();

        }
            
        private static testMethod void test1() {

                /*
                
            Test.startTest();
                
                //Run batch
                CventMyd_AutoRenewContractSchedulable BatchRun = new CventMyd_AutoRenewContractSchedulable();
                //CventMyd_QuoteSchedulable renewalQuoteSchedulable = new CventMyd_QuoteSchedulable(renewalQuoteMap.keySet(),renewalJobName,renewalJobAuditRecord.Id);
                //ID batchprocessid = Database.executeBatch(BatchRun,200);
                
                Test.stopTest();
                
                String sch = '0 0 23 * * ?';
                system.schedule('Test Run', sch, BatchRun);

                */
        
    }

                
        private static testMethod void test2() {
                    


        }

}