objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Prospect Lead</fullName>
                </value>
                <value>
                    <fullName>Fit Lead</fullName>
                </value>
                <value>
                    <fullName>Active Lead</fullName>
                </value>
                <value>
                    <fullName>Passive Win</fullName>
                </value>
                <value>
                    <fullName>Imp Win</fullName>
                </value>
                <value>
                    <fullName>Live Win</fullName>
                </value>
                <value>
                    <fullName>End Business</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RFP__c.object
<CustomObject>
    <fields>
        <fullName>Awarded_Value__c</fullName>
        <formula>IF(TEXT( Status__c)="Awarded", 
Case(RFP_Type__c, "Restaurant RFP", 50 *  Proposal_Attendee_Count__c , "Sleeping Rooms Only", 140 *  Proposal_Sleep_Room_Count__c *1.35, "Meeting Space and Sleeping Rooms", (140 * Proposal_Sleep_Room_Count__c  *1.35)+(Proposal_Attendee_Count__c *Event_Duration_of_Days__c*20) , 
"Meeting Space Only", 20 * Proposal_Attendee_Count__c*Event_Duration_of_Days__c,0 ),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Awarded Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budgeted_Room_Rate__c</fullName>
        <label>Budgeted Room Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RFP_Code__c</fullName>
        <externalId>true</externalId>
        <label>RFP Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFP_Type__c</fullName>
        <label>RFP Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Meeting Space and Sleeping Rooms</fullName>
                </value>
                <value>
                    <fullName>Meeting Space Only</fullName>
                </value>
                <value>
                    <fullName>Request for Information</fullName>
                </value>
                <value>
                    <fullName>Restaurant RFP</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
                <value>
                    <fullName>Sleeping Rooms Only</fullName>
                </value>
                <value>
                    <fullName>Special Events</fullName>
                </value>
                <value>
                    <fullName>Wedding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Awaiting Proposal</fullName>
                </value>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Awarded by Hotel</fullName>
                </value>
                <value>
                    <fullName>Awarded By Planner</fullName>
                </value>
                <value>
                    <fullName>Booked Elsewhere</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Forwarded</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Proposal Declined</fullName>
                </value>
                <value>
                    <fullName>Proposal Received</fullName>
                </value>
                <value>
                    <fullName>Receipt Confirmed</fullName>
                </value>
                <value>
                    <fullName>RFP Declined</fullName>
                </value>
                <value>
                    <fullName>RFP Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted Proposal</fullName>
                </value>
                <value>
                    <fullName>Turned Down</fullName>
                </value>
                <value>
                    <fullName>Will Not Accept Terms of Use</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <label>Supplier A/c</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RFPs (Supplier A/c)</relationshipLabel>
        <relationshipName>RFPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Code__c</fullName>
        <externalId>true</externalId>
        <label>Unique Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RFPs</label>
    <nameField>
        <label>RFP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestCSNRollUpFields.cls
@isTest
public class TestCSNRollUpFields {

    static testMethod void myUnitTest() {

        Profile pf = [Select Id from Profile where Name = 'System Administrator'];

        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.Email = 'testuser@test123456789.com';
        u.CompanyName = 'test.com';
        u.Title = 'Test User';
        u.Username = 'testuser@test123456789.com';
        u.Alias = 'testuser';
        u.CommunityNickname = 'Test User';
        u.TimeZoneSidKey = 'America/Mexico_City';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = pf.Id;
        u.LanguageLocaleKey = 'en_US';
        insert u;

        system.runAs(u){

            Account o = new Account();
            o.Name = 'Test Account';
          //  o.of_Total_RFP_s_Received_New1__c = null;
         //   o.Value_of_RFPs_Received_New__c = null;
            insert o;
            
          //  system.assertEquals(o.of_Total_RFP_s_Received_New1__c, null);
      
            //Test payments on insert
            RFP__c p1 = new RFP__c();
            p1.Supplier_Account__c = o.Id;
            p1.Name = 'Test RFP';
            p1.RFP_Code__c = 'Test Code';
            p1.Unique_Code__c = 'Test Unique Code';
            p1.Status__c = 'Awarded';
            p1.RFP_Type__c = 'Request for Information';          
            insert p1;
            
            Account ou1 = [select name from Account where Id =:o.Id];
          //  System.AssertEquals(ou1.of_Total_RFP_s_Received_New1__c,null);

            //Test payments on update

            RFP__c p1u = [select Awarded_Value__c from RFP__c where Id = :p1.Id];
            p1u.Budgeted_Room_Rate__c = 0;
            update p1u;
            
            Account ou2 = [select name from Account where Id = :o.Id];
           // system.assertEquals(ou2.of_Total_RFP_s_Received_New1__c, null);

            //Test payments on second insert
            RFP__c p2 = new RFP__c();
            p2.Supplier_Account__c = o.Id;
            p2.Name = 'Test RFP2';
            p2.RFP_Code__c = 'Test Code2';
            p2.Unique_Code__c = 'Test Unique Code2';
            p2.Status__c = 'Awaiting Proposal';
            p2.RFP_Type__c = 'Request for Information';
            insert p2;

            Account ou3 = [select name from Account where Id =:o.Id];
          //  System.AssertEquals((Double)ou3.of_Total_RFP_s_Received_New1__c,null);
    
            //Test payment on delete
            delete p2;

            Account ou4 = [select name from Account where Id = :o.Id];
          //  System.AssertEquals(ou4.of_Total_RFP_s_Received_New1__c,null);

        }

    }

}