objects/Account.object
<CustomObject>
    <fields>
        <fullName>EBS_Account_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise
Exclude from field purging exercise</description>
        <label>EBS Account ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Exclude from field purging exercise</description>
        <label>EBS Update</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ByPassTrigger__c.object
<CustomObject>
    <fields>
        <fullName>isDisabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDisabled</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Use to Bypass all triggers for data migration</description>
    <label>ByPass Trigger</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EBS Update</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EBS_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>EBS Integration</label>
</CustomObject>

objects/EBS_Order_Sync_Framework__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links to the Closed Won Opportunity which is to be sent over to EBS</description>
        <label>Opportunity (Related Order)</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EBS Order Sync Framework</relationshipLabel>
        <relationshipName>EBS_Order_Sync_Framework</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>This object would be used to control the Opportunity (Order) Sync process with EBS by ensuring that all dependencies like Account (new customer), associated  Addresses, Contacts and Contact Addresses have a valid EBS Id and if not, sync them with EBS first before pushing the Order. It does this by generating and queuing multiple Integration Queue records.</description>
    <label>EBS Order Sync Framework</label>
    <nameField>
        <displayFormat>OS-{00000000}</displayFormat>
        <label>Order Sync Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBS Order Sync Framework</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UserAssignment__c.object
<CustomObject>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>User Assignment</label>
</CustomObject>

classes/IntegrationAccountTest.cls
/**
*    
*   Author: Shanu Aggarwal
*   Date Added : 23-05-2017
*   This class tests the functionality of IntegrationAccount
* 
*/
@istest
public class IntegrationAccountTest {
    
    
    private static void createCustomsetting(){


        // custom setting for opportunity insert
        UserAssignment__c instUA = new UserAssignment__c();
        instUA.Name = 'OnArrival';
        instUA.User_id__c = userinfo.getUserID();
        instUA.UserName__c = 'Brett Wischow';
        insert instUA;

    }
    @testsetup
    public static void CreateTestData(){

        Test.startTest();
        //Inserting User...............
        Profile p = [SELECT Id FROM Profile WHERE Name='Finance - Management']; 
        USerrole[] testroleId=[select id from userRole where name ='AM (Event)' OR name ='Pre Sales - Special Projects' limit 2];

        User instUser=TestUtil.createUser(p.id,'Test_709deploymentuser@cvent.com');
        instUser.userRoleId=testroleId[0].id;
        instUser.firstname='John';



        system.runAs(instUser){
            
            createCustomsetting();
            
            Account instAccount=TestUtil.createAccount('TestAccount','Biz_Ac');       
            insert instAccount;
            

            Contact con=TestUtil.createContact(instAccount.id);
            insert con;
            List<Address__c> listOfAddress=new List<Address__c>();
            listOfAddress.add(TestUtil.createAccountAddress(instAccount.id,'Billing'));
            listOfAddress.add(TestUtil.createAccountAddress(instAccount.id,'Shipping'));
            insert listOfAddress;

            opportunity instOpp=TestUtil.createOpportunity('Test opp','CS_Lead','Opp Identified');
            instOpp.AccountId= instAccount.Id;
            instOpp.Contact_Associated__c = con.Id;
            instOpp.Bill_To_Address__c = listOfAddress[0].Id;
            instOpp.Ship_To_Address__c = listOfAddress[1].Id;
            insert instOpp;
            
            EBS_Order_Sync_Framework__c frameWork = new EBS_Order_Sync_Framework__c();
            framework.Opportunity__c  = instOpp.Id;
            insert frameWork;

            EBS_Integration__c eIntegration=TestUtil.createEbsIntegration('Account Integration','Account');

            insert eIntegration;

        }

        Test.stopTest();

    }
   
   //This method test Handle New Accounts, Resync Accounts
   
   public static testmethod void testResyncAccount(){
       createCustomsetting();
       Account acc = [Select Id,Name,LastModifiedById,EBS_Account_ID__c from Account Limit 1 ];
       acc.EBS_Account_ID__c = '16465478';
       acc.EBS_Update__c=true;
       update acc;
       
       System.assert(acc.EBS_Account_ID__c!=null);
       
       Account acc2 = new Account();
       acc2.Name = 'Biz Test Acc 1';
       acc.EBS_Account_ID__c = '654654654';  
       acc.EBS_Update__c=true;         
       insert acc2;
       
       //Run trigger again to resyncAccount for EBS Order
       EBS_Order_Sync_Framework__c frameWork = [Select Id From EBS_Order_Sync_Framework__c Limit 1 ];
       update frameWork;
       
       //Handle New Account 
       IntegrationAccount.handleNewAccounts(new Map<Id,Account>{acc.Id=>acc});
       IntegrationAccount.handleUpdatedAccounts(new List<Account>{acc},new Map<Id,Account>{acc2.Id=>acc2});
       IntegrationAccount.resyncAccount(acc.Id);
       //Resync Account for EBS Order
       
       
   }
   public static testmethod void testResyncAccount_1(){
       createCustomsetting();
       Account acc = [Select Id,Name,LastModifiedById,EBS_Account_ID__c from Account Limit 1 ];
       acc.EBS_Account_ID__c = '16465478';
       acc.EBS_Update__c=true;
       update acc;
       
       System.assert(acc.EBS_Account_ID__c!=null);
       
       Account acc2 = new Account();
       acc2.Name = 'Biz Test Acc 2';
       acc.EBS_Account_ID__c = '654654654';  
       acc.EBS_Update__c=true;         
       insert acc2;
       
       //Run trigger again to resyncAccount for EBS Order
       EBS_Order_Sync_Framework__c frameWork = [Select Id From EBS_Order_Sync_Framework__c Limit 1 ];
       update frameWork;
       
       //Handle New Account 
       //IntegrationAccount.handleNewAccounts(new Map<Id,Account>{acc.Id=>acc});
       IntegrationAccount.handleUpdatedAccounts(new List<Account>{acc},new Map<Id,Account>{acc.Id=>acc2});
       IntegrationAccount.handleDependentUpdates(new List<Account>{acc},new Map<Id,Account>{acc.Id=>acc2});
       IntegrationAccount.handleAddressUpdates(new List<Account>{acc},new Map<Id,Account>{acc.Id=>acc2});
       
   }   
   //Test BypassTriggerUtilityTest class 
   static testmethod void  testByPassTriggerLogic(){
        
        
        ByPassTrigger__c b = new ByPassTrigger__c();
        b.Name = 'test trigger';
        b.isDisabled__c =false;
        insert b;
        
        BypassTriggerUtility bu = new BypassTriggerUtility();
        bu.isTriggerBypassed();
        
    }
    
    //Test BypassTriggerUtilityTest class 
   static testmethod void  testNegativeByPassTriggerLogic(){
        
        ByPassTrigger__c b = new ByPassTrigger__c();
        b.Name = 'test trigger';
        b.isDisabled__c =true;
        insert b;
        
        BypassTriggerUtility bu = new BypassTriggerUtility();
        bu.isDisabled=true;
        bu.isTriggerBypassed();
        
    }
    
}