objects/Account_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Partners</relationshipLabel>
        <relationshipName>Account_Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Partners (Partner)</relationshipLabel>
        <relationshipName>Account_Partners1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Select__c</fullName>
        <description>Contains the selected Roles for the Account Partner association. When importing Account Partner data, be sure to populate this field (not the Role__c field).</description>
        <label>Role Select</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising Agency</fullName>
                </value>
                <value>
                    <fullName>Chain Affiliation</fullName>
                </value>
                <value>
                    <fullName>Management Company</fullName>
                </value>
                <value>
                    <fullName>Other Chain Name</fullName>
                </value>
                <value>
                    <fullName>Ownership Group</fullName>
                </value>
                <value>
                    <fullName>Regional Sales Office</fullName>
                </value>
                <value>
                    <fullName>Parent Management Company</fullName>
                </value>
                <value>
                    <fullName>Asset Management Firm</fullName>
                </value>
                <value>
                    <fullName>Consultant Firm</fullName>
                </value>
                <value>
                    <fullName>Accor Hotels</fullName>
                    <isActive>false</isActive>
                    <label>Accor Hotels</label>
                </value>
                <value>
                    <fullName>Advertising Agencies</fullName>
                    <isActive>false</isActive>
                    <label>Advertising Agencies</label>
                </value>
                <value>
                    <fullName>Chain Affilaition</fullName>
                    <isActive>false</isActive>
                    <label>Chain Affilaition</label>
                </value>
                <value>
                    <fullName>Chain Affilifation</fullName>
                    <isActive>false</isActive>
                    <label>Chain Affilifation</label>
                </value>
                <value>
                    <fullName>Chain Affliation</fullName>
                    <isActive>false</isActive>
                    <label>Chain Affliation</label>
                </value>
                <value>
                    <fullName>Choice Hotels</fullName>
                    <isActive>false</isActive>
                    <label>Choice Hotels</label>
                </value>
                <value>
                    <fullName>Hilton Worldwide</fullName>
                    <isActive>false</isActive>
                    <label>Hilton Worldwide</label>
                </value>
                <value>
                    <fullName>Independent / Other</fullName>
                    <isActive>false</isActive>
                    <label>Independent / Other</label>
                </value>
                <value>
                    <fullName>Independent Restaurants</fullName>
                    <isActive>false</isActive>
                    <label>Independent Restaurants</label>
                </value>
                <value>
                    <fullName>NH Hotel Group</fullName>
                    <isActive>false</isActive>
                    <label>NH Hotel Group</label>
                </value>
                <value>
                    <fullName>Role select</fullName>
                    <isActive>false</isActive>
                    <label>Role select</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>This field is automatically populated with values from the Role_Select__c field by the SetValuesOnAccountPartner trigger. Due to the limitations with multi-select fields (difficulty searching, can't sort, etc.), this text field value should be used for reporting, lists, views, etc. 
When importing Account Partner data, DO NOT IMPORT into this field - Role information should be imported to the Role_Select__c field.</description>
        <label>Role</label>
        <type>TextArea</type>
    </fields>
    <description>A custom Account Partner object to connect partner accounts</description>
    <label>Account Partner</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Account_Partner_EditController.cls
//*************************************************************************
//
//  Account_Partner_EditController
//    
//  This class is an Extension Controller for the
//  Account_Partner add/edit page.  A custom page is needed so we can
//  default field values properly and perform extra validation.
//
//  History:
//  InSitu  06/17/2013    Original version    
// *************************************************************************
public with sharing class Account_Partner_EditController 
{
    // -----------------------------------------------------
    //  Constants
    // -----------------------------------------------------
	
    // -----------------------------------------------------
    // Class Attributes
    // -----------------------------------------------------

    // -----------------------------------------------------
    //  Member variables
    // -----------------------------------------------------
	private ID						m_idAccountPartner;
	private ID						m_idAccount;
	private ID						m_idPartner;
	private String 					m_strMode;
	private String					m_strReturnURL;
	
	public Account_Partner__c 		AcctPartner	{get; set;} 

    // -----------------------------------------------------
    //  Methods
    // -----------------------------------------------------
    
    //-------------------------------------------------------------------
    // Getter methods for display components 
    //-------------------------------------------------------------------
    public String getPageTitle()				{return 'Account Partner';}		 
    public String getPageSubTitle()				{return getIsEdit() ? 'Edit Account Partner' : 'New Account Partner';}  
    public Boolean getIsAdd()					{return m_strMode == 'Add' ? true : false;}       
    public Boolean getIsEdit()					{return m_strMode == 'Edit' ? true : false;}

    // --------------------------------------------------------
    //  Constructor
    //
    //  Description: 
    //
    // 
    // --------------------------------------------------------
    public Account_Partner_EditController()
    {
    	system.debug(Logginglevel.WARN, 'in Account_Partner_EditController constructor.');

		// Get the mode parameter next - it will tell us if it is an Add or Edit operation.
		m_strMode = System.currentPageReference().getParameters().get('Mode');
		
		m_idAccount = System.currentPageReference().getParameters().get('AccountID');
		m_idPartner = System.currentPageReference().getParameters().get('PartnerID');
		
		// Get the ID of the Account Partner record, only if in edit mode.
		if (getIsEdit())
			m_idAccountPartner = System.currentPageReference().getParameters().get('ID');
		
		// Get the return URL, so we can redirect back to the calling page.
		m_strReturnURL = System.currentPageReference().getParameters().get('RetURL');
		
		// Retrieve associated records and initialize additional data members.
	    if (getIsEdit() == true)
	    {
			try
			{
		    	AcctPartner = [SELECT ID, Role__c, Role_Select__c, Partner__c, Partner__r.Name, Account__c, Account__r.Name 
					  			FROM Account_Partner__c
					  			WHERE ID = :m_idAccountPartner];
			}
			catch (Exception e) 
			{
		    	ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error initializing the page. The Account Partner record is currently not available.'));
				return;
			} 
	    }
	    else
	    {
	    	if (m_idAccount != null)
	    		AcctPartner = new Account_Partner__c(Account__c = m_idAccount);
	    	else if (m_idPartner != null)
	    		AcctPartner = new Account_Partner__c(Partner__c = m_idPartner);
	    }
	}

    //---------------------------------------------------
    // doSave
    //--------------------------------------------------- 
	public PageReference doSave() 
	{
    	system.debug(Logginglevel.WARN, 'in Account_Partner_EditController::doSave()');

		Pagereference pageReturn;
		
		try 
		{
			if (getIsEdit() == true)
			{
				update AcctPartner;				
			}
			else
			{
				insert AcctPartner;
			}
		} 
		catch (DMLException e) 
		{
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'An error occurred while saving the Account Partner record. Error: ' + e.getMessage()));
			return null;
		} 

		return returnToPrevPage();
	}
	
	//---------------------------------------------------
    // doCancel
    //--------------------------------------------------- 
	public PageReference doCancel() 
	{
		return returnToPrevPage();
	}
	
	//---------------------------------------------------
    // returnToPrevPage
    //--------------------------------------------------- 
	public PageReference returnToPrevPage() 
	{
		Pagereference pageReturn;

		// Return to previous page (most likely the View Initial order page)
		if (m_strReturnURL != null)
		{
			pageReturn = new Pagereference (m_strReturnURL);
			pageReturn.setRedirect(true); 
		}
		
		return pageReturn;
	}
}