objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Attention_To__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Bill To - Attention To</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Account_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise
Exclude from field purging exercise</description>
        <label>EBS Account ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Account_Number__c</fullName>
        <description>EBS Integration field</description>
        <label>EBS Account Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Party_Site_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Party Site ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account to which this Additional Address record is related.
This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <inlineHelpText>The Account to which this Additional Address record is related.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Additional_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Site_Number__c</fullName>
        <description>EBS Integration field</description>
        <externalId>true</externalId>
        <label>EBS Site Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EBS_Site_Use_ID__c</fullName>
        <description>EBS Integration field
This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <externalId>true</externalId>
        <label>EBS Site Use ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Operating_Unit_Name__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Operating Unit Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CVINC</fullName>
                </value>
                <value>
                    <fullName>CVUK</fullName>
                </value>
                <value>
                    <fullName>CVAUS</fullName>
                </value>
                <value>
                    <fullName>CVSGP</fullName>
                </value>
                <value>
                    <fullName>CVCDN</fullName>
                </value>
                <value>
                    <fullName>CVDE</fullName>
                </value>
                <value>
                    <fullName>CVUAE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payable_Name__c</fullName>
        <description>EBS Integration Field
This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Payable Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Sync?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProvinceCode__c</fullName>
        <label>Province Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>Used to track Canadian or other country's province data.</description>
        <inlineHelpText>This is required if Country = Canada.</inlineHelpText>
        <label>Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Remittance</fullName>
                    <default>true</default>
                    <label>Remittance</label>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
</CustomObject>

objects/CountryCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country Codes</label>
</CustomObject>

classes/CS_AccountTriggerHandler.cls
/*
* Author: B.ESPIRIDION
* Description: Handes all account trigger logic
* Created: 4-22-2015
*/
public with sharing class CS_AccountTriggerHandler {
    public static final String BILLING_FIELD = 'Billing';
    public static final String SHIPPING_FIELD = 'Shipping';
/*
* Author: B.ESPIRIDION
* Description: Updates Address__c releted records to account when billing and shipping address is updated
* Created: 4-22-2015
* Param: none
* Return: none
*/ 
    public static void handleAccountAddressModify(Account[] pNewAccounts, map<Id, Account> pOldAccountMap, boolean isPrimary){        
        Account[] UpdatedAccounts = new Account[]{};
        map<Id, AddressWrap> accountIdToAddressWrap = new map<Id, AddressWrap>();
        for(Account acc : pNewAccounts){
            AddressWrap aw = new AddressWrap();
            if(hasChangedAddress(acc, pOldAccountMap.get(acc.Id), aw)){
                
                UpdatedAccounts.add(acc);
                accountIdToAddressWrap.put(acc.Id, aw);
            }
            system.debug('\n\nBilling: ' + aw.BillingChanged + '\nShipping: ' + aw.ShippingChanged + '\n\n');
        }
        
        if(UpdatedAccounts.isEmpty()){
            system.debug('\n\nNo account that has updated address.\n\n');
            return;
        }

        /* Enhancement by PK on 7/13/17. The account header level BillingAddress and ShippingAddress changes will sync only
            with the addresses marked as Primary.  By default the first time addresses are generated they will be set as Primary. 
            Any subsequent addresses will be insulated from Header sync. */
        
        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, (select id, Primary_Sync__c, Type__c, Account__c, 
                                        Address__c, City__c, Country__c, CountryCode__c, Postal_Code__c, Province__c, ProvinceCode__c, State__c,
                                        EBS_Account_Id__c, EBS_Site_Number__c, EBS_Site_Use_ID__c from Additional_Addresses__r) from Account where Id IN:accountIdToAddressWrap.keySet()]);

        Map<Id, Address__c> accPrimaryBillingMap = new Map<Id, Address__c>();
        Map<Id, Address__c> accPrimaryShippingMap = new Map<Id, Address__c>();
        for(Account acc: accountMap.values()){
            for(Address__c addr: acc.Additional_Addresses__r){
                if(addr.Primary_Sync__c){
                    if(addr.Type__c == BILLING_FIELD){
                        accPrimaryBillingMap.put(addr.Account__c, addr);
                        accountIdToAddressWrap.get(addr.Account__c).Billing = addr;
                    }
                    if(addr.Type__c == SHIPPING_FIELD){
                        accPrimaryShippingMap.put(addr.Account__c, addr);
                        accountIdToAddressWrap.get(addr.Account__c).Shipping = addr;
                    }
                }    
            }
        }
            
        //getRelatedAddress(accountIdToAddressWrap);
        
        Address__c[] addressToUpdate = new Address__c[]{};
        for(Account acc : UpdatedAccounts){
            if(accountIdToAddressWrap.get(acc.Id).BillingChanged)
                addressToUpdate.add(updateAddressFields(accountIdToAddressWrap.get(acc.Id).billing, acc, BILLING_FIELD));
            
            if(accountIdToAddressWrap.get(acc.Id).ShippingChanged)
                addressToUpdate.add(updateAddressFields(accountIdToAddressWrap.get(acc.Id).shipping, acc, SHIPPING_FIELD));
        }
        
        upsert addressToUpdate;
    }
    
    private static Address__c updateAddressFields(Address__c pAddress, Account pAccount, String pAddressType){
        Address__c output;
        if(pAddress == null){
            output = new Address__c();
            output.Account__c = pAccount.Id;
            output.Type__c = pAddressType;
            //Enhancement by PK on 7/13/17
            output.Primary_Sync__c = true;
        }else{
            output = pAddress;
        }
        /*if(isPrimary != null && isPrimary != false){
            output.Primary_Sync__c = isPrimary;
        }*/
        output.EBS_Account_Id__c = pAccount.EBS_Account_ID__c;
        //output.EBS_Site_Number__c = pAccount.EBS_Account_Number__c;
        //output.EBS_Site_Use_ID__c = pAccount.EBS_Party_Site_ID__c;
        
        output.Address__c = (String)pAccount.get(pAddressType + 'Street');
        output.City__c = (String)pAccount.get(pAddressType + 'City');
        output.Postal_Code__c = (String)pAccount.get(pAddressType + 'PostalCode');
        //output.Country__c = (String)pAccount.get(pAddressType + 'Country');
        output.Country__c = (String)pAccount.get(pAddressType + 'CountryCode');
        output.CountryCode__c = (String)pAccount.get(pAddressType + 'CountryCode');
        output.State__c = (String)pAccount.get(pAddressType + 'StateCode');
        if(pAddressType == 'Billing' || pAddressType == 'Remittance')
            output.Payable_Name__c = (String)pAccount.get('Bill_To_Attention_To__c');
        /*if(output.CountryCode__c == 'CA'){
            output.ProvinceCode__c = output.State__c;
            output.Operating_Unit_Name__c = 'Active.com';
        }else if(output.CountryCode__c == 'US'){
            output.Operating_Unit_Name__c = 'Active.com';
        }*/
        return output;
    }

    
/*    private static void getRelatedAddress(map<Id, AddressWrap> accountIdToAddressWrap){
        for(Address__c address : [SELECT Primary_Sync__c, Type__c, Account__c, 
                                        Address__c, City__c, Country__c, CountryCode__c, Postal_Code__c, Province__c, ProvinceCode__c, State__c,
                                        EBS_Account_Id__c, EBS_Site_Number__c, EBS_Site_Use_ID__c
                                FROM Address__c WHERE Account__c IN :accountIdToAddressWrap.keySet() and Primary_Sync__c = true]){
            if(accountIdToAddressWrap.containsKey(address.Account__c)){
                if(address.Type__c == BILLING_FIELD){
                    accountIdToAddressWrap.get(address.Account__c).Billing = address;
                }else if(address.Type__c == SHIPPING_FIELD){
                    accountIdToAddressWrap.get(address.Account__c).Shipping = address;
                }
            }
        }
    } */

/*
* Author: B.ESPIRIDION
* Description: Updates Address__c releted records to account when billing and shipping address is updated
* Created: 4-22-2015
* Param: none
* Return: none
*/ 
    public static Boolean hasChangedAddress(Account pNew, Account pOld, AddressWrap pAddressObj){       
        set<String> addressToCheck = new set<String>{
            'Street',
            'City',
            'State',
            'PostalCode',
            'Country',
            'Bill_To_Attention_To__c'
                    };
        Boolean output = false;
        string FieldName;
        for(String address : new String[]{BILLING_FIELD, SHIPPING_FIELD}){
            system.debug('\n\n' + address + '\n\n');
            for(String type : addressToCheck){
                if(type == 'Bill_To_Attention_To__c'){
                    FieldName = 'Bill_To_Attention_To__c';
                    //break;
                }else    
                    FieldName = address+type;

                system.debug('\n\n' + FieldName + ' = ' +pNew.get(FieldName) + '\n\n');    
                if((pOld == null && pNew.get(FieldName) != null) || (pOld != null && pNew.get(FieldName) != pOld.get(FieldName))){
                    if(address == BILLING_FIELD && FieldName.contains('Bill')){ 
                        pAddressObj.BillingChanged = true;
                    }
                    if(address== SHIPPING_FIELD && FieldName.contains('Ship')){ 
                        pAddressObj.ShippingChanged = true;
                    }
                    output = true;
                }
            }
        }
        
        return output;
    }
/*****************************************************************
* Author: B.ESPIRIDION
* Description: Wrapper class to hold billing and shipping address__c records
* Created: 4-22-2015
********************************************************************/ 
    public class AddressWrap{
        public Address__c Shipping;
        public Address__c Billing;
        public Boolean ShippingChanged;
        public Boolean BillingChanged;
        
        public AddressWrap(){
            ShippingChanged = false;
            BillingChanged = false;
        }
    }
    
    public static void fakeMethod(){
    Integer i = 0;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
        i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
        i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
        i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
  }
}