objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Prospect Lead</fullName>
                </value>
                <value>
                    <fullName>Fit Lead</fullName>
                </value>
                <value>
                    <fullName>Active Lead</fullName>
                </value>
                <value>
                    <fullName>Passive Win</fullName>
                </value>
                <value>
                    <fullName>Imp Win</fullName>
                </value>
                <value>
                    <fullName>Live Win</fullName>
                </value>
                <value>
                    <fullName>End Business</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Type__c</fullName>
        <label>Supplier Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>Unique Venue</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue_Type__c</fullName>
        <label>Venue/Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Supplier_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Above- Property Account</fullName>
                </value>
                <value>
                    <fullName>Aquarium / Zoo</fullName>
                </value>
                <value>
                    <fullName>Arena / Stadium</fullName>
                </value>
                <value>
                    <fullName>AV / Production &amp; Design</fullName>
                </value>
                <value>
                    <fullName>Banquet Facility</fullName>
                </value>
                <value>
                    <fullName>Bar / Club</fullName>
                </value>
                <value>
                    <fullName>Boutique Hotel</fullName>
                </value>
                <value>
                    <fullName>Caterers / Food Services</fullName>
                </value>
                <value>
                    <fullName>Conference Center</fullName>
                </value>
                <value>
                    <fullName>Convention Center</fullName>
                </value>
                <value>
                    <fullName>Corporate Office Space</fullName>
                </value>
                <value>
                    <fullName>CVB</fullName>
                </value>
                <value>
                    <fullName>CVB/DMC</fullName>
                </value>
                <value>
                    <fullName>Educational Facility</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Entertainment Venue</fullName>
                </value>
                <value>
                    <fullName>Event hospitality &amp; entertainment Limited</fullName>
                </value>
                <value>
                    <fullName>Event Management / DMCs</fullName>
                </value>
                <value>
                    <fullName>Event Management Services</fullName>
                </value>
                <value>
                    <fullName>Event Rentals / Decor</fullName>
                </value>
                <value>
                    <fullName>Exposition Center</fullName>
                </value>
                <value>
                    <fullName>Gallery / Museum</fullName>
                </value>
                <value>
                    <fullName>Golf Course</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Internal Value</fullName>
                </value>
                <value>
                    <fullName>Luxury Hotel</fullName>
                </value>
                <value>
                    <fullName>Mail / Shipping Services</fullName>
                </value>
                <value>
                    <fullName>Movie Theatre</fullName>
                </value>
                <value>
                    <fullName>Printing / Marketing Services</fullName>
                </value>
                <value>
                    <fullName>Promotional Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Biz_Ac</fullName>
        <active>true</active>
        <label>Biz A/c</label>
    </recordTypes>
</CustomObject>

objects/Backlog_Item__c.object
<CustomObject>
    <fields>
        <fullName>Approach__c</fullName>
        <label>Approach</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Business_Case__c</fullName>
        <label>Business Case</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>CrowdCompass</fullName>
                </value>
                <value>
                    <fullName>CrowdTorch</fullName>
                </value>
                <value>
                    <fullName>CSN - Planners</fullName>
                </value>
                <value>
                    <fullName>CSN - Search &amp; DG</fullName>
                </value>
                <value>
                    <fullName>CSN - Suppliers</fullName>
                </value>
                <value>
                    <fullName>CVII</fullName>
                </value>
                <value>
                    <fullName>eMarketing</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>OnArrival</fullName>
                </value>
                <value>
                    <fullName>SMM</fullName>
                </value>
                <value>
                    <fullName>SocialWall</fullName>
                </value>
                <value>
                    <fullName>SpeedRFP/EMI</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On Ice</fullName>
                    <default>true</default>
                    <label>On Ice</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Closed - Released</fullName>
                </value>
                <value>
                    <fullName>Closed - Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Backlog Item</label>
    <nameField>
        <label>Backlog Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enhancement_Request__c.object
<CustomObject>
    <fields>
        <fullName>Business_Case__c</fullName>
        <inlineHelpText>Provide the “why.” How will this feedback/solution help the customer? What is their current process?</inlineHelpText>
        <label>Business Case</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enhancement Requests</relationshipLabel>
        <relationshipName>Enhancement_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Requested__c</fullName>
        <label>Date Requested</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>​Abstract Management</fullName>
                </value>
                <value>
                    <fullName>Appointments</fullName>
                </value>
                <value>
                    <fullName>CrowdCompass</fullName>
                </value>
                <value>
                    <fullName>CrowdTorch</fullName>
                </value>
                <value>
                    <fullName>CSN - Planners</fullName>
                </value>
                <value>
                    <fullName>CSN - Search &amp; DG</fullName>
                </value>
                <value>
                    <fullName>CSN - Suppliers</fullName>
                </value>
                <value>
                    <fullName>eMarketing</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Lead Scoring</fullName>
                </value>
                <value>
                    <fullName>OnArrival</fullName>
                </value>
                <value>
                    <fullName>Onsite Solutions</fullName>
                </value>
                <value>
                    <fullName>SMM</fullName>
                </value>
                <value>
                    <fullName>SocialWall</fullName>
                </value>
                <value>
                    <fullName>SpeedRFP/EMI</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Backlog_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Backlog Item</label>
        <referenceTo>Backlog_Item__c</referenceTo>
        <relationshipLabel>Related Enhancement Requests</relationshipLabel>
        <relationshipName>Enhancement_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>More Information Needed</fullName>
                </value>
                <value>
                    <fullName>Under Consideration</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Dismissed</fullName>
                </value>
                <value>
                    <fullName>Not Planned</fullName>
                </value>
                <value>
                    <fullName>On Roadmap</fullName>
                </value>
                <value>
                    <fullName>Existing Feature</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requesters_Priority__c</fullName>
        <description>Requester's priority based on impact to the requesting client(s)/prospect(s).</description>
        <inlineHelpText>Priority of the individual or group that is making the request. If this is an internal request, provide your priority</inlineHelpText>
        <label>Requester's Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enhancement Request</label>
    <nameField>
        <label>Enhancement Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enhancement Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/backlogItemTrgHelperClsTest.cls
/*
//////////////////////////////////////
//      @author Vaibhav Jain     //
/////////////////////////////////////
Version :   1.0
Date : 14th July 2015
*/
@isTest
public class backlogItemTrgHelperClsTest{
    public static Backlog_Item__c instOfBI = new Backlog_Item__c();
    static{
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User usrId = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='stansdfsddarduser@testorg.com');
        insert usrId;
        
        Account instofAcc = new Account();
        RecordType rtType = [SELECT r.SobjectType, r.DeveloperName,r.IsActive FROM RecordType r WHERE SobjectType='Account' And DeveloperName='Biz_Ac' And IsActive=true];
        instofAcc.Name = 'Test';
        instofAcc.Supplier_Type__c = 'Venue';
        instofAcc.Venue_Type__c = 'CVB';
        instofAcc.RecordTypeId = rtType.id;
        insert instofAcc;
        
        AccountTeamMember acctTM = new AccountTeamMember();
        acctTM.AccountId = instofAcc.Id;
        acctTM.TeamMemberRole = 'CS - CrowdCompass';
        acctTM.userId = usrId.Id;
        insert acctTM;
        
        Contact instofCon =  new Contact();
        instOfCon.LastName = 'Test';
        instOfCon.AccountId = instofAcc.Id;
        insert instOfCon;
        
        
        instOfBI.Name = 'Test';
        instOfBI.Product__c = 'API';
        instOfBI.Status__c = 'On Ice';
        instOfBI.Business_Case__c = 'Test';
        instOfBI.Approach__c = 'Test';
        insert instOfBI;
        
        Enhancement_Request__c instOfER = new Enhancement_Request__c();
        instOfER.Name = 'Test';
        instOfER.Product__c = 'CrowdCompass';
        instOfER.Requesters_Priority__c = 'High';
        instOfER.Date_Requested__c = system.today();
        instOfER.Request_Status__c = 'Reviewed - New';
        instOfER.Related_Backlog_Item__c = instOfBI.Id;
        instOfER.Contact__c = instOfCon.Id;
        insert instOfER;
    }
    static testMethod void myUnitTest() {
        instOfBI.Status__c = 'Closed - Released';
        update instOfBI;
    }
}