objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_GDPR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IS GDPR</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>GDPR</fullName>
        <active>true</active>
        <description>This is used for GDPR Records when it is marked GDPR true</description>
        <label>GDPR</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Alternate_Email__c</fullName>
        <label>Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CC_Contact_Status__c</fullName>
        <label>CC Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Suspect</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Marketing Qualified</fullName>
                </value>
                <value>
                    <fullName>Marketing Researched</fullName>
                </value>
                <value>
                    <fullName>Sales Accepted</fullName>
                </value>
                <value>
                    <fullName>Sales Generated</fullName>
                </value>
                <value>
                    <fullName>Sales Qualified</fullName>
                </value>
                <value>
                    <fullName>Open Opportunity</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Recycle</fullName>
                </value>
                <value>
                    <fullName>Trash</fullName>
                </value>
                <value>
                    <fullName>#N/A</fullName>
                    <isActive>false</isActive>
                    <label>#N/A</label>
                </value>
                <value>
                    <fullName>A - New Contact</fullName>
                    <isActive>false</isActive>
                    <label>A - New Contact</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                    <isActive>false</isActive>
                    <label>Attended</label>
                </value>
                <value>
                    <fullName>B - Working</fullName>
                    <isActive>false</isActive>
                    <label>B - Working</label>
                </value>
                <value>
                    <fullName>C - Qualified</fullName>
                    <isActive>false</isActive>
                    <label>C - Qualified</label>
                </value>
                <value>
                    <fullName>Chelsea Cantrell</fullName>
                    <isActive>false</isActive>
                    <label>Chelsea Cantrell</label>
                </value>
                <value>
                    <fullName>Colin Morrison</fullName>
                    <isActive>false</isActive>
                    <label>Colin Morrison</label>
                </value>
                <value>
                    <fullName>Cristina Estrella</fullName>
                    <isActive>false</isActive>
                    <label>Cristina Estrella</label>
                </value>
                <value>
                    <fullName>D - Set</fullName>
                    <isActive>false</isActive>
                    <label>D - Set</label>
                </value>
                <value>
                    <fullName>E  - Attended</fullName>
                    <isActive>false</isActive>
                    <label>E  - Attended</label>
                </value>
                <value>
                    <fullName>E - Aittended</fullName>
                    <isActive>false</isActive>
                    <label>E - Aittended</label>
                </value>
                <value>
                    <fullName>E - Atetnded</fullName>
                    <isActive>false</isActive>
                    <label>E - Atetnded</label>
                </value>
                <value>
                    <fullName>E - Attendd</fullName>
                    <isActive>false</isActive>
                    <label>E - Attendd</label>
                </value>
                <value>
                    <fullName>E - Attended</fullName>
                    <isActive>false</isActive>
                    <label>E - Attended</label>
                </value>
                <value>
                    <fullName>E - Attened</fullName>
                    <isActive>false</isActive>
                    <label>E - Attened</label>
                </value>
                <value>
                    <fullName>E -Attended</fullName>
                    <isActive>false</isActive>
                    <label>E -Attended</label>
                </value>
                <value>
                    <fullName>E- Attended</fullName>
                    <isActive>false</isActive>
                    <label>E- Attended</label>
                </value>
                <value>
                    <fullName>F - Pricing</fullName>
                    <isActive>false</isActive>
                    <label>F - Pricing</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_GDPR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is GDPR</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>GDPR</fullName>
        <active>true</active>
        <label>GDPR</label>
    </recordTypes>
</CustomObject>

objects/GDPR_Central_Repository__c.object
<CustomObject>
    <fields>
        <fullName>Alternate_Email__c</fullName>
        <label>Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Follow-Up Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_GDPR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is GDPR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject_type__c</fullName>
        <label>sObject type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Person Account</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This will hold the Contacts, Leads, Tasks, Cases which are being marked GDPR to validate if someone tries to create a new record with similar data.</description>
    <label>GDPR Central Repository</label>
    <nameField>
        <displayFormat>GDPR-{00000000}</displayFormat>
        <label>GDPR Central Repository Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDPR Central Repositories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/GDPR_Persona_Data__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GDPR_Central_Repository__c</fullName>
        <label>GDPR Central Repository</label>
        <referenceTo>GDPR_Central_Repository__c</referenceTo>
        <relationshipName>GDPR_Persona_Datas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Task_Subject__c</fullName>
        <label>Subject</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject_type__c</fullName>
        <label>sObject type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Email Messages</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>All the data related to Contact and Leads i.e Task/Event/Case</description>
    <label>GDPR Personal Data</label>
    <nameField>
        <displayFormat>GDPRPD-{000000000}</displayFormat>
        <label>GDPR Persona Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDPR Personal Datas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Alternate_Email__c</fullName>
        <label>Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_GDPR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is GDPR</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>GDPR</fullName>
        <active>true</active>
        <businessProcess>ROL Lead Process</businessProcess>
        <label>GDPR</label>
        
    </recordTypes>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>GDPR</fullName>
        <active>true</active>
        <label>GDPR</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Is_GDPR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is GDPR</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/testGDPR.cls
@istest
public class testGDPR{

public static testMethod void testGDPRMEthod(){
    
    Account acc1  = new Account();
    acc1.name = 'Test';
    acc1.BillingCountry='US';
    acc1.BillingState='TX';
    insert acc1;
        
    Account acc  = new Account();
    acc.name = 'Test123';
    acc.RecordTypeId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Biz A/c').getRecordTypeId();
    insert acc;
    
    Account accTest  = new Account();
    accTest.name = 'Test321';
    accTest.RecordTypeId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Biz A/c').getRecordTypeId();
    insert accTest;
    
    Task t1 = new task();
    t1.WhatId= accTest.id;
    t1.subject ='test GDPR';
    t1.description ='testing GDPR';
    T1.Campaign_ID__c='01p000000008yz5AAA';
    t1.RecordTypeId = '0120000000099ns';
    insert t1;
    
    Event e1 = new event();
    e1.WhatId = accTest.id;
    e1.subject ='test GDPR';
    e1.description ='testing GDPR';
    e1.Campaign_ID__c='01p000000008yz5AAA';
    e1.DurationInMinutes =1;
    e1.ActivityDateTime = system.now();
    insert e1;
    
    case c1 = new case();
    c1.accountId =accTest.id;
    c1.subject= 'testing';
    c1.description='testtt';
    insert c1;
    
    AccountHistory accHist = new AccountHistory();
    accHist.AccountId= accTest.Id;
    accHist.Field = 'FirstName';
    insert accHist;
     
    accTest.Is_GDPR__c= true;
    update accTest;
    
    Lead TestLead1 = new Lead(LastName='TestLead 1', Company='Test Company', Status='Qualified');
    insert TestLead1;
    
    TestLead1.Company = 'Cvent'; 
    update TestLead1;
    
    Lead TestLead = new Lead(LastName='TestLead 1', Company='Test Company', Status='Qualified');
    insert TestLead;
    TestLead.is_GDPR__C = true;
    update TestLead;
   
    Contact con = new Contact();
    con.LastName = 'Test Contact';
    con.AccountId = acc1.Id;
    insert con;
    Test.startTest();     
    con.CC_Contact_Status__c = 'Suspect';
    update con;
    
    Contact conTest = new Contact();
    conTest.LastName = 'Test Contact';
    conTest.AccountId = acc1.Id;
    conTest.email='test@test123.com';
    conTest.Alternate_Email__c ='testing@test.com';
    insert conTest;
    
    conTest.CC_Contact_Status__c = 'Suspect';
    update conTest;
    
    
    Task t = new task();
    t.WhoId = conTest.id;
    t.subject ='test GDPR';
    t.description ='testing GDPR';
    T.Campaign_ID__c='01p000000008yz5AAA';
    t.RecordTypeId = '0120000000099ns';
    insert t;
    
    Event e = new event();
    e.WhoId = conTest.id;
    e.subject ='test GDPR';
    e.description ='testing GDPR';
    e.Campaign_ID__c='01p000000008yz5AAA';
    e.DurationInMinutes =1;
    e.ActivityDateTime = system.now();
    insert e;
    
    case c = new case();
    c.contactId =conTest.id;
    c.subject= 'testing';
    c.description='testtt';
    insert c;
    
    ContactHistory conHist = new ContactHistory();
    conHist.ContactId= conTest.Id;
    conHist.Field = 'CC_Contact_Status__c';
    insert conHist;
    
    conTest.is_gdpr__c = true;
    update conTest;

    User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    System.runAs (thisUser) {

     user u = new User(
     ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
     LastName = 'last',
     Email = 'puser000@amamama.com',
     Username = 'puser000@amamama.com' + System.currentTimeMillis(),
     CompanyName = 'TEST',
     Title = 'title',
     Alias = 'alias',
     TimeZoneSidKey = 'America/Los_Angeles',
     EmailEncodingKey = 'UTF-8',
     LanguageLocaleKey = 'en_US',
     LocaleSidKey = 'en_US'//,
   //  UserRoleId = '00E00000006omly',
    // isPortalEnabled=true,
    // contactId = conTest.id
     );
     insert u;
     
     u.Is_GDPR__c = true;
     update u;
    } 

    String CRON_EXP = '0 0 0 1 1 ? 2025';  
    String jobId = System.schedule('schedulercreateGDPRPersonaBatch', CRON_EXP, new schedulercreateGDPRPersonaBatch() );

    CronTrigger ct = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId];

    System.assertEquals(CRON_EXP, ct.CronExpression); 
    System.assertEquals(0, ct.TimesTriggered);
    System.assertEquals('2025-01-01 00:00:00', String.valueOf(ct.NextFireTime));
            
    
    
    
// code for createGDPRPersonaBatch batch...........    
    GDPR_Central_Repository__c gdpr  = new GDPR_Central_Repository__c();
    gdpr.id__c = con.id; 
    gdpr.sObject_type__c ='Contact';
    gdpr.Is_GDPR__c = true;
    gdpr.LastName__c='testLastname';
    insert gdpr;
    
    GDPR_Central_Repository__c gdprLead  = new GDPR_Central_Repository__c();
    gdprLead.id__c = TestLead1.id; 
    gdprLead.sObject_type__c ='Lead';
    gdprLead.Is_GDPR__c = true;
    gdprLead.LastName__c='testLastname';
    insert gdprLead;
    
    GDPR_Central_Repository__c gdprAcc  = new GDPR_Central_Repository__c();
    gdprAcc.id__c = acc.id; 
    gdprAcc.sObject_type__c ='Person Account';
    gdprAcc.Is_GDPR__c = true;
    gdprAcc.LastName__c='testLastname';
    insert gdprAcc;
    
    String CRON_EXP2 = '0 0 0 1 1 ? 2025';  
    String jobId2 = System.schedule('schedulerCreateGDPRHistory', CRON_EXP2, new schedulerCreateGDPRHistory() );

    CronTrigger ct2 = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId2];

    System.assertEquals(CRON_EXP2, ct2.CronExpression); 
    System.assertEquals(0, ct2.TimesTriggered);
    System.assertEquals('2025-01-01 00:00:00', String.valueOf(ct2.NextFireTime));
                        
    LIST<GDPR_Central_Repository__c> gdprObj = NEW LIST<GDPR_Central_Repository__c> ();       
    gdprObj =[select id,Is_GDPR__c ,Follow_Up_Created__c from GDPR_Central_Repository__c where id__c = : conTest.id];
    IF(gdprObj.SIZE() > 0){
    gdprObj[0].Is_GDPR__c = false;
    gdprObj[0].Follow_Up_Created__c= true;    
    update gdprObj;
    

    // code for deleteGDPRPersonaBatch batch...........
    GDPR_Persona_Data__c gdpPersona = new GDPR_Persona_Data__c();
    gdpPersona.sObject_type__c ='Task';
    gdpPersona.id__C = t.id;
    gdpPersona.GDPR_Central_Repository__c = gdprObj[0].id;
    gdpPersona.Task_Subject__c = 'GDPR- test GDPR';
    gdpPersona.Comments__c = 'GDPR- testing GDPR';
    insert gdpPersona;
    
    GDPR_Persona_Data__c gdpPersona1 = new GDPR_Persona_Data__c();
    gdpPersona1.sObject_type__c ='Event';
    gdpPersona1.id__C = e.id;
    gdpPersona1.GDPR_Central_Repository__c = gdprObj[0].id;
    gdpPersona1.Task_Subject__c = 'GDPR- test GDPR';
    gdpPersona1.Comments__c = 'GDPR- testing GDPR';
    insert gdpPersona1;
    
    GDPR_Persona_Data__c gdpPersona2 = new GDPR_Persona_Data__c();
    gdpPersona2.sObject_type__c ='Case';
    gdpPersona2.id__C = c.id;
    gdpPersona2.GDPR_Central_Repository__c = gdprObj[0].id;
    gdpPersona2.Task_Subject__c = 'GDPR- test GDPR';
    gdpPersona2.Comments__c = 'GDPR- testing GDPR';
    insert gdpPersona2;
    
  //  gdprObj.Follow_Up_Created__c= true;    
 //   update gdprObj;
    
    gdprObj[0].Is_GDPR__c = false;
    update gdprObj;
    }
      
            
    String CRON_EXP1 = '0 0 0 1 1 ? 2025';  
    String jobId1 = System.schedule('schedulerdeleteGDPRPersonaBatch', CRON_EXP1, new schedulerdeleteGDPRPersonaBatch() );

    CronTrigger ct1 = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId1];

    System.assertEquals(CRON_EXP1, ct1.CronExpression); 
    System.assertEquals(0, ct1.TimesTriggered);
    System.assertEquals('2025-01-01 00:00:00', String.valueOf(ct1.NextFireTime));
    
    
    gdprLead.Is_GDPR__c = false;
    update gdprLead;
    
    
    gdprAcc.Is_GDPR__c = false;
    update gdprAcc;
    
                       
   Test.stopTest();    
   }
    
}