objects/Account.object
<CustomObject>
    <fields>
        <fullName>Desired_Tier_Dev__c</fullName>
        <description>When some one manually increases the TIER Level that value will be stored here until it is approved by approval process if rejected the value become null.</description>
        <label>Desired Tier Dev</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HODI_Count_Dev__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This will show the count of the HODI point when a TIER is changed on the HODI approval.</description>
        <label>HODI Count Dev</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HODI_Id_Dev__c</fullName>
        <description>This will store the recent HODI name to whom this account has been sent for approval or who has approved for change in service.</description>
        <label>HODI Id Dev</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Tier__c</fullName>
        <description>This will show the quality of service we will provide to the customer according to the Annual Contract Value.</description>
        <label>Service Tier (Hospitality Cloud)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Share_of_Wallet_Client__c</fullName>
        <label>EC Contracted ARR (Client)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HODI_Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Head_of_Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up field will show the name of the User.</description>
        <label>Head of Department</label>
        <referenceTo>User</referenceTo>
        <relationshipName>HODI_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pool_Point__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This will show the number of pool point assign to a User.</description>
        <label>Pool Point</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>This Object will show the User Name along with the POOL POINT assign to them.</description>
    <label>HODI Inventory</label>
    <nameField>
        <label>HODI Inventory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HODI Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountServiceHelperClass.cls
public class AccountServiceHelperClass
{
    @InvocableMethod
    public static void AccountServiceHelperMethod(List<Id> accountIds)
    {
        System.debug('Account===>'+accountIds);
        List<HODI_Inventory__c> HODIUpdate_List=new List<HODI_Inventory__c>();
        Map<Id,Decimal> HODIIdVsPoint_Map=new Map<Id,Decimal>();
        if(accountIds!=null && accountIds.size()>0){
           For(Account accValue: [SELECT Id,HODI_Id_Dev__c,HODI_Count_Dev__c,Service_Tier__c,Desired_Tier_Dev__c FROM Account WHERE Id IN : accountIds AND Service_Tier__c!=''])// AND Share_of_Wallet_Client__c!=null
           {
               HODIIdVsPoint_Map.put(Id.ValueOf(accValue.HODI_Id_Dev__c),math.abs(accValue.HODI_Count_Dev__c));
           }
        }
        System.debug('HODIIdVsPoint_Map===>'+HODIIdVsPoint_Map);
        if(HODIIdVsPoint_Map!=null)
        {
                For(HODI_Inventory__c HODIRecord : [SELECT Id,Name,Head_of_Department__c,Head_of_Department__r.Name,Pool_Point__c FROM HODI_Inventory__c WHERE Id IN :HODIIdVsPoint_Map.keySet()])
                {
                    HODIRecord.Pool_Point__c = HODIRecord.Pool_Point__c + HODIIdVsPoint_Map.get(HODIRecord.Id);
                    HODIUpdate_List.add(HODIRecord);
                }
        }
        System.debug('HODIUpdate_List===>'+HODIUpdate_List);
        if(HODIUpdate_List!=null && HODIUpdate_List.size()>0)
        update HODIUpdate_List;
    
    
    }
}