objects/Account.object
<CustomObject>
    <fields>
        <fullName>AM_CSN__c</fullName>
        <label>AM - CSN</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aaron Singh</fullName>
                </value>
                <value>
                    <fullName>Alan Day</fullName>
                </value>
                <value>
                    <fullName>Alda Egurrola-Wienke</fullName>
                </value>
                <value>
                    <fullName>Alison LeRoy</fullName>
                </value>
                <value>
                    <fullName>Alyssa Klimas</fullName>
                </value>
                <value>
                    <fullName>Becki Miltenberger</fullName>
                </value>
                <value>
                    <fullName>Becky Matlack</fullName>
                </value>
                <value>
                    <fullName>Benjamin Fama</fullName>
                </value>
                <value>
                    <fullName>Brian Fleagle</fullName>
                </value>
                <value>
                    <fullName>Brittney Garcia</fullName>
                </value>
                <value>
                    <fullName>Bryant Waters</fullName>
                </value>
                <value>
                    <fullName>Buledy Sangwa</fullName>
                </value>
                <value>
                    <fullName>Chela Evans</fullName>
                </value>
                <value>
                    <fullName>Elizabeth Almand</fullName>
                </value>
                <value>
                    <fullName>Georgette Young</fullName>
                </value>
                <value>
                    <fullName>Janine Alsalam</fullName>
                </value>
                <value>
                    <fullName>Joanne Augustin</fullName>
                </value>
                <value>
                    <fullName>John Doolittle</fullName>
                </value>
                <value>
                    <fullName>John Oliver</fullName>
                </value>
                <value>
                    <fullName>Keith Lange</fullName>
                </value>
                <value>
                    <fullName>Ken McGovern</fullName>
                </value>
                <value>
                    <fullName>Kyle Wolfson</fullName>
                </value>
                <value>
                    <fullName>Lindsay Watts</fullName>
                </value>
                <value>
                    <fullName>Madeleine Kent</fullName>
                </value>
                <value>
                    <fullName>Marina Machado</fullName>
                </value>
                <value>
                    <fullName>Mark Jacobs</fullName>
                </value>
                <value>
                    <fullName>Mark Nagy</fullName>
                </value>
                <value>
                    <fullName>Matt Macy</fullName>
                </value>
                <value>
                    <fullName>Melissa Negron</fullName>
                </value>
                <value>
                    <fullName>Michael Webber</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AM_Event__c</fullName>
        <inlineHelpText>Account Manager - Responsible for Managing and Renewing this Customer</inlineHelpText>
        <label>AM – Event Cloud</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adrian Arora</fullName>
                </value>
                <value>
                    <fullName>Afeef Khalil</fullName>
                </value>
                <value>
                    <fullName>Aftab Alam</fullName>
                </value>
                <value>
                    <fullName>Akshay Doshi</fullName>
                </value>
                <value>
                    <fullName>Alex Rolfe</fullName>
                </value>
                <value>
                    <fullName>Allison Spirer</fullName>
                </value>
                <value>
                    <fullName>Amanda Payne</fullName>
                </value>
                <value>
                    <fullName>Amy Chugh</fullName>
                </value>
                <value>
                    <fullName>Amy Zaczkowski</fullName>
                </value>
                <value>
                    <fullName>Andrew MacIsaac</fullName>
                </value>
                <value>
                    <fullName>Andy Rouhafzai</fullName>
                </value>
                <value>
                    <fullName>Anil Punyapu</fullName>
                </value>
                <value>
                    <fullName>Ann OBrien</fullName>
                </value>
                <value>
                    <fullName>Anujeet Verma</fullName>
                </value>
                <value>
                    <fullName>Arielle Meizen</fullName>
                </value>
                <value>
                    <fullName>Arvind Kumar</fullName>
                </value>
                <value>
                    <fullName>Ashley Mohney</fullName>
                </value>
                <value>
                    <fullName>Austin Alam</fullName>
                </value>
                <value>
                    <fullName>Barry Greene</fullName>
                </value>
                <value>
                    <fullName>Barry Womack</fullName>
                </value>
                <value>
                    <fullName>Becca Bicer</fullName>
                </value>
                <value>
                    <fullName>Benjamin Ball</fullName>
                </value>
                <value>
                    <fullName>Bill Piekarski</fullName>
                </value>
                <value>
                    <fullName>Blake Rivers</fullName>
                </value>
                <value>
                    <fullName>Bradley Blinn</fullName>
                </value>
                <value>
                    <fullName>Brandon Beall</fullName>
                </value>
                <value>
                    <fullName>Brian Ludwig</fullName>
                </value>
                <value>
                    <fullName>Brittany Jennings</fullName>
                </value>
                <value>
                    <fullName>Brittlynn Goddard</fullName>
                </value>
                <value>
                    <fullName>Caitlin Guichard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AM_PA__c</fullName>
        <label>AM - Sourcing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AM - Sourcing</fullName>
                </value>
                <value>
                    <fullName>Amy Chugh</fullName>
                </value>
                <value>
                    <fullName>Jessica John</fullName>
                </value>
                <value>
                    <fullName>Kathryn Kozak</fullName>
                </value>
                <value>
                    <fullName>Lisa Welch</fullName>
                </value>
                <value>
                    <fullName>Olivia Murray-Taylor</fullName>
                </value>
                <value>
                    <fullName>Taylor Mohrmann</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AM_Pre_Sales_Event__c</fullName>
        <label>AM Associate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lara Swan</fullName>
                </value>
                <value>
                    <fullName>Izzy Hettiarachchi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AM_Survey__c</fullName>
        <label>AM - Inquisium</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afeef Khalil</fullName>
                </value>
                <value>
                    <fullName>Allison Spirer</fullName>
                </value>
                <value>
                    <fullName>Amy Chugh</fullName>
                </value>
                <value>
                    <fullName>Anil Punyapu</fullName>
                </value>
                <value>
                    <fullName>Arvind Kumar</fullName>
                </value>
                <value>
                    <fullName>Ashley Mohney</fullName>
                </value>
                <value>
                    <fullName>Aftab Alam</fullName>
                </value>
                <value>
                    <fullName>Bart Hart</fullName>
                </value>
                <value>
                    <fullName>Becca Bicer</fullName>
                </value>
                <value>
                    <fullName>Brittany Jennings</fullName>
                </value>
                <value>
                    <fullName>Brittlynn Goddard</fullName>
                </value>
                <value>
                    <fullName>Caitlin Guichard</fullName>
                </value>
                <value>
                    <fullName>Chris Kearney</fullName>
                </value>
                <value>
                    <fullName>Christian Luik</fullName>
                </value>
                <value>
                    <fullName>Christopher Coultas</fullName>
                </value>
                <value>
                    <fullName>Christopher McNerney</fullName>
                </value>
                <value>
                    <fullName>Christopher Rost</fullName>
                </value>
                <value>
                    <fullName>Christopher Walizer</fullName>
                </value>
                <value>
                    <fullName>Coleman Bacon</fullName>
                </value>
                <value>
                    <fullName>Colin Morrison</fullName>
                </value>
                <value>
                    <fullName>Courtney Smith</fullName>
                </value>
                <value>
                    <fullName>Debby Fischer</fullName>
                </value>
                <value>
                    <fullName>Denise Farrell</fullName>
                </value>
                <value>
                    <fullName>Erin Dugan</fullName>
                </value>
                <value>
                    <fullName>Erin Phelps</fullName>
                </value>
                <value>
                    <fullName>Ibrahim Lamay</fullName>
                </value>
                <value>
                    <fullName>Jack Ross</fullName>
                </value>
                <value>
                    <fullName>Jaya Prasad</fullName>
                </value>
                <value>
                    <fullName>Jessica Arrazola</fullName>
                </value>
                <value>
                    <fullName>Jessica John</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CS_Rep__c</fullName>
        <inlineHelpText>This field is no longer in use. This will eventually be removed from page layout as well. Please see Account team to see the info you need.</inlineHelpText>
        <label>CS Rep</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abbas Izhar</fullName>
                </value>
                <value>
                    <fullName>Adam Crosby</fullName>
                </value>
                <value>
                    <fullName>Adam Verma</fullName>
                </value>
                <value>
                    <fullName>Addy Anand</fullName>
                </value>
                <value>
                    <fullName>Addy Verma</fullName>
                </value>
                <value>
                    <fullName>Adrianne Carpenter</fullName>
                </value>
                <value>
                    <fullName>Adrian Saxena</fullName>
                </value>
                <value>
                    <fullName>Akshay Saluja</fullName>
                </value>
                <value>
                    <fullName>Alan Sachdeva</fullName>
                </value>
                <value>
                    <fullName>Alexa Deucher</fullName>
                </value>
                <value>
                    <fullName>Alexandra Smith</fullName>
                </value>
                <value>
                    <fullName>Alexis Petrovich</fullName>
                </value>
                <value>
                    <fullName>Alex Migdol</fullName>
                </value>
                <value>
                    <fullName>Alice Saxena</fullName>
                </value>
                <value>
                    <fullName>Alicia Bawa</fullName>
                </value>
                <value>
                    <fullName>Alyson Toole</fullName>
                </value>
                <value>
                    <fullName>Amy Remmer</fullName>
                </value>
                <value>
                    <fullName>Anand Banerjee</fullName>
                </value>
                <value>
                    <fullName>Andrew Varghese</fullName>
                </value>
                <value>
                    <fullName>Angelle Stromeyer</fullName>
                </value>
                <value>
                    <fullName>Animesh Upadhyaya</fullName>
                </value>
                <value>
                    <fullName>Anna Thapa</fullName>
                </value>
                <value>
                    <fullName>Ann OBrien</fullName>
                </value>
                <value>
                    <fullName>April Durgapal</fullName>
                </value>
                <value>
                    <fullName>Archie Menon</fullName>
                </value>
                <value>
                    <fullName>Aria Chopra</fullName>
                </value>
                <value>
                    <fullName>Arvind Kumar</fullName>
                </value>
                <value>
                    <fullName>Ashna Patial</fullName>
                </value>
                <value>
                    <fullName>Audrey Staples</fullName>
                </value>
                <value>
                    <fullName>Avinash Kumar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BatchUpdateAccountTeamMembersOnAccount.cls
/**********************************************************************************
Class to update AccountTeamMemberInformation on Account
**********************************************************************************/
global class BatchUpdateAccountTeamMembersOnAccount implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //Fetching account and its associated team members
        return Database.getQueryLocator([Select id/*,AM_CrowdTorch__c*/,AM_CSN__c,/*AM_CT_TM__c,*/AM_Event__c,AM_Survey__c,AM_PA__c,/*AM_TicketMob__c,*/AM_Pre_Sales_Event__c,CS_Rep__c,(Select TeamMemberRole,User.Name From AccountTeamMembers) FROM Account where Account_Status__c Like 'Active%']);
        
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) {
        //try{
        //Crating a map of customsetting
        Map<String,String>teamRoleFieldAPIMap = new Map<String,String>();
        
        List<AccountAndTeamMembersSetting__c> teamFieldAPI = AccountAndTeamMembersSetting__c.getall().values();
        for(AccountAndTeamMembersSetting__c st: teamFieldAPI) {
            if(!teamRoleFieldAPIMap.containsKey(st.Name)) {
                teamRoleFieldAPIMap.put(st.Name,st.FieldAPIName__c);
            }
        }
        
        //Looping over account
        List<Account> accountsToUpdate = new List<Account>();
        for(Account acc: scope){
            String csRepValue = '';
            Map<String,String> fieldAndValueMap = new Map<String,String>();
            Set<String> alreadyExistCSRep = new Set<String>();
            
            for(AccountTeamMEmber actm: acc.AccountTeamMembers) {
                
                //creating map of fieldapiname and value to populate 
                if(teamRoleFieldAPIMap.containsKey(actm.TeamMemberRole) && actm.TeamMemberRole.startsWith('CS -') && !alreadyExistCSRep.contains(actm.TeamMemberRole)) {
                    csRepValue = csRepValue + actm.User.Name  + ';';
                    alreadyExistCSRep.add(actm.TeamMemberRole);
                    fieldAndValueMap.put(teamRoleFieldAPIMap.get(actm.TeamMemberRole),csRepValue);
                }
                if(teamRoleFieldAPIMap.containsKey(actm.TeamMemberRole) && !actm.TeamMemberRole.startsWith('CS -')) {
                    fieldAndValueMap.put(teamRoleFieldAPIMap.get(actm.TeamMemberRole),actm.User.Name);
                }
                
            }
            
            //loop over customsetting fields to populate values in fields used in custom setting
            for(String fname: teamRoleFieldAPIMap.values()) {
                //Added by Shanu : August 2016 ( Check If Field is being changed only updates) 
                if(fieldAndValueMap.containsKey(fname) && acc.get(fname)!=fieldAndValueMap.get(fname)) {
                    acc.put(fname,fieldAndValueMap.get(fname));
                } 
            }
            
            accountsToUpdate.add(acc);
        }
        
        if(accountsToUpdate.size() > 0) {
            update accountsToUpdate;
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
    } 
}