objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Prospect Lead</fullName>
                </value>
                <value>
                    <fullName>Fit Lead</fullName>
                </value>
                <value>
                    <fullName>Active Lead</fullName>
                </value>
                <value>
                    <fullName>Passive Win</fullName>
                </value>
                <value>
                    <fullName>Imp Win</fullName>
                </value>
                <value>
                    <fullName>Live Win</fullName>
                </value>
                <value>
                    <fullName>End Business</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RFP__c.object
<CustomObject>
    <fields>
        <fullName>Escalated_RFP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated RFP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFP_Code__c</fullName>
        <externalId>true</externalId>
        <label>RFP Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Awaiting Proposal</fullName>
                </value>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Awarded by Hotel</fullName>
                </value>
                <value>
                    <fullName>Awarded By Planner</fullName>
                </value>
                <value>
                    <fullName>Booked Elsewhere</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Forwarded</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Proposal Declined</fullName>
                </value>
                <value>
                    <fullName>Proposal Received</fullName>
                </value>
                <value>
                    <fullName>Receipt Confirmed</fullName>
                </value>
                <value>
                    <fullName>RFP Declined</fullName>
                </value>
                <value>
                    <fullName>RFP Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted Proposal</fullName>
                </value>
                <value>
                    <fullName>Turned Down</fullName>
                </value>
                <value>
                    <fullName>Will Not Accept Terms of Use</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <label>Supplier A/c</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RFPs (Supplier A/c)</relationshipLabel>
        <relationshipName>RFPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Code__c</fullName>
        <externalId>true</externalId>
        <label>Unique Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unique_RFP_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unique RFP ID</label>
        <referenceTo>Unique_RFPs__c</referenceTo>
        <relationshipName>RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFPs</label>
    <nameField>
        <label>RFP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Unique_RFPs__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Unique RFPs (Contact)</relationshipLabel>
        <relationshipName>Unique_RFPs1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Escalated_RFP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to automate the porcess with custom code.</description>
        <inlineHelpText>Clicking this check box will auto escalate all the 'awaiting proposal' RFP's.</inlineHelpText>
        <label>Escalated RFP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFP_Code__c</fullName>
        <externalId>true</externalId>
        <label>RFP Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awarded</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>RFP Declined</fullName>
                </value>
                <value>
                    <fullName>Booked Elsewhere</fullName>
                </value>
                <value>
                    <fullName>Awarded By Planner</fullName>
                </value>
                <value>
                    <fullName>Proposal Received</fullName>
                </value>
                <value>
                    <fullName>Awarded by Hotel</fullName>
                </value>
                <value>
                    <fullName>Proposal Declined</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>RFP Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_RFP_ID__c</fullName>
        <formula>Id</formula>
        <label>Unique RFP ID</label>
        <type>Text</type>
    </fields>
    <label>Unique RFPs</label>
    <nameField>
        <label>Unique RFPs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unique RFPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestUniqueRFPTrigger.cls
/*==========================================================================================================
//Created by Rishi Ojha 
//Unit testing for the Trigger : UpdateChildRFPs
============================================================================================================*/

@isTest(SeeAllData=True)
    
    Private class TestUniqueRFPTrigger
    
  {
    Static testmethod void testUpdateChildRFPs(){
            
            Recordtype  R1 = [select id,name from recordtype where SobjectType = 'Account' and name ='Biz A/c' ];
            
            Account Acc = new Account(Name='TestAcc',recordtypeid = R1.id);
            insert Acc;
            
            contact con = new Contact(LastName='testCon', Accountid = Acc.id);
            insert con; 
            
            Unique_RFPs__c urfp = New Unique_RFPs__c(Name='testerfp',RFP_Code__c='testcode', Contact__c=con.id);
            insert urfp;
    
            RFP__c rfp = New RFP__c(Name='testrfp', RFP_Code__c='1234256',Status__c='Awaiting Proposal', 
                                    Unique_Code__c='45461',Supplier_Account__c=Acc.id,Unique_RFP_ID__c=urfp.id);
            insert rfp;
            
            update New RFP__c(Name='testrfp222', id=rfp.id);
   
    if(urfp.Escalated_RFP__c = True)
   // For (RFP.Status__c = 'Awaiting Proposal')
    
    rfp.Escalated_RFP__c = True;
  //  rfp2.Escalated_RFP__c = True;
    //rfp3.Escalated_RFP__c = True;
   
  //  update urfp;
    
     
    List<Unique_RFPs__c> inserturfps = [SELECT Name,ID,Status__c,Escalated_RFP__c,(Select id,Name,Status__c,Escalated_RFP__c from RFPs__r) FROM Unique_RFPs__c where ID = : urfp.Id ];
    
   
    }
  }