objects/Account.object
<CustomObject>
    <fields>
        <fullName>API_connected_with__c</fullName>
        <label>API connected with</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>123Signup</fullName>
                </value>
                <value>
                    <fullName>44fish.com</fullName>
                </value>
                <value>
                    <fullName>Act-On</fullName>
                </value>
                <value>
                    <fullName>Acumen</fullName>
                </value>
                <value>
                    <fullName>Advanced CRM</fullName>
                </value>
                <value>
                    <fullName>Affiniscape (m360)</fullName>
                </value>
                <value>
                    <fullName>Alliance Tech</fullName>
                </value>
                <value>
                    <fullName>Alpha Software</fullName>
                </value>
                <value>
                    <fullName>Amadeus</fullName>
                </value>
                <value>
                    <fullName>aMember Pro</fullName>
                </value>
                <value>
                    <fullName>Apollo</fullName>
                </value>
                <value>
                    <fullName>Association Management Online</fullName>
                </value>
                <value>
                    <fullName>AssociationVoice</fullName>
                </value>
                <value>
                    <fullName>Attendee Interactive</fullName>
                </value>
                <value>
                    <fullName>Authorize.Net</fullName>
                </value>
                <value>
                    <fullName>Avectra</fullName>
                </value>
                <value>
                    <fullName>AWeber</fullName>
                </value>
                <value>
                    <fullName>Bernard Data Solutions</fullName>
                </value>
                <value>
                    <fullName>BuilderFusion</fullName>
                </value>
                <value>
                    <fullName>Capture</fullName>
                </value>
                <value>
                    <fullName>CDS (convention data services)</fullName>
                </value>
                <value>
                    <fullName>ChamberMaster</fullName>
                </value>
                <value>
                    <fullName>Ciboodle</fullName>
                </value>
                <value>
                    <fullName>CiviCRM</fullName>
                </value>
                <value>
                    <fullName>ClubExpress</fullName>
                </value>
                <value>
                    <fullName>CME Tracker</fullName>
                </value>
                <value>
                    <fullName>Concur Finance</fullName>
                </value>
                <value>
                    <fullName>Concur Travel</fullName>
                </value>
                <value>
                    <fullName>Constant Contact</fullName>
                </value>
                <value>
                    <fullName>Convio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Back_Office_System__c</fullName>
        <label>Back Office System</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>123Signup</fullName>
                </value>
                <value>
                    <fullName>44fish.com</fullName>
                </value>
                <value>
                    <fullName>Act-On</fullName>
                </value>
                <value>
                    <fullName>Acumen</fullName>
                </value>
                <value>
                    <fullName>Advanced CRM</fullName>
                </value>
                <value>
                    <fullName>Affiniscape (m360)</fullName>
                </value>
                <value>
                    <fullName>Alliance Tech</fullName>
                </value>
                <value>
                    <fullName>Alpha Software</fullName>
                </value>
                <value>
                    <fullName>Amadeus</fullName>
                </value>
                <value>
                    <fullName>aMember Pro</fullName>
                </value>
                <value>
                    <fullName>AMEX Card</fullName>
                </value>
                <value>
                    <fullName>Apollo</fullName>
                </value>
                <value>
                    <fullName>Association Management Online</fullName>
                </value>
                <value>
                    <fullName>AssociationVoice</fullName>
                </value>
                <value>
                    <fullName>Attendee Interactive</fullName>
                </value>
                <value>
                    <fullName>Attendify</fullName>
                </value>
                <value>
                    <fullName>Authorize.Net</fullName>
                </value>
                <value>
                    <fullName>Avectra</fullName>
                </value>
                <value>
                    <fullName>AWeber</fullName>
                </value>
                <value>
                    <fullName>Bernard Data Solutions</fullName>
                </value>
                <value>
                    <fullName>Blackboard</fullName>
                </value>
                <value>
                    <fullName>BuilderFusion</fullName>
                </value>
                <value>
                    <fullName>CAMMS</fullName>
                </value>
                <value>
                    <fullName>Canvas LMS</fullName>
                </value>
                <value>
                    <fullName>Capture</fullName>
                </value>
                <value>
                    <fullName>CDS (convention data services)</fullName>
                </value>
                <value>
                    <fullName>ChamberMaster</fullName>
                </value>
                <value>
                    <fullName>Ciboodle</fullName>
                </value>
                <value>
                    <fullName>Citi Virtual Card</fullName>
                </value>
                <value>
                    <fullName>CiviCRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Resources__c.object
<CustomObject>
    <fields>
        <fullName>API_connected_with__c</fullName>
        <label>API connected with</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>123Signup</fullName>
                </value>
                <value>
                    <fullName>44fish.com</fullName>
                </value>
                <value>
                    <fullName>Act-On</fullName>
                </value>
                <value>
                    <fullName>Acumen</fullName>
                </value>
                <value>
                    <fullName>Advanced CRM</fullName>
                </value>
                <value>
                    <fullName>Affiniscape (m360)</fullName>
                </value>
                <value>
                    <fullName>Alliance Tech</fullName>
                </value>
                <value>
                    <fullName>Alpha Software</fullName>
                </value>
                <value>
                    <fullName>Amadeus</fullName>
                </value>
                <value>
                    <fullName>aMember Pro</fullName>
                </value>
                <value>
                    <fullName>Apollo</fullName>
                </value>
                <value>
                    <fullName>Association Management Online</fullName>
                </value>
                <value>
                    <fullName>AssociationVoice</fullName>
                </value>
                <value>
                    <fullName>Attendee Interactive</fullName>
                </value>
                <value>
                    <fullName>Authorize.Net</fullName>
                </value>
                <value>
                    <fullName>Avectra</fullName>
                </value>
                <value>
                    <fullName>AWeber</fullName>
                </value>
                <value>
                    <fullName>Bernard Data Solutions</fullName>
                </value>
                <value>
                    <fullName>Blackbaud CRM</fullName>
                </value>
                <value>
                    <fullName>BuilderFusion</fullName>
                </value>
                <value>
                    <fullName>Capture</fullName>
                </value>
                <value>
                    <fullName>CDS (convention data services)</fullName>
                </value>
                <value>
                    <fullName>ChamberMaster</fullName>
                </value>
                <value>
                    <fullName>Ciboodle</fullName>
                </value>
                <value>
                    <fullName>CiviCRM</fullName>
                </value>
                <value>
                    <fullName>ClubExpress</fullName>
                </value>
                <value>
                    <fullName>CME Tracker</fullName>
                </value>
                <value>
                    <fullName>Concur Finance</fullName>
                </value>
                <value>
                    <fullName>Concur Travel</fullName>
                </value>
                <value>
                    <fullName>Constant Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sales_RFP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Back_Office_System_New__c</fullName>
        <label>Back Office System</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>123Signup</fullName>
                </value>
                <value>
                    <fullName>44fish.com</fullName>
                </value>
                <value>
                    <fullName>Act-On</fullName>
                </value>
                <value>
                    <fullName>Acumen</fullName>
                </value>
                <value>
                    <fullName>Advanced CRM</fullName>
                </value>
                <value>
                    <fullName>Affiniscape (m360)</fullName>
                </value>
                <value>
                    <fullName>Alliance Tech</fullName>
                </value>
                <value>
                    <fullName>Alpha Software</fullName>
                </value>
                <value>
                    <fullName>Amadeus</fullName>
                </value>
                <value>
                    <fullName>aMember Pro</fullName>
                </value>
                <value>
                    <fullName>Apollo</fullName>
                </value>
                <value>
                    <fullName>Association Management Online</fullName>
                </value>
                <value>
                    <fullName>AssociationVoice</fullName>
                </value>
                <value>
                    <fullName>Attendee Interactive</fullName>
                </value>
                <value>
                    <fullName>Authorize.Net</fullName>
                </value>
                <value>
                    <fullName>Avectra</fullName>
                </value>
                <value>
                    <fullName>AWeber</fullName>
                </value>
                <value>
                    <fullName>Bernard Data Solutions</fullName>
                </value>
                <value>
                    <fullName>Blackbaud CRM</fullName>
                </value>
                <value>
                    <fullName>Blackboard</fullName>
                </value>
                <value>
                    <fullName>BuilderFusion</fullName>
                </value>
                <value>
                    <fullName>CAMMS</fullName>
                </value>
                <value>
                    <fullName>Canvas LMS</fullName>
                </value>
                <value>
                    <fullName>Capture</fullName>
                </value>
                <value>
                    <fullName>CDS (convention data services)</fullName>
                </value>
                <value>
                    <fullName>ChamberMaster</fullName>
                </value>
                <value>
                    <fullName>Ciboodle</fullName>
                </value>
                <value>
                    <fullName>CiviCRM</fullName>
                </value>
                <value>
                    <fullName>ClubExpress</fullName>
                </value>
                <value>
                    <fullName>CME Tracker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Resources</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Sales_Engineering</fullName>
        <active>true</active>
        <label>Sales Engineering</label>
    </recordTypes>
</CustomObject>

classes/salesResourcesTrgHelperCls.cls
/**
///////////////////////////////
//    @author Rohit Saxena    //
///////////////////////////////

Version 1.0
Date: 10th July 2015
Description: Update/Insert 2 fields at Account with the same value Sales Resource Object have for same fields.
*/

public class salesResourcesTrgHelperCls {
    public void OnBeforeInsert(List<Sales_Resources__c> newValues){    
        RecordType instRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Sales_Engineering' And SobjectType = 'Sales_Resources__c' And IsActive = true];
        Set<Id> setAccId = new Set<Id>();
        
        for(Sales_Resources__c instOfSalRes : newValues){
            if(instOfSalRes.Account__c != null && instRecType.Id == instOfSalRes.RecordTypeId)
            setAccId.add(instOfSalRes.Account__c);
        }
        
        Map<Id,Account> mapAcc = new Map<Id,Account>();
        
        if(setAccId.size()>0)
        mapAcc = new map<Id,Account>([SELECT Id,API_connected_with__c,Back_Office_System__c,(SELECT Id FROM Sales_RFP__r WHERE RecordTypeId =: instRecType.Id) FROM Account WHERE Id=: setAccId]);
        
        for(Sales_Resources__c instOfSalRes : newValues){
            if(mapAcc.containsKey(instOfSalRes.Account__c)){
                if(mapAcc.get(instOfSalRes.Account__c).Sales_RFP__r.size()>0){
               /*     instOfSalRes.addError('Account already containse Sales Resource record with record type Sales Engineering');*/
                }else{
                    instOfSalRes.Back_Office_System_New__c = mapAcc.get(instOfSalRes.Account__c).Back_Office_System__c + ';' + instOfSalRes.Back_Office_System_New__c;
                    instOfSalRes.API_connected_with__c = mapAcc.get(instOfSalRes.Account__c).API_connected_with__c + ';' + instOfSalRes.API_connected_with__c;
                }
            }
        }
    }
    
    public void OnAfterInsert(Map<Id,Sales_Resources__c> newMapValues){  
        RecordType instRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Sales_Engineering' And SobjectType = 'Sales_Resources__c' And IsActive = true];
        Set<Id> setAccId = new Set<Id>();
        
        for(Sales_Resources__c instOfSalRes : newMapValues.values()){
            if(instOfSalRes.Account__c != null && instRecType.Id == instOfSalRes.RecordTypeId)
            setAccId.add(instOfSalRes.Account__c);
        }
        
        Map<Id,Account> mapAcc = new Map<Id,Account>();
        
        if(setAccId.size()>0)
        mapAcc = new map<Id,Account>([SELECT Id,API_connected_with__c,Back_Office_System__c,(SELECT Id FROM Sales_RFP__r WHERE RecordTypeId =: instRecType.Id) FROM Account WHERE Id=: setAccId]);
        
        List<Account> lstAccountUpd = new List<Account>();

        for(Sales_Resources__c instOfSalRes : newMapValues.values()){
            if(mapAcc.containsKey(instOfSalRes.Account__c)){
                Account instOfAcc = new Account();
                instOfAcc.Id = instOfSalRes.Account__c;
                instOfAcc.Back_Office_System__c = mapAcc.get(instOfSalRes.Account__c).Back_Office_System__c + ';' + instOfSalRes.Back_Office_System_New__c;
                instOfAcc.API_connected_with__c = mapAcc.get(instOfSalRes.Account__c).API_connected_with__c + ';' + instOfSalRes.API_connected_with__c;
                lstAccountUpd.add(instOfAcc);
            }
        }
        
        if(lstAccountUpd.size()>0)
        update lstAccountUpd;
    }
    
    public void OnBeforeUpdate(Map<Id,Sales_Resources__c> oldMapValues,Map<Id,Sales_Resources__c> newMapValues){ 
        
    }
    public void OnAfterUpdate(Map<Id,Sales_Resources__c> oldMapValues,Map<Id,Sales_Resources__c> newMapValues){ 
        RecordType instRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Sales_Engineering' And SobjectType = 'Sales_Resources__c' And IsActive = true];
        Set<Id> setAccId = new Set<Id>();
        Map<Id,String> mapOfBackOffice = new Map<Id,String>();
        Map<Id,String> mapOfApiCon = new Map<Id,String>();
        for(Sales_Resources__c instOfSalRes :  newMapValues.values()){
            
                if((instOfSalRes.Back_Office_System_New__c != oldMapValues.get(instOfSalRes.Id).Back_Office_System_New__c || instOfSalRes.API_connected_with__c != oldMapValues.get(instOfSalRes.Id).API_connected_with__c) && instOfSalRes.RecordTypeId == instRecType.Id){
                    if(instOfSalRes.Account__c != null){
                        
                        setAccId.add(instOfSalRes.Account__c);
                        
                        if(instOfSalRes.Back_Office_System_New__c != null && instOfSalRes.Back_Office_System_New__c !='')
                        mapOfBackOffice.put(instOfSalRes.Account__c,instOfSalRes.Back_Office_System_New__c);
                        else
                        mapOfBackOffice.put(instOfSalRes.Account__c,'');
                        
                        if(instOfSalRes.API_connected_with__c != null && instOfSalRes.API_connected_with__c !='')
                        mapOfApiCon.put(instOfSalRes.Account__c,instOfSalRes.API_connected_with__c);
                        else
                        mapOfApiCon.put(instOfSalRes.Account__c,'');
                    }
                }
            
        }
        
        List<Account> lstAccount = new List<Account>();
        
        if(setAccId.size()>0)
        lstAccount = [SELECT Id,API_connected_with__c,Back_Office_System__c FROM Account WHERE Id=: setAccId];
        
        List<Account> lstAccToBeUpdated = new List<Account>();
        
        for(Account instOfAcc : lstAccount){
            if(mapOfBackOffice.containsKey(instOfAcc.Id)){
                instOfAcc.Back_Office_System__c =  mapOfBackOffice.get(instOfAcc.Id);
            }
            if(mapOfApiCon.containsKey(instOfAcc.Id)){
                instOfAcc.API_connected_with__c =  mapOfApiCon.get(instOfAcc.Id);
            }
            lstAccToBeUpdated.add(instOfAcc);
        }
        
        if(lstAccToBeUpdated.size()> 0){
            update lstAccToBeUpdated;
            
        }
    }
    public void OnBeforeDelete(List<Sales_Resources__c> oldValues,Map<Id,Sales_Resources__c> oldMapValues){
        
    }
    
    public void OnAfterDelete(List<Sales_Resources__c> oldValues,Map<Id,Sales_Resources__c> oldMapValues){
    }
    
    public void OnUndelete(List<Sales_Resources__c> newValues){
        
    }
}