objects/Account.object
<CustomObject>
    <fields>
        <fullName>Supplier_Type__c</fullName>
        <label>Supplier Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>Unique Venue</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue_Type__c</fullName>
        <label>Venue/Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Supplier_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Above- Property Account</fullName>
                </value>
                <value>
                    <fullName>Aquarium / Zoo</fullName>
                </value>
                <value>
                    <fullName>Arena / Stadium</fullName>
                </value>
                <value>
                    <fullName>AV / Production &amp; Design</fullName>
                </value>
                <value>
                    <fullName>Banquet Facility</fullName>
                </value>
                <value>
                    <fullName>Bar / Club</fullName>
                </value>
                <value>
                    <fullName>Boutique Hotel</fullName>
                </value>
                <value>
                    <fullName>Caterers / Food Services</fullName>
                </value>
                <value>
                    <fullName>Conference Center</fullName>
                </value>
                <value>
                    <fullName>Convention Center</fullName>
                </value>
                <value>
                    <fullName>Corporate Office Space</fullName>
                </value>
                <value>
                    <fullName>CVB</fullName>
                </value>
                <value>
                    <fullName>CVB/DMC</fullName>
                </value>
                <value>
                    <fullName>Educational Facility</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Entertainment Venue</fullName>
                </value>
                <value>
                    <fullName>Event hospitality &amp; entertainment Limited</fullName>
                </value>
                <value>
                    <fullName>Event Management / DMCs</fullName>
                </value>
                <value>
                    <fullName>Event Management Services</fullName>
                </value>
                <value>
                    <fullName>Event Rentals / Decor</fullName>
                </value>
                <value>
                    <fullName>Exposition Center</fullName>
                </value>
                <value>
                    <fullName>Gallery / Museum</fullName>
                </value>
                <value>
                    <fullName>Golf Course</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Internal Value</fullName>
                </value>
                <value>
                    <fullName>Luxury Hotel</fullName>
                </value>
                <value>
                    <fullName>Mail / Shipping Services</fullName>
                </value>
                <value>
                    <fullName>Movie Theatre</fullName>
                </value>
                <value>
                    <fullName>Printing / Marketing Services</fullName>
                </value>
                <value>
                    <fullName>Promotional Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestMyCasesQuery.cls
@Istest

private class TestMyCasesQuery {

public static Account instofAcc = new Account();
public static Contact instofCon =  new Contact();
    
@testsetup
static void createData(){
    
    Id rtTypeId = Schema.SobjectType.Account.getRecordTypeInfosByName().get('Biz A/c').getRecordTypeId();
    
    instofAcc = new Account();
    instofAcc.Name = 'Test';
    instofAcc.Supplier_Type__c = 'Venue';
    instofAcc.Venue_Type__c = 'CVB';
    instofAcc.RecordTypeId = rtTypeId ;
    insert instofAcc;
    
    instofCon =  new Contact();
    instOfCon.LastName = 'Test';
    instOfCon.AccountId = instofAcc.Id;
    insert instOfCon;
       
       
    Id recTypeCase  = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Event').getRecordTypeId();
    
    Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
    //Create a Test User
    User u = new User(Alias = 'testUX', Email='ggg@torg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='deploymenttest@torg.com');
        
    System.RunAs(u) {
        Case c = new Case();
        c.recordTypeId = recTypeCase;
        c.Product_Type__c = 'Event Tool';
        c.Status = 'Open';
        c.Minutesoncase__c = 30; 
        c.ContactId = instOfCon.Id;
        c.OwnerId = u.Id;       
        insert c;
    }
    
}

public static testMethod void TestMyCasesQuery() {
       
       Profile p = [SELECT id, Name FROM Profile WHERE UserLicense.Name like '%Customer Community Login%' AND Name like '%Cvent Customer Community User%'] ;
       Contact c = [Select Id From Contact Limit 1 ];
       
       
       System.debug(' $$$$ Con $$$ ' +  instOfCon);
       User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
       EmailEncodingKey='UTF-8', FirstName = 'Test' , LastName='User', LanguageLocaleKey='en_US', 
       LocaleSidKey='en_US', ProfileId = p.Id, 
       TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com',federationIdentifier='1233454',contactId =c.Id,CommunityNickname = 'testUser123');
       
       //Use the PageReference Apex class to instantiate a page
       PageReference pageRef = Page.Mycases;
       
       //In this case, the Visualforce page named 'Mycases' is the starting point of this test method. 
       Test.setCurrentPage(pageRef);
     
       //Instantiate and construct the controller class.
       system.runAs(u){
       
       MyCasesQuery controller = new MyCasesQuery();
       controller.getItems();
       controller.processRequests();
    }
       
   }
}