objects/Account.object
<CustomObject>
    <fields>
        <fullName>AM_Event__c</fullName>
        <inlineHelpText>Account Manager - Responsible for Managing and Renewing this Customer</inlineHelpText>
        <label>AM – Event Cloud</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adrian Arora</fullName>
                </value>
                <value>
                    <fullName>Afeef Khalil</fullName>
                </value>
                <value>
                    <fullName>Aftab Alam</fullName>
                </value>
                <value>
                    <fullName>Akshay Doshi</fullName>
                </value>
                <value>
                    <fullName>Alex Rolfe</fullName>
                </value>
                <value>
                    <fullName>Allison Spirer</fullName>
                </value>
                <value>
                    <fullName>Amanda Payne</fullName>
                </value>
                <value>
                    <fullName>Amy Chugh</fullName>
                </value>
                <value>
                    <fullName>Amy Zaczkowski</fullName>
                </value>
                <value>
                    <fullName>Andrew MacIsaac</fullName>
                </value>
                <value>
                    <fullName>Andy Rouhafzai</fullName>
                </value>
                <value>
                    <fullName>Anil Punyapu</fullName>
                </value>
                <value>
                    <fullName>Ann OBrien</fullName>
                </value>
                <value>
                    <fullName>Anujeet Verma</fullName>
                </value>
                <value>
                    <fullName>Arielle Meizen</fullName>
                </value>
                <value>
                    <fullName>Arvind Kumar</fullName>
                </value>
                <value>
                    <fullName>Ashley Mohney</fullName>
                </value>
                <value>
                    <fullName>Austin Alam</fullName>
                </value>
                <value>
                    <fullName>Barry Greene</fullName>
                </value>
                <value>
                    <fullName>Barry Womack</fullName>
                </value>
                <value>
                    <fullName>Becca Bicer</fullName>
                </value>
                <value>
                    <fullName>Benjamin Ball</fullName>
                </value>
                <value>
                    <fullName>Bill Piekarski</fullName>
                </value>
                <value>
                    <fullName>Blake Rivers</fullName>
                </value>
                <value>
                    <fullName>Bradley Blinn</fullName>
                </value>
                <value>
                    <fullName>Brandon Beall</fullName>
                </value>
                <value>
                    <fullName>Brian Ludwig</fullName>
                </value>
                <value>
                    <fullName>Brittany Jennings</fullName>
                </value>
                <value>
                    <fullName>Brittlynn Goddard</fullName>
                </value>
                <value>
                    <fullName>Caitlin Guichard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <inlineHelpText>*Active/Inactive denotes whether the account is active or inactive in CVII.
*Billing/Collections: Billing is following up for the payment.
*Legal: The client is in Legal</inlineHelpText>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Active - AutoRenewal</fullName>
                </value>
                <value>
                    <fullName>Active - External Collections</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Customer - CSN Planner Active</fullName>
                </value>
                <value>
                    <fullName>Inactive Customer - CSN Supplier Active</fullName>
                </value>
                <value>
                    <fullName>Inactive Customer - Reflag</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Type__c</fullName>
        <label>Supplier Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Venue</fullName>
                </value>
                <value>
                    <fullName>Unique Venue</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <formula>TEXT(Account.Account_Status__c)</formula>
        <label>Account Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Desired__c</fullName>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CrowdCompass</fullName>
                </value>
                <value>
                    <fullName>CSN</fullName>
                </value>
                <value>
                    <fullName>eMarketing</fullName>
                </value>
                <value>
                    <fullName>EMI</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Inquisium</fullName>
                </value>
                <value>
                    <fullName>Lanyon Events</fullName>
                </value>
                <value>
                    <fullName>Lanyon Group</fullName>
                </value>
                <value>
                    <fullName>Lanyon Meetings</fullName>
                </value>
                <value>
                    <fullName>Lanyon Mobile</fullName>
                </value>
                <value>
                    <fullName>Lanyon Passkey</fullName>
                </value>
                <value>
                    <fullName>Lanyon Transient</fullName>
                </value>
                <value>
                    <fullName>Lanyon Travel</fullName>
                </value>
                <value>
                    <fullName>Onsite Solutions</fullName>
                </value>
                <value>
                    <fullName>QuickMobile</fullName>
                </value>
                <value>
                    <fullName>RegOnline</fullName>
                </value>
                <value>
                    <fullName>SignUp4</fullName>
                </value>
                <value>
                    <fullName>SMM</fullName>
                </value>
                <value>
                    <fullName>Social Tables</fullName>
                </value>
                <value>
                    <fullName>Universal Lead Capture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account_Buyer_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Buyer Roles are created/modified by sales and establish the role that the individual plays in the buying process.</inlineHelpText>
        <label>Account (Buyer Role)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact - Buyer Roles</relationshipLabel>
        <relationshipName>Buyer_Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Primary POC</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>R00N000000071h6REAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Contact Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AMValidationControllerTest.cls
// ===============================
// Name             : AMValidationControllerTest
// AUTHOR           : Shanu Aggarwal    
// CREATED DATE     : 20 Sep 2016
// CLASS            : AMValidationController
// SPECIAL NOTES    :
// ===============================
@istest
public class AMValidationControllerTest {
    
    
    public static testmethod void testvalidationController(){        
        
        //Inserting User...............
        Profile p = [SELECT Id FROM Profile WHERE Name='Finance - Management']; 
        
        USerrole[] testroleId=[select id from userRole where name ='AM (Event)' limit 1];
        USerrole[] testrole2Id=[select id from userRole where name = '' limit 1];
        
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Sops', LanguageLocaleKey='en_US', FirstName='TestUser',
                          LocaleSidKey='en_US', ProfileId = p.Id, userRoleId=testroleId[0].id,
                          TimeZoneSidKey='America/Los_Angeles', UserName='Test'+'deploymentuser@cvent.com');
        
        
        system.runAs(u){            
            Account acc= new Account();
            acc.Name = 'Test Account 1';
            acc.Supplier_Type__c = 'Venue';
            acc.AM_Event__c = 'TestUser Sops';
            acc.Account_Status__c = 'Active';
            acc.BillingCountryCode='US';
            acc.BillingStateCode = 'NY';
            insert acc;
            
            Contact con = new Contact();
            con.AccountId = acc.Id; 
            con.LastName = 'Contact 1';
            con.Product_Desired__c  = 'CrowdCompass';
            insert con;
            
            Contact con2 = new Contact();
            con2.AccountId = acc.Id; 
            con2.LastName = 'Contact 1';
            con2.Product_Desired__c  = 'CrowdCompass';
            insert con2;
            
            Contact_Role__c cr = new Contact_Role__c();
            cr.RecordTypeId = Schema.SObjectType.Contact_Role__c.getRecordTypeInfosByName().get('Buyer Role').getRecordTypeId();
            cr.Contact__c = con.Id;
            cr.Account_Buyer_Role__c = acc.Id;
            
            insert cr;
            
            Contact_Role__c cr3 = new Contact_Role__c();
            cr3.RecordTypeId = Schema.SObjectType.Contact_Role__c.getRecordTypeInfosByName().get('Buyer Role').getRecordTypeId();
            cr3.Contact__c = con2.Id;
            cr3.Account_Buyer_Role__c = acc.Id;
           
            insert cr3;
            
            PageReference pgRef = Page.AMValidation;
            pgRef.getParameters().put('id',acc.id);
            Test.setCurrentPageReference(pgRef);
            
            ApexPages.StandardController stdCtrl = new ApexPages.StandardController(acc);
            Map <Id,Contact_Role__c> selectedMap = new Map <Id,Contact_Role__c>();
            selectedMap.put(cr.Id, cr);
            AMValidationController aController = new AMValidationController(stdCtrl);
            aController.selectedcontactRoleMap = selectedMap;
            aController.getContactRoles();
            aController.pageNumber = 1;
            aController.ValidateSelected();
            aController.noOfRecords = 10;
            aController.ValidateAll();
            aController.pageNumber = 1;
            
            PageReference pgRef1 = Page.validateBuyerRole;
            pgRef1.getParameters().put('id',con.id);
            Test.setCurrentPageReference(pgRef1);
            
            ApexPages.StandardController stdCtrl1 = new ApexPages.StandardController(con);
            validateBuyerRoleOnContact obj = new validateBuyerRoleOnContact(stdCtrl1);
            obj.validateContact();
            obj.callNo();
            obj.editBuyerRole();            
            obj.selectedcontactRoleMap = selectedMap;
            obj.getContactRoles();
            obj.pageNumber = 1;
            obj.ValidateSelected();
            obj.noOfRecords = 10;
            obj.ValidateAll();
            obj.pageNumber = 1;
            validateBuyerRoleOnContact.WrapperContactRoleWrapper testWrap=new validateBuyerRoleOnContact.WrapperContactRoleWrapper(cr,false); 

        }
    }
}