objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Acct_Status__c</fullName>
        <label>CC Acct Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                    <default>true</default>
                    <label>Untouched</label>
                </value>
                <value>
                    <fullName>Working/No traction yet</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Current_Status__c.object
<CustomObject>
    <fields>
        <fullName>Account_Progress__c</fullName>
        <label>Event Core Account Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Engaged buyer</fullName>
                </value>
                <value>
                    <fullName>Presentation scheduled</fullName>
                </value>
                <value>
                    <fullName>Correct Contacts Identified</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Price Quote/Proposal</fullName>
                </value>
                <value>
                    <fullName>Negotiation</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Using Competitor/Keeping in Touch</fullName>
                </value>
                <value>
                    <fullName>No Opportunity / Not a Fit</fullName>
                </value>
                <value>
                    <fullName>Active Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Parent</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Parent &amp; Subsidiary</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Sourcing</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Subsidiary</fullName>
                </value>
                <value>
                    <fullName>Completely Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - CT</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in CSN</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in Event</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in Mobile</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch -  Interested in SMM</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                    <default>true</default>
                    <label>No Contact</label>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Acct_Status__c</fullName>
        <label>Mobile Solutions Account Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                    <default>true</default>
                    <label>Untouched</label>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Engaged buyer</fullName>
                </value>
                <value>
                    <fullName>Presentation scheduled</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Assigned User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>A_c_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Progress_Details__c</fullName>
        <label>CC Progress Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Current_Status</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>A/c Status</label>
    <nameField>
        <displayFormat>CS{0000}</displayFormat>
        <label>Current Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>A/c Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Top_Accounts</fullName>
        <active>true</active>
        <label>Top Accounts</label>
    </recordTypes>
</CustomObject>

classes/CCAcctStatus.cls
public class CCAcctStatus  {

    public Current_Status__c accdetails {get; private set;}
    String id = ApexPages.currentPage().getParameters().get('id');
    String id2 = ApexPages.currentPage().getParameters().get('PID');
    @TestVisible private String Parent_account_name;
    
    public CCAcctStatus(){
        RecordType instRecTypeThir = [SELECT Id FROM RecordType WHERE SobjectType='Current_Status__c' And IsActive = true And DeveloperName = 'Top_Accounts' ];
        accdetails = [Select c.CC_Acct_Status__c,c.Parent_Account__c, c.CC_Progress_Details__c,c.CC_Assigned_User__c From Current_Status__c c where Parent_Account__c = :id2 AND RecordTypeId !=:instRecTypeThir.Id];
        Parent_account_name = [select name from account where id = :id2 limit 1].name;
    }
   
    public PageReference edit() {
        String xx;      
        xx = id + '&PID=' + id2;
        String x1 = '/apex/CCStatusEdit?id=' + xx;
        PageReference opptyPage = new PageReference(x1);
        opptyPage.setRedirect(true);
        return opptyPage;
    }
        
    public PageReference cancel(){
        String xx;      
        xx = id + '&PID=' + id2;
        //ccstatustext = accdetails.Account_Progress__c;
        String x1 = '/apex/CCStatus?id=' + xx;
        PageReference opptyPage = new PageReference(x1);
        opptyPage.setRedirect(true);
        return opptyPage;
    }

    public PageReference save(){
        try{
            update(accdetails);
            String xx;      
            xx = id + '&PID=' + id2;
            String x1 = '/apex/CCStatus?id=' + xx;
            PageReference opptyPage = new PageReference(x1);
            opptyPage.setRedirect(true);
            return opptyPage;
        }
        catch(System.DMLException e){ ApexPages.addMessages(e); return null; }
        //return null;
    }
       
    public string getparentaccount(){
        return this.Parent_account_name ;
    }

    //class
}