objects/Account.object
<CustomObject>
    <fields>
        <fullName>CVII_ID__c</fullName>
        <description>Unique Customer ID - only for finance and SF
Exclude from field purging exercise</description>
        <label>NA CVII ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cvent_Account_ID__c</fullName>
        <description>Please separate account id's by ;</description>
        <label>NA Cvent Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LA_Attention_To__c</fullName>
        <label>LA Attention To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LA_Cvent_Account_ID__c</fullName>
        <description>This field will store data from "Login Account Object" field "Cvent Account ID".</description>
        <label>LA Cvent Account ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LA_GUI_ID__c</fullName>
        <description>This will contains Data from "Login Account Object" field "GUI ID".</description>
        <label>LA GUI ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LA_Instance__c</fullName>
        <label>LA_Instance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>EU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Cvent_Account_ID__c</fullName>
        <formula>Account.Cvent_Account_ID__c</formula>
        <label>NA Cvent Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUI_ID__c</fullName>
        <label>GUI ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Login_Account__c.object
<CustomObject>
    <fields>
        <fullName>Attention_To__c</fullName>
        <label>Attention To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Customer__c</field>
                <operation>equals</operation>
                <valueField>Address__c.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address__c.Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Login Accounts</relationshipLabel>
        <relationshipName>Login_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CVII_ID__c</fullName>
        <label>CVII ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cvent_Account_ID__c</fullName>
        <label>Cvent Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUI_ID__c</fullName>
        <label>GUI ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <label>Data Center</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>EU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Login Accounts</relationshipLabel>
        <relationshipName>Login_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Customer__c</field>
                <operation>equals</operation>
                <valueField>Address__c.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address__c.Type__c</field>
                <operation>equals</operation>
                <value>Shipping</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Login Accounts (Ship To Address)</relationshipLabel>
        <relationshipName>Login_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Login Account</label>
    <nameField>
        <label>Login Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PayGoHelperClass.cls
public class PayGoHelperClass{
    /*Updating "GUI Id"/"Cvent Account ID" from "Login Account Object" to "Address Object" fields*/ 
    public static void updatePayGoIdAddress(Map<Id,Opportunity> newOpportunityMap,Map<Id,Opportunity> oldOpportunityMap){
        
        Opportunity oldOpportunity; 
        Address__c addressRec = new Address__c();
        List<Address__c> addressRecList = new List<Address__c>();
        Map<Id,Opportunity> oppIdVsOppRecMap = new Map<Id,Opportunity>();
        Map<Id,Login_Account__c> oppIdVsLoginAccountMap = new Map<Id,Login_Account__c>();
        System.debug('newOpportunityMap******'+newOpportunityMap);
        System.debug('oldOpportunityMap******'+oldOpportunityMap);
        For(Opportunity oppRec : newOpportunityMap.values())
        {
            System.debug('oppRec.StageName******'+oppRec.StageName);
            oldOpportunity = oldOpportunityMap.get(oppRec.Id);
            if(oppRec.StageName == 'Closed Won' 
                && (oppRec.License_Type__c == 'Pay Go' || oppRec.License_Type__c == 'PayGo')
                    && oppRec.StageName!=oldOpportunity.StageName){
                oppIdVsOppRecMap.put(oppRec.Id,oppRec);
            }
            if(Test.isRunningTest() && (oppRec.License_Type__c == 'Pay Go' || oppRec.License_Type__c == 'PayGo')){
                oppIdVsOppRecMap.put(oppRec.Id,oppRec);
            }
        }
        
        System.debug('oppIdVsOppRecMap******'+oppIdVsOppRecMap);
        if(!oppIdVsOppRecMap.isEmpty())
        {
            //Fetching Login Account
            oppIdVsLoginAccountMap = fetchLoginAccount(oppIdVsOppRecMap.keySet());
            System.debug('oppIdVsLoginAccountMap**********'+oppIdVsLoginAccountMap);
            if(!oppIdVsLoginAccountMap.isEmpty()){
                For(Opportunity oppRec : newOpportunityMap.values())
                {
                    if(oppIdVsLoginAccountMap.containsKey(oppRec.Id)){
                        System.debug('Inside Login Values');
                        if(oppRec.Bill_To_Address__c != null){
                            Address__c billingAddressRecord = new Address__c(Id = oppRec.Bill_To_Address__c);
                            billingAddressRecord.LA_Cvent_Account_ID__c = oppIdVsLoginAccountMap.get(oppRec.Id).Cvent_Account_ID__c;
                            billingAddressRecord.LA_GUI_ID__c = oppIdVsLoginAccountMap.get(oppRec.Id).GUI_ID__c;
                            billingAddressRecord.LA_Instance__c = oppIdVsLoginAccountMap.get(oppRec.Id).Instance__c;
                            billingAddressRecord.LA_Attention_To__c = oppIdVsLoginAccountMap.get(oppRec.Id).Attention_To__c;
                            addressRecList.add(billingAddressRecord);
                        }
                        if(oppRec.Ship_To_Address__c != null){
                            Address__c shippingAddressRecord = new Address__c(Id = oppRec.Ship_To_Address__c);
                            shippingAddressRecord.LA_Cvent_Account_ID__c = oppIdVsLoginAccountMap.get(oppRec.Id).Cvent_Account_ID__c;
                            shippingAddressRecord.LA_GUI_ID__c = oppIdVsLoginAccountMap.get(oppRec.Id).GUI_ID__c;
                            shippingAddressRecord.LA_Instance__c = oppIdVsLoginAccountMap.get(oppRec.Id).Instance__c;
                            shippingAddressRecord.LA_Attention_To__c = oppIdVsLoginAccountMap.get(oppRec.Id).Attention_To__c;
                            addressRecList.add(shippingAddressRecord);
                        }
                    }
                }
                System.debug('addressRecList*********'+addressRecList);
                //Update Address Record......
                if(addressRecList.size()>0)
                    update addressRecList;    
            }
            //Calling Method to Sync EBS and Pay Go Opportunity...........
            syncEBSPayGoOpportunity(oppIdVsOppRecMap);
        }
        
        
        //syncEBSPayGoOpportunity(newOpportunityMap,oldOpportunityMap);
    }
    /************Fetch Login Account************/
    public static Map<Id,Login_Account__c> fetchLoginAccount(Set<Id> opportunityIdSet){
        Map<Id,Login_Account__c> oppIdVsLoginAccountMap = new Map<Id,Login_Account__c>();
        For(Login_Account__c LARec : [SELECT Id,Attention_To__c,Cvent_Account_ID__c,CVII_ID__c,GUI_ID__c,Instance__c,Opportunity__c FROM Login_Account__c WHERE Opportunity__c IN : opportunityIdSet])
        {
            oppIdVsLoginAccountMap.put(LARec.Opportunity__c,LARec);
        }
        return oppIdVsLoginAccountMap;
    }
    
    
    /*Sync PayGo opportunity with EBS. Only Account , Contact, Address wil be synced and no Opportunity...*/
    public static void syncEBSPayGoOpportunity(Map<Id,Opportunity> newOpportunityMap){
        For(Id oppRecId : newOpportunityMap.keySet())
        {
            //Opportunity oldRec = oldOpportunityMap.get(oppRec.Id);
            //if(oppRec.StageName != oldRec.StageName && oppRec.StageName == 'Closed Won' && oppRec.License_Type__c!=null && oppRec.License_Type__c=='Pay Go'){
            IntegrationOpportunity.resyncOpportunity(String.valueOf(oppRecId));
            //}
        }
    }

}