objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cvent_Account_ID__c</fullName>
        <description>Please separate account id's by ;</description>
        <label>NA Cvent Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Prospect Lead</fullName>
                </value>
                <value>
                    <fullName>Fit Lead</fullName>
                </value>
                <value>
                    <fullName>Active Lead</fullName>
                </value>
                <value>
                    <fullName>Passive Win</fullName>
                </value>
                <value>
                    <fullName>Imp Win</fullName>
                </value>
                <value>
                    <fullName>Live Win</fullName>
                </value>
                <value>
                    <fullName>End Business</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account to which this Additional Address record is related.
This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <inlineHelpText>The Account to which this Additional Address record is related.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Additional_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Remittance</fullName>
                    <default>true</default>
                    <label>Remittance</label>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
</CustomObject>

objects/Login_Account__c.object
<CustomObject>
    <fields>
        <fullName>Attention_To__c</fullName>
        <label>Attention To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Customer__c</field>
                <operation>equals</operation>
                <valueField>Address__c.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address__c.Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Login Accounts</relationshipLabel>
        <relationshipName>Login_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Login Accounts</relationshipLabel>
        <relationshipName>Login_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cvent_Account_ID__c</fullName>
        <label>Cvent Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUI_ID__c</fullName>
        <label>GUI ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <label>Data Center</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>EU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Login Accounts</relationshipLabel>
        <relationshipName>Login_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Customer__c</field>
                <operation>equals</operation>
                <valueField>Address__c.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address__c.Type__c</field>
                <operation>equals</operation>
                <value>Shipping</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Login Accounts (Ship To Address)</relationshipLabel>
        <relationshipName>Login_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PayGo_Statuses</valueSetName>
        </valueSet>
    </fields>
    <label>Login Account</label>
    <nameField>
        <label>Login Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PayGo_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PayGo Summary</relationshipLabel>
        <relationshipName>PayGo_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>PayGo Summary</relationshipLabel>
        <relationshipName>PayGo_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cvent_Account_ID__c</fullName>
        <formula>Login_Account__r.Account_Number__c</formula>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUI_ID__c</fullName>
        <label>GUI ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Login Account</label>
        <referenceTo>Login_Account__c</referenceTo>
        <relationshipLabel>PayGo Summary</relationshipLabel>
        <relationshipName>PayGo_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PayGo Summary</relationshipLabel>
        <relationshipName>PayGo_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>PayGo Summary (Ship To Address)</relationshipLabel>
        <relationshipName>PayGo_Summary1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PayGo_Statuses</valueSetName>
        </valueSet>
    </fields>
    <description>This object will hold the data of PayGo transaction lifecycle from account signup to activation to event build to event launch</description>
    <label>PayGo Summary</label>
    <nameField>
        <displayFormat>PayGo-{0000}</displayFormat>
        <label>PayGo Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PayGo Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/PayGo_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Account Request</fullName>
    </customValue>
    <customValue>
        <fullName>Account Open</fullName>
    </customValue>
    <customValue>
        <fullName>Event Create</fullName>
    </customValue>
    <customValue>
        <fullName>Event Launch</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant - Lost</fullName>
    </customValue>
    <masterLabel>PayGo Statuses</masterLabel>
</GlobalValueSet>

classes/PayGoHelperClassTest.cls
@isTest
public class PayGoHelperClassTest{
    static testmethod void updatePayGoIdAddressTest(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        Address__c addr = new Address__c();
        addr.Address__c = 'Test Address';
        addr.Type__c = 'Billing';
        addr.Account__c = acc.Id;
        insert addr;
        
        Address__c shipAddr = new Address__c();
        shipAddr.Address__c = 'Test Address';
        shipAddr.Type__c = 'Shipping';
        shipAddr.Account__c = acc.Id;
        insert shipAddr;
        
        Opportunity opp2 = TestUtil.createOpportunity('Test Opp', 'Renewal', 'Open');
        opp2.CurrencyIsoCode  = 'USD';
        opp2.Bill_To_Address__c = addr.id;
        opp2.Ship_To_Address__c = shipAddr.id;
        opp2.License_Type__c = 'Pay Go';
        opp2.AccountId = acc.Id;
        insert opp2;
        
        Login_Account__c LA = new Login_Account__c();
        LA.Opportunity__c = opp2.Id;
        LA.Cvent_Account_ID__c = '111111111111';
        LA.GUI_ID__c = '22222222222';
        LA.Instance__c = 'NA';
        LA.Attention_To__c = '44444444444';
        LA.Customer__c = acc.Id;
        insert LA;
        
        Login_Account__c LA2 = new Login_Account__c();
        LA2.Opportunity__c = opp2.Id;
        LA2.Cvent_Account_ID__c = '111111111111';
        LA2.GUI_ID__c = '22222222222';
        LA2.Instance__c = 'NA';
        LA2.Attention_To__c = '44444444444';
        LA2.Customer__c = acc.Id;
        LA2.Status__c = 'Event Launch';
        insert LA2;
        LA2.Status__c = 'Event Create';
        update LA2;
        LA2.Status__c = 'Account Open';
        update LA2;
        LA2.Status__c = 'Account Request';
        update LA2;
        
        opp2.StageName = 'Closed Won';
        update opp2;
        Map<Id,Opportunity> oppMap = new Map<Id,Opportunity>();
        oppMap.put(opp2.Id,opp2);
        PayGoHelperClass.updatePayGoIdAddress(oppMap,oppMap);
        
        PayGo_Summary__c paygoRec = new PayGo_Summary__c();
        paygoRec.Account__c = acc.Id;
        insert paygoRec;
        try      
        {
            delete LA;
            delete paygoRec;
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('You') ? true : false;
            //System.AssertEquals(expectedExceptionThrown, true);
        } 
    } 
}