objects/Acquisition__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner_for_Acquired_Org__c</fullName>
        <label>Account Owner for Acquired Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Type_for_Aquired_Org__c</fullName>
        <label>Account Type for Acquired Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Former Client</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Migrated_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>Migrated Record ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Acquisition</label>
    <nameField>
        <displayFormat>ACN-{00000}</displayFormat>
        <label>Acquisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acquisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountOwnerSyncRestAPI.cls
@RestResource(urlMapping='/AccountOwnerSyncRestAPI/*')
global class AccountOwnerSyncRestAPI 
{
    @HttpPost
    global static void doPost() 
    {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        String jsonBody;
        if (req.requestBody != NULL) 
        {
            jsonBody = req.requestBody.toString();
        }
        Map<String, Object> deserilizeBody = (Map<String, Object>)JSON.deserializeUntyped(jsonBody);
        //System.debug('deserilizeBody>>>'+deserilizeBody);
        List<Acquisition__c> acquisitionsToBeUpdated = new List<Acquisition__c>();
        for(Acquisition__c acquisitionInstance : [SELECT Account_Type_for_Aquired_Org__c,Migrated_Record_ID__c FROM Acquisition__c WHERE Migrated_Record_ID__c IN :deserilizeBody.keySet()])
        {
            acquisitionInstance.Account_Owner_for_Acquired_Org__c = String.valueOf(deserilizeBody.get(acquisitionInstance.Migrated_Record_ID__c));
            acquisitionsToBeUpdated.add(acquisitionInstance);
        }
        System.debug('acquisitionsToBeUpdated>>>'+acquisitionsToBeUpdated);
        if(!acquisitionsToBeUpdated.isEmpty())
        {
            update acquisitionsToBeUpdated;
        }
    }
}