objects/Acquisition__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner_for_Acquired_Org__c</fullName>
        <label>Account Owner for Acquired Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Type_for_Aquired_Org__c</fullName>
        <label>Account Type for Acquired Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Former Client</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Acquisitions</relationshipLabel>
        <relationshipName>Acquisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Migrated_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>Migrated Record ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Migrated_Record__c</fullName>
        <label>Migrated Record</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Merged</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Acquisition</label>
    <nameField>
        <displayFormat>ACN-{00000}</displayFormat>
        <label>Acquisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acquisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KapowSocialTablesRestAPITest.cls
@IsTest
private class KapowSocialTablesRestAPITest{
    @isTest static void doGetTest() {
        Test.startTest();
        
        Id accountRecordId = createAccountRecord();
        Id recordId = createTestRecord(accountRecordId);
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://cvent--pgo.cs25.my.salesforce.com/services/apexrest/AccountId/'
            + recordId;
        request.params.put('id', recordId);
    
        request.httpMethod = 'GET';
        RestContext.request = request;
        // Call the method to test
        KapowSocialTablesRestAPI.doGet();
        Test.stopTest();
    }
     // Helper method
    static Id createTestRecord(Id accountId) {
        // Create test record
        Acquisition__c acquisitionTest = new Acquisition__c(
            Account__c = accountId,
            Migrated_Record_ID__c =accountId,
            Migrated_Record__c = 'Merged',
            Account_Type_for_Aquired_Org__c = 'Client',
            Account_Owner_for_Acquired_Org__c = 'Test');
        insert acquisitionTest;
        return acquisitionTest.Id;
    } 
// Helper method
    static Id createAccountRecord() {
        // Create test record
        Account accountTest = new Account(
            Name='Test record');
        insert accountTest;
        return accountTest.Id;
    }   
}