objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Validation__c</fullName>
        <label>Address Validation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VALID</fullName>
                </value>
                <value>
                    <fullName>INVALID</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EBS_Account_Id__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>EBS Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_EBS_Synced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is EBS Synced ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Remittance</fullName>
                    <default>true</default>
                    <label>Remittance</label>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>These are address records associated with Accounts.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
</CustomObject>

objects/AddressValidationUsers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Address Validation Users</label>
</CustomObject>

objects/AddressValidator__c.object
<CustomObject>
    <fields>
        <fullName>FormatType__c</fullName>
        <label>Format Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_Id__c</fullName>
        <label>Login Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MatchingScope__c</fullName>
        <label>Matching Scope</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rest_URL__c</fullName>
        <label>Rest URL</label>
        <type>Url</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>AddressValidator</label>
</CustomObject>

objects/CountryCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country Codes</label>
</CustomObject>

classes/AddressValidator.cls
/*
** Author: Shanu Aggarwal
** Added on: 03/13/2018
** Validate addresses on submitting quote for an approval 
**/
global with sharing class AddressValidator{
    
    /**
    ** Added on 03/13/2018 - Shanu Aggarwal
    ** SUBMIT FOR APPROVAL - Button on Quote
    ** This method performs check on Country,City,State,PostalCode agains the external database. 
    ** The JSON response returns the ProcessStatus based on the inputs and if status is not betwween V1 > V4, Address becoms invalid. 
    **/
    webservice static boolean validateAddress(Id quoteId) { 
        
        string status;
        
        //Sample URL 
        string endpoint ='https://rest-adcloud.informaticadaas.com/adcloud/verifyaddress?'
            +'Login=165520&Password=im22NUdN&MatchingScope=LOCALITY_LEVEL&FormatWithCountry=True&CountryOfOriginISO3CountryOfOriginISO3=US'
            +'&street=&Locality=ORLEANS&Province=LA&postalcode=70128-3503&Country=US&FORMATType=ALL&Format=json';
        endpoint ='https://rest-adcloud.informaticadaas.com/adcloud/verifyaddress?Login=165520&Password=im22NUdN&MatchingScope=LOCALITY_LEVEL&FormatWithCountry=True&CountryOfOriginISO3CountryOfOriginISO3=US&street=&Locality=New%20Orleans&Province=LA&postalcode=70128-3503&Country=US&FORMATType=ALL&Format=json';
        //custom setting to build the URL with parameters defined in the setting  
        AddressValidator__c  validator = AddressValidator__c.getAll().Values()[0];
        
        SBQQ__Quote__c quote = [Select SBQQ__Opportunity2__r.Ship_To_Address__r.CountryCode__c,SBQQ__Opportunity2__r.Ship_To_Address__r.City__c,SBQQ__Opportunity2__r.Ship_To_Address__r.State__c,SBQQ__Opportunity2__r.Ship_To_Address__r.Postal_Code__c From SBQQ__Quote__c Where Id=:quoteId ];
        
        if(quote.SBQQ__Opportunity2__r.Ship_To_Address__r.CountryCode__c!='US' && quote.SBQQ__Opportunity2__r.Ship_To_Address__r.CountryCode__c!='CA'){return true;}
        
        //If country and zip code is blank, address is invalid 
        if(quote.SBQQ__Opportunity2__r.Ship_To_Address__r.CountryCode__c==null || quote.SBQQ__Opportunity2__r.Ship_To_Address__r.Postal_Code__c==null){return false;}
        
        string city = quote.SBQQ__Opportunity2__r.Ship_To_Address__r.City__c;
        string postalCode = quote.SBQQ__Opportunity2__r.Ship_To_Address__r.Postal_Code__c;
                
        if(city!=null)
            city= city.replaceAll( '\\s+', '%20');
        if(postalCode!=null)
            postalCode= postalCode.replaceAll( '\\s+', '%20');
        
        //build URL    
        endpoint = validator.Rest_URL__c + 'Login='+ validator.Login_Id__c + '&Password='+ validator.Password__c + '&MatchingScope=' + validator.MatchingScope__c 
            +  '&FormatWithCountry=True&CountryOfOriginISO3CountryOfOriginISO3='+quote.SBQQ__Opportunity2__r.Ship_To_Address__r.CountryCode__c+
            +  '&street=&Locality='+ city +'&Province='+ quote.SBQQ__Opportunity2__r.Ship_To_Address__r.State__c + '&postalcode=' + postalCode +'&Country='+quote.SBQQ__Opportunity2__r.Ship_To_Address__r.CountryCode__c+'&FORMATType='+ validator.FormatType__c+'&Format=json';  
        
        System.debug('***endpoint***'+ endpoint);
        //make callout         
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setMethod('GET');
        
        HttpResponse res;
        JSONParser parser;
        
        if(!test.isRunningTest()){
            res = h.send(req); parser = JSON.createParser(res.getBody());
        }else{
            parser = JSON.createParser('{"ResultPercentage":"78.00"}');
        }
        
        while (parser.nextToken() != null) {
            System.debug('***parser.getCurrentToken()***'+ parser.getCurrentToken());
            System.debug('***JSONToken.FIELD_NAME***'+ JSONToken.FIELD_NAME);
            System.debug('***parser.getText()***'+ parser.getText());
            
            if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && 
                (parser.getText() == 'ProcessStatus')) {
                    // Get the value.
                    parser.nextToken();
                    status = parser.getText();
                }
        }
                
        
        
        //If process status is either of these
        if(status=='V1' || status=='V2' || status=='V3' || status=='V4' ){
            return true;
        }else{
            return false;
        }
        
    }
    /**
    ** Added on 04/05/2018 - Shanu Aggarwal
    ** ADDRESS LEVEL
    ** This method performs check on Country,City,State,PostalCode against the external database. 
    ** Updates the flag on Is EBS Sync ? AND Address Validation field on Address level
    **/
    @future(callout=true)
    public static void validateShippingAddressBulk(Set<ID> addIds){ 
        
        string userId = UserInfo.getUserId().substring(0,15);
        string profileId = UserInfo.getProfileId().substring(0,15);
        
        //Only 100 Addresses are allowed in one transaction for call outs
        //Validation works only for these two users 
        if(addIds.size()<101 && (AddressValidationUsers__c.getValues(userId)!=null || AddressValidationUsers__c.getValues(profileId)!=null)){
            
            Map<Id,Address__c> updateAddMap = new Map<Id,Address__c>();
            string status;
            string endpoint;
            //custom setting to build the URL with parameters defined in the setting  
            AddressValidator__c  validator = AddressValidator__c.getAll().Values()[0];


            for( Address__c adr : [Select Id,Type__c,EBS_Account_Id__c,CountryCode__c,City__c,State__c,Postal_Code__c  From Address__c Where Type__c = 'Shipping' and ID IN:addIds]){
                
                
                //IF country is rather than US and CANADA , the address become valid
                if(adr.CountryCode__c!='US' && adr.CountryCode__c!='CA'){
                    adr.Address_Validation__c = 'VALID';
                    adr.Is_EBS_Synced__c=true;
                    updateAddMap.put(adr.Id, adr);
                    continue;
                }

                //If country and zip code is blank, address is invalid 
                if(adr.CountryCode__c==null || adr.Postal_Code__c==null){
                    adr.Address_Validation__c = 'INVALID';
                    adr.Is_EBS_Synced__c=false;
                    updateAddMap.put(adr.Id, adr);
                    continue;
                }
                                
                string city = adr.City__c;
                string postalCode = adr.Postal_Code__c;
                
                if(city!=null)
                    city= city.replaceAll( '\\s+', '%20');
                if(postalCode!=null)
                    postalCode= postalCode.replaceAll( '\\s+', '%20');
                
                //build URL    
                endpoint = validator.Rest_URL__c + 'Login='+ validator.Login_Id__c + '&Password='+ validator.Password__c + '&MatchingScope=' + validator.MatchingScope__c 
                    +  '&FormatWithCountry=True&CountryOfOriginISO3CountryOfOriginISO3='+adr.CountryCode__c+
                    +  '&street=&Locality='+ city +'&Province='+ adr.State__c + '&postalcode=' + postalCode +'&Country='+adr.CountryCode__c+'&FORMATType='+ validator.FormatType__c+'&Format=json';  
                
                System.debug('***endpoint***'+ endpoint);
                //make callout         
                Http h = new Http();
                HttpRequest req = new HttpRequest();
                req.setEndpoint(endpoint);
                req.setMethod('GET');
                
                HttpResponse res;
                JSONParser parser;
                
                if(!test.isRunningTest()){
                    res = h.send(req); parser = JSON.createParser(res.getBody());
                }else{
                    parser = JSON.createParser('{"ResultPercentage":"78.00"}');
                }
                
                while (parser.nextToken() != null) {
                    System.debug('***parser.getCurrentToken()***'+ parser.getCurrentToken());
                    System.debug('***JSONToken.FIELD_NAME***'+ JSONToken.FIELD_NAME);
                    System.debug('***parser.getText()***'+ parser.getText());
                    
                    if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && 
                        (parser.getText() == 'ProcessStatus')) {
                            // Get the value.
                            parser.nextToken();
                            status = parser.getText();
                        }
                }
                        
                
                //If process status is either of these
                if(status=='V1' || status=='V2' || status=='V3' || status=='V4' ){
                    adr.Address_Validation__c = 'VALID';
                    adr.Is_EBS_Synced__c=true;
                }else{
                    adr.Address_Validation__c = 'INVALID';
                    adr.Is_EBS_Synced__c=false;
                }

                updateAddMap.put(adr.Id, adr);
            }
            
            //Update Addresses 
            if(!updateAddMap.isEmpty())
                update updateAddMap.values();

        }
   
        
    }


    /**
    ** Added on -03/19/2018
    ** Validate country codes against the codes stored in custom setting 
    **
    **/
    public static void validateCountryCode(List<Address__c> newList, Map<Id,Address__c> oldMap){
        /*
        Map<String,CountryCode__c> codes = CountryCode__c.getAll();
        
        for(Address__c adr : newList){
        
            if(adr.Country__c!=null && (oldMap==null || (oldMap!=null && adr.Country__c!=oldMap.get(adr.id).Country__c))){
                if(!codes.containsKey(adr.Country__c)){//&& UserInfo.getUserId()!='005o0000002QzQsAAK'
                    adr.addError('Country Code is Invalid');
                }
                //sync country code
                adr.CountryCode__c = adr.Country__c;
            }
        }*/
    }
    
}