objects/AM_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AM Checklists</relationshipLabel>
        <relationshipName>AM_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AM Checklist</label>
    <nameField>
        <displayFormat>AMC{00000}</displayFormat>
        <label>AM Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Checklists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Am_Checklist_Check_AM_Test_Class.cls
@isTest
private class Am_Checklist_Check_AM_Test_Class {

	    static testMethod void myUnitTest() {
        ApexPages.currentPage().getParameters().put('id', 'a03P0000002Yx0A');
        ApexPages.currentPage().getParameters().put('acc_name', '001P000000GF1fq');
        Id id = '001P000000GF1fq';
        Integer x;
		String id2,id3;
    	Am_Checklist_Check_AM_Class controller = new Am_Checklist_Check_AM_Class(); 
        Integer i = [select count() from AM_Checklist__c a where a.Account__c = :id];
        x = i;
		if (x>0)
		{
			AM_Checklist__c account = [select a.Id from AM_Checklist__c a where a.Account__c = :id limit 1];
			id2 = account.Id;
			id3 = id;
     	}
     	if (x==0)
		{
			String x1 = 'https://ssl.salesforce.com/apex/NoFeatureset';
		}
		else
		{	
			String xx;	
			xx = id2 + '&acc_name=' + id3 + '&tab_name=name1';
			String x1 = 'https://ssl.salesforce.com/apex/ViewAmFeatureSet?id=' + xx;
		}	
       		String nextPage = controller.validate().getUrl();
       
    }
}