objects/Analysis_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Type_of_Project__c</fullName>
        <label>Type of Project</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Excel Report</fullName>
                </value>
                <value>
                    <fullName>Word Report in AUSA Format</fullName>
                </value>
                <value>
                    <fullName>Word Report in Island Timberland Format</fullName>
                </value>
                <value>
                    <fullName>PPT in AUSA Format</fullName>
                </value>
                <value>
                    <fullName>PPT in Island Timberland Format</fullName>
                </value>
                <value>
                    <fullName>Word Report</fullName>
                </value>
                <value>
                    <fullName>PPT Report</fullName>
                </value>
                <value>
                    <fullName>PDF Report</fullName>
                </value>
                <value>
                    <fullName>Excel Based Portal</fullName>
                </value>
                <value>
                    <fullName>Business Object</fullName>
                </value>
                <value>
                    <fullName>Data Dump</fullName>
                </value>
                <value>
                    <fullName>MDU Type of Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains all PSG Reports projects</description>
    <label>PSG Projects</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Analysis Projects Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Project_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_End_Date__c</fullName>
        <inlineHelpText>Internal end date of the component.</inlineHelpText>
        <label>Component End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Activity_Start_Date__c</fullName>
        <inlineHelpText>Internal start date of the component.</inlineHelpText>
        <label>Component Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Activity_Status__c</fullName>
        <label>Component Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yet to Start</fullName>
                    <default>true</default>
                    <label>Yet to Start</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Delivered - Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Analysis_Project__c</fullName>
        <label>Analysis Project</label>
        <referenceTo>Analysis_Projects__c</referenceTo>
        <relationshipName>Project_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Component_Owner__c</fullName>
        <label>Component Owner</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abhi Pradhan</fullName>
                </value>
                <value>
                    <fullName>Azim Haque</fullName>
                </value>
                <value>
                    <fullName>Bianca Lama</fullName>
                </value>
                <value>
                    <fullName>Brittany Krout</fullName>
                </value>
                <value>
                    <fullName>Carla Castellucci</fullName>
                </value>
                <value>
                    <fullName>Deepak Kumar</fullName>
                </value>
                <value>
                    <fullName>Dorian Rosen</fullName>
                </value>
                <value>
                    <fullName>Jamal Scott</fullName>
                </value>
                <value>
                    <fullName>Kerry Lambert</fullName>
                    <default>true</default>
                    <label>Kerry Lambert</label>
                </value>
                <value>
                    <fullName>Michael Phillips</fullName>
                </value>
                <value>
                    <fullName>Samarjeet Malhotra</fullName>
                </value>
                <value>
                    <fullName>Sam Bhat</fullName>
                </value>
                <value>
                    <fullName>Scott Verma</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entitled_Hours__c</fullName>
        <label>Entitled Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Report_Description__c</fullName>
        <inlineHelpText>Write Bullet points to explain why it belongs to this category.</inlineHelpText>
        <label>Report Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type_of_Project__c</fullName>
        <label>Type of Project</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Object  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>Data Dump  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>Excel Based Portal  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>Excel Report  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>MDU Type of Report</fullName>
                </value>
                <value>
                    <fullName>PDF Report  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>PPT in AUSA Format  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>PPT in Island Timberland Format  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>PPT Report  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>Word Report  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>Word Report in AUSA Format  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>Word Report in Island Timberland Format  Assigned dynamically</fullName>
                </value>
                <value>
                    <fullName>Review Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Sub-object of Analysis Projects - contains the list of all reports under each Analysis project</description>
    <label>PSG Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Component</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Project_Component_Act_Trigger_Test_Class.cls
@isTest
private class Project_Component_Act_Trigger_Test_Class {

    static testMethod void myUnitTest() {
         
        //User u1 = [SELECT Id FROM User WHERE Alias='Sam'];
       //System.runAs(u1){
       Date s_Date = Date.Today();
       s_Date = s_Date.addDays(5);
       String ap_id, ownername;
       ownername = 'Sid Dasgupta(00500000006rFIC)';
       ap_id = 'a0500000002fcfn';  // Prod
       Date e_Date = s_Date.addDays(8);
        
        for (Analysis_Projects__c check_ap : [Select a.Id From Analysis_Projects__c a limit 1])
        {
            ap_id = check_ap.id ;
        }
        
        Project_Activity__c Pro_Act = new  Project_Activity__c (Report_Description__c='sa',Analysis_Project__c =ap_id, Entitled_Hours__c = 26, Name='Test', Activity_Status__c ='Yet to Start',Activity_Start_Date__c=s_Date ,Activity_End_Date__c=e_Date);
        insert Pro_Act;
        ID x = Pro_Act.id;
        Project_Activity__c accs1 = [Select Activity_Start_Date__c ,Activity_End_Date__c, Component_Owner__c, Entitled_Hours__c from Project_Activity__c where Id = :x];
        //accs1.Component_Owner__c = 'Sandeep Bhat(00500000006xrtu)';
        update accs1;
        
        
        Project_Activity__c Pro_Act2 = new  Project_Activity__c (Report_Description__c='sa',Analysis_Project__c =ap_id, Entitled_Hours__c = 10, Name='Test', Activity_Status__c ='Yet to Start',Activity_Start_Date__c=s_Date ,Activity_End_Date__c=e_Date);
        insert Pro_Act2;
        x = Pro_Act2.id;
        Project_Activity__c accs12 = [Select Activity_Start_Date__c ,Activity_End_Date__c, Component_Owner__c, Entitled_Hours__c from Project_Activity__c where Id = :x];
        //accs12.Component_Owner__c = 'Sandeep Bhat(00500000006xrtu)';
        accs12.Entitled_Hours__c = 9;
        update accs12;
        
        
        
        Project_Activity__c Pro_Act_new = new  Project_Activity__c (Report_Description__c='sa',Type_of_Project__c= 'Data Dump  Assigned dynamically', Analysis_Project__c =ap_id, Entitled_Hours__c = 40, Name='Test',  Activity_Status__c ='Yet to Start',Activity_Start_Date__c=s_Date ,Activity_End_Date__c=e_Date);
        insert Pro_Act_new;
        x = Pro_Act_new.id;
        Project_Activity__c accs2 = [Select Type_of_Project__c, Id, Component_Owner__c from Project_Activity__c where Id = :x];
        accs2.Type_of_Project__c = 'Data Dump  Assigned dynamically';   
        update accs2;
        
        
}
}
//}