objects/App_Support_Custom_Setting__c.object
<CustomObject>
    <fields>
        <fullName>App_Support_Case_Record_Type__c</fullName>
        <label>App Support Case Record Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>App Support Custom Setting</label>
</CustomObject>

objects/App_Support_Question__c.object
<CustomObject>
    <fields>
        <fullName>Case_Record_Type__c</fullName>
        <label>Case Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New_Event</fullName>
                </value>
                <value>
                    <fullName>New_Onsite_Solutions</fullName>
                </value>
                <value>
                    <fullName>New_CrowdCompass</fullName>
                </value>
                <value>
                    <fullName>New_Inquisium</fullName>
                </value>
                <value>
                    <fullName>New_CSN_Planner</fullName>
                </value>
                <value>
                    <fullName>New_CSN_Supplier</fullName>
                </value>
                <value>
                    <fullName>New_Abstact_Management</fullName>
                </value>
                <value>
                    <fullName>New_Appointments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Submission_Guidelines__c</fullName>
        <label>Case Submission Guidelines</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Escalated_Topic__c</fullName>
        <label>Escalated Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Record_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Registration</fullName>
                </value>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>Other integrations (SalesForce, Marketo, Eloqua, Webhooks etc)</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Planner side</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Badges</fullName>
                </value>
                <value>
                    <fullName>PNR / GDS</fullName>
                </value>
                <value>
                    <fullName>Look and Feel</fullName>
                </value>
                <value>
                    <fullName>Import Issues</fullName>
                </value>
                <value>
                    <fullName>Web Application / General Issue</fullName>
                </value>
                <value>
                    <fullName>LeadCapture Mobile App</fullName>
                </value>
                <value>
                    <fullName>OnArrival Mobile App</fullName>
                </value>
                <value>
                    <fullName>Badge Printing</fullName>
                </value>
                <value>
                    <fullName>Utility Mobile App</fullName>
                </value>
                <value>
                    <fullName>OSS to CC Integration</fullName>
                </value>
                <value>
                    <fullName>Custom Reports</fullName>
                </value>
                <value>
                    <fullName>OSS SSO</fullName>
                </value>
                <value>
                    <fullName>Mobile Application Issue</fullName>
                </value>
                <value>
                    <fullName>Cvent Integration Issue</fullName>
                </value>
                <value>
                    <fullName>Third party sync</fullName>
                </value>
                <value>
                    <fullName>Partner API</fullName>
                </value>
                <value>
                    <fullName>Master Admin Creation</fullName>
                </value>
                <value>
                    <fullName>Survey Design</fullName>
                </value>
                <value>
                    <fullName>Emails</fullName>
                </value>
                <value>
                    <fullName>Reports</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Imports</fullName>
                </value>
                <value>
                    <fullName>Respondent Auditing</fullName>
                </value>
                <value>
                    <fullName>General requirement </fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>App Support Question</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>App Support Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Support Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AppSupportQueriesClass.cls
public class AppSupportQueriesClass{
    public Map<String,String> escalatedTopicVsGuildelines{get;set;}
    public String query{get;set;}
    Public string selectedname{get;set;}
    public String suggestedGuidelines{get;set;}
    public string queryTopic{get;set;}
    private Id caseId;
    private String caseRecordType;
    public Case caseObj{get;set;}
    public Map<String,App_Support_Custom_Setting__c> fetchCustomSetting;
    //public String productType{get;set;}
    public String appSupportRecordId{get;set;}
    public AppSupportQueriesClass(ApexPages.StandardController controller) {
        fetchCustomSetting = App_Support_Custom_Setting__c.getAll();
        
        case caseRec = (Case)controller.getRecord();
        caseId = caseRec.Id;
        suggestedGuidelines = '';
        selectedname = '- None -';
        escalatedTopicVsGuildelines = new Map<String,String>();
        caseObj = [SELECT Id,Event_Type_New__c,AccountId,RecordTypeId,RecordType.DeveloperName FROM Case WHERE Id = : caseId];
        //productType = fetchCustomSetting.get(caseObj.RecordType.DeveloperName).Product_Type__c;
        System.debug('caseObj.RecordType.DeveloperName***********'+caseObj.RecordType.DeveloperName);
        System.debug('fetchCustomSetting*********'+fetchCustomSetting);
        System.debug('fetchCustomSetting*********'+fetchCustomSetting.get(caseObj.RecordType.DeveloperName));
        appSupportRecordId = fetchCustomSetting.get(caseObj.RecordType.DeveloperName).App_Support_Case_Record_Type__c;

        query = 'SELECT Id,Case_Record_Type__c,Case_Submission_Guidelines__c,Escalated_Topic__c FROM App_Support_Question__c WHERE Case_Record_Type__c ='+'\''+caseObj.RecordType.DeveloperName+'\'';
        System.debug('*************'+query);
        escalatedTopicVsGuildelines.put('- None -','');
        For(App_Support_Question__c appSupRec : Database.query(query)){
            escalatedTopicVsGuildelines.put(appSupRec.Escalated_Topic__c,appSupRec.Case_Submission_Guidelines__c);    
        }
        
        System.debug('escalatedTopicVsGuildelines*************'+escalatedTopicVsGuildelines.keySet().size());

    }
    Public List<Selectoption> getSelectedEscalatedTopic(){
        
        List<Selectoption> lstnamesel = new List<selectoption>();
        //lstnamesel.add(new selectOption('', '- None -'));
        for(String escalatedTopic :escalatedTopicVsGuildelines.keySet()){
            lstnamesel.add(new selectoption(escalatedTopic,escalatedTopic));
        }
        System.debug('selectedname********'+selectedname);
        return lstnamesel; 
    }
    public void findSuggestions(){
        System.debug('queryTopic*****'+queryTopic);
        System.debug('escalatedTopicVsGuildelines*****'+escalatedTopicVsGuildelines);
        System.debug('suggestedGuidelines*****'+suggestedGuidelines);
        suggestedGuidelines = escalatedTopicVsGuildelines.get(selectedname);
    }
}