objects/Booking_Classification__c.object
<CustomObject>
    <label>Booking Classification</label>
    <nameField>
        <displayFormat>OPS-{00000}</displayFormat>
        <label>Booking Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Contract_Output_Grouping__c</fullName>
        <label>Contract Output Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contract_Output_Grouping</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Contract_Output_Grouping.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bundle Advertisements</fullName>
    </customValue>
    <customValue>
        <fullName>Convenience Fee Field</fullName>
    </customValue>
    <customValue>
        <fullName>Cvent Passkey, Transient &amp; Lanyon Group</fullName>
    </customValue>
    <customValue>
        <fullName>Elite Meetings Alliance</fullName>
    </customValue>
    <customValue>
        <fullName>Event Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Listing Advertisement(s), Software, Services &amp; CONNECT</fullName>
    </customValue>
    <customValue>
        <fullName>RegOnline</fullName>
    </customValue>
    <customValue>
        <fullName>Reporting &amp; Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Suggested Advertisements</fullName>
    </customValue>
    <customValue>
        <fullName>Video Retargeting</fullName>
    </customValue>
    <customValue>
        <fullName>Merchant</fullName>
    </customValue>
    <customValue>
        <fullName>Professional</fullName>
    </customValue>
    <customValue>
        <fullName>OnDemand</fullName>
    </customValue>
    <customValue>
        <fullName>OA360 Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Software Platform</fullName>
    </customValue>
    <customValue>
        <fullName>OA360 Support</fullName>
    </customValue>
    <customValue>
        <fullName>OA360 Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>OA 360 Software</fullName>
    </customValue>
    <customValue>
        <fullName>Social Tables</fullName>
    </customValue>
    <customValue>
        <fullName>OA 360 Equipment</fullName>
        <isActive>false</isActive>
        <label>OA 360 Equipment</label>
    </customValue>
    <masterLabel>Contract Output Grouping</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/OpportunitySplitsController_Test.cls
@isTest
private class OpportunitySplitsController_Test {

   @testSetup static void setup() {
        Id RecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Parent Contract').getRecordTypeId();
        
        //Account
        Account TestAccount = new Account();
        TestAccount.Name = 'Test Account';
        insert TestAccount;
        
        //Insert Opp
        Opportunity opp = TestUtil.createOpportunity('Test Opp', 'Renewal', 'Budget');
        //opp.SBQQ__Contracted__c = true;
        opp.CurrencyIsoCode  = 'USD';
        insert opp;

        //Product
        Product2 product1 = new Product2();
        product1.Name = 'Product 1';
        product1.Contract_Output_Grouping__c = 'Bundle Advertisements';
        insert product1;

        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(), Product2Id = product1.Id,
            UnitPrice = 12000, IsActive = true
        );
        insert customPrice;

        OpportunityLineItem lineItem = new OpportunityLineItem(opportunityId = opp.Id, Product2Id = product1.Id, Quantity = 5, UnitPrice = 6);
        lineItem.PricebookEntryId = customPrice.Id;
        insert lineItem;        
   }

    private static testMethod void testStuff() {
        List<Booking_Classification__c> bookingClassifications = [SELECT Id FROM Booking_Classification__c];
        System.assertEquals(bookingClassifications.size(),1);
        PageReference pageRef = Page.OpportunitySplits;
        Id opportunityId = [SELECT Id FROM Opportunity LIMIT 1].Id;
        pageRef.getParameters().put('opportunityIdString', String.valueOf(opportunityId));
        Test.setCurrentPage(pageRef);
        OpportunitySplitsController splitsController = new OpportunitySplitsController();
        List<OpportunitySplitsController.SplitRow> splitRows = splitsController.splitRows;
        OpportunitySplitsController.getBcIdToBcWrapper(splitRows);
        splitsController.getSplitRowIds(splitRows);
        splitsController.validateUserUniqueness(splitRows);
        String splitRowMapJson = splitsController.splitRowMapJson;
        pageRef.getParameters().put('splitRowMapJson', splitRowMapJson);
        pageRef.getParameters().put('trySave','true');
        pageRef.getParameters().put('splittingBy','Amount');
        splitsController.receiveSplitRowMap();
    }

}