objects/ByPassTrigger__c.object
<CustomObject>
    <fields>
        <fullName>isDisabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDisabled</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Use to Bypass all triggers for data migration</description>
    <label>ByPass Trigger</label>
</CustomObject>

objects/Cvent_Category_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>OwnerId__c</fullName>
        <label>OwnerId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Cvent Category Mapping</label>
</CustomObject>

classes/AddCaseCommentTest.cls
@isTest
public class AddCaseCommentTest {
    @isTest
  public static void unitTest(){
    
     
    Cvent_Category_Mapping__c categoryMapping = new Cvent_Category_Mapping__c();
        categoryMapping.Name = 'Test';
        categoryMapping.OwnerId__c = '00G00000006vs24';
        categoryMapping.Product__c= 'CrowdCompass';
        categoryMapping.RecordType_Id__c = '0120000000099RT';
        insert categoryMapping;
    
    ByPassTrigger__c oByPassTrigger = new ByPassTrigger__c();
   oByPassTrigger.isDisabled__c = true;
   insert oByPassTrigger;
      
   Account oAccount = new Account();
    oAccount.Name = 'Lanyon Master';
  insert oAccount;
  
  Contact oContact = new Contact();
    oContact.AccountID = oAccount.id;
    oContact.FirstName = 'Fname';
    oContact.LastName = 'Lname';  
    oContact.Email = 'test@test.com';
    insert oContact;
        
   Case oCase = new Case();
    oCase.AccountId = oAccount.id;
    oCase.ContactId = oContact.id;
    oCase.Origin = 'test@test.com';
    oCase.Status = 'Closed';
    insert oCase;
    
    CaseComment oCaseComment = new CaseComment();
    oCaseComment.ParentId = oCase.Id;
    oCaseComment.IsPublished = true;
    oCaseComment.CommentBody = 'Test Comment';
   insert oCaseComment;
   
   AddCaseComment oController = new AddCaseComment();
      
    Apexpages.currentPage().getParameters().put('ccId',oCase.Id);
    oController = new AddCaseComment();
    oController.SubmitComment();
    
    oController.CommentBody = 'Test Comment';
    oController.SubmitComment();
    oController.SubmitComments();
    
    AddCaseComment.updaeComment('test Case Comment',oCase.id);
    //oController.Cancel();
  }
}