objects/ByPassTrigger__c.object
<CustomObject>
    <fields>
        <fullName>isDisabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDisabled</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Use to Bypass all triggers for data migration</description>
    <label>ByPass Trigger</label>
</CustomObject>

objects/Case_Deflection_Track__c.object
<CustomObject>
    <fields>
        <fullName>No_I_found_my_Answer_Count__c</fullName>
        <description>How many times a case is not created even after visiting the case page.</description>
        <label>No, I found my Answer Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>This object will keep track of the community user that will tell how many times Case page is being used.
It will also track the count that how many time the user goes to the Case page and didn't create a case because it got helped from the articles show over there.</description>
    <label>Case Deflection Track</label>
    <nameField>
        <displayFormat>CDT-{00000000}</displayFormat>
        <label>Case Deflection Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Deflection Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cvent_Category_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>OwnerId__c</fullName>
        <label>OwnerId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Cvent Category Mapping</label>
</CustomObject>

objects/Cvent_Community_Record_Types__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Cvent Community Record Types</label>
</CustomObject>

objects/Download__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Links to documents in SF or Cvent.</description>
    <label>Download</label>
    <pluralLabel>Downloads</pluralLabel>
</CustomObject>

objects/User__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User Name/Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>User (Custom)</label>
    <nameField>
        <displayFormat>User# {00000000}</displayFormat>
        <label>User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Contact_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Contact Relations</relationshipLabel>
        <relationshipName>User_Contact_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Contact_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfxId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>sfxId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This object is used to maintain relationships between Portal User and their Contact records. This way portal user can be related to multiple contacts and will be able to manage cases for all the contacts that share same email Id.</description>
    <label>User Contact Relation</label>
    <nameField>
        <displayFormat>UC-{00000000}</displayFormat>
        <label>Unique Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Contact Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CaseDeflectionTestClass.cls
@isTest
public class CaseDeflectionTestClass{

    //Test method for SupportPage_Controller Class
    static testMethod void SupportPage_ControllerMethod(){
        //Create Custom Setting for recordtype Names.....
        Cvent_Community_Record_Types__c ccRecTypeName = new Cvent_Community_Record_Types__c();
        ccRecTypeName.name = 'New Event';
        insert ccRecTypeName;
        
        //Setting Page Name.....
        PageReference pageref = Page.SupportPage;
        Test.setCurrentPage(pageRef);
        
        //Insert cases........
        Case cc = new Case();
        cc.Subject = 'Test';
        cc.Status = 'Open';
        cc.recordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('New Event').getRecordTypeId();
        insert cc;
        //Calling Class.....
        SupportPage_Controller controller = new SupportPage_Controller();
        //Calling method.....
        controller.createTracker();
        
    }
    //Test method for FindHelp_Class Class
    static testMethod void FindHelp_ClassMethod(){
        //Create Knowldege Articles....
        Download__kav newArticle = new Download__kav(Title='Event test article', UrlName='testarticleurl', Language='en_US');
        //Insert Article
        insert newArticle;
        
        Download__DataCategorySelection insftOfFAWDCS =  new Download__DataCategorySelection();
        insftOfFAWDCS.DataCategoryGroupName = 'Products';
        insftOfFAWDCS.DataCategoryName = 'Event';
        insftOfFAWDCS.ParentId = newArticle.Id;
        insert insftOfFAWDCS;
        
        Download__kav k = [SELECT Id,KnowledgeArticleId,ArticleNumber,ArticleType,IsLatestVersion,Title,UrlName FROM Download__kav WHERE Id = :newArticle.Id];    
        KbManagement.PublishingService.publishArticle(k.KnowledgeArticleId, true);
        
        //Setting this so that SOSL should return result....
        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = k.Id;
        Test.setFixedSearchResults(fixedSearchResults);

        //Create Case Deflection record......
        Case_Deflection_Track__c caseDeflectTrack = new Case_Deflection_Track__c();
        caseDeflectTrack.No_I_found_my_Answer_Count__c = 1;
        insert caseDeflectTrack;

        //Setting Page Name.....
        PageReference pageref = Page.FindHelp;
        Test.setCurrentPage(pageRef);
        
        //Calling Class.....
        FindHelp_Class controller = new FindHelp_Class();
        
        //Setting Parameter..........
        System.currentPageReference().getParameters().put('id', caseDeflectTrack.Id);

        //Calling method.....
        controller.updateNoTrackerCount();
        controller.updateTrackerCount();
        FindHelp_Class.actfast(caseDeflectTrack.Id,'Event__c','Event');
    }
    //Test method for CreateNewCase_Class Class
    static testMethod void CreateNewCase_ClassMethod(){
        //Inserting Custom Setting....
        Cvent_Category_Mapping__c categoryMapping = new Cvent_Category_Mapping__c();
        categoryMapping.Name = 'Test';
        categoryMapping.OwnerId__c = '00G00000006vs24';
        categoryMapping.Product__c= 'CrowdCompass';
        categoryMapping.RecordType_Id__c = '0120000000099RT';
        insert categoryMapping;
        
        //Setting Page Name.....
        PageReference pageref = Page.CreateNewCase;
        Test.setCurrentPage(pageRef);
        //Setting Parameter..........
        System.currentPageReference().getParameters().put('Subject', 'test subject');
        //Create Case Deflection record......
        Case_Deflection_Track__c caseDeflectTrack = new Case_Deflection_Track__c();
        caseDeflectTrack.No_I_found_my_Answer_Count__c = 1;
        insert caseDeflectTrack;
        
        //Calling Class.....
        CreateNewCase_Class controller = new CreateNewCase_Class();
        controller.save();
        
        

        //Calling method.....
        
        
        
        
        
        
        //Insert Account...
        Account accRec = new Account();
        accRec.name = 'Test Account';
        insert accRec;
        
        //Insert Contact......
        Contact conRec = new Contact();
        conRec.AccountId = accRec.id;
        conRec.LastName = 'test';
        insert conRec;
        
        User_Contact_Relation__c ucr = new User_Contact_Relation__c();
        ucr.User__c = Userinfo.getUserId();
        ucr.Related_Contact__c = conRec.Id;
        ucr.sfxId__c = 'NIK16514344';
        insert ucr;
     
        controller = new CreateNewCase_Class();
        controller.PopulateAccountId();
        controller.saveAndAddAttachment();
        controller.getContactName(conRec.id);
        
        /*controller.isSite = true;
        controller.sFirstName = 'fname';
        controller.sLastName = 'lname';
        controller.sEmail = 'email@email.com';
        controller.sCompanyName = 'compname';
        controller.save();*/

    }
     //Test method for CaseAddAttachmentController Class
    static testMethod void CaseAddAttachmentControllerMethod(){
        ByPassTrigger__c oByPassTrigger = new ByPassTrigger__c();
        oByPassTrigger.isDisabled__c = true;
        insert oByPassTrigger;
        
        Account oAccount = new Account();
        oAccount.Name = 'Lanyon Master';
        insert oAccount;
        
        Contact oContact = new Contact();
        oContact.AccountID = oAccount.id;
        oContact.FirstName = 'Fname';
        oContact.LastName = 'Lname';  
        oContact.Email = 'test@test.com';
        insert oContact;
        
        Case oCase = new Case();
        oCase.AccountId = oAccount.id;
        oCase.ContactId = oContact.id;
        oCase.Origin = 'test@test.com';
        oCase.Status = 'Closed';
        oCase.Subject = 'Test Closed Case';
        insert oCase;
        
        Apexpages.currentPage().getParameters().put('caseid',oCase.Id);
        CaseAddAttachmentController cont = new CaseAddAttachmentController();
        
        Attachment oAttachment = cont.getAttachment();
        cont.setAttachment(oAttachment);
        
        oAttachment.Name = 'test';
        oAttachment.body = Blob.valueOf('test');
        oAttachment.parentId = oCase.Id;
        
        cont.upload();
        cont.done();  
    
    }
    static testMethod void CaseDetail_ClassMethod(){
        ByPassTrigger__c oByPassTrigger = new ByPassTrigger__c();
        oByPassTrigger.isDisabled__c = true;
        insert oByPassTrigger;
        
        Account oAccount = new Account();
        oAccount.Name = 'Lanyon Master';
        insert oAccount;
        
        Contact oContact = new Contact();
        oContact.AccountID = oAccount.id;
        oContact.FirstName = 'Fname';
        oContact.LastName = 'Lname';    
        oContact.Email = 'test@test.com';
        insert oContact;
        
        Case oCase = new Case();
        oCase.AccountId = oAccount.id;
        oCase.ContactId = oContact.id;
        oCase.Origin = 'test@test.com';
        oCase.Status = 'Closed';
        oCase.Subject= 'Closed';
        insert oCase;
        
        CaseComment ccmt = new CaseComment();
        ccmt.ParentId = oCase.Id;
        ccmt.IsPublished = true;
        ccmt.CommentBody = 'Test Comment';
        insert ccmt;
        
        Attachment oAtt = new Attachment(Name = 'test', body= Blob.valueOf('test'),parentId=oCase.Id);
        insert oAtt;
        
        EmailMessage EMS = new EmailMessage();
        EMS.ParentId = oCase.Id;
        EMS.FromAddress = 'testmail@yahoo.com';
        EMS.FromName = 'TEst';
        EMS.MessageDate = system.Today();
        EMS.Subject = 'Test Subject';
        insert EMS;
        
        ApexPages.currentPage().getParameters().put('id',oCase.Id);
        CaseDetail_Class rcd = new CaseDetail_Class();
        
        oCase.Status = 'Open';
        update oCase;
        
        ApexPages.currentPage().getParameters().put('id',oCase.Id);
        rcd = new CaseDetail_Class();
        rcd.getCaseComments();
        rcd.getAttachments();
        rcd.getKav();
        rcd.getEmails();
        rcd.AddCaseComments();
        rcd.AddAuthorization();
        //rcd.closeCase();
        rcd.done();
        rcd.AddAttachments();

    
    }

}