objects/Case_Deflection_Track__c.object
<CustomObject>
    <fields>
        <fullName>No_I_found_my_Answer_Count__c</fullName>
        <description>How many times a case is not created even after visiting the case page.</description>
        <label>No, I found my Answer Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>This object will keep track of the community user that will tell how many times Case page is being used.
It will also track the count that how many time the user goes to the Case page and didn't create a case because it got helped from the articles show over there.</description>
    <label>Case Deflection Track</label>
    <nameField>
        <displayFormat>CDT-{00000000}</displayFormat>
        <label>Case Deflection Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Deflection Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cvent_Category_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>OwnerId__c</fullName>
        <label>OwnerId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Cvent Category Mapping</label>
</CustomObject>

objects/User__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User Name/Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>User (Custom)</label>
    <nameField>
        <displayFormat>User# {00000000}</displayFormat>
        <label>User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Contact_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Contact Relations</relationshipLabel>
        <relationshipName>User_Contact_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Contact_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfxId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>sfxId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This object is used to maintain relationships between Portal User and their Contact records. This way portal user can be related to multiple contacts and will be able to manage cases for all the contacts that share same email Id.</description>
    <label>User Contact Relation</label>
    <nameField>
        <displayFormat>UC-{00000000}</displayFormat>
        <label>Unique Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Contact Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RegOnlineDataMigrationTestClass.cls
@isTest
    public class RegOnlineDataMigrationTestClass{
  //Test method for CreateNewCase_Class Class
    static testMethod void unitMethod(){
        //Inserting Custom Setting....
        Cvent_Category_Mapping__c categoryMapping = new Cvent_Category_Mapping__c();
        categoryMapping.Name = 'Test';
        categoryMapping.OwnerId__c = '00G00000006vs24';
        categoryMapping.Product__c= 'CrowdCompass';
        categoryMapping.RecordType_Id__c = '0120000000099RT';
        insert categoryMapping;
        
        //Setting Page Name.....
        PageReference pageref = Page.RegOnlineDataMigrationPages;
        Test.setCurrentPage(pageRef);
        //Setting Parameter..........
        System.currentPageReference().getParameters().put('Subject', 'test subject');
        //Create Case Deflection record......
        Case_Deflection_Track__c caseDeflectTrack = new Case_Deflection_Track__c();
        caseDeflectTrack.No_I_found_my_Answer_Count__c = 1;
        insert caseDeflectTrack;
        
        //Calling Class.....
        RegOnlineDataMigrationClass controller = new RegOnlineDataMigrationClass();
        controller.save();
        //Calling method.....
        //Insert Account...
        Account accRec = new Account();
        accRec.name = 'Test Account';
        //accRec.BillingCountry ='India';
        accRec.BillingCountryCode ='IN';
        insert accRec;
        
        //Insert Contact......
        Contact conRec = new Contact();
        conRec.AccountId = accRec.id;
        conRec.LastName = 'test';
        insert conRec;
        
        User_Contact_Relation__c ucr = new User_Contact_Relation__c();
        ucr.User__c = Userinfo.getUserId();
        ucr.Related_Contact__c = conRec.Id;
        ucr.sfxId__c = 'NIK16514344';
        insert ucr;
     
        controller = new RegOnlineDataMigrationClass();
        controller.save();
    }
    }