objects/CategoryMapping__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Community_Name__c</fullName>
        <label>Actual Community Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <label>OwnerId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_Name__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>CategoryMapping</label>
</CustomObject>

objects/TabConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Tabs__c</fullName>
        <label>Tabs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Tab Configuration</label>
</CustomObject>

classes/ro_navbarControllerTest.cls
@isTest
public class ro_navbarControllerTest {
	@isTest
	public static void unitTest(){
		TabConfiguration__c oTabConfiguration = new TabConfiguration__c();
		oTabConfiguration.Name = 'Internal';
		oTabConfiguration.Tabs__c = 'home,articles,training,guides,lanyoncommunities,ideas,support';
		insert oTabConfiguration;
     
		CategoryMapping__c oCategoryMapping = new CategoryMapping__c();
		oCategoryMapping.Name = 'Internal';
		oCategoryMapping.Actual_Community_Name__c = 'Internal';
		oCategoryMapping.Category__c = 'REGONLINE';
		oCategoryMapping.Category_Group__c = 'CATEGORIES';
		oCategoryMapping.Product__c = 'RegOnline';
		oCategoryMapping.Product_Family_Name__c = 'RegOnline';
		oCategoryMapping.OwnerId__c = userinfo.getUserId();
		insert oCategoryMapping;
  
  ro_navbarController oController = new ro_navbarController();   
  Boolean isSite = oController.isSite;
  String sitePrefix = oController.sitePrefix;
  String sCategory = oController.sCategory;
  String sCategoryGroup = oController.sCategoryGroup;   
  list<String> lstTab = oController.lstTab;
	}
 
}