objects/CategoryMapping__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Community_Name__c</fullName>
        <label>Actual Community Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <label>OwnerId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_Name__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>CategoryMapping</label>
</CustomObject>

objects/TabConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Tabs__c</fullName>
        <label>Tabs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Tab Configuration</label>
</CustomObject>

objects/User__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User Name/Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>User (Custom)</label>
    <nameField>
        <displayFormat>User# {00000000}</displayFormat>
        <label>User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Contact_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Contact Relations</relationshipLabel>
        <relationshipName>User_Contact_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Contact_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfxId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>sfxId</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This object is used to maintain relationships between Portal User and their Contact records. This way portal user can be related to multiple contacts and will be able to manage cases for all the contacts that share same email Id.</description>
    <label>User Contact Relation</label>
    <nameField>
        <displayFormat>UC-{00000000}</displayFormat>
        <label>Unique Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Contact Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ro_CreateNewCase_Test.cls
@isTest
public class ro_CreateNewCase_Test {
    static testMethod void myUnitTest() {
     TabConfiguration__c oTabConfiguration = new TabConfiguration__c();
     oTabConfiguration.Name = 'Internal';
     oTabConfiguration.Tabs__c = 'home,articles,training,guides,lanyoncommunities,ideas,support';
     insert oTabConfiguration;
     
     CategoryMapping__c oCategoryMapping = new CategoryMapping__c();
     oCategoryMapping.Name = 'Internal';
     oCategoryMapping.Actual_Community_Name__c = 'Internal';
     oCategoryMapping.Category__c = 'REGONLINE';
     oCategoryMapping.Category_Group__c = 'CATEGORIES';
     oCategoryMapping.Product__c = 'RegOnline';
     oCategoryMapping.Product_Family_Name__c = 'RegOnline';
     oCategoryMapping.OwnerId__c = userinfo.getUserId();
     insert oCategoryMapping;
     
     system.debug('@Developer -->oCategoryMapping:' +ro_ConfigHelper.self.oCategoryMapping); 
       
	    ro_CreateNewCase rcn = new ro_CreateNewCase();
	    rcn.saveAndAddAttachment();
	    rcn.save();
	      
	    Account oAccount = new Account();
					oAccount.Name = 'Lanyon Master';
  		 insert oAccount;
        
     Contact oContact = new Contact();
					oContact.AccountID = oAccount.id;
					oContact.FirstName = 'Fname';
					oContact.LastName = 'Lname';	
					oContact.Email = 'test@test.com';
					insert oContact;
    
	    User_Contact_Relation__c ucr = new User_Contact_Relation__c();
	    ucr.User__c = Userinfo.getUserId();
	    ucr.Related_Contact__c = oContact.Id;
	    ucr.sfxId__c = 'NIK16514344';
	    insert ucr;
     
     rcn = new ro_CreateNewCase();
					rcn.PopulateAccountId();
					rcn.c.Subject = 'Test Subject';
					rcn.c.Description = 'Test Description';
					rcn.c.Customer_Impact__c = 'Test Impact';
					rcn.saveAndAddAttachment();
    	
    	rcn.isSite = true;
    	rcn.sFirstName = 'fname';
					rcn.sLastName = 'lname';
					rcn.sEmail = 'email@email.com';
					rcn.sCompanyName = 'compname';
    	rcn.save();

	    ro_AccountSelectionController rac = new ro_AccountSelectionController();
    }
}