objects/CategoryMapping__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Community_Name__c</fullName>
        <label>Actual Community Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <label>OwnerId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_Name__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>CategoryMapping</label>
</CustomObject>

objects/Community__c.object
<CustomObject>
    <label>Community</label>
    <nameField>
        <label>Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Community_Content__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tab__c</fullName>
        <label>Tab</label>
        <referenceTo>Community_Tab__c</referenceTo>
        <relationshipLabel>Community Contents</relationshipLabel>
        <relationshipName>Community_Contents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                    <label>Text</label>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
                <value>
                    <fullName>User Guide</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Community Content</label>
    <nameField>
        <label>Community Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Community_Tab__c.object
<CustomObject>
    <fields>
        <fullName>Community__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community</label>
        <referenceTo>Community__c</referenceTo>
        <relationshipLabel>Community Tabs</relationshipLabel>
        <relationshipName>Community_Tabs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Tab</label>
    <nameField>
        <label>Community Tab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Tabs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TabConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Tabs__c</fullName>
        <label>Tabs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Tab Configuration</label>
</CustomObject>

classes/ro_HomeControllerTest.cls
@isTest
private class ro_HomeControllerTest {
	@isTest
 static void unitTest() {
 	TabConfiguration__c oTabConfiguration = new TabConfiguration__c();
		oTabConfiguration.Name = 'Internal';
		oTabConfiguration.Tabs__c = 'home,articles,training,guides,lanyoncommunities,ideas,support';
		insert oTabConfiguration;
     
		CategoryMapping__c oCategoryMapping = new CategoryMapping__c();
		oCategoryMapping.Name = 'Internal';
		oCategoryMapping.Actual_Community_Name__c = 'Internal';
		oCategoryMapping.Category__c = 'REGONLINE';
		oCategoryMapping.Category_Group__c = 'CATEGORIES';
		oCategoryMapping.Product__c = 'RegOnline';
		oCategoryMapping.Product_Family_Name__c = 'RegOnline';
		oCategoryMapping.OwnerId__c = userinfo.getUserId();
		insert oCategoryMapping;
					
		Community__c oCommunity = new Community__c();
		oCommunity.Name = 'Internal';
		insert oCommunity;
		
		Community_Tab__c oCommunityTab = new Community_Tab__c();
		oCommunityTab.Name = 'Home';
		oCommunityTab.Community__c = oCommunity.Id;
		insert oCommunityTab;
		
		list<Community_Content__c> lstCommunityContent = new list<Community_Content__c>();
		for(Integer indx = 0 ;indx < 10 ; indx++){
			Community_Content__c oCommunityContent = new Community_Content__c();
			oCommunityContent.Order__c = indx;
			oCommunityContent.Tab__c = oCommunityTab.Id;
			oCommunityContent.Type__c = 'Text';
			oCommunityContent.Value__c = 'Test' + indx;
			lstCommunityContent.add(oCommunityContent);
		}
		insert lstCommunityContent;		
		
		ro_HomeController oController = new ro_HomeController();
		map<String,Community_Content__c> mapContents = oController.mapContents;
 }	
}