objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AVA- remove from list</fullName>
                </value>
                <value>
                    <fullName>Colleague identified as primary</fullName>
                </value>
                <value>
                    <fullName>Follow Up</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>No interest</fullName>
                </value>
                <value>
                    <fullName>No longer at Company</fullName>
                </value>
                <value>
                    <fullName>Opportunity Identified</fullName>
                </value>
                <value>
                    <fullName>Qualified Out</fullName>
                </value>
                <value>
                    <fullName>Unable to Contact</fullName>
                </value>
                <value>
                    <fullName>Currently Employed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Creation_Source_System_External_ID__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <externalId>true</externalId>
        <label>Creation Source System External ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Creation_Source_System__c</fullName>
        <description>This is being used in Cast Iron Integration, exclude from field purging exercise</description>
        <label>Creation Source System</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Super_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Super User</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User Name/Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>User (Custom)</label>
    <nameField>
        <displayFormat>User# {00000000}</displayFormat>
        <label>User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Contact_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <formula>TEXT(Related_Contact__r.Contact_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Contact Relations</relationshipLabel>
        <relationshipName>User_Contact_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SSO_User_ID__c</fullName>
        <description>Should contain the value of external</description>
        <externalId>true</externalId>
        <label>Single SignOn Id</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Super_User__c</fullName>
        <formula>Related_Contact__r.Super_User__c</formula>
        <label>Super User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Contact_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object is used to maintain relationships between Portal User and their Contact records. This way portal user can be related to multiple contacts and will be able to manage cases for all the contacts that share same email Id.</description>
    <label>User Contact Relation</label>
    <nameField>
        <displayFormat>UC-{00000000}</displayFormat>
        <label>Unique Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Contact Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ManageUserContactsRelation.cls
/***Test Class : EBProjectCustomRelatedList_ContExt_Test : Udita ****/
public class ManageUserContactsRelation {    

   public static void addUserContactsRelation(Set<Id> uSet)
    { 
        system.debug('Adding User Contact Relation Records ' );    
        Map<Id,User> uMap=new Map<Id,User>([SELECT Id,ContactId,AccountId,Email,isActive,(SELECT Id,PermissionSet.Label FROM PermissionSetAssignments)/*,Contact.Super_User__c  */
                                            FROM User 
                                            WHERE isActive=True AND Id IN :uSet]);//UD:Commented Super_User__c for FP:4thApril

        List<User> uList=uMap.values();
        Map<String,Id> EmailUserMap = new Map<String,Id>();        
        Map<Id,Id> ContactUserMap = new Map<Id,Id>();

        for(User u :uMap.values()) {
           EmailUserMap.put(u.Email,u.Id);
           ContactUserMap.put(u.ContactId,u.Id);
        }
        system.debug('----uMap'+uMap);
        system.debug('----ContactUserMap'+ContactUserMap);
        system.debug('----EmailUserMap'+EmailUserMap);
        Map<Id,Contact> cMap=new Map<Id,Contact>([SELECT Id,Email/*,Contact_Status__c*/,Creation_Source_System_External_Id__c,Creation_Source_System__c FROM Contact 
                                            WHERE /*Contact_Status__c!='No Longer at Company' AND*/ Email IN :EmailUserMap.KeySet()]);    //UD:Commented Contact_Status__c for FP:4thApril                                  

        Map<Id,User_Contact_Relation__c> ucrMap = new Map<Id,User_Contact_Relation__c>();

        for(Contact c: cMap.values()) {
           if(!ucrMap.KeySet().contains(c.Id) && EmailUserMap.get(c.Email)!=null){ 
               User_Contact_Relation__c ucr = new User_Contact_Relation__c(User__c=EmailUserMap.get(c.Email),Related_Contact__c=c.Id,SSO_User_Id__c=null);                                         
               if((c.Creation_Source_System__c=='ROL'||c.Creation_Source_System__c=='ROLUK'||c.Creation_Source_System__c=='ROLAINTL')&&!String.isBlank(c.Creation_Source_System_External_Id__c))
                   ucr.SSO_User_ID__c=c.Creation_Source_System_External_Id__c;               
               ucrMap.put(c.Id,ucr);            
           }         
        } 
    
        if(ucrMap.values().Size() > 0) {
           try { 
               Insert ucrMap.Values();                                                                          
               }
           catch (exception err)
               {
                System.Debug(Logginglevel.ERROR,'ManageUserContactsRelation.addUserContactsRelation - Error inserting new User Contact Relation!'+err.getMessage()+'\n'+ucrMap);
               }
        }        
    }


}