objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EU_Cvent_Account_ID__c</fullName>
        <formula>Account.EU_Cvent_Account_ID__c</formula>
        <label>EU Cvent Account ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ShowLitmosTab__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Just used for the Dark Release. Can be deleted in the future once Litmos is live for all Community User.</description>
        <label>ShowLitmosTab</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CventCommunityHeaderClass.cls
public class CventCommunityHeaderClass{
    public User usr{get;set;}
    /*HSR:2ndFeb2018:Initializing Variables to fetch if this is pblic site or authenticated community*/
    public Boolean isPublicSite{get;set;}
    public CventCommunityHeaderClass(){
        usr = [SELECT Id,ShowLitmosTab__c,SmallPhotoUrl,contact.EU_Cvent_Account_ID__c FROM User WHERE Id = : UserInfo.getUserId()];
        isPublicSite = false;
        //Checking if this is a Public Site User.... 
        if(UserInfo.getUserId() == '005o0000001zagpAAA')
            isPublicSite = true;
    }
}