objects/Contract_Reviewing__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Hybrid_Review_Ok__c</fullName>
        <label>Accounting (Hybrid)Review Ok?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Error Correct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Review_Ok__c</fullName>
        <label>Contract Review Ok?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Re-Review</fullName>
                </value>
                <value>
                    <fullName>Error Correct</fullName>
                </value>
                <value>
                    <fullName>Error in other opp</fullName>
                </value>
                <value>
                    <fullName>Error Rectify</fullName>
                </value>
                <value>
                    <fullName>No Review needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Reviewer__c</fullName>
        <label>Contract Reviewer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Harish Arora</fullName>
                </value>
                <value>
                    <fullName>Deepshikha Sharma</fullName>
                </value>
                <value>
                    <fullName>Akash Tiwari</fullName>
                </value>
                <value>
                    <fullName>Bishnu Singh</fullName>
                </value>
                <value>
                    <fullName>Vishav Garg</fullName>
                </value>
                <value>
                    <fullName>Akriti Puri</fullName>
                </value>
                <value>
                    <fullName>Poshali Gauba</fullName>
                </value>
                <value>
                    <fullName>Lalit Rawat</fullName>
                </value>
                <value>
                    <fullName>Dimple Kocher</fullName>
                </value>
                <value>
                    <fullName>Lalit Kashyap</fullName>
                </value>
                <value>
                    <fullName>Tushar Gautam</fullName>
                </value>
                <value>
                    <fullName>Ankit Pandey</fullName>
                </value>
                <value>
                    <fullName>Vishal Sharma</fullName>
                </value>
                <value>
                    <fullName>Prachi Tanwar</fullName>
                </value>
                <value>
                    <fullName>Tushar Vats</fullName>
                </value>
                <value>
                    <fullName>Vishal Gandhi</fullName>
                </value>
                <value>
                    <fullName>Gaurav Singh</fullName>
                </value>
                <value>
                    <fullName>Himanshi Chawla</fullName>
                </value>
                <value>
                    <fullName>Samridhi Rathi</fullName>
                </value>
                <value>
                    <fullName>Aman Singla</fullName>
                </value>
                <value>
                    <fullName>Aastha Dagdi</fullName>
                </value>
                <value>
                    <fullName>Vikas Arora</fullName>
                </value>
                <value>
                    <fullName>Anurag Singh</fullName>
                </value>
                <value>
                    <fullName>Manisha Parti</fullName>
                </value>
                <value>
                    <fullName>Shrishti Singh</fullName>
                </value>
                <value>
                    <fullName>Pradeep Deoli</fullName>
                </value>
                <value>
                    <fullName>Swati Gautam</fullName>
                </value>
                <value>
                    <fullName>Mohd Suhail</fullName>
                </value>
                <value>
                    <fullName>Kritika Singh</fullName>
                </value>
                <value>
                    <fullName>Shivangi Gupta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Review_Date__c</fullName>
        <label>Final Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Contract__c</fullName>
        <formula>Opportunity__r.Contract_Number_New__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Contract #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contract Reviews</relationshipLabel>
        <relationshipName>Contract_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Review</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Contract Reviewing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ScheduledFinanceShellBatch_Test.cls
@isTest
private class ScheduledFinanceShellBatch_Test{

    @isTest static void ScheduledFinanceShellBatchTest() {
        user u = TestUtil.CreateDeploymentUser();
        insert u;
        
        system.runAs(u)
        {
        
            Account objAccount = CventMYDDataFactory.createAccounts(1);
            insert objAccount;
            
            Contact objContact = CventMYDDataFactory.createContacts(1,objAccount.Id);
            insert objContact;
            
            Opportunity objOpport = CventMYDDataFactory.createOpportunities(1,objAccount.Id,objContact.Id);
            insert objOpport;
            
            Date todayDate = Date.today();
            Date lastWeekDate = todayDate.addDays(-10);
            
            Contract_Reviewing__c conRev = new Contract_Reviewing__c();
            conRev.Accounting_Hybrid_Review_Ok__c='Yes';
            conRev.Contract_Review_Ok__c = 'Yes';
            conRev.Contract_Reviewer__c=u.Id;
            conRev.Opportunity__c =objOpport.Id;
            conRev.Final_Review_Date__c = lastWeekDate;
            conrev.Final_Review_Date__c = todayDate.addDays(-5);
            //conRev.Opportunity_Contract__c =123;
            insert conRev;
            
            Test.startTest();
            ScheduledFinanceShellBatch sh1 = new ScheduledFinanceShellBatch();
            String sch = '0 0 2 * * ?'; 
            system.schedule('Test Schedule Class', sch, sh1); 
            Test.stopTest();
        }
    }
}