objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Implementation_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implementation Surveys</relationshipLabel>
        <relationshipName>Implementation_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Mobile_Event_Date__c</fullName>
        <label>First Mobile Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Mobile_Event_Launch_Date__c</fullName>
        <label>First Mobile Event Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>How_Many_Mobile_Apps_Purchased_in_Year_1__c</fullName>
        <label>How Many Mobile Apps Purchased in Year 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Delivery_Date__c</fullName>
        <label>Mobile Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AttendeeHub</fullName>
                </value>
                <value>
                    <fullName>Self-Publishing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Implementation Surveys</relationshipLabel>
        <relationshipName>Implementation_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This identifies the person who will be receiving the welcome email.</inlineHelpText>
        <label>Welcome Email Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Implementation Surveys (Primary User)</relationshipLabel>
        <relationshipName>Primary_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rush_Request__c</fullName>
        <inlineHelpText>If &lt;60 days, select Yes</inlineHelpText>
        <label>Rush Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Implementation Survey</label>
    <nameField>
        <displayFormat>IMS-{0000}</displayFormat>
        <label>Implementation Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mobile_Card__c.object
<CustomObject>
    <fields>
        <fullName>Agent_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent Profile</label>
        <referenceTo>EB_Agent_Profile__c</referenceTo>
        <relationshipLabel>Mobile Apps</relationshipLabel>
        <relationshipName>Mobile_Apps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attributes__c</fullName>
        <label>Attributes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Affinity</fullName>
                </value>
                <value>
                    <fullName>Alliance Tech</fullName>
                </value>
                <value>
                    <fullName>App build platinum</fullName>
                </value>
                <value>
                    <fullName>App Build Plus</fullName>
                </value>
                <value>
                    <fullName>App Build Premium</fullName>
                </value>
                <value>
                    <fullName>Apple Transition</fullName>
                </value>
                <value>
                    <fullName>AttendeeHub</fullName>
                </value>
                <value>
                    <fullName>Click</fullName>
                </value>
                <value>
                    <fullName>Client Directory</fullName>
                </value>
                <value>
                    <fullName>Custom Video 2 Minutes</fullName>
                </value>
                <value>
                    <fullName>Custom Video 5 Minutes</fullName>
                </value>
                <value>
                    <fullName>Cvent Conference Integration</fullName>
                </value>
                <value>
                    <fullName>Cvent Event</fullName>
                </value>
                <value>
                    <fullName>Data loading service</fullName>
                </value>
                <value>
                    <fullName>Design Studio Advanced</fullName>
                </value>
                <value>
                    <fullName>Design Studio - Simple</fullName>
                </value>
                <value>
                    <fullName>DoubleDutch</fullName>
                </value>
                <value>
                    <fullName>Early Adopter – Falcon</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Enterprise Distribution</fullName>
                </value>
                <value>
                    <fullName>European Data Center</fullName>
                </value>
                <value>
                    <fullName>Exception: CC Dev Acct</fullName>
                </value>
                <value>
                    <fullName>Graphics Work</fullName>
                </value>
                <value>
                    <fullName>High Volume</fullName>
                </value>
                <value>
                    <fullName>Hospitality Cloud</fullName>
                </value>
                <value>
                    <fullName>Inquisium</fullName>
                </value>
                <value>
                    <fullName>Lanyon Transition</fullName>
                </value>
                <value>
                    <fullName>Lanyon Transition - App Build Plus</fullName>
                </value>
                <value>
                    <fullName>Lead Retrieval</fullName>
                </value>
                <value>
                    <fullName>Live Q&amp;A</fullName>
                </value>
                <value>
                    <fullName>Rush Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Assignment_Date__c</fullName>
        <label>Auto - Assignment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CC_Form_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CC Form Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_End_Date__c</fullName>
        <label>Event End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ideal_App_Launch_Date__c</fullName>
        <label>Ideal App Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation_Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Survey</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>Implementation_Survey__c.Opportunity__c</valueField>
            </filterItems>
            <infoMessage>Please associate the "Implementation Survey" associated with the Mobile App Opportunity.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Implementation_Survey__c</referenceTo>
        <relationshipLabel>Mobile Apps</relationshipLabel>
        <relationshipName>Mobile_Apps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Cards_CC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Cards_CC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Build Plus</fullName>
                </value>
                <value>
                    <fullName>Rush Request</fullName>
                </value>
                <value>
                    <fullName>Data Loading Service</fullName>
                </value>
                <value>
                    <fullName>App Build Platinum</fullName>
                </value>
                <value>
                    <fullName>Rush Request + App Build Plus</fullName>
                </value>
                <value>
                    <fullName>Rush Request + Data Loading Service</fullName>
                </value>
                <value>
                    <fullName>Rush Request + App Build Platinum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Sent_By__c</fullName>
        <label>Survey Sent By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>Track Projects for Mobile App Builders in SF</description>
    <label>Mobile App</label>
    <nameField>
        <label>Mobile Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CCMobileAppPrePopulateDataTrig_Act.cls
/**************************************************************************************
* Author: Sandeep Kumar
* Date: 18 October 2018
* Description: CC Mobile App pre-Populate Data, created as a part of CC ABP Automation  
* Class updates Mobile App fields from the Opportunties Implementation Survey in the Before Context to avoid DML
* Test Class : CCMobileAppAutoAssignment_TrigAct_Test
****************************************************************************************/
public class CCMobileAppPrePopulateDataTrig_Act extends TriggerAction{
    private Set<Id> mobileAppOppIdSet;
    private Map<Id,Implementation_Survey__c> oppIdToImpSurveyMap;
    
    public CCMobileAppPrePopulateDataTrig_Act(){
        // Call super to set batch variables & context
        super();
        mobileAppOppIdSet = new Set<Id>();
        oppIdToImpSurveyMap = new Map<Id,Implementation_Survey__c>();
    }
    
    public override Boolean shouldRun(){
        if(this.isBefore() && !this.hasRun()){
            if(this.isInsert()){
                for(Mobile_Card__c newMobileApp: (List<Mobile_Card__c>)this.triggerList){
                    // mobile app must have a valid opportunity to pre-populate the data from implementation survey
                    if(newMobileApp.Opportunity__c != null)
                        mobileAppOppIdSet.add(newMobileApp.Opportunity__c);
                }
                // get the Implementation survey response for the associated opportunity
                if(!mobileAppOppIdSet.isEmpty()){
                    for(Implementation_Survey__c 
                        impSurvey : [Select Id,Opportunity__c,
                                     First_Mobile_Event_Date__c,Contact__c,Primary_User__c,
                                     First_Mobile_Event_Launch_Date__c,Mobile_Delivery_Date__c,
                                     Rush_Request__c,How_Many_Mobile_Apps_Purchased_in_Year_1__c,
                                     Additional_Comments__c
                                     From Implementation_Survey__c 
                                     Where Opportunity__c IN :mobileAppOppIdSet
                                    ]
                       ){
                           // prepare map of OppId to Implementation Survey considering the fact that only one survey will be associated
                           // per Opportunity in Salesforce.
                           oppIdToImpSurveyMap.put(impSurvey.Opportunity__c, impSurvey);                    
                       } 
                }
            }
            if(this.isUpdate()){
                for(Mobile_Card__c newMobileApp: (List<Mobile_Card__c>)this.triggerMap.values()){
                    if(newMobileApp.Agent_Profile__c != null){
                        Mobile_Card__c oldMobileApp = (Mobile_Card__c)this.triggerOldMap.get(newMobileApp.Id);
                        // mobile App Ownership is Changed or existing App Builder is modified by the new App Builder
                        if((oldMobileApp.Agent_Profile__c != null && oldMobileApp.Agent_Profile__c != newMobileApp.Agent_Profile__c)
                           // ideal App Launch Date Entered by the App Builder after Assignment
                           || (oldMobileApp.Ideal_App_Launch_Date__c == null && oldMobileApp.Ideal_App_Launch_Date__c != newMobileApp.Ideal_App_Launch_Date__c)
                           // event Start Date Entered by the App Builder after Assignment
                           || (oldMobileApp.Event_Start_Date__c == null && oldMobileApp.Event_Start_Date__c != newMobileApp.Event_Start_Date__c))
                        {
                            // update today's date as Auto-Assignment Date
                            newMobileApp.Auto_Assignment_Date__c = Date.today();
                        }                        
                    }                             
                }
            }           
        }
        // call doaction only if the set is not empty.
        return !oppIdToImpSurveyMap.isEmpty();
    }
    
    public override void doAction(){
        // variable declaration
        Boolean setEventStartAndLaunchDate = true;
        // set trigger action variable to indicate that the doAction has been called and it will avoid recursion.
        this.markRun();
        
        // process only newly inserted mobile apps, therefore doesn't work in update operation.
        for(Mobile_Card__c newMobileApp: (List<Mobile_Card__c>)this.triggerList){
            // proceed only if the values are contained in the previously created map.
            if(oppIdToImpSurveyMap.containsKey(newMobileApp.Opportunity__c)){
                // CC Form will be sent to the Primary Contact on a Mobile App and some fields should prepopulated with the data from Imp Survey.
                if(setEventStartAndLaunchDate){
                    // IMPSurvey (First Mobile Event Date) => Mobile App (Event Start Date)
                    newMobileApp.Event_Date__c = oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).First_Mobile_Event_Date__c;
                    // IMPSurvey (First Mobile Event Date) => Mobile App (Event Start Date)
                    newMobileApp.Event_Start_Date__c = oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).First_Mobile_Event_Date__c;
                    // IMPSurvey (First Mobile Event Date) => Mobile App (Event End Date)
                    newMobileApp.Event_End_Date__c = oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).First_Mobile_Event_Date__c;
                    // IMPSurvey (First Mobile Event Date) => Mobile App (Ideal App Launch Date)
                    newMobileApp.Ideal_App_Launch_Date__c = oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).First_Mobile_Event_Launch_Date__c;
                    // populate survey related fields on Mobile App 
                    // Survey field be sent by CCMobileAppAutoCaseCreation_TrigAct once the mobile apps are created
                    // using the CC Foem Sent field. With this we can also avoid the DML operation on the same object post email delivery.
                    newMobileApp.CC_Form_Sent__c = true;          
                    newMobileApp.Survey_Sent_By__c = 'Email has been already sent by '+userInfo.getName()+' on '+System.Today().Format()+'.';     
                    setEventStartAndLaunchDate = false; 
                }
                // IMPSurvey (Record ID) => Mobile App (Implementation Survey)
                newMobileApp.Implementation_Survey__c = oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).Id;
                // IMPSurvey (Additional Comments) => Mobile App (Notes)
                newMobileApp.Notes__c = oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).Additional_Comments__c;
                // IMPSurvey (Primary User) => Mobile App (Primary Contact)
                if(oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).Primary_User__c != null){
                    newMobileApp.Primary_Contact__c = oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).Primary_User__c;
                }                	
                // IMPSurvey (Mobile Delivery Date) => Mobile App (Attributes)
                newMobileApp.Attributes__c = oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).Mobile_Delivery_Date__c;
                if(oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).Rush_Request__c != null && oppIdToImpSurveyMap.get(newMobileApp.Opportunity__c).Rush_Request__c == 'Yes'){
                    newMobileApp.Attributes__c += ';Rush Request';
                    newMobileApp.Request_Type__c = 'Rush Request';   
                }
            }
        }        
    }    
}