objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Activity_History__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity History</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Advocate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advocate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Activity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Activity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Primary POC</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>R00N000000071h6REAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Login_Date__c</fullName>
        <label>Core Last Login Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CrowdCompass</fullName>
                </value>
                <value>
                    <fullName>CSN</fullName>
                </value>
                <value>
                    <fullName>Decision Street</fullName>
                </value>
                <value>
                    <fullName>eMarketing</fullName>
                </value>
                <value>
                    <fullName>EMI</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Onsite Solutions</fullName>
                </value>
                <value>
                    <fullName>RappidApp</fullName>
                </value>
                <value>
                    <fullName>SignUp4</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>HC</fullName>
                </value>
                <value>
                    <fullName>CSN-P</fullName>
                </value>
                <value>
                    <fullName>Inquisium</fullName>
                </value>
                <value>
                    <fullName>Abstract Management</fullName>
                </value>
                <value>
                    <fullName>Appointments</fullName>
                </value>
                <value>
                    <fullName>OnArrival Premium</fullName>
                </value>
                <value>
                    <fullName>Lead Retrieval</fullName>
                </value>
                <value>
                    <fullName>Starcite Report Recipient</fullName>
                </value>
                <value>
                    <fullName>PayGo</fullName>
                </value>
                <value>
                    <fullName>PassKey</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Login__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Login</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>User Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>User__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Sub_Role__c</fullName>
        <label>User Sub Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Community Portal Administrator</fullName>
                </value>
                <value>
                    <fullName>Lead Catcher</fullName>
                </value>
                <value>
                    <fullName>NSO Contact</fullName>
                </value>
                <value>
                    <fullName>Passkey-Generic Call Center</fullName>
                </value>
                <value>
                    <fullName>Passkey-Hotel</fullName>
                </value>
                <value>
                    <fullName>Passkey-Hotel (ADMIN)</fullName>
                </value>
                <value>
                    <fullName>Passkey-Hotel Call Center</fullName>
                </value>
                <value>
                    <fullName>Passkey-Marketing</fullName>
                </value>
                <value>
                    <fullName>Passkey-Organizer</fullName>
                </value>
                <value>
                    <fullName>Passkey-Organizer (ADMIN)</fullName>
                </value>
                <value>
                    <fullName>Passkey-RoomListManager</fullName>
                </value>
                <value>
                    <fullName>Passkey-Sr Organizer</fullName>
                </value>
                <value>
                    <fullName>Passkey-Sr Organizer (ADMIN)</fullName>
                </value>
                <value>
                    <fullName>Profile Edit POC</fullName>
                </value>
                <value>
                    <fullName>Venue Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Contact Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoicing_Details__c.object
<CustomObject>
    <fields>
        <fullName>Billing_POC__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing POC</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoicing Details</relationshipLabel>
        <relationshipName>Invoicing_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Created for Invoicing Details for TRACT</description>
    <label>Invoicing Details</label>
    <nameField>
        <displayFormat>Invoice-{0000000000}</displayFormat>
        <label>Invoicing Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoicing Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Last_Login_Date__c</fullName>
        <label>Last Login Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>Active User</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User Name/Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>User (Custom)</label>
    <nameField>
        <displayFormat>User# {00000000}</displayFormat>
        <label>User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactRoleSyncBatch.cls
// ===============================
// AUTHOR           : Shanu Aggarwal    
// CREATED DATE     : 12 Jan 2017
// PURPOSE          : Customer Contact Role Synchronization
// TEST CLASS       :  CustomerRoleTriggerTest
// SPECIAL NOTES    :
// ===============================



global class ContactRoleSyncBatch implements Database.Batchable<sObject>,Schedulable {
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Id customerRecTypeId = Schema.SObjectType.Contact_Role__c.getRecordTypeInfosByName().get('Customer Role').getRecordTypeId();
        string query = 'Select Id,Contact__c,Product__c,Advocate__c,User_Sub_Role__c,User_Status__c,Billing__c,Last_Login_Date__c From Contact_Role__c where Last_Login_Date__c!=NULL ' +
                       'And RecordTypeId =: customerRecTypeId ';
        
        return Database.getQueryLocator(query);

        
    }
        
    global void execute(Database.BatchableContext BC, List<Contact_Role__c> scope) {
        
        List<Contact_Role__c> conRoleUpdateList = new List<Contact_Role__c>();
        
        Set<ID> conIds = new Set<ID>();
        Set<ID> advocatecustomerConIds = new Set<ID>();
        Set<ID> communitycustomerConIds = new Set<ID>();
        Set<ID> engagedcustomerConIds = new Set<ID>();
        Set<ID> billPocConIds = new Set<ID>();
        Map<Id,Boolean> setCaseActivityFlagMap,setActivityHistoryFlagMap;
        
        for(Contact_Role__c  con : scope ){
          conIds.add(con.Contact__c);
        }
          
        if(conIds.size()>0){
            
            setCaseActivityFlagMap = new Map<Id,Boolean>();
            setActivityHistoryFlagMap = new Map<Id,Boolean>();
            //User Status (Engaged) & Advocate Hub & Billing POC
            for( Contact c : [Select Id, (Select Id From Cases Limit 1),
                                (Select Id From Tasks Where NOT (LastModifiedBy.Name like '%Sops%' 
                                 OR LastModifiedBy.Name ='Lead Management (Sops)') Limit 1),
                                (Select Id,AdvocateHub__Contact__c From AdvocateHub__AdvocacyActivities__r Limit 1),
                                (Select Id,User__c,RecordTypeId From R00N000000071h6REAQ__r),
                                (Select Id From Invoicing_Details__r Limit 1)                           
                                From Contact Where Id IN:conIds]){
                
                if(c.Cases.size()>0 || c.Tasks.size()>0){
                        engagedcustomerConIds.add(c.Id);
                        // Added by Sandeep Kumar
                         for(Contact_Role__c conRole : c.R00N000000071h6REAQ__r){                                          
                             if(c.Cases !=null && c.Cases.size() > 0){
                                 setCaseActivityFlagMap.put(conRole.Id,true);
                             }else{
                                 setCaseActivityFlagMap.put(conRole.Id,false);
                             }
                             if(c.Tasks != null && c.Tasks.size() > 0){
                                 setActivityHistoryFlagMap.put(conRole.Id,true);
                             }else{
                                 setActivityHistoryFlagMap.put(conRole.Id,false);
                             }
                        }                                                                      
                }
                                 
                if(c.AdvocateHub__AdvocacyActivities__r.size()>0)
                    advocatecustomerConIds.add(c.Id);
                
                if(c.Invoicing_Details__r.size()>0)
                    billPocConIds.add(c.Id);
                
            }
            
            //Get Community Useer
            for( User u : [Select Id,ContactId From User Where ContactId IN: conIds and isPortalEnabled=true]){
                communitycustomerConIds.add(u.ContactId);
            }
            
            Boolean subRolePresent; 
            
            for(Contact_Role__c cr : scope ){
                subRolePresent=false;
                //Advocate Checkbox
                /*if(advocatecustomerConIds.contains(cr.Contact__c))
                    cr.Advocate__c = true;
                else
                    cr.Advocate__c = false;*/ //  commented by udita for contact roles
                
                //Mark Billing POC 
                if(billPocConIds.contains(cr.Contact__c))
                    cr.Billing__c = true;
                else
                    cr.Billing__c = false;
                
                //Community User
                Set<String> products = new Set<String>();
                if(cr.Product__c!=null){
                    
                    List<String> prods = cr.Product__c.split(';');
                    products.addAll(prods);
                    
                }               
                  
                //All the exception handling + validation check + Duplication check etc...
                if(cr.User_Sub_Role__c==null && communitycustomerConIds.contains(cr.Contact__c) && !products.contains('CrowdCompass')){
                    cr.User_Sub_Role__c = 'Community Portal Administrator';
                }else{
                    // Modified by: Sandeep Kumar, Additional check IS provided to avoid numerous addition of "Community Portal Administrator"
                    if(communitycustomerConIds.contains(cr.Contact__c) && !products.contains('CrowdCompass') || Test.isRunningTest()){
                        subRolePresent = Boolean.valueOf('false');                    
                        for(String subRole : cr.User_Sub_Role__c.split(';')){
                            if(subRole == 'Community Portal Administrator'){
                                subRolePresent = true;
                            }
                        }
                        if(!subRolePresent){
                            cr.User_Sub_Role__c = cr.User_Sub_Role__c + ';Community Portal Administrator';
                        }
                    }
                }
                //by default
                cr.User_Status__c = 'Dormant';
                // Added by Sandeep Kumar - validate to check 
                if(setCaseActivityFlagMap != null && setCaseActivityFlagMap.get(cr.Id) != null){
                    cr.Case_Activity__c = setCaseActivityFlagMap.get(cr.Id); 
                    cr.User_Status__c = 'Engaged';
                }                
                if(setActivityHistoryFlagMap != null && setActivityHistoryFlagMap.get(cr.Id) != null){
                    cr.Activity_History__c = setActivityHistoryFlagMap.get(cr.Id);  
                    cr.User_Status__c = 'Engaged';
                }
                
                //User Status
                Date lastLoginDate = Date.ValueOf(cr.Last_Login_Date__c);
                
                // Added by Sandeep Kumar - Update User status and system login checkbox. 
                if( lastLoginDate != null && lastLoginDate.daysBetween(System.today()) < 365 && !engagedcustomerConIds.contains(cr.Contact__c)){
                    cr.User_Status__c = 'Active';
                    cr.System_Login__c = true;
                }                   
                if( lastLoginDate != null && lastLoginDate.daysBetween(System.today()) < 365 && engagedcustomerConIds.contains(cr.Contact__c)){
                    cr.System_Login__c = true;
                    cr.User_Status__c = 'Engaged';   
                }   
                if(lastLoginDate != null && lastLoginDate.daysBetween(System.today()) > 365 && !engagedcustomerConIds.contains(cr.Contact__c)){cr.User_Status__c = 'Dormant';}
                if(lastLoginDate != null && lastLoginDate.daysBetween(System.today()) > 365){cr.System_Login__c = false;}
                if(lastLoginDate == null && !engagedcustomerConIds.contains(cr.Contact__c)){cr.User_Status__c = 'Dormant';}
                
                        
                
                conRoleUpdateList.add(cr);
                
            }
            
            if(conRoleUpdateList.size()>0)
                Database.Update(conRoleUpdateList);
        }
    
    }
    
    global void execute(SchedulableContext sc)
    {
        
        // We now call the batch class to be scheduled
        ContactRoleSyncBatch b = new ContactRoleSyncBatch();
       
        //Parameters of ExecuteBatch(context,BatchSize)
        database.executebatch(b,2000);
    }
    
    
    global void finish(Database.BatchableContext BC) {
        
    }
        

}