objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Attended__c</fullName>
        <label>Attended</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSG</fullName>
                </value>
                <value>
                    <fullName>OD/PS</fullName>
                </value>
                <value>
                    <fullName>Training Workshop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CT_Contact_Status__c</fullName>
        <label>CT-Mobile Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - New Contact</fullName>
                </value>
                <value>
                    <fullName>B - Working</fullName>
                </value>
                <value>
                    <fullName>C - Qualified</fullName>
                </value>
                <value>
                    <fullName>D - Set</fullName>
                </value>
                <value>
                    <fullName>E - Attended</fullName>
                </value>
                <value>
                    <fullName>F - Pricing</fullName>
                </value>
                <value>
                    <fullName>G - Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>H - Closed Won</fullName>
                </value>
                <value>
                    <fullName>I - Recycle</fullName>
                </value>
                <value>
                    <fullName>J - Trash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Contact_Status__c</fullName>
        <label>Event Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Suspect</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Marketing Qualified</fullName>
                </value>
                <value>
                    <fullName>Marketing Researched</fullName>
                </value>
                <value>
                    <fullName>Sales Accepted</fullName>
                </value>
                <value>
                    <fullName>Sales Generated</fullName>
                </value>
                <value>
                    <fullName>Sales Qualified</fullName>
                </value>
                <value>
                    <fullName>Open Opportunity</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Recycle</fullName>
                </value>
                <value>
                    <fullName>Trash</fullName>
                </value>
                <value>
                    <fullName>SignUp</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Event Created</fullName>
                </value>
                <value>
                    <fullName>Event Launched</fullName>
                </value>
                <value>
                    <fullName>#N/A</fullName>
                    <isActive>false</isActive>
                    <label>#N/A</label>
                </value>
                <value>
                    <fullName>0</fullName>
                    <isActive>false</isActive>
                    <label>0</label>
                </value>
                <value>
                    <fullName>A - New Contact</fullName>
                    <isActive>false</isActive>
                    <label>A - New Contact</label>
                </value>
                <value>
                    <fullName>A - New Lead</fullName>
                    <isActive>false</isActive>
                    <label>A - New Lead</label>
                </value>
                <value>
                    <fullName>Akshay Doshi</fullName>
                    <isActive>false</isActive>
                    <label>Akshay Doshi</label>
                </value>
                <value>
                    <fullName>Alesha Lorca</fullName>
                    <isActive>false</isActive>
                    <label>Alesha Lorca</label>
                </value>
                <value>
                    <fullName>Amanda Zeile</fullName>
                    <isActive>false</isActive>
                    <label>Amanda Zeile</label>
                </value>
                <value>
                    <fullName>Arvind Kumar</fullName>
                    <isActive>false</isActive>
                    <label>Arvind Kumar</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                    <isActive>false</isActive>
                    <label>Attended</label>
                </value>
                <value>
                    <fullName>B - Working</fullName>
                    <isActive>false</isActive>
                    <label>B - Working</label>
                </value>
                <value>
                    <fullName>Ben Gambhir</fullName>
                    <isActive>false</isActive>
                    <label>Ben Gambhir</label>
                </value>
                <value>
                    <fullName>Brittany Jennings</fullName>
                    <isActive>false</isActive>
                    <label>Brittany Jennings</label>
                </value>
                <value>
                    <fullName>C - Qualified</fullName>
                    <isActive>false</isActive>
                    <label>C - Qualified</label>
                </value>
                <value>
                    <fullName>Christopher Condley</fullName>
                    <isActive>false</isActive>
                    <label>Christopher Condley</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mood_Level__c</fullName>
        <label>Mood Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purchasing_Interest_CSNP__c</fullName>
        <label>Purchasing Interest (CSN-P)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5 - Extremely interested</fullName>
                </value>
                <value>
                    <fullName>4 - Very interested</fullName>
                </value>
                <value>
                    <fullName>3 - Somewhat interested</fullName>
                </value>
                <value>
                    <fullName>2 - Not very interested</fullName>
                </value>
                <value>
                    <fullName>1 - Not interested at all</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                    <isActive>false</isActive>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <isActive>false</isActive>
                    <label>1</label>
                </value>
                <value>
                    <fullName>1 - 3 months</fullName>
                    <isActive>false</isActive>
                    <label>1 - 3 months</label>
                </value>
                <value>
                    <fullName>1 - Not at all interested</fullName>
                    <isActive>false</isActive>
                    <label>1 - Not at all interested</label>
                </value>
                <value>
                    <fullName>1 - Not interested</fullName>
                    <isActive>false</isActive>
                    <label>1 - Not interested</label>
                </value>
                <value>
                    <fullName>1- Not at all Interested</fullName>
                    <isActive>false</isActive>
                    <label>1- Not at all Interested</label>
                </value>
                <value>
                    <fullName>1- Not interested</fullName>
                    <isActive>false</isActive>
                    <label>1- Not interested</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <isActive>false</isActive>
                    <label>2</label>
                </value>
                <value>
                    <fullName>2 - Not 4 - Very interested</fullName>
                    <isActive>false</isActive>
                    <label>2 - Not 4 - Very interested</label>
                </value>
                <value>
                    <fullName>2 - Not interested</fullName>
                    <isActive>false</isActive>
                    <label>2 - Not interested</label>
                </value>
                <value>
                    <fullName>200</fullName>
                    <isActive>false</isActive>
                    <label>200</label>
                </value>
                <value>
                    <fullName>2000</fullName>
                    <isActive>false</isActive>
                    <label>2000</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <isActive>false</isActive>
                    <label>3</label>
                </value>
                <value>
                    <fullName>3 - Somehwat Interested</fullName>
                    <isActive>false</isActive>
                    <label>3 - Somehwat Interested</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <isActive>false</isActive>
                    <label>300</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <isActive>false</isActive>
                    <label>4</label>
                </value>
                <value>
                    <fullName>4 - 6 months</fullName>
                    <isActive>false</isActive>
                    <label>4 - 6 months</label>
                </value>
                <value>
                    <fullName>4 - Very interested - Very interested</fullName>
                    <isActive>false</isActive>
                    <label>4 - Very interested - Very interested</label>
                </value>
                <value>
                    <fullName>4 - Very interestedUndo</fullName>
                    <isActive>false</isActive>
                    <label>4 - Very interestedUndo</label>
                </value>
                <value>
                    <fullName>4- Very interested</fullName>
                    <isActive>false</isActive>
                    <label>4- Very interested</label>
                </value>
                <value>
                    <fullName>400</fullName>
                    <isActive>false</isActive>
                    <label>400</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <isActive>false</isActive>
                    <label>5</label>
                </value>
                <value>
                    <fullName>5 - Extremely interestedUndo</fullName>
                    <isActive>false</isActive>
                    <label>5 - Extremely interestedUndo</label>
                </value>
                <value>
                    <fullName>Extremely interested</fullName>
                    <isActive>false</isActive>
                    <label>Extremely interested</label>
                </value>
                <value>
                    <fullName>Not interested at all</fullName>
                    <isActive>false</isActive>
                    <label>Not interested at all</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchasing_Interest_PK__c</fullName>
        <label>Purchasing Interest (PK)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5 - Extremely interested</fullName>
                </value>
                <value>
                    <fullName>4 - Very interested</fullName>
                </value>
                <value>
                    <fullName>3 - Somewhat interested</fullName>
                </value>
                <value>
                    <fullName>2 - Not very interested</fullName>
                </value>
                <value>
                    <fullName>1 - Not interested at all</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Contact_Status__c</fullName>
        <label>CT-Ticketing Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A - New Contact</fullName>
                </value>
                <value>
                    <fullName>B - Working</fullName>
                </value>
                <value>
                    <fullName>C - Qualified</fullName>
                </value>
                <value>
                    <fullName>D - Set</fullName>
                </value>
                <value>
                    <fullName>E - Attended</fullName>
                </value>
                <value>
                    <fullName>F - Pricing</fullName>
                </value>
                <value>
                    <fullName>G - Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>H - Closed Won</fullName>
                </value>
                <value>
                    <fullName>I - Recycle</fullName>
                </value>
                <value>
                    <fullName>J - Trash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HL_Community_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>HL Community Activities</relationshipLabel>
        <relationshipName>HL_Community_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <label>Activity Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HL Community Activity</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>HL Community Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HL Community Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CommunityActivityTriggerTest.cls
@isTest
private class CommunityActivityTriggerTest{
    static testMethod void myUnitTest() {
        
        //Insert Account......
        Account acctA1 = new Account(Name = 'AAA-Account');
        insert acctA1;
        //Insert Contact..........
        Contact instContact = new Contact();
        instContact.LastName = 'Test';
        instContact.AccountId = acctA1.Id;
        instContact.CT_Contact_Status__c= 'Open Opportunity';
        instContact.Event_Contact_Status__c = 'Open Opportunity';
        instContact.TM_Contact_Status__c = 'Open Opportunity';
        instContact.LeadSource = 'WEB-Chat (CrowdCompass)';
        instContact.Mood_Level__c = 2;
        instContact.Purchasing_Interest_CSNP__c = '4 - Very interested';
        instContact.Purchasing_Interest_PK__c='3 - Somewhat interested';
        instContact.Attended__c = 'CSG';
        instContact.MailingCountryCode = 'IN';
        insert instContact;

        HL_Community_Activity__c HLObject = new HL_Community_Activity__c();
        HLObject.Account__c = acctA1.Id;
        HLObject.Activity_Type__c= 'Test Type';
        HLObject.Activity_Date__c= system.now();
        HLObject.Contact__c= instContact.Id;
        HLObject.Description__c= 'Test Description';
        insert HLObject;
    }
}