objects/Contract_Reviewing__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Review_Ok__c</fullName>
        <label>Contract Review Ok?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Re-Review</fullName>
                </value>
                <value>
                    <fullName>Error Correct</fullName>
                </value>
                <value>
                    <fullName>Error in other opp</fullName>
                </value>
                <value>
                    <fullName>Error Rectify</fullName>
                </value>
                <value>
                    <fullName>No Review needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Review_Date__c</fullName>
        <label>Final Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contract Reviews</relationshipLabel>
        <relationshipName>Contract_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Review</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Contract Reviewing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ScheduledFinanceShellBatch.cls
global class ScheduledFinanceShellBatch implements Schedulable {
    global void execute(SchedulableContext sc) {
      Date todayDate = Date.today();
      Integer dateValue = Integer.valueof(Label.Finance_Shell_Date_Range);
      Date lastWeekDate = todayDate.addDays(dateValue);
      Set<Id> opportunityIds = new Set<Id>();
      

      List<Contract_Reviewing__c> lstContractReviewed = [SELECT Opportunity__c
                                                           FROM Contract_Reviewing__c 
                                                          WHERE Final_Review_Date__c >= :lastWeekDate 
                                                            AND Final_Review_Date__c <= :todayDate
                                                            AND Contract_Review_Ok__c = 'Yes'];

      for(Contract_Reviewing__c lstItr : lstContractReviewed){
            opportunityIds.add(lstItr.Opportunity__c);
      }
      // Dishank - updated to work only for Closed Won opportunities
      /*List<Opportunity> lstOpportunities = [SELECT Id 
                                              FROM Opportunity 
                                             WHERE CloseDate>=:lastWeekDate 
                                               AND CloseDate <= :todayDate
                                               AND StageName IN ('Closed Lost',
                                                                  'Closed -- Never Qualified',
                                                                  'Cancelled', 
                                                                  'Opted-Out', 
                                                                  'Closed Lost - Opted Out/Cancelled', 
                                                                  'Closed Reassigned')];

      for(Opportunity lstItr : lstOpportunities){
            opportunityIds.add(lstItr.Id);
      }*/
      String mailSubject = 'Finance Shell Opportunities for Date ' + lastWeekDate.day() +'/'+ lastWeekDate.month() + '/' + lastWeekDate.year() 
                         + ' - ' + todayDate.day() + '/' + todayDate.month() + '/' +todayDate.year();
      String body = '';
       if(opportunityIds.size()>0){
            body = '<table border = "1"><tr><th>Opportunity List </th></tr>';
            for(Id setItr : opportunityIds){
                  body +='<tr><td>'+ setItr + '</td></tr>';
            }
            body += '</table>';           
      }
      else {
            body += '<b>No Opportunities</b>';
      }
      String emailRecevierList = Label.Opportunity_Email_Receivers;
      String[] sendingTo= emailRecevierList.split(',');
      sendEmail(opportunityIds,mailSubject,body,sendingTo);

      CreateFincanceShallFromOpp b = new CreateFincanceShallFromOpp(opportunityIds); 
      Database.executeBatch(b,1);
   }

   public void sendEmail(Set<Id> opportunityIds,String mailSubject ,String mailBody, String[] strReceipent){
      Messaging.SingleEmailMessage semail=new Messaging.SingleEmailMessage();
      semail.setToAddresses(strReceipent);
      semail.setSubject(mailSubject);
      semail.setHtmlBody(mailBody);
      Messaging.SendEmail(new Messaging.SingleEmailMessage[]{semail});
   }
}