objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Higher_Logic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Higher Logic</label>
        <referenceTo>Higher_Logic__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Advocate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advocate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Primary POC</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>R00N000000071h6REAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Decision_Maker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Decision Maker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Executive_Sponsor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Executive Sponsor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Influencer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Influencer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>User Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>User__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Sub_Role__c</fullName>
        <label>User Sub Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Community Portal Administrator</fullName>
                </value>
                <value>
                    <fullName>Lead Catcher</fullName>
                </value>
                <value>
                    <fullName>NSO Contact</fullName>
                </value>
                <value>
                    <fullName>Passkey-Generic Call Center</fullName>
                </value>
                <value>
                    <fullName>Passkey-Hotel</fullName>
                </value>
                <value>
                    <fullName>Passkey-Hotel (ADMIN)</fullName>
                </value>
                <value>
                    <fullName>Passkey-Hotel Call Center</fullName>
                </value>
                <value>
                    <fullName>Passkey-Marketing</fullName>
                </value>
                <value>
                    <fullName>Passkey-Organizer</fullName>
                </value>
                <value>
                    <fullName>Passkey-Organizer (ADMIN)</fullName>
                </value>
                <value>
                    <fullName>Passkey-RoomListManager</fullName>
                </value>
                <value>
                    <fullName>Passkey-Sr Organizer</fullName>
                </value>
                <value>
                    <fullName>Passkey-Sr Organizer (ADMIN)</fullName>
                </value>
                <value>
                    <fullName>Profile Edit POC</fullName>
                </value>
                <value>
                    <fullName>Venue Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Contact Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Buyer_Role</fullName>
        <active>true</active>
        <label>Buyer Role</label>
    </recordTypes>
</CustomObject>

objects/Higher_Logic__c.object
<CustomObject>
    <fields>
        <fullName>Buyer_Decision_Maker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Buyer - Decision Maker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Buyer_Executive_Sponsor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Buyer - Executive Sponsor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Buyer_Influencer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Buyer - Influencer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Advocate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer - Advocate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer - Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_User_Status__c</fullName>
        <label>Customer User Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_User_Sub_Role__c</fullName>
        <label>Customer User Sub-Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer - User</label>
        <type>Checkbox</type>
    </fields>
    <label>Higher Logic</label>
    <nameField>
        <displayFormat>HLR-{0000000000}</displayFormat>
        <label>HLR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Higher Logics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User__c.object
<CustomObject>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>Active User</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User Name/Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>User (Custom)</label>
    <nameField>
        <displayFormat>User# {00000000}</displayFormat>
        <label>User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactRoleTriggerHelper.cls
public class ContactRoleTriggerHelper 
{
	public static void onAfterInsert(Map<Id,Contact_Role__c> newMap)
    {
        Map<Id,Contact_Role__c> contactsVSContactRole = new Map<Id,Contact_Role__c>();
        for(Contact_Role__c conRole : newMap.values())
        {
            if(conRole.Contact__c != NULL)
            {
                contactsVSContactRole.put(conRole.Contact__c,conRole);
            }
        }
        
        Map<Id,Higher_Logic__c> mapOfContactIdVSHigherLogic = new Map<Id,Higher_Logic__c>();
        List<Higher_Logic__c> listOfHigherLogic = new List<Higher_Logic__c>();
        Map<Id,Contact> mapOfContacts = new Map<Id,Contact>();
        for(Contact con : [select Higher_Logic__c,Higher_Logic__r.Customer_User_Sub_Role__c,Higher_Logic__r.Buyer_Decision_Maker__c,Higher_Logic__r.Buyer_Executive_Sponsor__c,Higher_Logic__r.Buyer_Influencer__c,Higher_Logic__r.Customer_Advocate__c,Higher_Logic__r.Customer_Billing__c,Higher_Logic__r.Customer_User__c,Higher_Logic__r.Customer_User_Status__c from Contact where ID IN :contactsVSContactRole.keySet()])
        {
            Id buyerRoleRecordTypeId = Schema.SObjectType.Contact_Role__c.getRecordTypeInfosByDeveloperName().get('Buyer_Role').getRecordTypeId();
            if(con.Higher_Logic__c != NULL)
            {
                Higher_Logic__c higherLogicRecord = new Higher_Logic__c(Id = con.Higher_Logic__c);
                System.debug('contactsVSContactRole.get(con.Id).RecordTypeId>>'+contactsVSContactRole.get(con.Id).RecordTypeId);
                if(contactsVSContactRole.get(con.Id).RecordTypeId == buyerRoleRecordTypeId)
                {
                    if(con.Higher_Logic__r.Buyer_Decision_Maker__c == FALSE)
                    {
                        higherLogicRecord.Buyer_Decision_Maker__c = contactsVSContactRole.get(con.Id).Decision_Maker__c;
                    }
                    if(con.Higher_Logic__r.Buyer_Executive_Sponsor__c == FALSE)
                    {
                        higherLogicRecord.Buyer_Executive_Sponsor__c = contactsVSContactRole.get(con.Id).Executive_Sponsor__c;
                    }
                    if(con.Higher_Logic__r.Buyer_Influencer__c == FALSE)
                    {
                        higherLogicRecord.Buyer_Influencer__c = contactsVSContactRole.get(con.Id).Influencer__c;
                    }
                }
                else
                {
                    if(con.Higher_Logic__r.Customer_Advocate__c == FALSE)
                    {
                        higherLogicRecord.Customer_Advocate__c = contactsVSContactRole.get(con.Id).Advocate__c;
                    }
                    if(con.Higher_Logic__r.Customer_Billing__c == FALSE)
                    {
                        higherLogicRecord.Customer_Billing__c = contactsVSContactRole.get(con.Id).Billing__c;
                    }
                    if(con.Higher_Logic__r.Customer_User__c == FALSE)
                    {
                        higherLogicRecord.Customer_User__c = contactsVSContactRole.get(con.Id).User__c;
                    }
                    if(String.isBlank(con.Higher_Logic__r.Customer_User_Status__c))
                    {
                        higherLogicRecord.Customer_User_Status__c = contactsVSContactRole.get(con.Id).User_Status__c;
                    }	
                    if(String.isBlank(con.Higher_Logic__r.Customer_User_Sub_Role__c))
                    {
                        higherLogicRecord.Customer_User_Sub_Role__c = contactsVSContactRole.get(con.Id).User_Sub_Role__c;
                    }
                }
                listOfHigherLogic.add(higherLogicRecord);
            }
            else
            {
                Higher_Logic__c higherLogicRec = new Higher_Logic__c();
                mapOfContacts.put(con.Id,con);
                if(contactsVSContactRole.get(con.Id).RecordTypeId == buyerRoleRecordTypeId)
                {
                    higherLogicRec.Buyer_Decision_Maker__c = contactsVSContactRole.get(con.Id).Decision_Maker__c;
                    higherLogicRec.Buyer_Executive_Sponsor__c = contactsVSContactRole.get(con.Id).Executive_Sponsor__c;
                    higherLogicRec.Buyer_Influencer__c = contactsVSContactRole.get(con.Id).Influencer__c;
                }
                else
                {
                    higherLogicRec.Customer_Advocate__c = contactsVSContactRole.get(con.Id).Advocate__c;
                    higherLogicRec.Customer_Billing__c = contactsVSContactRole.get(con.Id).Billing__c;
                    higherLogicRec.Customer_User__c = contactsVSContactRole.get(con.Id).User__c;
                    higherLogicRec.Customer_User_Status__c = contactsVSContactRole.get(con.Id).User_Status__c;
                    higherLogicRec.Customer_User_Sub_Role__c = contactsVSContactRole.get(con.Id).User_Sub_Role__c;
                }
                mapOfContactIdVSHigherLogic.put(con.Id,higherLogicRec);
            }
        }
        
        if(!mapOfContactIdVSHigherLogic.isEmpty())
        {
            insert mapOfContactIdVSHigherLogic.values();
        }
        
        if(!listOfHigherLogic.isEmpty())
        {
            update listOfHigherLogic;
        }
        
        for(Id conId : mapOfContactIdVSHigherLogic.keySet())
        {
            mapOfContacts.get(conId).Higher_Logic__c = mapOfContactIdVSHigherLogic.get(conId).Id;
        }
        
        if(!mapOfContacts.isEmpty())
        {
            update mapOfContacts.values();
        }
    }
    
    public static void onAfterUpdate(Map<Id,Contact_Role__c> oldMap, Map<Id,Contact_Role__c> newMap)
    {
        Map<Id,Contact_Role__c> contactsVSContactRole = new Map<Id,Contact_Role__c>();
        for(Contact_Role__c conRole : newMap.values())
        {
            if(conRole.Contact__c != NULL && (oldMap.get(conRole.Id).Decision_Maker__c != conRole.Decision_Maker__c || oldMap.get(conRole.Id).Executive_Sponsor__c != conRole.Executive_Sponsor__c || oldMap.get(conRole.Id).Influencer__c != conRole.Influencer__c || oldMap.get(conRole.Id).Advocate__c != conRole.Advocate__c || oldMap.get(conRole.Id).Billing__c != conRole.Billing__c || oldMap.get(conRole.Id).User__c != conRole.User__c || oldMap.get(conRole.Id).User_Status__c != conRole.User_Status__c || oldMap.get(conRole.Id).User_Sub_Role__c != conRole.User_Sub_Role__c))
            {
                contactsVSContactRole.put(conRole.Contact__c,conRole);
            }
        }
        List<Higher_Logic__c> listOfHigherLogic = new List<Higher_Logic__c>();
        Map<Id,Contact> mapOfContacts = new Map<Id,Contact>();
        Map<Id,Higher_Logic__c> mapOfContactIdVSHigherLogic = new Map<Id,Higher_Logic__c>();
        for(Contact con : [select Higher_Logic__c,Higher_Logic__r.Buyer_Decision_Maker__c,Higher_Logic__r.Buyer_Executive_Sponsor__c,Higher_Logic__r.Buyer_Influencer__c,Higher_Logic__r.Customer_Advocate__c,Higher_Logic__r.Customer_Billing__c,Higher_Logic__r.Customer_User__c,Higher_Logic__r.Customer_User_Status__c from Contact where ID IN :contactsVSContactRole.keySet()])
        {
            Id buyerRoleRecordTypeId = Schema.SObjectType.Contact_Role__c.getRecordTypeInfosByDeveloperName().get('Buyer_Role').getRecordTypeId();
            if(con.Higher_Logic__c != NULL)
            {
                Higher_Logic__c higherLogicRecord = new Higher_Logic__c(Id = con.Higher_Logic__c);
                
                if(contactsVSContactRole.get(con.Id).RecordTypeId == buyerRoleRecordTypeId)
                {
                    higherLogicRecord.Buyer_Decision_Maker__c = contactsVSContactRole.get(con.Id).Decision_Maker__c;
                    higherLogicRecord.Buyer_Executive_Sponsor__c = contactsVSContactRole.get(con.Id).Executive_Sponsor__c;
                    higherLogicRecord.Buyer_Influencer__c = contactsVSContactRole.get(con.Id).Influencer__c;
                }
                else
                {
                    higherLogicRecord.Customer_Advocate__c = contactsVSContactRole.get(con.Id).Advocate__c;
                    higherLogicRecord.Customer_Billing__c = contactsVSContactRole.get(con.Id).Billing__c;
                    higherLogicRecord.Customer_User__c = contactsVSContactRole.get(con.Id).User__c;
                    higherLogicRecord.Customer_User_Status__c = contactsVSContactRole.get(con.Id).User_Status__c;
                    higherLogicRecord.Customer_User_Sub_Role__c = contactsVSContactRole.get(con.Id).User_Sub_Role__c;
                 }
                listOfHigherLogic.add(higherLogicRecord);
            }
            else
            {
                Higher_Logic__c higherLogicRec = new Higher_Logic__c();
                mapOfContacts.put(con.Id,con);
                if(contactsVSContactRole.get(con.Id).RecordTypeId == buyerRoleRecordTypeId)
                {
                    higherLogicRec.Buyer_Decision_Maker__c = contactsVSContactRole.get(con.Id).Decision_Maker__c;
                    higherLogicRec.Buyer_Executive_Sponsor__c = contactsVSContactRole.get(con.Id).Executive_Sponsor__c;
                    higherLogicRec.Buyer_Influencer__c = contactsVSContactRole.get(con.Id).Influencer__c;
                }
                else
                {
                    higherLogicRec.Customer_Advocate__c = contactsVSContactRole.get(con.Id).Advocate__c;
                    higherLogicRec.Customer_Billing__c = contactsVSContactRole.get(con.Id).Billing__c;
                    higherLogicRec.Customer_User__c = contactsVSContactRole.get(con.Id).User__c;
                    higherLogicRec.Customer_User_Status__c = contactsVSContactRole.get(con.Id).User_Status__c;
                    higherLogicRec.Customer_User_Sub_Role__c = contactsVSContactRole.get(con.Id).User_Sub_Role__c;
                }
                mapOfContactIdVSHigherLogic.put(con.Id,higherLogicRec);
            }
        }
        
        if(!mapOfContactIdVSHigherLogic.isEmpty())
        {
            insert mapOfContactIdVSHigherLogic.values();
        }
        
        if(!listOfHigherLogic.isEmpty())
        {
            update listOfHigherLogic;
        }
        
        for(Id conId : mapOfContactIdVSHigherLogic.keySet())
        {
            mapOfContacts.get(conId).Higher_Logic__c = mapOfContactIdVSHigherLogic.get(conId).Id;
        }
        
        if(!mapOfContacts.isEmpty())
        {
            update mapOfContacts.values();
        }
    }
}