objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_GDPR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is GDPR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>FirstName &amp; ' ' &amp; LastName</formula>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>GDPR</fullName>
        <active>true</active>
        <label>GDPR</label>
    </recordTypes>
</CustomObject>

objects/GDPR_Central_Repository__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Follow-Up Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_GDPR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is GDPR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>sObject_type__c</fullName>
        <label>sObject type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Person Account</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This will hold the Contacts, Leads, Tasks, Cases which are being marked GDPR to validate if someone tries to create a new record with similar data.</description>
    <label>GDPR Central Repository</label>
    <nameField>
        <displayFormat>GDPR-{00000000}</displayFormat>
        <label>GDPR Central Repository Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDPR Central Repositories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/GDPR_Persona_Data__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromAddress__c</fullName>
        <label>FromAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromName__c</fullName>
        <label>FromName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GDPR_Central_Repository__c</fullName>
        <label>GDPR Central Repository</label>
        <referenceTo>GDPR_Central_Repository__c</referenceTo>
        <relationshipName>GDPR_Persona_Datas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Subject__c</fullName>
        <label>Subject</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextBody__c</fullName>
        <label>TextBody</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Web_Email__c</fullName>
        <label>Web Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Phone__c</fullName>
        <label>Web Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Zone__c</fullName>
        <label>Web Zone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObject_type__c</fullName>
        <label>sObject type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Email Messages</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>All the data related to Contact and Leads i.e Task/Event/Case</description>
    <label>GDPR Personal Data</label>
    <nameField>
        <displayFormat>GDPRPD-{000000000}</displayFormat>
        <label>GDPR Persona Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDPR Personal Datas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>GDPR</fullName>
        <active>true</active>
        <label>GDPR</label>
    </recordTypes>
</CustomObject>

classes/deleteGDPRPersonaBatch.cls
/* ===============================
AUTHOR     :     Udita Dwivedi
CREATED DATE   : 17 April 2018
PURPOSE     :    When a contact is removed from GDPR it deletes it's info from GDPR Persona data and restores it in task.
TEST CLASS :     testGDPR 
============================= 
*/
global class deleteGDPRPersonaBatch implements Database.Batchable<sobject>{

    global Database.QueryLocator start(Database.BatchableContext BC){
        string query='select id,Id__c,Follow_Up_Created__c,sObject_type__c from GDPR_Central_Repository__c where Is_GDPR__c = false  and Follow_Up_Created__c= true';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC,list<GDPR_Central_Repository__c> gdprList){
     
     list<Task> taskList = new list<Task>();
     list<Event> eventList = new list<Event>();
     list<Case> caseList = new list<Case>();
     list<GDPR_Persona_Data__c> deleteGDP = new list<GDPR_Persona_Data__c>();
     map<id,GDPR_Central_Repository__c> gdprMap = new map<id,GDPR_Central_Repository__c>();
     
    for(GDPR_Central_Repository__c gdpr : gdprList){  
        gdprMap.put(gdpr.id,gdpr);  
    } 
           
    deleteGDP =[SELECT Comments__c,CreatedById,CreatedDate,CurrencyIsoCode,Email__c,FromAddress__c,FromName__c,GDPR_Central_Repository__c,
                 Id,Id__c,IsDeleted,LastModifiedById,LastModifiedDate,Name,Name__c,Phone__c, 
                 RecordTypeId__c,sObject_type__c,SystemModstamp,Task_Subject__c,TextBody__c,Web_Email__c,Web_Phone__c,Web_Zone__c
                 FROM GDPR_Persona_Data__c where GDPR_Central_Repository__c in : gdprMap.keyset()];
                     
     for(GDPR_Persona_Data__c gdp : deleteGDP ){
       if(gdp.sObject_type__c =='Task'){
         Task t = new task(id= gdp.id__c); 
         t.RecordTypeId = gdp.RecordTypeId__c;
         t.Subject = gdp.Task_Subject__c.substringAfter('GDPR- ');
         t.Description = gdp.Comments__c.substringAfter('GDPR- ');
         GDPR_Central_Repository__c gdpObject = gdprMap.get(gdp.GDPR_Central_Repository__c);
         gdpObject.Follow_Up_Created__c = false;  
         taskList.add(t);
       }
      if(gdp.sObject_type__c =='Event'){
         Event evt  = new Event(id= gdp.id__c);      
         evt.RecordTypeId = gdp.RecordTypeId__c;
         evt.Subject = gdp.Task_Subject__c.substringAfter('GDPR- ');
         evt.Description = gdp.Comments__c.substringAfter('GDPR- ');
         GDPR_Central_Repository__c gdpObject = gdprMap.get(gdp.GDPR_Central_Repository__c);
         gdpObject.Follow_Up_Created__c = false;  
         eventList.add(evt);
       }
      if(gdp.sObject_type__c =='Case'){
         Case cs  = new Case(id= gdp.id__c);      
         cs.RecordTypeId = gdp.RecordTypeId__c;
         cs.Subject = gdp.Task_Subject__c.substringAfter('GDPR- ');
         cs.Description = gdp.Comments__c.substringAfter('GDPR- ');
         cs.RecordTypeId = gdp.RecordTypeId__c;
         cs.Subject = gdp.Task_Subject__c.substringAfter('GDPR- ');
         GDPR_Central_Repository__c gdpObject = gdprMap.get(gdp.GDPR_Central_Repository__c);
         gdpObject.Follow_Up_Created__c = false;  
         caseList.add(cs);
       }
     }
     
     if(caseList.size() > 0){
       update caseList;
     } 
     if(eventList.size() > 0){
       update eventList;
     } 
     if(taskList.size() > 0){
       update taskList;
     }   
     
     if(gdprMap.size() > 0){
        update gdprMap.values();
     } 
     if(deleteGDP.size() > 0){
      delete deleteGDP;
     }
    }
    global void finish(Database.BatchableContext BC){
        
    }
}