objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <description>Email id of the manager. Used in Trigger for updating the Mood Levels</description>
        <label>Level 1 Manager</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mood__c</fullName>
        <formula>CASE(Mood_Level__c,1,IMAGE("https://cvent--c.na17.content.force.com/servlet/servlet.FileDownload?file=01500000000htcg","image from Documents tab"),2,IMAGE("https://cvent--c.na17.content.force.com/servlet/servlet.FileDownload?file=01500000000htcW","image from Documents tab"),3,IMAGE("https://cvent--c.na17.content.force.com/servlet/servlet.FileDownload?file=01500000000htcR","image from Documents tab"),4,IMAGE("https://cvent--c.na17.content.force.com/servlet/servlet.FileDownload?file=01500000000htcM","image from Documents tab"),5,IMAGE("https://cvent--c.na17.content.force.com/servlet/servlet.FileDownload?file=01500000000htcH","image from Documents tab"),"")</formula>
        <label>Mood</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/T_D__c.object
<CustomObject>
    <fields>
        <fullName>Deliverables__c</fullName>
        <label>Deliverables</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <inlineHelpText>Desired end result of the project and why we're doing it in the first place.</inlineHelpText>
        <label>Goal</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Requestor_Name__c</fullName>
        <label>Requestor Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>T&amp;D Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T&amp;D Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <description>For Sales Team</description>
        <label>Sales</label>
    </recordTypes>
</CustomObject>

classes/TestActivitytrigger.cls
//========================Created By Rishi Ojha dated 22/07/13====================================

//========================This class is created to test the Trigger >>SetFirstactivityDate

@isTest(SeeAllData=True)

private class TestActivitytrigger
{
static testMethod void testSetFirstActivityDate()

{
        List<T_D__c> tdp = new List<T_D__c>{ new T_D__c(
        Name= 'test tdp 1',
        Requestor_Name__c = 'xyz',
        Goal__c = 'test test',
        Deliverables__c = 'test test'), new T_D__c(
        Name= 'test tdp 2',
        Requestor_Name__c = 'xyz',
        Goal__c = 'test test',
        Deliverables__c = 'test test')};
                                    
        insert tdp;
        
        List<Contact> con = new List<Contact>{ new contact(
        FirstName = 'test con 1',
        LastName = 'xyz',
        LeadSource = 'Web'/*,
        Manager_Email__c = 'test@test.com'*/), new contact(
        FirstName = 'test con 2',
        LastName = 'xyz',
        LeadSource = 'Web'/*,
        Manager_Email__c = 'test@test.com'*/)};
        //insert con;
        
        List<task> t = new List<task>{ new task(
        WhoID = con[1].id,
        Subject='Newtask',
        Status='Completed',
        OwnerId=UserInfo.getUserId(),
        Task_Event_Type__c = 'Client Emails',
        Priority='High'),new task(
        WhoID = con[1].id,
        Subject='Newtask',
        Status='Completed',
        OwnerId=UserInfo.getUserId(),
        Task_Event_Type__c = 'Client Emails',
        Priority='High',
        Mood__c='2 - Frustrated',
        Primary_Reason_for_Mood_Driver__c = 'Sales',
        Reason__c = 'Oversold'),new task(
        WhoID = con[1].id,
        Subject='Newtask',
        Status='Completed',
        OwnerId=UserInfo.getUserId(),
        Task_Event_Type__c = 'Client Emails',
        Priority='High',
        Mood__c='4 - Happy'),new task(
        whatId= tdp[0].id,
        Subject='Newtask',
        Status='Completed',
        Priority='High',
        OwnerId=UserInfo.getUserId(),
        Minutes_on_tasks__c=40)};
        
        insert t;  
        
        t[0].status = 'Completed';
        t[0].Mood__c='1 - Irate';
        t[0].Primary_Reason_for_Mood_Driver__c = 'Sales';
        t[0].Reason__c = 'Oversold';
        
        update t[0];
        
        /*List<task> taskstoupdate = new List<task>{ [select id from task where id =: t[0].id]};
        List<task> taskL = new List<task>();
        for(task tOK:taskstoupdate){
            tOK.status = 'Completed';
            tOK.Mood__c='1 - Irate';
            tOK.Primary_Reason_for_Mood_Driver__c = 'Sales';
            tOK.Reason__c = 'Oversold';
            taskL.add(tOK);
        }
        update taskL;*/
        
       Contact[] cons = [select id from Contact where id in :con];
      delete t[2];

}
}