objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Mobile_Card__c.object
<CustomObject>
    <fields>
        <fullName>Attributes__c</fullName>
        <label>Attributes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Affinity</fullName>
                </value>
                <value>
                    <fullName>Alliance Tech</fullName>
                </value>
                <value>
                    <fullName>App build platinum</fullName>
                </value>
                <value>
                    <fullName>App Build Plus</fullName>
                </value>
                <value>
                    <fullName>App Build Premium</fullName>
                </value>
                <value>
                    <fullName>Apple Transition</fullName>
                </value>
                <value>
                    <fullName>AttendeeHub</fullName>
                </value>
                <value>
                    <fullName>Click</fullName>
                </value>
                <value>
                    <fullName>Client Directory</fullName>
                </value>
                <value>
                    <fullName>Custom Video 2 Minutes</fullName>
                </value>
                <value>
                    <fullName>Custom Video 5 Minutes</fullName>
                </value>
                <value>
                    <fullName>Cvent Conference Integration</fullName>
                </value>
                <value>
                    <fullName>Cvent Event</fullName>
                </value>
                <value>
                    <fullName>Data loading service</fullName>
                </value>
                <value>
                    <fullName>Design Studio Advanced</fullName>
                </value>
                <value>
                    <fullName>Design Studio - Simple</fullName>
                </value>
                <value>
                    <fullName>DoubleDutch</fullName>
                </value>
                <value>
                    <fullName>Early Adopter – Falcon</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Enterprise Distribution</fullName>
                </value>
                <value>
                    <fullName>European Data Center</fullName>
                </value>
                <value>
                    <fullName>Exception: CC Dev Acct</fullName>
                </value>
                <value>
                    <fullName>Graphics Work</fullName>
                </value>
                <value>
                    <fullName>High Volume</fullName>
                </value>
                <value>
                    <fullName>Hospitality Cloud</fullName>
                </value>
                <value>
                    <fullName>Inquisium</fullName>
                </value>
                <value>
                    <fullName>Lanyon Transition</fullName>
                </value>
                <value>
                    <fullName>Lanyon Transition - App Build Plus</fullName>
                </value>
                <value>
                    <fullName>Lead Retrieval</fullName>
                </value>
                <value>
                    <fullName>Live Q&amp;A</fullName>
                </value>
                <value>
                    <fullName>Rush Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Form_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CC Form Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Cards_CC</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Track Projects for Mobile App Builders in SF</description>
    <label>Mobile App</label>
    <nameField>
        <label>Mobile Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CCMobileAppAutoSendCCForm_TrigAct.cls
/**************************************************************************************
* Author: Sandeep Kumar
* Date: 06 November 2018
* Description: CC Mobile App Auto Send CC Form to Primary Contact, created as a part of CC ABP Automation  
* Class sends an email to the customer for filling out the survey
* Test Class : CCMobileAppAutoAssignment_TrigAct_Test
****************************************************************************************/
public class CCMobileAppAutoSendCCForm_TrigAct  extends TriggerAction{
    private set<Id> mobAppIdSet;
    private final String NormalABPTemplateID = Label.CC_Normal_ABP_Form_Template_ID;
    private final String RushABPTemplateID = Label.CC_Rush_Request_Form_Template_ID;
    private final String oweaForCrowdCompassSupportId = Label.CC_Automation_Org_Wide_Email_Address;    
    private final Id crowdCompassRecTypeId = Schema.SObjectType.Mobile_Card__c.getRecordTypeInfosByDeveloperName().get(Label.Mobile_App_RT_Label_Name).getRecordTypeId();
    
    public CCMobileAppAutoSendCCForm_TrigAct(){
        // call super to set batch variables & context
        super();
        mobAppIdSet = new set<Id>();
    }

    public override Boolean shouldRun(){
        if(this.isAfter() && this.isInsert() && !this.hasRun()){
            for(Mobile_Card__c newMobileApp: (List<Mobile_Card__c>)this.triggerMap.values()){
                // mobile app must have a valid record type for falling under CC Automation
                if(newMobileApp.RecordTypeId == crowdCompassRecTypeId)
                    mobAppIdSet.add(newMobileApp.Id);
            }
        }
        return !mobAppIdSet.isEmpty();
    }    
    
    public override void doAction(){
        // set trigger action variable to indicate that the doAction has been called and it will avoid recursion.        
        this.markRun();
        
        // iterate on valid mobile apps and create follow up cases where the CC Form Sent field is unchecked.
        for(Mobile_Card__c newMobileApp: (List<Mobile_Card__c>)this.triggerMap.values()){
            // mobile app must have a valid record type for falling under CC Automation
            if(mobAppIdSet.contains(newMobileApp.Id)){
                // sends an email to primary contact for asking him to fill out the survey form.
                if(newMobileApp.CC_Form_Sent__c){
                    // below code will be executed only if the email is not sent due to any email exception.
                    // error message will be displayed to the end user, so that business is aware about it and they should wait for 
                    // customer to fill out a survey which is not being sent to them originally.
                    if(!sendCCFormToPrimaryContact(newMobileApp)) newMobileApp.addError(Label.CC_Form_Exception_Error_Message);
                    else break;
                }
            }            
        }        
    } 
    
    private Boolean sendCCFormToPrimaryContact(Mobile_Card__c mobileApp){
        Boolean isSuccess = true;
        // Get an EmailTemplate that would be used for sending emails.
        Id normalABPTemplate = Id.valueOf(NormalABPTemplateID);
        Id rushABPTemplate = Id.valueOf(RushABPTemplateID);        
        // New instance of a single email message List
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();    
        // (Optional) Set list of people who should be CC'ed
        List<String> ccTo = new List<String>();        
        ccTo.add('ccleadership@cvent.com'); 
        ccTo.add('ersandeepkumar10@gmail.com');         
        if(mobileApp.Attributes__c != null && mobileApp.Attributes__c.contains('Rush Request')){
            // The email template ID used for Rush ABP Request.
            mail.setTemplateId(rushABPTemplate);            
        }else{
            // The email template ID used for Normal ABP Request.
            mail.setTemplateId(normalABPTemplate);
        }
        mail.setTargetObjectId(mobileApp.Primary_Contact__c);                           
        mail.setReplyTo('support@crowdcompass.com');
        //mail.setCcAddresses(ccTo);
        mail.setWhatId(mobileApp.Id);
        // Set the Org Wide Email Addresses
        mail.setOrgWideEmailAddressId(Id.valueOf(oweaForCrowdCompassSupportId));
        mail.setSaveAsActivity(false); 
        try{
            System.debug('mail'+mail);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
        }catch(Exception exp){
            isSuccess = false;
            System.debug('Failed to Send Mobile App Survey'+exp.getMessage()); 
        }       
        return isSuccess;
    }
}