objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Event_Contact_Status__c</fullName>
        <label>Event Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Suspect</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Marketing Qualified</fullName>
                </value>
                <value>
                    <fullName>Marketing Researched</fullName>
                </value>
                <value>
                    <fullName>Sales Accepted</fullName>
                </value>
                <value>
                    <fullName>Sales Generated</fullName>
                </value>
                <value>
                    <fullName>Sales Qualified</fullName>
                </value>
                <value>
                    <fullName>Open Opportunity</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Recycle</fullName>
                </value>
                <value>
                    <fullName>Trash</fullName>
                </value>
                <value>
                    <fullName>SignUp</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Event Created</fullName>
                </value>
                <value>
                    <fullName>Event Launched</fullName>
                </value>
                <value>
                    <fullName>#N/A</fullName>
                    <isActive>false</isActive>
                    <label>#N/A</label>
                </value>
                <value>
                    <fullName>0</fullName>
                    <isActive>false</isActive>
                    <label>0</label>
                </value>
                <value>
                    <fullName>A - New Contact</fullName>
                    <isActive>false</isActive>
                    <label>A - New Contact</label>
                </value>
                <value>
                    <fullName>A - New Lead</fullName>
                    <isActive>false</isActive>
                    <label>A - New Lead</label>
                </value>
                <value>
                    <fullName>Akshay Doshi</fullName>
                    <isActive>false</isActive>
                    <label>Akshay Doshi</label>
                </value>
                <value>
                    <fullName>Alesha Lorca</fullName>
                    <isActive>false</isActive>
                    <label>Alesha Lorca</label>
                </value>
                <value>
                    <fullName>Amanda Zeile</fullName>
                    <isActive>false</isActive>
                    <label>Amanda Zeile</label>
                </value>
                <value>
                    <fullName>Arvind Kumar</fullName>
                    <isActive>false</isActive>
                    <label>Arvind Kumar</label>
                </value>
                <value>
                    <fullName>Attended</fullName>
                    <isActive>false</isActive>
                    <label>Attended</label>
                </value>
                <value>
                    <fullName>B - Working</fullName>
                    <isActive>false</isActive>
                    <label>B - Working</label>
                </value>
                <value>
                    <fullName>Ben Gambhir</fullName>
                    <isActive>false</isActive>
                    <label>Ben Gambhir</label>
                </value>
                <value>
                    <fullName>Brittany Jennings</fullName>
                    <isActive>false</isActive>
                    <label>Brittany Jennings</label>
                </value>
                <value>
                    <fullName>C - Qualified</fullName>
                    <isActive>false</isActive>
                    <label>C - Qualified</label>
                </value>
                <value>
                    <fullName>Christopher Condley</fullName>
                    <isActive>false</isActive>
                    <label>Christopher Condley</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <description>For Sales Team</description>
        <label>Sales</label>
    </recordTypes>
</CustomObject>

classes/TestDataFactory.cls
/**=====================================================================
* Cvent
* Name: TestDataFactory 
* Description: It will create a common Test Record for all the Test Classes.
* Created Date: [22/07/2016]
* Created By: Hemant Rana
* 
* Date Modified                Modified By                  Description of the update
* [MON DD, YYYY]               [FirstName LastName]         [Short description for changes]
=====================================================================*/ 

@isTest
public class TestDataFactory {
    @testSetup public static void createTestRecord() {
        Integer numAccts=2; Integer numConPerAccts=4;Integer numTaskPerConts=3;

        //Inserting User...............
        Profile p = [SELECT Id FROM Profile WHERE Name='Finance - Management']; 

        USerrole[] testroleId=[select id from userRole where name ='AM (Event)' OR name ='Pre Sales - Special Projects' limit 2];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Sops', LanguageLocaleKey='en_US', FirstName='TestUser',
        LocaleSidKey='en_US', ProfileId = p.Id, userRoleId=testroleId[0].id,
        TimeZoneSidKey='America/Los_Angeles', UserName='Test'+'deploymentuser@cvent.com');
        
        User u1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Sops', LanguageLocaleKey='en_US', FirstName='TestUser',
        LocaleSidKey='en_US', ProfileId = p.Id, userRoleId=testroleId[1].id,
        TimeZoneSidKey='America/Los_Angeles', UserName='TestIST'+'deploymentuser@cvent.com');
        
        system.runAs(u){
            //Insert Account
            List<Account> accts = new List<Account>();
            for(Integer i=0;i<numAccts;i++) {
                Account a = new Account(Name='TestAccount' + i);
                accts.add(a);
            }
            insert accts;
            //Insert Contact        
            List<Contact> contList = new List<Contact>();
            for (Integer j=0;j<numAccts;j++) {
                Account acct = accts[j];
                // For each account just inserted, add opportunities
                for (Integer k=0;k<numConPerAccts;k++) {
                    contList.add(new Contact(LastName=acct.Name + ' Contact ' + k,
                    AccountId=acct.Id,Event_Contact_Status__c='Marketing Qualified'));
                }
            }
            insert contList;
            //Insert Task
            List<Task> taskList = new List<Task>();
            for (Integer j=0;j<numConPerAccts;j++) {
                Contact cont = contList[j];
                // For each account just inserted, add opportunities
                for (Integer k=0;k<numTaskPerConts;k++) {
                    taskList.add(new Task(Subject=cont.LastName + ' Marketing Qualified ' + k,OwnerId=u.Id,
                    WhoId=cont.Id));
                    taskList.add(new Task(Subject=cont.LastName + ' Marketing Qualified OD-CC ' + k,OwnerId=u.Id,
                    WhoId=cont.Id));
                    taskList.add(new Task(Subject=cont.LastName + ' Marketing Qualified OD-CC ' + k,OwnerId=u.Id,
                    WhoId=cont.Id,Product__c='Cvent Connect',Status='Completed'));
                    taskList.add(new Task(Subject=cont.LastName + ' Marketing Qualified OD-CC ' + k,OwnerId=u.Id,
                    WhoId=cont.Id,Product__c='Cvent Connect;Diamonds',Status='Completed'));
                }
            }
            insert taskList;
        }
        //Inserting new Task with different OWNER Id
        system.runAs(u1){
            //Insert Account
            List<Account> accts = new List<Account>();
            for(Integer i=0;i<numAccts;i++) {
                Account a = new Account(Name='TestAccount' + i);
                accts.add(a);
            }
            insert accts;
            //Insert Contact        
            List<Contact> contList = new List<Contact>();
            for (Integer j=0;j<numAccts;j++) {
                Account acct = accts[j];
                // For each account just inserted, add opportunities
                for (Integer k=0;k<numConPerAccts;k++) {
                    contList.add(new Contact(LastName=acct.Name + ' Contact ' + k,
                    AccountId=acct.Id,Event_Contact_Status__c='Marketing Qualified'));
                }
            }
            insert contList;
            //Insert Task
            List<Task> taskList = new List<Task>();
            for (Integer j=0;j<numConPerAccts;j++) {
                Contact cont = contList[j];
                // For each account just inserted, add opportunities
                for (Integer k=0;k<numTaskPerConts;k++) {
                    taskList.add(new Task(Subject=cont.LastName + ' Marketing Qualified ' + k,OwnerId=u1.Id,
                    WhoId=cont.Id));
                    taskList.add(new Task(Subject=cont.LastName + ' Marketing Qualified OD-CC ' + k,OwnerId=u1.Id,
                    WhoId=cont.Id,Status='Completed'));
                    taskList.add(new Task(Subject=cont.LastName + ' Marketing Qualified OD-CC ' + k,OwnerId=u1.Id,
                    WhoId=cont.Id,Product__c='Cvent Connect',Status='Completed'));
                    taskList.add(new Task(Subject=cont.LastName + ' Marketing Qualified OD-CC ' + k,OwnerId=u1.Id,
                    WhoId=cont.Id,Product__c='Cvent Connect;Diamonds',Status='Completed'));
                }
            }
            insert taskList;
        }
    }
}