objects/CpqAudit__c.object
<CustomObject>
    <fields>
        <fullName>chainMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>chainMaster</label>
        <referenceTo>CpqAudit__c</referenceTo>
        <relationshipLabel>CPQ Audit Records (Contracting Reports)</relationshipLabel>
        <relationshipName>Cpq_Audit_Records3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>exceptionOccurred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>exceptionOccurred</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isQuoteSchedulableMaster__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isQuoteSchedulableMaster</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>processingInformation__c</fullName>
        <label>processingInformation</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>quoteCurrentYear__c</fullName>
        <formula>quote__r.Current_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>quoteCurrentYear</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>quoteFinalYear__c</fullName>
        <formula>VALUE(TEXT(quote__r.Contract_Term_Years__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>quoteFinalYear</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>quoteIsVariableOptions__c</fullName>
        <formula>IF(

OR(ISNULL(quote__c),ISBLANK(quote__c)),

contract__r.Multiple_Years_Commitment__c,

quote__r.Multiple_Years_Commitment__c

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>quoteIsVariableOptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>quoteJobMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>quoteJobMaster</label>
        <referenceTo>CpqAudit__c</referenceTo>
        <relationshipLabel>Cpq Audit Records (quoteJobMaster)</relationshipLabel>
        <relationshipName>Cpq_Audit_Records2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>quoteStatusCheckCount__c</fullName>
        <formula>quote__r.statusCheckCount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>quoteStatusCheckCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>quoteType__c</fullName>
        <formula>TEXT(quote__r.SBQQ__Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>quoteType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Cpq Audit Records</relationshipLabel>
        <relationshipName>Cpq_Audit_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CPQ Audit</label>
    <nameField>
        <label>CpqAudit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Audit Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CventMyd_CpqAuditTriggerHandler.cls
public without sharing class CventMyd_CpqAuditTriggerHandler {
    
    public static void handleBeforeInsert() {

        Map<Id,SBQQ__Quote__c> renewalQuoteMap = new Map<Id,SBQQ__Quote__c>();

        Map<Id,SBQQ__Quote__c> amendmentQuoteMap = new Map<Id,SBQQ__Quote__c>();

        Integer statusCheckMax = CventMyd_Settings.renewalGenerationSettings.statusChecksPerQuote;

        Boolean inRenewalSchedulable = (CventMyd_AutoRenewContractSchedulable.firstJobOfChain != null);

        Boolean firstJobOfChain = CventMyd_AutoRenewContractSchedulable.firstJobOfChain;

        Boolean inQuoteSchedulableChain = (CventMyd_QuoteSchedulable.renewalChainMasterId != null);

        Boolean inChain = (inQuoteSchedulableChain || inRenewalSchedulable);

        Id renewalChainMasterId = CventMyd_AutoRenewContractSchedulable.renewalChainMasterId;

        renewalChainMasterId = (renewalChainMasterId != null) ? renewalChainMasterId : CventMyd_QuoteSchedulable.renewalChainMasterId ;

        Integer chainLinkNumber = (CventMyd_AutoRenewContractSchedulable.chainJobNumber != null) ? CventMyd_AutoRenewContractSchedulable.chainJobNumber : -1 ;

        Boolean chainFinishedInQuote = (CventMyd_QuoteSchedulable.chainFinished != null) ? CventMyd_QuoteSchedulable.chainFinished : false;

        Boolean chainFinishedInRenewal =  (CventMyd_AutoRenewContractSchedulable.chainFinished != null) ? CventMyd_AutoRenewContractSchedulable.chainFinished : false;

        Boolean chainFinished = (chainFinishedInQuote || chainFinishedInRenewal);        

        for(CpqAudit__c auditRecord : (List<CpqAudit__c>)Trigger.new) {

            auditRecord.chainMaster__c = (renewalChainMasterId != null) ? renewalChainMasterId : auditRecord.chainMaster__c;

            SBQQ__Quote__c quote = new SBQQ__Quote__c (

                Current_Year__c = auditRecord.quoteCurrentYear__c,

                Contract_Term_Years__c = String.valueOf(auditRecord.quoteFinalYear__c),

                SBQQ__Type__c = auditRecord.quoteType__c,

                Multiple_Years_Commitment__c = auditRecord.quoteIsVariableOptions__c,

                Id = auditRecord.quote__c

            );

            Boolean recordLock = (auditRecord.processingInformation__c != null) ? auditRecord.processingInformation__c.contains('UNABLE_TO_LOCK_ROW') : false;

            Boolean quotesFinishedInChain = (auditRecord.processingInformation__c != null) ? auditRecord.processingInformation__c.contains('no more quotes to process') : false;

            Boolean exceptionOccurred = auditRecord.exceptionOccurred__c;

            Boolean statusChecksRemaining = (auditRecord.quoteStatusCheckCount__c < statusCheckMax);

            statusChecksRemaining = (chainFinishedInQuote) ? true : statusChecksRemaining;

            Boolean isQuoteMaster = auditRecord.isQuoteSchedulableMaster__c;
            
            if(statusChecksRemaining && (inChain || recordLock || !exceptionOccurred) && !isQuoteMaster && !quotesFinishedInChain) {

                if(auditRecord.quoteType__c == 'Renewal') {

                    renewalQuoteMap.put(quote.Id,quote);

                }

                else if (auditRecord.quoteType__c == 'Amendment' && auditRecord.quoteIsVariableOptions__c) {

                    amendmentQuoteMap.put(quote.Id,quote);

                }

            }

        }

        Integer renewalCount = renewalQuoteMap.keySet().size();

        Boolean isEvenJobNumber = (Math.mod(chainLinkNumber,2) == 0);

        Boolean scheduleFromChain = ( isEvenJobNumber || chainFinished && inQuoteSchedulableChain || !isEvenJobNumber && chainFinished );

        if( renewalCount > 0 && (!inChain || scheduleFromChain) ) {

            CpqAudit__c renewalJobAuditRecord = new CpqAudit__c(Name = 'Renewal Quote Job Master @ ' + DateTime.now(), isQuoteSchedulableMaster__c = true);

            renewalJobAuditRecord.chainMaster__c = renewalChainMasterId;

            insert renewalJobAuditRecord;

            Boolean quoteInsertion = false;

            Boolean lastStatusCheck = false;

            for(CpqAudit__c auditRecord : (List<CpqAudit__c>)Trigger.new) {

                if(auditRecord.quoteType__c == 'Renewal') {

                    auditRecord.quoteJobMaster__c = renewalJobAuditRecord.Id;

                    if(auditRecord.Name.containsIgnoreCase('insertion')) {

                        quoteInsertion = true;

                    }

                    if(auditRecord.quoteStatusCheckCount__c == statusCheckMax - 1) {

                        lastStatusCheck = true;

                    }

                }

            }

            Integer secondsBeforeJobStart = (quoteInsertion) ? CventMyd_Settings.renewalGenerationSettings.secondsBeforeFirstQuoteJob : CventMyd_Settings.renewalGenerationSettings.secondsBetweenQuoteJobs;

            inRenewalSchedulable = CventMyd_QuoteSchedulable.renewalChainMasterId != null;

            if(!inChain && lastStatusCheck) {

                secondsBeforeJobStart = CventMyd_Settings.renewalGenerationSettings.secondsBeforeLastQuoteJob;

            }

            else if(inChain) {

                secondsBeforeJobStart = (firstJobOfChain != null && firstJobOfChain) ? CventMyd_Settings.renewalGenerationSettings.secondsBeforeFirstQuoteJob : CventMyd_Settings.renewalGenerationSettings.secondsBetweenQuoteJobs ;

                if(chainFinished && inQuoteSchedulableChain) {

                    secondsBeforeJobStart = 10;

                }

            }

            String renewalCronString = CventMyd_UtilityMethods.getCronString(secondsBeforeJobStart);            

            String renewalJobName = renewalJobAuditRecord.name + ', Id: ' + renewalJobAuditRecord.Id;

            renewalJobAuditRecord.Name = renewalJobName;

            update renewalJobAuditRecord;

            CventMyd_QuoteSchedulable renewalQuoteSchedulable = new CventMyd_QuoteSchedulable(renewalQuoteMap.keySet(),renewalJobName,renewalJobAuditRecord.Id);

            System.schedule(renewalJobName,renewalCronString,renewalQuoteSchedulable);

        }

    }

}