objects/CRM_Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Effort_Hours__c</fullName>
        <label>Actual Effort (Hours)</label>
        <summarizedField>CRM_Project_Item__c.Actual_Effort_Hours__c</summarizedField>
        <summaryForeignKey>CRM_Project_Item__c.CRM_Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CRM_Release__c</fullName>
        <label>Release</label>
        <referenceTo>ResourceProject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>CRM_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Identifies the related Case# if there is one</description>
        <inlineHelpText>Identifies the related Case# if there is one</inlineHelpText>
        <label>Case #</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Estimated_Effort_Hours__c</fullName>
        <label>Estimated Effort (Hours)</label>
        <summarizedField>CRM_Project_Item__c.Estimated_Effort_Hours__c</summarizedField>
        <summaryForeignKey>CRM_Project_Item__c.CRM_Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Team__c</fullName>
        <label>Project Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRM Management</fullName>
                    <default>true</default>
                    <label>CRM Management</label>
                </value>
                <value>
                    <fullName>SOPS</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business User who originally requested for this project</description>
        <inlineHelpText>Business User who originally requested for this project</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Requirements</fullName>
                </value>
                <value>
                    <fullName>Waiting for Response</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deferred - Requirements Changed</fullName>
                </value>
                <value>
                    <fullName>Deferred - Dev Incomplete</fullName>
                </value>
                <value>
                    <fullName>Deferred - UAT Incomplete</fullName>
                </value>
                <value>
                    <fullName>Ready For UAT</fullName>
                </value>
                <value>
                    <fullName>UAT Sign Off Received</fullName>
                </value>
                <value>
                    <fullName>Deployed</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Requirement Complete</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
                <value>
                    <fullName>Dependancy on Refactoring</fullName>
                </value>
                <value>
                    <fullName>Partially Deployed - Data Updates Still Pending</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Ready for QA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UAT_Start_Date__c</fullName>
        <formula>CRM_Release__r.UAT_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UAT Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Project #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ResourceProject__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Effort_Hours__c</fullName>
        <label>Actual Effort (Hours)</label>
        <summarizedField>CRM_Project__c.Actual_Effort_Hours__c</summarizedField>
        <summaryForeignKey>CRM_Project__c.CRM_Release__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Deployment_Date__c</fullName>
        <label>Deployment Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Effort_Hours__c</fullName>
        <label>Estimated Effort (Hours)</label>
        <summarizedField>CRM_Project__c.Estimated_Effort_Hours__c</summarizedField>
        <summaryForeignKey>CRM_Project__c.CRM_Release__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Release Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_Type__c</fullName>
        <label>Release Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
                <value>
                    <fullName>Emergency/Out of Cycle</fullName>
                </value>
                <value>
                    <fullName>Patch/Bug Fix</fullName>
                </value>
                <value>
                    <fullName>Non CRM team</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UAT_Sign_Off_Date__c</fullName>
        <label>UAT Sign Off Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UAT_Start_Date__c</fullName>
        <label>UAT Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>of_Projects_Sign_Off_Received__c</fullName>
        <inlineHelpText># of projects with status 'UAT Sign Off Received'</inlineHelpText>
        <label># of Projects (Sign Off Received)</label>
        <summaryFilterItems>
            <field>CRM_Project__c.Status__c</field>
            <operation>equals</operation>
            <value>UAT Sign Off Received</value>
        </summaryFilterItems>
        <summaryForeignKey>CRM_Project__c.CRM_Release__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>of_projects_total__c</fullName>
        <label># of Projects (Total)</label>
        <summaryForeignKey>CRM_Project__c.CRM_Release__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CRM_EmailComponentController.cls
/*
 * Class Name: CRM_EmailComponentController
 * Description: This class acts as the shared controller for VF Components "CRM_EmailComponent" and "CRM_EmailComponentRelease"
 * 
 * 
 *  History:
 *  Date            Version     Change/Description                          Author
 * -------------------------------------------------------------------------------------------
 *  May 3, 2016     1.0         Created                                     Praveen Kaushik
 * -------------------------------------------------------------------------------------------
*/
public without sharing class CRM_EmailComponentController {
    public String releaseIdCtrl;
    public String requestorIdCtrl;
    public Boolean readyForUATCtrl;
    public String projectStatusCtrl;
    
    public void setReleaseIdCtrl(string val){
        releaseIdCtrl = val;
    }
    public String getReleaseIdCtrl(){
        return releaseIdCtrl;
    }
    
    public void setRequestorIdCtrl(string val){
        requestorIdCtrl = val;
    }
    public String getRequestorIdCtrl(){
        return requestorIdCtrl;
    }

    public void setReadyForUATCtrl(boolean val){
        readyForUATCtrl = val;
    }
    public boolean getReadyForUATCtrl(){
        return readyForUATCtrl;
    }
    
    public void setProjectStatusCtrl(string val){
        projectStatusCtrl = val;
    }
    public String getProjectStatusCtrl(){
        return projectStatusCtrl;
    }
    
    public CRM_EmailComponentController() {
    }

    public List<CRM_Project__c> getProjects() {
        List<CRM_Project__c> projects = [select Id, Name, Project_Team__c, Status__c, CRM_Release__c, Case__c, Actual_Effort_Hours__c, Project_Name__c, Description__c, Estimated_Effort_Hours__c, Requestor__r.FirstName, Requestor__r.LastName  from CRM_Project__c where CRM_Release__c =: releaseIdCtrl];
        if(projectStatusCtrl != null){
            if(requestorIdCtrl != null) {
                projects = [select Id, Name, Project_Team__c, Status__c, CRM_Release__c, Case__c, Actual_Effort_Hours__c, Project_Name__c, Description__c, Estimated_Effort_Hours__c, Requestor__r.FirstName, Requestor__r.LastName  from CRM_Project__c where CRM_Release__c =: releaseIdCtrl and Status__c =: projectStatusCtrl and Requestor__c =: requestorIdCtrl];
            } else {
                projects = [select Id, Name, Project_Team__c, Status__c, CRM_Release__c,  Case__c, Actual_Effort_Hours__c, Project_Name__c, Description__c, Estimated_Effort_Hours__c, Requestor__r.FirstName, Requestor__r.LastName  from CRM_Project__c where CRM_Release__c =: releaseIdCtrl and Status__c =: projectStatusCtrl];                
            }
        } else {
            if(requestorIdCtrl != null) {
                projects = [select Id, Name, Project_Team__c, Status__c, CRM_Release__c, Case__c, Actual_Effort_Hours__c, Project_Name__c, Description__c, Estimated_Effort_Hours__c, Requestor__r.FirstName, Requestor__r.LastName  from CRM_Project__c where CRM_Release__c =: releaseIdCtrl and Requestor__c =: requestorIdCtrl];
            }
        }
        return projects;
    }

    
    public ResourceProject__c getCRMRelease(){
        List<ResourceProject__c> releases = [select Id, UAT_Sign_Off_Date__c, UAT_Start_Date__c, Deployment_Date__c, Release_Type__c, Estimated_Effort_Hours__c, of_projects_total__c, of_Projects_Sign_Off_Received__c from ResourceProject__c where id =:releaseIdCtrl];
        return releases.size() > 0 ? releases[0] : null;
    }
}