objects/CRM_Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Project #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cvent_Email_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <description>Predefined Subject if Any</description>
        <inlineHelpText>Predefined Subject if Any</inlineHelpText>
        <label>Email Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placeholder_Attribute_1__c</fullName>
        <description>Placeholder 1 - Use this for any value you want to use as part of Email Template or Workflow Condition. For Release Management; we are using this placeholder to store the Release Name</description>
        <inlineHelpText>Placeholder 1 - Use this for any value you want to use as part of Email Template or Workflow Condition. For Release Management; we are using this placeholder to store the Release Name</inlineHelpText>
        <label>Placeholder Attribute 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placeholder_Attribute_2__c</fullName>
        <description>Placeholder 2 - Use this for any value you want to use as part of Email Template or Workflow Condition.</description>
        <inlineHelpText>Placeholder 2 - Use this for any value you want to use as part of Email Template or Workflow Condition.</inlineHelpText>
        <label>Placeholder Attribute 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Email__c</fullName>
        <description>Email address for the intended recipient</description>
        <inlineHelpText>Email address for the intended recipient</inlineHelpText>
        <label>Recipient Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Recipient_Name__c</fullName>
        <description>Full Name for the Recipient</description>
        <inlineHelpText>Full Name for the Recipient</inlineHelpText>
        <label>Recipient Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_User_Id__c</fullName>
        <label>Recipient User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object_API_Name__c</fullName>
        <description>Provide the Object API Name for the source record</description>
        <inlineHelpText>Provide the Object API Name for the source record</inlineHelpText>
        <label>Source Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Process__c</fullName>
        <description>Identify the source process for which this notification is generated</description>
        <inlineHelpText>Identify the source process for which this notification is generated</inlineHelpText>
        <label>Source Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ReleaseManagement</fullName>
                </value>
                <value>
                    <fullName>AccountTeamAssignment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Record_Id__c</fullName>
        <description>Identifies the source record for which this email is being generated. This could be used in advanced VF templates to pull more information about the source record</description>
        <inlineHelpText>Identifies the source record for which this email is being generated. This could be used in advanced VF templates to pull more information about the source record</inlineHelpText>
        <label>Source Record Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Time__c</fullName>
        <description>Use this field to schedule time based notifications</description>
        <inlineHelpText>Use this field to schedule time based notifications</inlineHelpText>
        <label>Trigger Time</label>
        <type>DateTime</type>
    </fields>
    <description>This object is a custom framework to send out email notifications for objects that are not supported otherwise for workflow email alerts. For example; Account Team
Any record created in this object should trigger an email alert (using native workflow) using the Recipient and Subject information. A batch job would purge this object for all records created as of Yesterday.</description>
    <label>Cvent Email Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Cvent Email Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Email Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CventEmailNotificationHelper.cls
/*
 * Class Name: CventEmailNotificationHelper
 * Description: This class is at the core of the Custom Email Notification framework. It run in admin context and provides for the helper methods to create and insert record(s)
 *              in the Email Notification object.
 *              Cvent Email Notification framework is developed to support email notifications (can also configure field updates, task creation using the same native rules) for 
 *              1) Objects like Account Team that doesn't provide for native workflow email alerts
 *              2) Custom/Special use cases where a personalized email is to be sent out based on derived values. Example: Release Management 
 *              
 *              The framework comprises of  
 *              - Custom Object "Cvent Email Notification": Any record created in this object should trigger an email alert (using native workflow on this object) using 
 *                the Recipient and Subject information. It also supports Time Based notification based on the date field "Trigger_Time__c"
 *              - Class "CventEmailNotificationHelper": Provides helper methods to support DML on custom object
 *              - Class "Batch_PurgeCventEmailNotification": Batch job to purge all expired notification records (records created as of yesterday and (Trigger_Time__c is null or elapsed))
 *              - Class "Scheduler_Batch_PurgeCventEmailNotification": Scheduler class to schedule the purge batch job
 *              - Class "Test_CventEmailNotificationFramework": Testcases and related coverage for all components in this framework
 *              
 *              Sample snippet to create a notification record using this helper class:
 *              CventEmailNotificationHelper.insertEmailNotification('005o0000002QrNR','Praveen Kaushik', 'Test 1', 'pkaushik@cvent.com', CventEmailNotificationHelper.SourceProcessName.ReleaseManagement, null, 'CRM_Project__c', 'aAE7A0000008OLT', null, null);
 * 
 *  History:
 *  Date            Version     Change/Description                          Author
 * -------------------------------------------------------------------------------------------
 *  April 27, 2016  1.0         Created                                     Praveen Kaushik
 * -------------------------------------------------------------------------------------------
*/
public without sharing class CventEmailNotificationHelper {
    /* Custom Exception Class for this Framework */
    public class NotificationFrameworkException extends Exception {}
    
    public static boolean isEmailSent = false;
    
    /* Enum to enforce valid values for Source Process Name */
    public enum SourceProcessName {ReleaseManagement, AccountTeamAssignment, Other}

    /* Initializes and Returns a new Cvent_Email_Notification__c record */
    public static Cvent_Email_Notification__c createEmailNotification() {
        Cvent_Email_Notification__c notification = new Cvent_Email_Notification__c();
        return notification;
    }
    
    /* Initializes and Returns a new Cvent_Email_Notification__c record. The caller has the responsibility to insert the newly initialized record */
    public static Cvent_Email_Notification__c createEmailNotification(String recipeintId, String recipientName, String emailSubject, String emailAddress, SourceProcessName processName, 
                                                                            Datetime triggerTime, String sourceRecordId, String objectAPIName,  String attribute1, String attribute2, String releaseName) {
        if(isBlank(emailAddress)){
            throw new NotificationFrameworkException('A valid email address is required.');
        }
        Cvent_Email_Notification__c notification = createEmailNotification();
        notification.Recipient_User_Id__c = recipeintId;
        notification.Recipient_Name__c = recipientName;
        notification.Email_Subject__c = emailSubject;
        notification.Recipient_Email__c = emailAddress;
        notification.Source_Process__c = processName.name();
        notification.Source_Object_API_Name__c = objectAPIName;
        notification.Source_Record_Id__c = sourceRecordId;
        notification.Placeholder_Attribute_1__c = attribute1 != null ? attribute1 : '';
        notification.Placeholder_Attribute_2__c = attribute2 != null ? attribute2 : '';
        notification.Trigger_Time__c = triggerTime != null ? triggerTime : null;
        notification.Release__c = releaseName;
        return notification;
    }

    /* Inserts a new Cvent_Email_Notification__c record. This is different from createEmailNotification which only initializes the record */
    public static Cvent_Email_Notification__c insertEmailNotification(String recipeintId, String recipientName, String emailSubject, String emailAddress, SourceProcessName processName, 
                                                                            Datetime triggerTime, String sourceRecordId, String objectAPIName,  String attribute1, String attribute2, String releaseName) {
        Cvent_Email_Notification__c notification = createEmailNotification(recipeintId, recipientName, emailSubject, emailAddress, processName, triggerTime, sourceRecordId, objectAPIName, attribute1, attribute2,releaseName);
        insert notification;
        return notification;
    }
    
    /* Returns true if the string passed as parameter is either NULL or BLANK */
    private static boolean isBlank(String strValue){
        return (strValue == null || String.isBlank(strValue));
    }
    
    
}