objects/CRM_Help__c.object
<CustomObject>
    <label>CRM Help</label>
    <nameField>
        <displayFormat>CRM-{0000}</displayFormat>
        <label>CRM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM Help</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_Article__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Help__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM Help</label>
        <referenceTo>CRM_Help__c</referenceTo>
        <relationshipLabel>Salesforce Articles</relationshipLabel>
        <relationshipName>Salesforce_Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Salesforce Articles</relationshipLabel>
        <relationshipName>Salesforce_Articles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Salesforce Article</label>
    <nameField>
        <displayFormat>SFA-{0000000}</displayFormat>
        <label>Article Attachment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Articles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CRMHelpDetailController.cls
public class CRMHelpDetailController{
    public List<Attachment> crmAttachment{get;set;}
    public Id caseId{get;set;}
    public Id helpId{get;set;}
    public Boolean showSuccessMessage{get;set;}
    public CRMHelpDetailController(ApexPages.StandardController controller) {
        showSuccessMessage = false;
        if(ApexPages.currentPage().getParameters().get('caseId') != null)
            caseId = ApexPages.currentPage().getParameters().get('caseId');
        if(ApexPages.currentPage().getParameters().get('id') != null)
            helpId = apexpages.currentpage().getparameters().get('id');
        System.debug('caseId*****'+caseId);
        crmAttachment = new List<Attachment>();
        crmAttachment = [SELECT Id,Name FROM Attachment WHERE ParentId = :helpId];
        System.debug('crmAttachment*****'+crmAttachment );
    }

    public void attachCase(){
        Integer sfRec = [SELECT count() FROM Salesforce_Article__c WHERE Case_Number__c = : caseId AND CRM_Help__c =:helpId];
        if(sfRec==0){
            showSuccessMessage = true;
            Salesforce_Article__c salesforceArticleObject = new Salesforce_Article__c();
            salesforceArticleObject.Case_Number__c = caseId;
            salesforceArticleObject.CRM_Help__c = helpId;
            insert salesforceArticleObject;
        }
        else{
            showSuccessMessage = true;
        }
    }
   
}