objects/CRM_Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Requirements</fullName>
                </value>
                <value>
                    <fullName>Waiting for Response</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deferred - Requirements Changed</fullName>
                </value>
                <value>
                    <fullName>Deferred - Dev Incomplete</fullName>
                </value>
                <value>
                    <fullName>Deferred - UAT Incomplete</fullName>
                </value>
                <value>
                    <fullName>Ready For UAT</fullName>
                </value>
                <value>
                    <fullName>UAT Sign Off Received</fullName>
                </value>
                <value>
                    <fullName>Deployed</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Requirement Complete</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
                <value>
                    <fullName>Dependancy on Refactoring</fullName>
                </value>
                <value>
                    <fullName>Partially Deployed - Data Updates Still Pending</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Ready for QA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Project #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CRMProjAgeSetting__c.object
<CustomObject>
    <fields>
        <fullName>StatusField__c</fullName>
        <label>Status Field API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>CRM Project Aging</label>
</CustomObject>

classes/CRMProjectAgingBatch.cls
/** Author - Shanu Aggarwal
*** Added on - 03/01/2018
*** Batch process to update the aging of projects
***/

global class CRMProjectAgingBatch implements Database.Batchable<sObject>, Schedulable{


    global Database.querylocator start(Database.BatchableContext BC){
        
        
        //Get status fields from custom setting 
        String statusFields = ' ';
        for(CRMProjAgeSetting__c setting : CRMProjAgeSetting__c.getAll().values()){
            statusFields += setting.StatusField__c+',';
        }
        statusFields = statusFields.removeEnd(',');

        //Get Status filters
        Set<String> statusFilter = CRMProjAgeSetting__c.getAll().keySet();

        return Database.getQueryLocator('Select Status__c, ' + statusFields + ' From CRM_Project__c Where Status__c IN:statusFilter');
    }
    
    global void execute(Database.BatchableContext BC, List<CRM_Project__c> scope){
        
        List<CRM_Project__c> updateProjList = new List<CRM_Project__c> ();
        Map<String,CRMProjAgeSetting__c> statusVsField = CRMProjAgeSetting__c.getAll();
        String fieldApiName;

        for(CRM_Project__c currentProj : scope){
            //Current project status stored in custom setting 
            if(statusVsField.containsKey(currentProj.Status__c)){    
                CRM_Project__c project = new CRM_Project__c();
                project.Id = currentProj.Id;
                
                //Get the Field API based on Status
                fieldApiName = statusVsField.get(currentProj.Status__c).StatusField__c;

                //increment the existing count 
                if(currentProj.get(fieldApiName)!=null){
                    project.put(fieldApiName,Integer.valueOf(currentProj.get(fieldApiName))+1);
                }else{
                    project.put(fieldApiName,1);
                }


                updateProjList.add(project);
    
            }
        }
        if(updateProjList.size()>0)
            update updateProjList;

        
    }
    global void finish(Database.BatchableContext BC){
        
    }
    
    global void execute(SchedulableContext SC) {
        Database.executeBatch(new CRMProjectAgingBatch(),200);
    }
}