objects/CRM_Help__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPQ</fullName>
                </value>
                <value>
                    <fullName>FinancialForce</fullName>
                </value>
                <value>
                    <fullName>Troubleshooting</fullName>
                </value>
                <value>
                    <fullName>DocuSign</fullName>
                </value>
                <value>
                    <fullName>EBS</fullName>
                </value>
                <value>
                    <fullName>Core Processes</fullName>
                </value>
                <value>
                    <fullName>Multi Currency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <description>Please input a brief description of Issue.</description>
        <label>Issue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Keywords__c</fullName>
        <label>Keywords</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Renewals</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Output Document</fullName>
                </value>
                <value>
                    <fullName>CPQ Batch Jobs</fullName>
                </value>
                <value>
                    <fullName>Contact Roles</fullName>
                </value>
                <value>
                    <fullName>State and Country Picklist Schema</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>CRM Help</label>
    <nameField>
        <displayFormat>CRM-{0000}</displayFormat>
        <label>CRM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM Help</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_Article__c.object
<CustomObject>
    <fields>
        <fullName>CRM_Help__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRM Help</label>
        <referenceTo>CRM_Help__c</referenceTo>
        <relationshipLabel>Salesforce Articles</relationshipLabel>
        <relationshipName>Salesforce_Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Salesforce Articles</relationshipLabel>
        <relationshipName>Salesforce_Articles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Salesforce Article</label>
    <nameField>
        <displayFormat>SFA-{0000000}</displayFormat>
        <label>Article Attachment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Articles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CRMHelp_ControllerTest.cls
@isTest
public class CRMHelp_ControllerTest{

    public static testMethod void testMyController() {
        
        Case caseRec = new Case();
        caseRec.Subject = 'Test';
        insert caseRec;
        
        CRM_Help__c crmObj = new CRM_Help__c();
        crmObj.Category__c = 'CPQ';
        crmObj.Issue__c = 'CPQ';
        crmObj.Keywords__c = 'CPQ';
        crmObj.Process__c= 'Opportunity';
        crmObj.Resolution__c= 'CPQ';
        
        
        insert crmObj;
        
        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = crmObj.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        
        PageReference pageRef = Page.CRMHelp;
        Test.setCurrentPage(pageRef);
      
        CRMHelp_Controller controller = new CRMHelp_Controller();
        

        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('subject', 'CPQ');
        List<List<SObject>> searchList = [FIND 'CPQ' IN ALL FIELDS RETURNING CRM_Help__c(Id,Category__c,Keywords__c,Resolution__c,Issue__c)];
  
        CRMHelp_Controller.searchArticle('CPQ');
        
        
        
        
        PageReference pref = Page.CRMHelpDetail;
        pref.getParameters().put('id',crmObj.id);
        pref.getParameters().put('caseId',caseRec.id);
        Test.setCurrentPage(pref);
        
        Salesforce_Article__c sfArticle = new Salesforce_Article__c();
        sfArticle.Case_Number__c = caseRec.Id;
        sfArticle.CRM_Help__c = crmObj.Id;
        insert sfArticle;
        
        ApexPages.StandardController con = new ApexPages.StandardController(crmObj);
        CRMHelpDetailController ext = new CRMHelpDetailController(con);
        ext.attachCase();
    }
}