objects/CRM_Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Effort_Hours__c</fullName>
        <label>Actual Effort (Hours)</label>
        <summarizedField>CRM_Project_Item__c.Actual_Effort_Hours__c</summarizedField>
        <summaryForeignKey>CRM_Project_Item__c.CRM_Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CRM_Release__c</fullName>
        <label>Release</label>
        <referenceTo>ResourceProject__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>CRM_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Estimated_Effort_Hours__c</fullName>
        <label>Estimated Effort (Hours)</label>
        <summarizedField>CRM_Project_Item__c.Estimated_Effort_Hours__c</summarizedField>
        <summaryForeignKey>CRM_Project_Item__c.CRM_Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Team__c</fullName>
        <label>Project Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRM Management</fullName>
                    <default>true</default>
                    <label>CRM Management</label>
                </value>
                <value>
                    <fullName>SOPS</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reporting_Process_Improvement_Automation__c</fullName>
        <label>Project Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project_Team__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Both (Admin/Dev)</fullName>
                </value>
                <value>
                    <fullName>Bug Fix/Maintenance</fullName>
                </value>
                <value>
                    <fullName>Data Governance</fullName>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>CPQ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requester_Department__c</fullName>
        <formula>Requestor__r.Department</formula>
        <label>Requester Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business User who originally requested for this project</description>
        <inlineHelpText>Business User who originally requested for this project</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Requirements</fullName>
                </value>
                <value>
                    <fullName>Waiting for Response</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Deferred - Requirements Changed</fullName>
                </value>
                <value>
                    <fullName>Deferred - Dev Incomplete</fullName>
                </value>
                <value>
                    <fullName>Deferred - UAT Incomplete</fullName>
                </value>
                <value>
                    <fullName>Ready For UAT</fullName>
                </value>
                <value>
                    <fullName>UAT Sign Off Received</fullName>
                </value>
                <value>
                    <fullName>Deployed</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Requirement Complete</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
                <value>
                    <fullName>Dependancy on Refactoring</fullName>
                </value>
                <value>
                    <fullName>Partially Deployed - Data Updates Still Pending</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Ready for QA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UAT_Start_Date__c</fullName>
        <formula>CRM_Release__r.UAT_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UAT Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Project #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CRM_Project_Item__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Effort_Hours__c</fullName>
        <label>Actual Effort (Hours)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the developer/support rep responsible to complete this activity</description>
        <inlineHelpText>Identifies the developer/support rep responsible to complete this activity</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRM_Project_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available_Hours__c</fullName>
        <formula>Estimated_Effort_Hours__c - Actual_Effort_Hours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Hours</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRM_Project__c</fullName>
        <description>Module/Project this work item is associated to</description>
        <inlineHelpText>Module/Project this work item is associated to</inlineHelpText>
        <label>CRM Project</label>
        <referenceTo>CRM_Project__c</referenceTo>
        <relationshipName>CRM_Project_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Effort_Hours__c</fullName>
        <label>Estimated Effort (Hours)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <formula>CRM_Project__r.Project_Owner__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Team__c</fullName>
        <formula>Text(CRM_Project__r.Project_Team__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Clarification</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Configuration</fullName>
                </value>
                <value>
                    <fullName>Reports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Work Item</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>Project Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ResourceProject__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Effort_Hours__c</fullName>
        <label>Actual Effort (Hours)</label>
        <summarizedField>CRM_Project__c.Actual_Effort_Hours__c</summarizedField>
        <summaryForeignKey>CRM_Project__c.CRM_Release__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Available_Hours__c</fullName>
        <formula>IF(
CONTAINS(Project_Name__c,"Minor"),
             (((10*No_of_Devs__c*6)-6)+((10*2.5*No_of_Admins__c)-2.5)),
             IF(
                 CONTAINS(Project_Name__c,"Major"),
                        (((8*No_of_Devs__c*6)-6)+((8*2.5*No_of_Admins__c)-2.5)),0         
             )

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deployment_Date__c</fullName>
        <label>Deployment Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Effort_Hours__c</fullName>
        <label>Estimated Effort (Hours)</label>
        <summarizedField>CRM_Project__c.Estimated_Effort_Hours__c</summarizedField>
        <summaryForeignKey>CRM_Project__c.CRM_Release__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Release Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_Type__c</fullName>
        <label>Release Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
                <value>
                    <fullName>Emergency/Out of Cycle</fullName>
                </value>
                <value>
                    <fullName>Patch/Bug Fix</fullName>
                </value>
                <value>
                    <fullName>Non CRM team</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UAT_Sign_Off_Date__c</fullName>
        <label>UAT Sign Off Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UAT_Start_Date__c</fullName>
        <label>UAT Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CRMProjectViewController.cls
public class CRMProjectViewController {

    public string assigneeName {get;set;}
    public Id releaseId {get;set;}
    public Id projectId {get;set;}
    public boolean showProjects {get;set;}
    List<ResourceProject__c> releaseList;
    
    public  string statusSelected {get;set;}
    public List<CRM_Project__c> projectList {get;set;}
    public Map<Id,ResourceProject__c> releaseMap {get;set;}
    Map<Id,List<CRM_Project_Item__c>> mapOfProjects;
    List<CRM_Project_Item__c> dataList;     
    
    
    public CRMProjectViewController(){  
        showProjects=false;
        statusSelected = '---All---';
        //Default value to current user
        assigneeName = UserInfo.getName();  
        
             
        releaseMap = new Map<Id,ResourceProject__c>([Select Id ,UAT_Start_Date__c,UAT_Sign_Off_Date__c ,Name,Release_Type__c,Estimated_Effort_Hours__c,Actual_Effort_Hours__c,Deployment_Date__c From ResourceProject__c 
        where Name like '%CRM%' AND ( Deployment_Date__c = THIS_MONTH OR Deployment_Date__c = LAST_N_MONTHS:2 OR Deployment_Date__c =NEXT_N_MONTHS:1 ) 
        Order by Deployment_Date__c DESC LIMIT 10]);
        
        releaseList =  releaseMap.values();
        if(!releaseMap.isEmpty()){
            releaseId = releaseList.get(0).Id;
        }
        //Default Value to Current Release
        for(ResourceProject__c  rl : releaseList){
    
            if(rl.Deployment_Date__c<System.today()){
                break;
            }
            releaseId =rl.Id;
        }
        
        RefereshProjects();
                   
    }
    
    //Get All Releases 
    public List<SelectOption> getReleases(){
        
        List<SelectOption> options = new List<SelectOption>();
        
        for(ResourceProject__c release : releaseList ){
            options.add(new SelectOption(release.Id,release.Name));
        }
        
        return options;
    }
    
    //get status
    public List<SelectOption> getProjStatuses()
    {
       List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult =
       CRM_Project__c.Status__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
       options.add(new SelectOption('---All---','---All---'));     
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       
       return options;
    }
    
    //Get All Releases 
    public List<SelectOption> getProjects(){
        
        List<SelectOption> options = new List<SelectOption>();
       
            for(CRM_Project__c proj : projectList){
                options.add(new SelectOption(proj.Id,proj.Project_Name__c));
            }
        
        return options;
    }
    
     
    
    //Get WorkItems          
    public List<CRM_Project_Item__c> getWorkItemsList(){
           
           System.debug('*******projectId*** @@@ ' + projectId);
           dataList = new List<CRM_Project_Item__c>();

           if(projectId!=null){
               /*dataList =[ Select Id, Name, Subject__c,CreatedDate, Estimated_Effort_Hours__c,Actual_Effort_Hours__c, Description__c,Assigned_To__c,Project_Owner__c, Type__c, Available_Hours__c, Status__c
                            From CRM_Project_Item__c Where CRM_Project__c =:projectId ];  */
                            
            if(mapOfProjects.get(projectId)!=null){
                dataList = mapOfProjects.get(projectId);
            }
            
            System.debug('*******dataList *** @@@ ' + dataList );    
            
           
            return dataList;
        }
        
        return null;
    
    }
    
    //Get WorkItems          
    public List<Note> getNotesAttachments(){
           
           List<Note> noteList = new List<Note>();
           
           if(projectId!=null){
                noteList = [Select Id,Title,Body From Note Where ParentId=:projectId];
                return noteList;
            }
    
            return null;   
    }
   
    
    //Referesh Projects
    public void RefereshProjects(){
        
        mapOfProjects = new Map<Id,List<CRM_Project_Item__c>>();
        Set<CRM_Project__c> projectsSet = new Set<CRM_Project__c>();
        projectList = new List<CRM_Project__c>();
        dataList = new List<CRM_Project_Item__c>();
        system.debug('***statusSelected**'+ statusSelected);
        System.debug('releaseId'+ releaseId);
        System.debug('assigneeName'+ assigneeName);
        System.debug('projectId'+ projectId);
        
         String query = 'Select Id, Name, Subject__c,CreatedDate, Estimated_Effort_Hours__c,Actual_Effort_Hours__c, Description__c,Assigned_To__c,Project_Owner__c, Type__c, Available_Hours__c,'+
           'Status__c,CRM_Project__c,CRM_Project__r.Name,CRM_Project__r.Description__c,CRM_Project__r.CreatedDate ,CRM_Project__r.Project_Name__c,CRM_Project__r.Reporting_Process_Improvement_Automation__c,'+ 
           'CRM_Project__r.Requester_Department__c ,CRM_Project__r.Project_Team__c,CRM_Project__r.CRM_Release__c,CRM_Project__r.Status__c,CRM_Project__r.Requestor__c,'+
           'CRM_Project__r.Requestor__r.Name,CRM_Project__r.Estimated_Effort_Hours__c,CRM_Project__r.Actual_Effort_Hours__c From CRM_Project_Item__c Where CRM_Project__r.CRM_Release__c =:releaseID' ;
        
        if(assigneeName!='---All---'){
            query += ' And Assigned_To__r.Name =:assigneeName';
        }
        
        if(statusSelected!='---All---'){
            query += ' And CRM_Project__r.Status__c =:statusSelected';
        }
        
        if(releaseId!=null){
            
            for(CRM_Project_Item__c cItem : Database.Query(query)){
                 projectsSet.add(cItem.CRM_Project__r);
                 
                 if(mapOfProjects.containsKey(cItem.CRM_Project__c))
                     mapOfProjects.get(cItem.CRM_Project__c).add(cItem);
                 else
                     mapOfProjects.put(cItem.CRM_Project__c, new List<CRM_Project_Item__c>{cItem});
            }
        }  
       
            
        /*    
        if( releaseId!=null)
        projectList = [ Select Id,Name,CreatedDate ,Project_Name__c,Reporting_Process_Improvement_Automation__c,Requester_Department__c ,Project_Team__c,CRM_Release__c,Status__c,Requestor__c, Requestor__r.Name,
                        Estimated_Effort_Hours__c,Actual_Effort_Hours__c From CRM_Project__c Where CRM_Release__c =:releaseID];
        */
        projectList.addAll(projectsSet);
         
        if( projectList!=null && projectList.size() >0 )
           showProjects =true;
        else
           showProjects =false;
        
       
    }
   
}