objects/CSN_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>CSN_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Created for the Contracts Team</description>
    <label>Credit</label>
    <nameField>
        <displayFormat>CSN Credit-{0000}</displayFormat>
        <label>CSN Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Feature__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Feature</label>
</CustomObject>

objects/Feature_Set__c.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>***Cvent Payment Services</fullName>
                </value>
                <value>
                    <fullName>1:1 Meeting Schedular</fullName>
                </value>
                <value>
                    <fullName>12 HTML pages per event</fullName>
                </value>
                <value>
                    <fullName>1 Pg PMPP EPrint</fullName>
                </value>
                <value>
                    <fullName>1 Pg RePrint</fullName>
                </value>
                <value>
                    <fullName>2 Pg PMPP EPrint</fullName>
                </value>
                <value>
                    <fullName>2 Pg RePrint</fullName>
                </value>
                <value>
                    <fullName>3rd Party Web Service Creation</fullName>
                </value>
                <value>
                    <fullName>5 GB document of Storage</fullName>
                </value>
                <value>
                    <fullName>Abstract Management</fullName>
                </value>
                <value>
                    <fullName>Access to account : Wright Leadership Institute WLITIL001</fullName>
                </value>
                <value>
                    <fullName>Accounts Added</fullName>
                </value>
                <value>
                    <fullName>Acuvent Fees</fullName>
                </value>
                <value>
                    <fullName>Additional Account Emails</fullName>
                </value>
                <value>
                    <fullName>Additional Contacts</fullName>
                </value>
                <value>
                    <fullName>Additional Custom Contact Fields</fullName>
                </value>
                <value>
                    <fullName>Additional database contacts</fullName>
                </value>
                <value>
                    <fullName>Additional Data Storage</fullName>
                </value>
                <value>
                    <fullName>Additional Direct Costs for Client Services Task</fullName>
                </value>
                <value>
                    <fullName>Additional Instances for Multi-Instance/City/Selection/Language (Qty 5)</fullName>
                </value>
                <value>
                    <fullName>Additional language</fullName>
                </value>
                <value>
                    <fullName>Additional Languages</fullName>
                </value>
                <value>
                    <fullName>Additional Locations</fullName>
                </value>
                <value>
                    <fullName>Additional Round of Changes</fullName>
                </value>
                <value>
                    <fullName>Additional Surveys</fullName>
                </value>
                <value>
                    <fullName>Additional User Logins</fullName>
                </value>
                <value>
                    <fullName>Address Book Segmentation</fullName>
                </value>
                <value>
                    <fullName>Adjustment FEE</fullName>
                </value>
                <value>
                    <fullName>Adjustment Fees</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_N__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Feature Sets</relationshipLabel>
        <relationshipName>Feature_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Feature Set</label>
    <nameField>
        <displayFormat>{00000} - {DD}{MM}{YY}</displayFormat>
        <label>Feature Set</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoicing_Details__c.object
<CustomObject>
    <fields>
        <fullName>Billing_POC__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing POC</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoicing Details</relationshipLabel>
        <relationshipName>Invoicing_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoicing Details</relationshipLabel>
        <relationshipName>Invoicing_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Created for Invoicing Details for TRACT</description>
    <label>Invoicing Details</label>
    <nameField>
        <displayFormat>Invoice-{0000000000}</displayFormat>
        <label>Invoicing Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoicing Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoicing_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoicing_Details__c</fullName>
        <label>Invoicing Details</label>
        <referenceTo>Invoicing_Details__c</referenceTo>
        <relationshipLabel>Invoicing Line Items</relationshipLabel>
        <relationshipName>Invoicing_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoicing Line Items</label>
    <nameField>
        <displayFormat>Invoice Item-{0000000000}</displayFormat>
        <label>Invoicing Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoicing Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Multi_Property_Bundles__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Signer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>CSN_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>CSN_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MSA/Bundle Campaigns</label>
    <nameField>
        <label>test name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MSA/Bundle Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>PricebookEntry.Product2.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/TM_Fee_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TM Fee Structure</relationshipLabel>
        <relationshipName>TM_Fee_Structure</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TM Fee Structure</label>
    <nameField>
        <label>TM Fee Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TM Fee Structure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateCurrencyBatchOppCls.cls
/*
//////////////////////////////////////
//      @author Abhishek Pandey     //
/////////////////////////////////////
Version :   1.0
Date : 10th March 2015
Description : Update all opps falling on same day with correct exchange rate.
Tested in OpportunityTrgHelperClsTest


    Version 2.0
    Date:7th Nov 2016
    Description : Migrating FEATURESET to PRODUCT/PRICEBOOK. Below are the name of the field which needs to be replaced - 
    OLD FIELD NAME       = NEW FIELD NAME
    Feature_Sets__r      = OpportunityLineItems;
    R00N00000008aGEXEA2  = OpportunityLineItems;
    Feature_Set__c       = OpportunityLineItem;
    Feature__c           = Product_Name__c;
    Opportunity_N__c     = OpportunityId;
    //Lines Commented as Can't update CurrencyISOCode of OpportunityLineItem
*/
global class UpdateCurrencyBatchOppCls implements Database.Batchable<sObject>{
    
    global String Query;
    
    global UpdateCurrencyBatchOppCls(){
        query = '';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        Date dateInst = system.today();
        query = 'SELECT Id,CurrencyIsoCode,Exchange_Rate__c,CloseDate,(SELECT Id,CurrencyIsoCode,Exchange_Rate__c FROM TM_Fee_Structure__r),(SELECT Id,CurrencyIsoCode,Exchange_Rate__c FROM OpportunityLineItems),(SELECT Id,CurrencyIsoCode FROM Invoicing_Details__r),(SELECT Id,CurrencyIsoCode,Exchange_Rate__c FROM CSN_Credits__r),(SELECT Id,CurrencyIsoCode,Exchange_Rate__c FROM CSN_Campaigns__r) FROM Opportunity WHERE CloseDate =: dateInst';
        system.debug('query++'+query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Opportunity> scope){
        map<String,Decimal> mapConv = new map<String,Decimal>();
        
        List<DatedConversionRate> lstDateCR =  [SELECT StartDate, IsoCode, ConversionRate FROM DatedConversionRate WHERE StartDate =: System.Today()];
        for(DatedConversionRate instOfDCR :lstDateCR){
            String instStr = instOfDCR.StartDate + instOfDCR.IsoCode;
            system.debug('instStr++'+instStr);
            system.debug('instOfDCR.ConversionRate+++'+instOfDCR.ConversionRate);
            mapConv.put(instStr,instOfDCR.ConversionRate);
        }
        
        List<Opportunity> lstOpp = new List<Opportunity>();
        List<TM_Fee_Structure__c> lstofTMFS = new List<TM_Fee_Structure__c>();
        List<OpportunityLineItem> lstOfFeat = new List<OpportunityLineItem>();
        List<Multi_Property_Bundles__c> lstOfMPB = new List<Multi_Property_Bundles__c>();
        List<CSN_Credit__c> lstCSNCr = new List<CSN_Credit__c>();
        Set<Id> setInvoicingLI = new Set<Id>();
        
        for(Opportunity instOfOpp : scope){
            system.debug(instOfOpp.Id);
            
            String instStr = instOfOpp.CloseDate + instOfOpp.CurrencyIsoCode;
            system.debug('instStr++'+instStr);
            system.debug('mapConv++'+mapConv);
            if(mapConv.ContainsKey(instStr)){
                instOfOpp.Exchange_Rate__c = mapConv.get(instStr);
                lstOpp.add(instOfOpp);
            }else if(instOfOpp.CurrencyIsoCode == 'USD'){
                instOfOpp.Exchange_Rate__c = 1;
                lstOpp.add(instOfOpp);
            }
            
            for(TM_Fee_Structure__c instofTMFS : instOfOpp.TM_Fee_Structure__r){
                instofTMFS.Exchange_Rate__c = instOfOpp.Exchange_Rate__c;
                lstofTMFS.add(instofTMFS);
            }
            for(OpportunityLineItem instOfFeat : instOfOpp.OpportunityLineItems){
                instOfFeat.Exchange_Rate__c = instOfOpp.Exchange_Rate__c;
                lstOfFeat.add(instOfFeat);
            }
            for(Invoicing_Details__c instOfDet : instOfOpp.Invoicing_Details__r){
                setInvoicingLI.add(instOfDet.Id);
            }
            for(Multi_Property_Bundles__c instOfMPB : instOfOpp.CSN_Campaigns__r){
                instOfMPB.Exchange_Rate__c = instOfOpp.Exchange_Rate__c;
                lstOfMPB.add(instOfMPB);
            }
            for(CSN_Credit__c instCSNCr : instOfOpp.CSN_Credits__r){
                instCSNCr.Exchange_Rate__c = instOfOpp.Exchange_Rate__c;
                lstCSNCr.add(instCSNCr);
            }
        }
        
        if(lstOpp.size()>0)
        Database.SaveResult[] sr = Database.update(lstOpp , false);
        //update lstOpp;
        
        List<Invoicing_Details__c> lstInvDetLI = new List<Invoicing_Details__c>();
        
        lstInvDetLI = [SELECT Id,Opportunity__r.CurrencyIsoCode,Opportunity__r.Exchange_Rate__c,(SELECT Id,Exchange_Rate__c,CurrencyIsoCode FROM Invoicing_Line_Items__r) FROM Invoicing_Details__c WHERE Id =: setInvoicingLI];
        
        List<Invoicing_Line_Items__c> lstILI = new List<Invoicing_Line_Items__c>();
        
        for(Invoicing_Details__c incvoicingDet : lstInvDetLI){
            for(Invoicing_Line_Items__c instOfInvLI : incvoicingDet.Invoicing_Line_Items__r){
                instOfInvLI.CurrencyIsoCode = incvoicingDet.Opportunity__r.CurrencyIsoCode;
                instOfInvLI.Exchange_Rate__c = incvoicingDet.Opportunity__r.Exchange_Rate__c;
                lstILI.add(instOfInvLI);
            }
        }
        
        if(lstILI.size()>0)
        Database.SaveResult[] sr = Database.update(lstILI , false);
        //update lstILI;  
        
        if(lstofTMFS.size()>0)
        Database.SaveResult[] sr = Database.update(lstofTMFS , false);
        //update lstofTMFS;
        
        if(lstOfFeat.size()>0)
        Database.SaveResult[] sr = Database.update(lstOfFeat , false);
        //update lstOfFeat;
        
        if(lstOfMPB.size()>0)
        Database.SaveResult[] sr = Database.update(lstOfMPB , false);
        //update lstOfMPB;
        
        if(lstCSNCr.size()>0)
        Database.SaveResult[] sr = Database.update(lstCSNCr , false);
        //update lstCSNCr;
        
        
    }

    global void finish(Database.BatchableContext BC){
        Integer currencyRecCount = 0;
        //String recipientsEmail = System.Label.Admin_Team_Emails;
        String[] toAddresses = new String[]{};
        currencyRecCount = [SELECT count() FROM DatedConversionRate WHERE StartDate = today];
        
        // Send an email alert if their is an failure.
        if(currencyRecCount <6){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
            toAddresses = System.Label.Admin_Team_Emails.split(',');
            //String[] toAddresses = new String[] {recipientsEmail};  
            mail.setToAddresses(toAddresses);  
            mail.setSubject('Failed to update some currencies information from Oanda servers');
            String body='<span style='+'\''+'color:#1F497D; font-size:11.0pt;font-family:"Calibri",sans-serif;'+'\''+'><b>Hi '+', </b></br></br>You have been identified as a Designated Contact for this Integration.</br></br> Scheduled Batch Job (ACMRestIntegrationcls) has been failed to update some currencies information from Oanda servers.</br>'+'</span></br><span style='+'\''+'font-size:11.0pt;font-family:"Calibri",sans-serif;color:#000000'+'\''+'><b>Thanks,</br>'+'Salesforce'+'<o:p></o:p></b></span>';//mail.setHtmlBody(body);
            mail.setHtmlBody(body);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
        //=============================================================
    }
}