objects/CSScoring__c.object
<CustomObject>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>CS Scoring</label>
</CustomObject>

objects/Quality_Check_Done__c.object
<CustomObject>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score(%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Quality Check Done</label>
    <nameField>
        <displayFormat>QC-{00000000}</displayFormat>
        <label>Quality Check Done Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Check Dones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Check_Response__c.object
<CustomObject>
    <fields>
        <fullName>Criticality__c</fullName>
        <formula>TEXT(Quality_Check_Question__r.Criticality__c)</formula>
        <label>Criticality</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Score__c</fullName>
        <formula>Quality_Check_Question__r.Max_Score__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quality_Check_Done__c</fullName>
        <label>Quality Check Done</label>
        <referenceTo>Quality_Check_Done__c</referenceTo>
        <relationshipLabel>Quality Check Response</relationshipLabel>
        <relationshipName>Quality_Check_Response</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quality_Check_Filled_Response__c</fullName>
        <label>Quality Check Filled Response</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <formula>TEXT(Quality_Check_Question__r.Question_Type_CC__c)</formula>
        <label>Question Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <formula>Quality_Check_Question__r.Question__c</formula>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quality Check Response</label>
    <nameField>
        <displayFormat>QC Resp-{000000000}</displayFormat>
        <label>Quality Check Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Check Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/qualityCheckRespTrgHelperCls.cls
/*
//////////////////////////////////////
//      @author Abhishek Pandey     //
/////////////////////////////////////
Version :   1.0
Date : 15th Sept 2015
Description : Score roll-up.
*/
public class qualityCheckRespTrgHelperCls{
    public static map<String,Decimal> mapQuesScore = new map<String,Decimal>();
    public static List<CSScoring__c> lstQCR = new List<CSScoring__c>();
    static{
        lstQCR = CSScoring__c.getall().values();
        for(CSScoring__c isntOfQCR : lstQCR ){
             mapQuesScore.put(isntOfQCR.Question__c+isntOfQCR.Response__c+isntOfQCR.Question_Type__c,isntOfQCR.Score__c);
        }
    }
    public void OnBeforeInsert(List<Quality_Check_Response__c> newValues){    
        for(Quality_Check_Response__c instOfQCR : newValues){
            if(mapQuesScore.containsKey(instOfQCR.Question__c+instOfQCR.Quality_Check_Filled_Response__c+instOfQCR.Question_Type__c)){
                instOfQCR.Score__c = mapQuesScore.get(instOfQCR.Question__c+instOfQCR.Quality_Check_Filled_Response__c+instOfQCR.Question_Type__c);
            }
        }
    }
    public void OnAfterInsert(Map<Id,Quality_Check_Response__c> newMapValues){ 
        Set<Id> setIdQCDone = new Set<Id>();
        for(Quality_Check_Response__c instOfQCR : newMapValues.values()){
            setIdQCDone.add(instOfQCR.Quality_Check_Done__c);
        }
        List<Quality_Check_Done__c> lstQCDone = [SELECT ID,(SELECT ID,Score__c,Criticality__c,Quality_Check_Filled_Response__c,Max_Score__c FROM Quality_Check_Response__r) FROM Quality_Check_Done__c WHERE Id=:setIdQCDone];
        
        List<Quality_Check_Done__c> lstQCDoneUpd = new List<Quality_Check_Done__c>(); 
        for(Quality_Check_Done__c instQCDone : lstQCDone){
            Decimal maxScore = 0;
            Integer criticalCount = 0;
            Integer naCount = 0;
            Decimal score =0; 
            //totalCount++; 
            for(Quality_Check_Response__c instQCRes : instQCDone.Quality_Check_Response__r){
                if(instQCRes.Criticality__c == 'Critical' && instQCRes.Score__c == 0){
                    criticalCount++;
                }
                if(instQCRes.Quality_Check_Filled_Response__c != 'NA'){
                    score = score + instQCRes.Score__c;
                    maxScore = maxScore + instQCRes.Max_Score__c;
                }
            }
            //instQCDone.Score__c = score;
            
            instQCDone.Score__c = 0;
            
            if(criticalCount == 0)
            instQCDone.Score__c = score/maxScore *100;
            
            lstQCDoneUpd.add(instQCDone);
        }
        
        if(lstQCDoneUpd.size()>0)
        update lstQCDoneUpd;
    }
    public void OnBeforeUpdate(Map<Id,Quality_Check_Response__c> oldMapValues,Map<Id,Quality_Check_Response__c> newMapValues){ 
        for(Quality_Check_Response__c instOfQCR : newMapValues.values()){
            if(mapQuesScore.containsKey(instOfQCR.Question__c+instOfQCR.Quality_Check_Filled_Response__c+instOfQCR.Question_Type__c)){
                instOfQCR.Score__c = mapQuesScore.get(instOfQCR.Question__c+instOfQCR.Quality_Check_Filled_Response__c+instOfQCR.Question_Type__c);
            }
        }
    }
    public void OnAfterUpdate(Map<Id,Quality_Check_Response__c> oldMapValues,Map<Id,Quality_Check_Response__c> newMapValues){ 
        Set<Id> setIdQCDone = new Set<Id>();
        for(Quality_Check_Response__c instOfQCR : newMapValues.values()){
            setIdQCDone.add(instOfQCR.Quality_Check_Done__c);
        }
        List<Quality_Check_Done__c> lstQCDone = [SELECT ID,Score__c,(SELECT ID,Score__c,Criticality__c,Quality_Check_Filled_Response__c,Max_Score__c FROM Quality_Check_Response__r) FROM Quality_Check_Done__c WHERE Id=:setIdQCDone];
        
        List<Quality_Check_Done__c> lstQCDoneUpd = new List<Quality_Check_Done__c>(); 
        for(Quality_Check_Done__c instQCDone : lstQCDone){
            Decimal maxScore = 0;
            Integer criticalCount = 0;
            Integer naCount = 0;
            Decimal score =0; 
            //totalCount++; 
            for(Quality_Check_Response__c instQCRes : instQCDone.Quality_Check_Response__r){
                system.debug('instQCRes.Score__c++'+instQCRes.Criticality__c);
                system.debug('instQCRes.Score__c++'+instQCRes.Score__c);
                if(instQCRes.Criticality__c == 'Critical' && instQCRes.Score__c == 0){
                    criticalCount++;
                }
                if(instQCRes.Quality_Check_Filled_Response__c != 'NA'){
                    score = score + instQCRes.Score__c;
                    maxScore = maxScore + instQCRes.Max_Score__c;
                }
            }
            //instQCDone.Score__c = score;
            
            instQCDone.Score__c = 0;
            system.debug('instQCDone.Score__c+++'+instQCDone.Score__c);
            system.debug('criticalCount+++'+criticalCount);
            
            if(criticalCount == 0)
            instQCDone.Score__c = score/maxScore * 100;
            
            lstQCDoneUpd.add(instQCDone);
        }
        
        if(lstQCDoneUpd.size()>0)
        update lstQCDoneUpd;
    }
    public void OnBeforeDelete(List<Quality_Check_Response__c> oldValues,Map<Id,Quality_Check_Response__c> oldMapValues){
    }
    public void OnAfterDelete(List<Quality_Check_Response__c> oldValues,Map<Id,Quality_Check_Response__c> oldMapValues){
    }
    public void OnUndelete(List<Quality_Check_Response__c> newValues){     
    }
}