objects/Current_Status__c.object
<CustomObject>
    <fields>
        <fullName>Account_Progress__c</fullName>
        <label>Event Core Account Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Untouched</fullName>
                </value>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Engaged buyer</fullName>
                </value>
                <value>
                    <fullName>Presentation scheduled</fullName>
                </value>
                <value>
                    <fullName>Correct Contacts Identified</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Price Quote/Proposal</fullName>
                </value>
                <value>
                    <fullName>Negotiation</fullName>
                </value>
                <value>
                    <fullName>Verbal</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Using Competitor/Keeping in Touch</fullName>
                </value>
                <value>
                    <fullName>No Opportunity / Not a Fit</fullName>
                </value>
                <value>
                    <fullName>Active Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Parent</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Parent &amp; Subsidiary</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Sourcing</fullName>
                </value>
                <value>
                    <fullName>Closed Won - Subsidiary</fullName>
                </value>
                <value>
                    <fullName>Completely Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - CT</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in CSN</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in Event</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch - Interested in Mobile</fullName>
                </value>
                <value>
                    <fullName>Keeping in touch -  Interested in SMM</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                    <default>true</default>
                    <label>No Contact</label>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
                <value>
                    <fullName>Technology Through TMC/MMC</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Using Competitor/In-house system</fullName>
                </value>
                <value>
                    <fullName>Working - CT</fullName>
                </value>
                <value>
                    <fullName>Working - Event</fullName>
                </value>
                <value>
                    <fullName>Working - Mobile</fullName>
                </value>
                <value>
                    <fullName>Working - SMM</fullName>
                </value>
                <value>
                    <fullName>Working - Sourcing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BCP_Status__c</fullName>
        <label>Progress Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Current_Status</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>A/c Status</label>
    <nameField>
        <displayFormat>CS{0000}</displayFormat>
        <label>Current Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>A/c Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Top_Accounts</fullName>
        <active>true</active>
        <label>Top Accounts</label>
    </recordTypes>
</CustomObject>

classes/BCP_Project_Class.cls
public class BCP_Project_Class {
        public Current_Status__c account {get; private set;}
        //public Account account_name {get; private set;}
        String id = ApexPages.currentPage().getParameters().get('id');
        String id2 = ApexPages.currentPage().getParameters().get('PID');
        private String Parent_account_name, Current_account_name, countries, testname;
        //private String[] countries = new String[]{};
        public string selectedLevel1 {get; set;}
        
        
        private String tab_name;
                public BCP_Project_Class() {
                RecordType instRecTypeThir = [SELECT Id FROM RecordType WHERE SobjectType='Current_Status__c' And IsActive = true And DeveloperName = 'Top_Accounts' ];
                 //id2 = '001S000000H7bkN';
                 //id = '001S000000H7bkN';   
                account = [Select c.Parent_Account__c, c.BCP_Status__c, c.Account_Progress__c From Current_Status__c c where Parent_Account__c = :id2 AND RecordTypeId !=:instRecTypeThir.Id];
                Current_account_name  = [select name from account where id = :id limit 1].name;
                Parent_account_name   = [select name from account where id = :id2 limit 1].name;
                 countries = account.Account_Progress__c;
                }
                
         public string getcurrentaccount() {
        return this.Current_account_name ;
        }    
        
         public string getparentaccount() {
        return this.Parent_account_name ;
        }
           
        public PageReference edit() {
                
        String xx;      
        xx = id + '&PID=' + id2;
        String x1 = '/apex/BCP_Project_Edit?id=' + xx;
        //String x1 = 'https://c.cs1.visual.force.com/apex/BCP_Project_Edit?id=' + xx;
        PageReference opptyPage = new PageReference(x1);
        opptyPage.setRedirect(true);
        return opptyPage;
        }
        
        public PageReference cancel() {
                
        String xx;      
        xx = id + '&PID=' + id2;
         countries =account.Account_Progress__c;
        String x1 = '/apex/BCP_Project?id=' + xx;
        //String x1 = 'https://c.cs1.visual.force.com/apex/BCP_Project?id=' + xx;
        PageReference opptyPage = new PageReference(x1);
        opptyPage.setRedirect(true);
        return opptyPage;
        }
        
        public PageReference save() {
                try {
                account.Account_Progress__c = countries;
        update(account);
        String xx;      
        xx = id + '&PID=' + id2;
        String x1 = '/apex/BCP_Project?id=' + xx;
        //String x1 = 'https://c.cs1.visual.force.com/apex/BCP_Project?id=' + xx;
        PageReference opptyPage = new PageReference(x1);
        opptyPage.setRedirect(true);
        return opptyPage;
        } catch(System.DMLException e) {
        ApexPages.addMessages(e);
        return null;
        }
                return null;
        }
         
        public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('No Contact','No Contact'));
        options.add(new SelectOption('Prospecting','Prospecting'));
        options.add(new SelectOption('Working - SMM','Working - SMM'));
        options.add(new SelectOption('Working - Event','Working - Event'));
        options.add(new SelectOption('Working - Sourcing','Working - Sourcing'));
        options.add(new SelectOption('Working - Mobile','Working - Mobile'));
        options.add(new SelectOption('Working - CT','Working - CT'));
        options.add(new SelectOption('Using Competitor/In-house system','Using Competitor/In-house system'));
        options.add(new SelectOption('Keeping in touch - Interested in SMM','Keeping in touch - Interested in SMM'));
        options.add(new SelectOption('Keeping in touch - Interested in Event','Keeping in touch - Interested in Event'));
        options.add(new SelectOption('Keeping in touch - Interested in CSN','Keeping in touch - Interested in CSN'));
        options.add(new SelectOption('Keeping in touch - Interested in Mobile','Keeping in touch - Interested in Mobile'));
        options.add(new SelectOption('Keeping in touch - CT','Keeping in touch - CT'));
        options.add(new SelectOption('Active Review','Active Review'));
        options.add(new SelectOption('Trial','Trial'));
        options.add(new SelectOption('Price Quote/Proposal','Price Quote/Proposal'));
        options.add(new SelectOption('Negotiation','Negotiation'));
        options.add(new SelectOption('Verbal','Verbal'));
        options.add(new SelectOption('Technology Through TMC/MMC','Technology Through TMC/MMC'));
        options.add(new SelectOption('Closed Won','Closed Won'));
        options.add(new SelectOption('Closed Won - Parent','Closed Won - Parent'));
        options.add(new SelectOption('Closed Won - Parent & Subsidiary','Closed Won - Parent & Subsidiary'));
        options.add(new SelectOption('Closed Won - Subsidiary','Closed Won - Subsidiary'));
        options.add(new SelectOption('Closed Won - Sourcing','Closed Won - Sourcing'));
        options.add(new SelectOption('No Opportunity','No Opportunity'));
        
        return options;
        }
        public String getCountries() {
        return countries;
        }
        public void setCountries(String countries) {
        this.countries = countries;
        }
        
        
        }