objects/Customer_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Status__c</fullName>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Signed, Not Delivered</fullName>
                    <default>true</default>
                    <label>Signed, Not Delivered</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending Decommission</fullName>
                </value>
                <value>
                    <fullName>Decommissioned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Decommission_Effective_Date__c</fullName>
        <description>The effective date to decommission this asset. Used for future dating decommission of assets.</description>
        <inlineHelpText>The effective date to decommission this asset. Used for future dating decommission of assets.</inlineHelpText>
        <label>Decommission Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Quantity owned.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <description>A summarization of the Steelbrick Subscriptions and Steelbrick Assets for the Customer.</description>
    <label>Customer Asset</label>
    <nameField>
        <displayFormat>CA-{0000000}</displayFormat>
        <label>Customer Asset</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VistaAssetExpiredBatchable.cls
global class VistaAssetExpiredBatchable implements Database.Batchable<sObject> {
	/* batch job to expire assets that ended in the past */
	Date dt = System.Today();
	String query = 'SELECT Id, Asset_Status__c, Quantity__c, Decommission_Effective_Date__c FROM Customer_Asset__c WHERE Asset_Status__c = \'Active\' AND ((Term_End_Date__c <: dt AND Term_End_Date__c != null) OR (Quantity__c = 0 and Term_Start_Date__c <=: dt) OR (Decommission_Effective_Date__c <=: dt))';
 
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Customer_Asset__c> scope) {
		for(Customer_Asset__c a: scope) {
			if(a.Quantity__c == 0 || a.Decommission_Effective_Date__c <= dt) {
				a.Asset_Status__c = 'Decommissioned';
			} else {
				a.Asset_Status__c = 'Expired';
			}
		}
		update scope;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}