objects/Cvent_Asset_Group__c.object
<CustomObject>
    <label>Cvent Asset Group</label>
    <nameField>
        <label>Cvent Asset Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cvent Asset Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cvent_Asset_Subgroup__c.object
<CustomObject>
    <fields>
        <fullName>Cvent_Asset_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cvent Asset Group</label>
        <referenceTo>Cvent_Asset_Group__c</referenceTo>
        <relationshipLabel>Cvent Asset Subgroups</relationshipLabel>
        <relationshipName>Cvent_Asset_Subgroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cvent Asset Subgroup</label>
    <nameField>
        <label>Cvent Asset Subgroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cvent Asset Subgroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cvent_Asset_Type__c.object
<CustomObject>
    <label>Cvent Asset Type</label>
    <nameField>
        <label>Cvent Asset Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cvent Asset Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onsite_Hardware_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cvent_Asset_Group__c</fullName>
        <formula>Onsite_Hardware_Request_Bundle__r.Cvent_Asset_Subgroup_Bundle__r.Cvent_Asset_Subgroup__r.Cvent_Asset_Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cvent Asset Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cvent_Asset_Subgroup__c</fullName>
        <formula>Onsite_Hardware_Request_Bundle__r.Cvent_Asset_Subgroup_Bundle__r.Cvent_Asset_Subgroup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cvent Asset Subgroup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cvent_Asset_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cvent Asset Type</label>
        <referenceTo>Cvent_Asset_Type__c</referenceTo>
        <relationshipLabel>Onsite Hardware Request Items</relationshipLabel>
        <relationshipName>Onsite_Hardware_Request_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packlist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packlist</label>
        <referenceTo>Packlist__c</referenceTo>
        <relationshipLabel>Onsite Hardware Request Items</relationshipLabel>
        <relationshipName>Onsite_Hardware_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_to_be_Packed__c</fullName>
        <formula>if ( Packlist_Quantity__c &lt;&gt; 0, Packlist_Quantity__c , Requested_Quantity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Auto-calculated. Uses the Logistics Team's entry (Packlist Quantity), if there is one. If not, defaults to the Requested Quantity entered by the PM.</inlineHelpText>
        <label>Quantity to be Packed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity_Others__c</fullName>
        <inlineHelpText>Number of items being shipped. 
Used for non-unique assets or consumables.</inlineHelpText>
        <label>Shipped Quantity - Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity_Unique_Assets__c</fullName>
        <inlineHelpText>Auto-calculated.
Count of all unique assets scanned to be shipped. 
May include incorrectly scanned items.</inlineHelpText>
        <label>Shipped Quantity - All Unique Assets</label>
        <summaryForeignKey>Packlist_Item__c.Onsite_Hardware_Request_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity__c</fullName>
        <formula>if(  Shipped_Quantity_Correct_Unique_Assets__c == 0, Shipped_Quantity_Others__c,  Shipped_Quantity_Correct_Unique_Assets__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Auto-calculated.
Number of items being shipped: unique hardware or quantity entered for non-unique hardware or consumable.</inlineHelpText>
        <label>Shipped Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Onsite Hardware Request Item</label>
    <nameField>
        <displayFormat>OHRI - {0}</displayFormat>
        <label>Onsite Hardware Request Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onsite Hardware Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Packlist__c.object
<CustomObject>
    <label>Packlist</label>
    <nameField>
        <label>Packlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CAM_PrepareShipmentFromPacklist_E.cls
public with sharing class CAM_PrepareShipmentFromPacklist_E {
    private final ApexPages.StandardController controller;
    public String firstItemId;

    public CAM_PrepareShipmentFromPacklist_E(ApexPages.StandardController stdController) {
		this.controller = stdController;
        refreshthePacklist();
    }
    
    public Packlist__c thePacklist {
        get {
            if (thePacklist == null){
                thePacklist = (Packlist__c)controller.getRecord();
				refreshthePacklist();
            }
            return thePacklist;
        }
        set;
    } //thePacklist
    
    public void refreshthePacklist() {
        thePacklist = [SELECT Id, Name, 
                                    (SELECT id, Name, Cvent_Asset_Type__c, Cvent_Asset_Type__r.Name, Cvent_Asset_Group__c, Cvent_Asset_Subgroup__c, 
                                            Quantity_to_be_Packed__c, CreatedDate,
                                            Shipped_Quantity_Unique_Assets__c, Shipped_Quantity_Others__c, Shipped_Quantity__c
                                        FROM Onsite_Hardware_Request_Items__r 
                                        ORDER BY name, Cvent_Asset_Type__c, Cvent_Asset_Group__c, Cvent_Asset_Subgroup__c ) 
                        FROM  Packlist__c WHERE Id= :thePacklist.Id
                            ];
        firstItemId = thePacklist.Onsite_Hardware_Request_Items__r[0].id;
    }//refreshthePacklist

    public PageReference redirectMe() {
        PageReference p = new PageReference('/apex/CAM_PrepareShipment?id=' + firstItemId);
        p.setRedirect(true);
        return p;

    }//redirectMe

}