objects/Cvent_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Cvent_Asset_Type__c</fullName>
        <label>Cvent Asset Type</label>
        <referenceTo>Cvent_Asset_Type__c</referenceTo>
        <relationshipLabel>Cvent Assets</relationshipLabel>
        <relationshipName>Cvent_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>This object stores records of all the Cvent Assets that can be used at a Cent managed Event.</description>
    <label>Cvent Asset</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Cvent Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cvent_Asset_Group__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>In search screens the results will be ordered in ascending order of this number. If the numbers are the same, alphabetical sort will be used.</inlineHelpText>
        <label>Sort Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cvent Asset Group</label>
    <nameField>
        <label>Cvent Asset Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cvent Asset Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cvent_Asset_Subgroup__c.object
<CustomObject>
    <fields>
        <fullName>Cvent_Asset_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cvent Asset Group</label>
        <referenceTo>Cvent_Asset_Group__c</referenceTo>
        <relationshipLabel>Cvent Asset Subgroups</relationshipLabel>
        <relationshipName>Cvent_Asset_Subgroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cvent Asset Subgroup</label>
    <nameField>
        <label>Cvent Asset Subgroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cvent Asset Subgroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cvent_Asset_Type__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unique Asset</fullName>
                </value>
                <value>
                    <fullName>Non-Unique Asset</fullName>
                </value>
                <value>
                    <fullName>Consumable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cvent Asset Type</label>
    <nameField>
        <label>Cvent Asset Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cvent Asset Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cvent_Box__c.object
<CustomObject>
    <fields>
        <fullName>Packlist__c</fullName>
        <label>Packlist</label>
        <referenceTo>Packlist__c</referenceTo>
        <relationshipName>Cvent_Boxes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Piece Count</label>
    <nameField>
        <displayFormat>Box-{0}</displayFormat>
        <label>Piece Count</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Piece Count</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Data__c.object
<CustomObject>
    <fields>
        <fullName>Event_Name__c</fullName>
        <inlineHelpText>Public facing event name</inlineHelpText>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <formula>Project__r.pse__Project_Manager__r.FirstName &amp; " " &amp; Project__r.pse__Project_Manager__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Manager</label>
        <type>Text</type>
    </fields>
    <label>Event Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Onsite_Hardware_Request__c.object
<CustomObject>
    <fields>
        <fullName>Event_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Name</label>
        <referenceTo>Event_Data__c</referenceTo>
        <relationshipLabel>Onsite Hardware Requests</relationshipLabel>
        <relationshipName>Onsite_Hardware_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Onsite Hardware Requests</relationshipLabel>
        <relationshipName>Onsite_Hardware_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Onsite Hardware Request</label>
    <nameField>
        <displayFormat>OHR - {0}</displayFormat>
        <label>Onsite Hardware Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onsite Hardware Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onsite_Hardware_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>Cvent_Asset_Group__c</fullName>
        <formula>Onsite_Hardware_Request_Bundle__r.Cvent_Asset_Subgroup_Bundle__r.Cvent_Asset_Subgroup__r.Cvent_Asset_Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cvent Asset Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cvent_Asset_Subgroup__c</fullName>
        <formula>Onsite_Hardware_Request_Bundle__r.Cvent_Asset_Subgroup_Bundle__r.Cvent_Asset_Subgroup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cvent Asset Subgroup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cvent_Asset_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cvent Asset Type</label>
        <referenceTo>Cvent_Asset_Type__c</referenceTo>
        <relationshipLabel>Onsite Hardware Request Items</relationshipLabel>
        <relationshipName>Onsite_Hardware_Request_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cvent_Box__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cvent Box</label>
        <referenceTo>Cvent_Box__c</referenceTo>
        <relationshipLabel>Onsite Hardware Request Items</relationshipLabel>
        <relationshipName>Onsite_Hardware_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Onsite_Hardware_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Onsite Hardware Request</label>
        <referenceTo>Onsite_Hardware_Request__c</referenceTo>
        <relationshipLabel>Onsite Hardware Request Items</relationshipLabel>
        <relationshipName>Onsite_Hardware_Request_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packlist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packlist</label>
        <referenceTo>Packlist__c</referenceTo>
        <relationshipLabel>Onsite Hardware Request Items</relationshipLabel>
        <relationshipName>Onsite_Hardware_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_to_be_Packed__c</fullName>
        <formula>if ( Packlist_Quantity__c &lt;&gt; 0, Packlist_Quantity__c , Requested_Quantity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Auto-calculated. Uses the Logistics Team's entry (Packlist Quantity), if there is one. If not, defaults to the Requested Quantity entered by the PM.</inlineHelpText>
        <label>Quantity to be Packed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Returned_Quantity_Others__c</fullName>
        <inlineHelpText>Entered by the Logistics Team. 
Indicates the number of non-unique hardware returned from the event.</inlineHelpText>
        <label>Returned Quantity - Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Returned_Quantity__c</fullName>
        <formula>if( Returned_Quantity_All_Unique_Assets__c == 0, Returned_Quantity_Others__c, Returned_Quantity_All_Unique_Assets__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Auto-calculated.
Number of items being returned: unique hardware or quantity entered for non-unique hardware.</inlineHelpText>
        <label>Returned Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Returned__c</fullName>
        <formula>IF (  OR(ISNULL(Shipped_Quantity__c),Shipped_Quantity__c==0) , null, Returned_Quantity__c /  Shipped_Quantity__c)</formula>
        <label>Returned %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity_Correct_Unique_Assets__c</fullName>
        <inlineHelpText>Auto-calculated.
Count of all unique assets scanned to be shipped - excludes incorrectly scanned items.</inlineHelpText>
        <label>Shipped Quantity - Correct Unique Assets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity_Others__c</fullName>
        <inlineHelpText>Number of items being shipped. 
Used for non-unique assets or consumables.</inlineHelpText>
        <label>Shipped Quantity - Others</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity_Unique_Assets__c</fullName>
        <inlineHelpText>Auto-calculated.
Count of all unique assets scanned to be shipped. 
May include incorrectly scanned items.</inlineHelpText>
        <label>Shipped Quantity - All Unique Assets</label>
        <summaryForeignKey>Packlist_Item__c.Onsite_Hardware_Request_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Shipped_Quantity__c</fullName>
        <formula>if(  Shipped_Quantity_Correct_Unique_Assets__c == 0, Shipped_Quantity_Others__c,  Shipped_Quantity_Correct_Unique_Assets__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Auto-calculated.
Number of items being shipped: unique hardware or quantity entered for non-unique hardware or consumable.</inlineHelpText>
        <label>Shipped Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Onsite Hardware Request Item</label>
    <nameField>
        <displayFormat>OHRI - {0}</displayFormat>
        <label>Onsite Hardware Request Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onsite Hardware Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Packlist__c.object
<CustomObject>
    <fields>
        <fullName>Onsite_Hardware_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onsite Hardware Request</label>
        <referenceTo>Onsite_Hardware_Request__c</referenceTo>
        <relationshipLabel>Packlists</relationshipLabel>
        <relationshipName>Packlists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Packlist</label>
    <nameField>
        <label>Packlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Packlist_Item__c.object
<CustomObject>
    <fields>
        <fullName>Onsite_Hardware_Request_Item__c</fullName>
        <label>Onsite Hardware Request Item</label>
        <referenceTo>Onsite_Hardware_Request_Item__c</referenceTo>
        <relationshipLabel>Packlist Items</relationshipLabel>
        <relationshipName>Packlist_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Packlist Item</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Packlist Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packlist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CAM_ReturnShipment_E.cls
public with sharing class CAM_ReturnShipment_E {
    private final ApexPages.StandardController controller;
    public String   pageID { get; set; }
    public String   warehouseId { get; set; }
    public String   packlistId { get; set; }
    public Boolean  anonMode { get; set; }
    public Boolean uniqueAssetMode { get; set; }
    public String   scannedIdList { get; set; }
    public Onsite_Hardware_Request_Item__c  theItem { get; set; }
    public Packlist__c                      thePacklist { get; set; }
    public List<Packlist_Item__c>           packlistItems { get; set; }
    public String newLine { get {
        newLine = '\n';
        return newLine;
        }
        set;
    }

    public CAM_ReturnShipment_E (ApexPages.StandardController stdController) {
		this.controller = stdController;
        pageID = apexpages.currentpage().getparameters().get('id');
        warehouseId = apexpages.currentpage().getparameters().get('warehouse');
        packlistId = apexpages.currentpage().getparameters().get('Packlist__c');

        if ( packlistId <> null ){
            //if this parameter is not empty, it means that the page was called from a Packlist page. We will grab the first item in the Packlist, and redirect to the page with that ID
            System.System.debug('Found Packlist Id');
            redirectMe();
        }
        
        if ( pageID == null ) {
            anonMode = true;
        } else {
            anonMode = false;
            refreshPacklist();
            refreshPacklistItems();
        }
    }//constructor

    public void refreshPacklist(){
        // Consumables do not return back from onsite, therefore are excluded from this list
        // Items only show in the list if their Shipped Quantity is larger than 0. (The exception is that incorrect type unique assets are added, but the shipped quantity has not increased)
        thePacklist = [SELECT Id, Name, 
                                    (SELECT id, Name, Cvent_Asset_Type__c, Cvent_Asset_Type__r.Name, Cvent_Asset_Type__r.Type__c, Packlist__c, Returned_Quantity__c, Returned__c, Returned_Quantity_Others__c,
                                            Cvent_Asset_Group__c, Cvent_Asset_Subgroup__c, Quantity_to_be_Packed__c, CreatedDate,
                                            Onsite_Hardware_Request__r.Event_Name__r.Project_Manager__c, Onsite_Hardware_Request__r.Name, Onsite_Hardware_Request__c, Onsite_Hardware_Request__r.Event_Name__c, Onsite_Hardware_Request__r.Event_Name__r.Event_Name__c,
                                            Shipped_Quantity_Unique_Assets__c, Shipped_Quantity_Correct_Unique_Assets__c, Shipped_Quantity_Others__c, Shipped_Quantity__c
                                        FROM Onsite_Hardware_Request_Items__r 
                                        WHERE   Cvent_Asset_Type__r.Type__c <> 'Consumable'
                                            AND (Shipped_Quantity__c > 0 OR Shipped_Quantity_Unique_Assets__c > 0)
                                        ORDER BY Cvent_Asset_Type__r.Sort_Order__c, Cvent_Asset_Group__c, Cvent_Asset_Subgroup__c, name) 
                        FROM Packlist__c WHERE Id IN (SELECT Packlist__c FROM Onsite_Hardware_Request_Item__c WHERE id=:pageID) ];

        for (Onsite_Hardware_Request_Item__c i : thePacklist.Onsite_Hardware_Request_Items__r){
            if (i.id == pageID){
                theItem = i;
                if (theItem.Cvent_Asset_Type__r.Type__c == 'Unique Asset'){
                    uniqueAssetMode = TRUE;
                } else {
                    uniqueAssetMode = FALSE;
                    if ( theItem.Returned_Quantity_Others__c == null ){
                        theItem.Returned_Quantity_Others__c = theItem.Shipped_Quantity__c;
                    }
                }
            }
        }
    }//refreshPacklist

    public void refreshPacklistItems(){
        packlistItems = new List<Packlist_Item__c>();
        packlistItems = [SELECT id, Name, Cvent_Asset__c, Validate_Asset_Types_Match__c, Date_Actual_Return__c,
                            Cvent_Asset__r.Asset_Name__c, Cvent_Asset__r.Asset_Tag__c, Cvent_Asset__r.Cvent_Asset_Type__r.Name,
                            Cvent_Asset__r.IMEI__c, Cvent_Asset__r.Manufacturer__c, Cvent_Asset__r.Model_Number__c, Cvent_Asset__r.Phone_Number__c, Cvent_Asset__r.SIM_Number__c,
                            Cvent_Asset__r.Kit_Asset_Tag__c, Cvent_Asset__r.Kit_Asset_Tag__r.Asset_Name__c, Cvent_Asset__r.Kit_Asset_Tag__r.Asset_Tag__c, Cvent_Asset__r.Kit_Asset_Tag__r.Cvent_Asset_Type__r.Name,
                            Cvent_Asset__r.Kit_Asset_Tag__r.IMEI__c, Cvent_Asset__r.Kit_Asset_Tag__r.Manufacturer__c, Cvent_Asset__r.Kit_Asset_Tag__r.Model_Number__c, Cvent_Asset__r.Kit_Asset_Tag__r.Phone_Number__c, Cvent_Asset__r.Kit_Asset_Tag__r.SIM_Number__c,
                            Cvent_Box__c, Cvent_Box__r.Number_Label__c, Cvent_Box__r.Cvent_Box_Type__r.Name, Cvent_Box__r.Dimensions_in__c, Cvent_Box__r.Dimensions_cm__c
                            FROM Packlist_Item__c
                            WHERE Onsite_Hardware_Request_Item__c = :pageID AND Cvent_Asset__r.Status__c = 'Deployed'
                            ORDER BY Cvent_Box__r.Number_Label__c, Cvent_Asset__r.Asset_Tag__c
                        ];
    }//refreshPacklistItems

    public PageReference redirectMe(){
        thePacklist = [SELECT Id, Name, 
                                        (SELECT id, Name, Returned__c
                                        FROM Onsite_Hardware_Request_Items__r 
                                        WHERE Cvent_Asset_Type__r.Type__c <> 'Consumable'
                                        ORDER BY Cvent_Asset_Type__r.Sort_Order__c, Cvent_Asset_Group__c, Cvent_Asset_Subgroup__c, name ) 
                        FROM  Packlist__c WHERE Id= :packlistId LIMIT 1
                        ];
        pageID = thePacklist.Onsite_Hardware_Request_Items__r[0].id;
        for ( integer i=0; i<thePacklist.Onsite_Hardware_Request_Items__r.size(); i++ ){
            //look for the first item that still needs to be returned
            if (thePacklist.Onsite_Hardware_Request_Items__r[i].Returned__c < 100){
                pageID = thePacklist.Onsite_Hardware_Request_Items__r[i].id;
                i = thePacklist.Onsite_Hardware_Request_Items__r.size();
            }
        }
        PageReference p = new PageReference('/apex/CAM_ReturnShipment?id=' + pageID);
        p.setRedirect(true);
        System.System.debug('Redirecting to CAM_ReturnShipment with the pageID');
        return p;
    }//redirectMe

    public List<SelectOption> getWarehouses() {
        List<SelectOption> options = new List<SelectOption>();
        List<Cvent_Warehouse__c> wList = new List<Cvent_Warehouse__c>();
        
        //add the default option
        options.add(new SelectOption('', '-- Select Warehouse --'));
        wList = [SELECT ID, Name, Country__c FROM Cvent_Warehouse__c ORDER BY Name ASC];
        
        for (integer i = 0; i < wList.size(); i++) {
            options.add(new SelectOption(wList[i].ID, wList[i].Name));
        }

        return options;
    }//getWarehouses

    public void returnAssets(){
        //if the warehouse is not selected, stop the process. We need to know where the items are going back in.
        if (warehouseId == null){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select the Return Warehouse and try again'));
        } else {
            String[] idList = new String[0];
            idList = scannedIdList.split('\n');
            //somehow some browsers use \n or \r or both to indicate newline. will remove both, just in case
            for (integer i=0; i<idList.size(); i++){
                idList[i] = idList[i].replace('\r', '');
            }
            Integer[] results = new Integer[] {0, 0, 0, 0, 0};
            //Results: Total input, Duplicate, Not found, Found but not deployed, Returned
            results[0] = idList.size();
            
            for (integer i1=0; i1<idList.size(); i1++){
                Integer count = 0;
                for (integer i2=0; i2<idList.size(); i2++){
                    if (idList[i1] == idList[i2]){
                        count++;
                    }
                }
                if (count > 1) {
                    results[1]++;
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'Duplicate barcode found: ' + idList[i1]));
                    idList.remove(i1);
                    i1--;
                }
            }//duplicate check


            List<Cvent_Asset__c> assets = new List<Cvent_Asset__c>();
            try {
                //find the assets based on the Asset Tags
                assets = [SELECT Id, Name, Asset_Tag__c, Status__c FROM Cvent_Asset__c WHERE Asset_Tag__c IN :idList];
            } catch(Exception ex){
                assets = null;
                //ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'None of the barcodes scanned matched an asset'));
            }

            //ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,'IDList size: ' + idList.size()));
            //ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,'assets size: ' + assets.size()));

            //check if any barcodes are not actual assets. remove the ones that match, therefore
            //whatever is remaining in the original list, is Not Found.
            if (idList.size() <> assets.size()){
                for (integer i1=0; i1<idList.size(); i1++){
                    for (integer i2=0; i2<assets.size(); i2++){
                        if (idList[i1] == assets[i2].Asset_Tag__c){
                            idList.remove(i1);
                            i1--;
                            i2 = assets.size();//exit the inner loop
                        }
                    }
                }
                
                //inform the user about unmatched barcode(s)
                for (String s : idList){
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Barcode not found: ' + s));
                    results[2]++;
                }
            }


            //matched barcodes
            if (assets <> null) {
                String[] assetIdList = new String[0];

                for (integer i=0; i<assets.size(); i++){
                    if (assets[i].Status__c == 'Available'){
                        // if the status is Available, then the asset cannot be returned
                        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'Barcode found but Asset was already marked as returned: ' + assets[i].Asset_Tag__c));
                        assets.remove(i);
                        i--;
                        results[3]++;
                    } else {
                        //the remaining ones should be ok to return
                        assets[i].Status__c = 'Available';
                        assets[i].Location_Current__c = warehouseId;

                        update assets[i];
                        results[4]++;
                        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Asset returned: ' + assets[i].Asset_Tag__c));

                        assetIdList.add(assets[i].id);
                    }
                }//for loop for each asset scanned

                //find the corresponding Packlist Items and mark them as Returned 
                List<Packlist_Item__c> plItems = new List<Packlist_Item__c>();
                plItems = [SELECT id, name, Date_Actual_Return__c, Onsite_Hardware_Request_Item__c
                            FROM Packlist_Item__c
                            WHERE Cvent_Asset__c IN :assetIdList AND 	Date_Actual_Return__c = null
                            ];

                //updating the Actual Return Date marks the Packlist Item as returned
                for (Packlist_Item__c p: plItems){
                    p.Date_Actual_Return__c = System.today();
                    update p;
                }
                
                //the page is designed to show details of a single packlist. set the OHRI ID as the parameter to refresh it accordinly. 
                if ( plItems.size() > 0 ) { 
                    pageID = plItems[0].Onsite_Hardware_Request_Item__c;
                    ApexPages.currentPage().getParameters().put('id', plItems[0].Onsite_Hardware_Request_Item__c);
                    anonMode = false;
                    refreshPacklist();
                    refreshPacklistItems();
                } 
                //TODO: warn the user that there are other items being returned
                //TODO: check if the asset is in working condition. if not, highlight it


            }//main check for matched
        
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'--- Results ---'));
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Barcodes entered: ' + results[0]));
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Duplicates: ' + results[1]));
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Barcode not found: ' + results[2]));
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Barcode found but Asset was already marked as returned: ' + results[3]));
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Asset returned: ' + results[4]));

        }//initial warehouse check
    }//returnAssets

    public void returnAsset(){
		String packlistItemIDtobeReturned = ApexPages.currentPage().getParameters().get('packlistItemIDtobeReturned');
		String assetIDtobeReturned = ApexPages.currentPage().getParameters().get('assetIDtobeReturned');

        if (warehouseId == null){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select the Return Warehouse and try again'));
        } else {
            Cvent_Asset__c asset = new Cvent_Asset__c();
            asset = [SELECT ID, Name, Status__c, Asset_Tag__c FROM Cvent_Asset__c WHERE ID =:assetIDtobeReturned LIMIT 1];
            asset.Status__c = 'Available';
            asset.Location_Current__c = warehouseId;

            update asset;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Asset returned: ' + asset.Asset_Tag__c));

            Packlist_Item__c packlistItem = new Packlist_Item__c();
            packlistItem = [SELECT id, name, Date_Actual_Return__c FROM Packlist_Item__c WHERE ID =: packlistItemIDtobeReturned LIMIT 1];
            packlistItem.Date_Actual_Return__c = System.today();
            update packlistItem;

            refreshPacklist();
            refreshPacklistItems();
        }
    }//returnAsset

    public void confirmReturnedQuantity(){
        if (warehouseId == null){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select the Return Warehouse and try again'));
        } else {
            
            //TODO: check for negative numbers
            update theItem;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Item marked as returned'));

            refreshPacklist();
            refreshPacklistItems();
        }
    }//confirmReturnedQuantity
}