objects/EB_Agent_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Agent_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EB_Project_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent_Score__c</fullName>
        <formula>IF(ISPICKVAL(Agent_Skill_Group__c,'1'),'1',IF(ISPICKVAL(Agent_Skill_Group__c,'2'),'2',
   IF(ISPICKVAL(Agent_Skill_Group__c,'3'),'3',IF(ISPICKVAL(Agent_Skill_Group__c,'5'),'5',
   IF(ISPICKVAL(Agent_Skill_Group__c,'ARA'),'6',IF(ISPICKVAL(Agent_Skill_Group__c,'Enterprise Project'),'7',IF(ISPICKVAL(Agent_Skill_Group__c,'Event Quarterback Project'),'8','')))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agent Score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Assignment__c</fullName>
        <label>Current Assignment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Client Visit</fullName>
                </value>
                <value>
                    <fullName>HQ Visit</fullName>
                </value>
                <value>
                    <fullName>Mentoring</fullName>
                </value>
                <value>
                    <fullName>Out of Office</fullName>
                </value>
                <value>
                    <fullName>Training Alignment</fullName>
                </value>
                <value>
                    <fullName>Do Not Assign EB (Other Reason)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Work_Load_hrs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Work Load (hrs.)</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_also_Handling_Scope_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This should be set to true for agents working on scope requests.</description>
        <inlineHelpText>Select if agent is also eligible to work on scope request.</inlineHelpText>
        <label>Is also Handling Scope Request ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Project_Assignment__c</fullName>
        <inlineHelpText>Stores the last project assignment date and time.</inlineHelpText>
        <label>Last_Project_Assignment</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Max_Workload_Agent_Hrs__c</fullName>
        <defaultValue>90</defaultValue>
        <label>Max Workload/ Agent(Hrs.)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_of_Projects_Per_Week__c</fullName>
        <defaultValue>2</defaultValue>
        <inlineHelpText># of new projects that can be assigned to a Agent per week.</inlineHelpText>
        <label>Max # of projects per week</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Millisecond__c</fullName>
        <label>Millisecond</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Active__c</fullName>
        <formula>Agent_Name__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_Advanced_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Advanced Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Complex_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Complex Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Medium_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Medium Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Projects_Agent__c</fullName>
        <defaultValue>7</defaultValue>
        <label>Max Number of Projects to be Assigned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Projects Assigned</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Simple_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Simple Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EB/CC Agent Profile</label>
    <nameField>
        <label>EB Agent Profile</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EB/CC Agent Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event_Builder_Survey_Q_A__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <description>Stores the answer type for survey questions.</description>
        <label>Answer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Attachment1</fullName>
                </value>
                <value>
                    <fullName>Attachment2</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Country Name</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>MultiSelect1</fullName>
                </value>
                <value>
                    <fullName>MultiSelect2</fullName>
                </value>
                <value>
                    <fullName>Picklist - Complexity</fullName>
                </value>
                <value>
                    <fullName>Picklist - Yes/No</fullName>
                </value>
                <value>
                    <fullName>Static Display</fullName>
                </value>
                <value>
                    <fullName>Sub Questions</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Text Area</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Stores the answer for Survey Question's.</description>
        <label>Answer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Survey_for_EB__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Survey for EB</label>
        <referenceTo>Internal_Survey_for_EB__c</referenceTo>
        <relationshipLabel>Event Builder Survey Q &amp; A's</relationshipLabel>
        <relationshipName>Internal_Surveys_for_EB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Question__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Differentiate between the question's and the survey responses.</description>
        <inlineHelpText>Please select this checkbox, if you're creating a new question.</inlineHelpText>
        <label>Is Question ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Stores the event builder survey questions.</description>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Stores the sequence of  question on the survey.</description>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Answer_1__c</fullName>
        <label>Sub Answer 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Answer_2__c</fullName>
        <label>Sub Answer 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Answer__c</fullName>
        <label>Sub Answer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Question_1__c</fullName>
        <label>Sub - Question 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Question_2__c</fullName>
        <label>Sub - Question 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Question__c</fullName>
        <description>Stores the sub-question for the parent question.</description>
        <label>Sub - Question</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Type__c</fullName>
        <description>Stores the survey type, it either stores the "Event Builder Scope Request" or "Event Builder Rush Request".</description>
        <label>Survey Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scope Request</fullName>
                </value>
                <value>
                    <fullName>Rush Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Builder Survey Q &amp; A</label>
    <nameField>
        <displayFormat>EBSQA - {YYYY}{MM}-{0000}</displayFormat>
        <label>Event Builder Survey Q &amp; A Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Builder Survey Q &amp; A's</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Internal_Survey_for_EB__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Event_Builder_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Internal Surveys for EB</relationshipLabel>
        <relationshipName>Internal_Surveys_for_EB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Respondent_Email__c</fullName>
        <label>Respondent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Survey_Respondent__c</fullName>
        <description>Stores the name of person, who fills the survey.</description>
        <label>Survey Respondent</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Type__c</fullName>
        <label>Survey Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rush Request</fullName>
                </value>
                <value>
                    <fullName>Scope Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Internal Survey for EB</label>
    <nameField>
        <displayFormat>Survey-{YYYY}{MM}-{0000}</displayFormat>
        <label>Internal Survey for EB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Surveys for EB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Professional_Services_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PSGs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Builder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Event Builder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSP_Year__c</fullName>
        <formula>TEXT(YEAR(DATEVALUE(CreatedDate)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PSP Year</label>
        <type>Text</type>
    </fields>
    <description>(List of all Additional Services)</description>
    <label>PSP</label>
    <nameField>
        <displayFormat>PSPs-{YYYY} #{0000}#</displayFormat>
        <label>PSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ScopeRequestSurvey_Cont.cls
/**
* Author : Sandeep Kumar
* Date : 02 June, 2017
* Description : ScopeRequestSurvey_Cont class fullfills below functionalities,
* 1) This class is called from a custom button (Create Scope Request) provided on the Account standard page for Account Managers. 
* 2) Survey form is filled by the account manager and it creates a case to handle further conversation for scope request.
* Cases are assigned to EB Agent Profiles who are eligible for working in the scope request. This eligibity is decided by the EB Leadership by selecting "Is also Handling Scope Request's".
* VF Page - ScopeRequestSurvey_StartPage,ScopeRequestSurvey_ResponsePage and ScopeRequestSurvey_FinishPage
* Scope Request Form - ScopeRequestPreview_Page
* Test Class - ScopeRushRequestSurvey_Cont_Test
*/
public class ScopeRequestSurvey_Cont{ 
    public Id accountId;
    public string surveyType;
    public string accountName;     
    public Id internalSurveyForEBObjId;    
    public string respondentName {get;set;}
    public string respondentFirstName {get;set;}
    public string respondentLastName {get;set;}
    public string respondentEmailAddress {get;set;}
    public string selectedCountry {get;set;}   
    public Boolean showMultiSelect1Question {get;set;}
    public string selectedMultiSelect1Question {get;set;}
    public string selectedMultiSelectYesNoQuestion{get;set;}    
    public List<Event_Builder_Survey_Q_A__c> surveyResultList{get;set;}
    public List<Event_Builder_Survey_Q_A__c> surQuestnAnsList{get;set;}
    public Event_Builder_Survey_Q_A__c surveyResponseObj;
    public List<Event_Builder_Survey_Q_A__c> surveyResponseList;
    public final static Id eventBuilderLeadersQueueId = Label.Event_Builder_Leaders_Queue_Id;       
    
    //Default Constructor
    public ScopeRequestSurvey_Cont(){  
        surveyResultList = new List<Event_Builder_Survey_Q_A__c>();
        surQuestnAnsList = new List<Event_Builder_Survey_Q_A__c>();                    
        if(apexpages.currentpage().getparameters().get('surveyType') == 'scopeRequest'){
            surveyType = 'Scope Request';
        }
        if(surveyType != null){
            accountId = apexpages.currentpage().getparameters().get('id');
            accountName = apexpages.currentpage().getparameters().get('accountName');
            for(Event_Builder_Survey_Q_A__c sqa :[select Id,Sequence__c,Question__c,Answer_Type__c,
                                                  Survey_Type__c,Sub_Question__c,Sub_Answer__c,Sub_Question_1__c,
                                                  Sub_Question_2__c,Answer__c,
                                                  Sub_Answer_1__c,Sub_Answer_2__c
                                                  from Event_Builder_Survey_Q_A__c 
                                                  where Survey_Type__c =:surveyType AND Is_Question__c = true ORDER BY Sequence__c ASC]){
                                                      if(sqa.Sequence__c == 1){
                                                          sqa.Answer__c = accountName;
                                                      }  
                                                      surQuestnAnsList.add(sqa);
                                                  }        
            this.surQuestnAnsList = surQuestnAnsList;
        }else{
            Id internalSurveyForEBId = apexpages.currentpage().getparameters().get('id');
            for(Event_Builder_Survey_Q_A__c sqa :[select Id,Answer__c,Internal_Survey_for_EB__r.Survey_Respondent__c,
                                                  Internal_Survey_for_EB__r.Respondent_Email__c,Sequence__c,
                                                  Question__c,Survey_Type__c,Answer_Type__c,Sub_Question__c,
                                                  Sub_Answer__c,Sub_Question_1__c,Sub_Question_2__c,
                                                  Sub_Answer_1__c,Sub_Answer_2__c
                                                  from Event_Builder_Survey_Q_A__c 
                                                  where Internal_Survey_for_EB__c =:internalSurveyForEBId ORDER BY Sequence__c ASC]){
                                                      system.debug('Answer==='+sqa.Answer__c);
                                                      surveyResultList.add(sqa);                                                            
                                                      respondentName = sqa.Internal_Survey_for_EB__r.Survey_Respondent__c;
                                                      respondentEmailAddress = sqa.Internal_Survey_for_EB__r.Respondent_Email__c;
                                                  } 
            this.surveyResultList = surveyResultList;
        }         
    }
    
    // Method responsible for showing countries on VF - Page
    public List<SelectOption> getCountries(){
        // Declare Selectoption List that will store all the available countires.
        List<SelectOption> countires = new List<SelectOption>();
        // Describe call to get all the countires with country code.
        Schema.DescribeFieldResult fieldResult = User.Countrycode.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();        
        // First option will be shown as blank
        countires.add(new SelectOption('--None--','--None--'));
        for( Schema.PicklistEntry f : ple){           
            countires.add(new SelectOption(f.getLabel(),f.getLabel()));
        }       
        return countires;
    }
    
    // Method responsible for showing Yes/ No options on VF - Page
    public List<SelectOption> getAnswers(){
        // Declare Selectoption List that will store all the available countires.
        List<SelectOption> answers = new List<SelectOption>();
        answers.add(new SelectOption('--None--','--None--'));
        answers.add(new SelectOption('Yes','Yes'));
        answers.add(new SelectOption('No','No'));
        return answers;
    }
    // Method called from the MultiSelect1Question onChange event.
    public void MultiSelect1QuestionVisibility(){   
        if(selectedMultiSelect1Question == 'Yes'){
            showMultiSelect1Question = true;
        }else{
            showMultiSelect1Question = false;
        }
        return; 
    }
    
    // Button called from Scope Request Start Page
    public PageReference scopeRequestStartPage(){ 
        Internal_Survey_for_EB__c evntBuilderSurveyObj = new Internal_Survey_for_EB__c();
        if(accountId!= null){
            evntBuilderSurveyObj.Account__c = accountId;
        }
        evntBuilderSurveyObj.Survey_Respondent__c = respondentFirstName+' '+respondentLastName;
        evntBuilderSurveyObj.Respondent_Email__c = respondentEmailAddress;
        evntBuilderSurveyObj.Survey_Type__c = surveyType;
        
        try{
            insert evntBuilderSurveyObj;
            system.debug('evntBuilderSurveyObj=='+evntBuilderSurveyObj);
            internalSurveyForEBObjId = evntBuilderSurveyObj.Id;
            return Page.ScopeRequestSurvey_ResponsePage;       
        }Catch(Exception exp){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error uploading file'));
            system.debug('Exception==1='+exp.getMessage());            
            return null;
        }
    }
    
    // Button called from Scope Request Finish Page
    public PageReference scopeRequestFinish(){       
        surveyResponseList = new List<Event_Builder_Survey_Q_A__c>();      
        for(Event_Builder_Survey_Q_A__c sqa :surQuestnAnsList){
            // Instatiate Event Builder Survey Q A Object
            surveyResponseObj = new Event_Builder_Survey_Q_A__c();
            surveyResponseObj.Internal_Survey_for_EB__c = internalSurveyForEBObjId; 
            surveyResponseObj.Question__c = sqa.Question__c;
            surveyResponseObj.Sub_Question__c = sqa.Sub_Question__c;  
            surveyResponseObj.Sub_Answer__c = sqa.Sub_Answer__c;  
            surveyResponseObj.Answer_Type__c = sqa.Answer_Type__c;
            surveyResponseObj.Sequence__c = sqa.Sequence__c;
            surveyResponseObj.Survey_Type__c = sqa.Survey_Type__c;
            if(sqa.Answer_Type__c == 'Country Name'){
                surveyResponseObj.Answer__c = selectedCountry;
                surveyResponseList.add(surveyResponseObj);
            }else if(sqa.Answer_Type__c == 'MultiSelect1' && selectedMultiSelect1Question != null){
                surveyResponseObj.Answer__c = selectedMultiSelect1Question;
                surveyResponseList.add(surveyResponseObj);
            }else if(sqa.Answer_Type__c == 'Picklist - Yes/No' && selectedMultiSelectYesNoQuestion != null){
                surveyResponseObj.Answer__c = selectedMultiSelectYesNoQuestion;
                surveyResponseList.add(surveyResponseObj);
            }else{
                surveyResponseObj.Answer__c = sqa.Answer__c;
                surveyResponseList.add(surveyResponseObj);
            }
        }         
        try{
            if(!surveyResponseList.isEmpty()){                
                insert surveyResponseList;
                // Call the method to create Case and Assign Case to Agent.
                createCaseAndRunAssignmentRules(accountId,internalSurveyForEBObjId,respondentEmailAddress);
                // Redirect User to Survey Submitted Page.
                return Page.ScopeRequestSurvey_FinishPage;
            }else{
                return null;
            }
        }Catch(Exception exp){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error uploading file'));
            system.debug('Exception==2='+exp.getMessage());
            return null;
        }       
    }
    
    // Button called from Scope Request Response Page
    public PageReference scopeRequestCancel(){        
        return Page.ScopeRequestSurvey_StartPage; 
    } 
    
    public static void createCaseAndRunAssignmentRules(Id accountId, Id evntBuilderSurveyId,String contactEmail){
        Professional_Services_Project__c PSPObj;
        String currentYear = String.valueOf(System.today().Year());
        Integer currentYearPSPCount = 0;
        List<Professional_Services_Project__c> PSPObjList = [Select Id,Account__c From Professional_Services_Project__c where Account__c =:accountId and PSP_Year__c =:currentYear];
        
        // Create PSP if there is no record exists for the current year.
        if(PSPObjList.Size() == 0){
            PSPObj = new Professional_Services_Project__c();
            PSPObj.Account__c = accountId;
            PSPObj.Event_Builder__c = true;
            insert PSPObj;
        }
        
        // Create new Case for fullfilling survey request and this case shall be assigned Event Builder Rep based on rules.                  
        Case newCase = new Case();
        newCase.AccountId = accountId;
        newCase.SuppliedEmail = contactEmail;
        newCase.RecordTypeId = RecordTypeUtil.getRecordTypeIDByDevName('Case','Eventbuilder');
        newCase.Status = 'Open';
        newCase.Priority = 'Medium';
        newCase.Origin = 'Admin';
        newCase.Client_Services_Category__c = 'Scope Call';
        newCase.Subject = 'A new Scope Request has been created.';
        newCase.Description = 'Please refer the attached email for more information.'; 
        if(PSPObjList.Size() == 1){
            newCase.PSP__c = PSPObjList[0].Id;
        }else{
            newCase.PSP__c = PSPObj.Id;
        }
        insert newCase; 
        
        // Updates the case Id on the Survey Record.
        Internal_Survey_for_EB__c intSurveyForEBObj = new Internal_Survey_for_EB__c();
        intSurveyForEBObj.Id = evntBuilderSurveyId;
        intSurveyForEBObj.Case__c = newCase.Id;
        update intSurveyForEBObj;
        
        // Prepare Agent score to EB Project Assignment Map
        List<Id> agentIdList = new List<Id>(); 
        Map<Integer,List<Id>> agentScoreToAgentIdsMap = new Map<Integer,List<Id>>();
        Map<Id,EB_Agent_Profile__c> agentIdEBAgentProfileObjMap = new Map<Id,EB_Agent_Profile__c>(); 
        
        for(EB_Agent_Profile__c AssignRec : [Select Id,Agent_Name__c,Agent_Score__c,Last_Project_Assignment__c,of_Projects__c,of_Projects_Agent__c,Max_Workload_Agent_Hrs__c,Max_of_Projects_Per_Week__c,Current_Assignment__c,Current_Work_Load_hrs__c,of_Simple_Projects__c,of_Medium_Projects__c,Millisecond__c,of_Advanced_Projects__c,of_Complex_Projects__c from EB_Agent_Profile__c where Is_also_Handling_Scope_Request__c = true AND User_Active__c = true Order By Agent_Score__c,Last_Project_Assignment__c]){
            // Prepare a with User Id to EbAgent Profile Id.
            agentIdEBAgentProfileObjMap.put(AssignRec.Agent_Name__c, AssignRec);            
            // Add agent Id in the list. It will be used later for the auto assignment.         
            agentIdList.add(AssignRec.Agent_Name__c);
        }
        
        String newAssigneeId = '';
        
        system.debug('agentIdList'+agentIdList);
        // Assign the case to EB Agent Profile.
        for(Id agentId :agentIdList){
            if(agentIdEBAgentProfileObjMap.containsKey(agentId)){
                if(agentIdEBAgentProfileObjMap.get(agentId).Current_Assignment__c == 'Available'){
                    if(agentIdEBAgentProfileObjMap.get(agentId).of_Projects__c < agentIdEBAgentProfileObjMap.get(agentId).of_Projects_Agent__c && agentIdEBAgentProfileObjMap.get(agentId).Current_Work_Load_hrs__c < agentIdEBAgentProfileObjMap.get(agentId).Max_Workload_Agent_Hrs__c){
                        newAssigneeId = agentId;
                        break;
                    }
                }                               
            }                    
        }
        // Declare Eb Agent Profile Object.
        EB_Agent_Profile__c eBAgentProfile;
        Set<Id> eBAgentProfileIds = new Set<Id>();
        Boolean sendEmail = false;
        // Instantiate List
        List<EB_Agent_Profile__c> eBAgentProfilesToUpdateList = new List<EB_Agent_Profile__c>();
        // Assign the case to EB Agent Profile.
        if(newAssigneeId != null && newAssigneeId != ''){
            // Assign new Agent Id
            newCase.OwnerId =Id.valueOf(newAssigneeId);   
            if(agentIdEBAgentProfileObjMap.containsKey(newAssigneeId) && !eBAgentProfileIds.contains(agentIdEBAgentProfileObjMap.get(newAssigneeId).Id)){
                // Update the Last Project Assignment Details on EB Agent Profile.
                eBAgentProfile  = new EB_Agent_Profile__c();
                eBAgentProfile.Id = agentIdEBAgentProfileObjMap.get(newAssigneeId).Id;
                eBAgentProfile.Last_Project_Assignment__c = System.Datetime.now();
                eBAgentProfilesToUpdateList.add(eBAgentProfile);
                // Add Agent Profile Id to avoid duplicate Ids.
                eBAgentProfileIds.add(eBAgentProfile.Id);                    
            }
        }else{
            // Assign to Queue if their is no available user found.                
            Database.DMLOptions dmo = new Database.DMLOptions(); 
            dmo.EmailHeader.triggerUserEmail = true; 
            newCase.OwnerId = eventBuilderLeadersQueueId;
            newCase.setOptions(dmo);  
            sendEmail = true;
        }  
        // Update new Case owner
        update newCase;
        // Updates EB Agent Profiles.
        if(!eBAgentProfilesToUpdateList.isEmpty())
            update eBAgentProfilesToUpdateList;
        // Send email to newly assigned owner's.
        if(!sendEmail){
            EBSurveyNotificationEmail sendAssignementEmail = new EBSurveyNotificationEmail();
            sendAssignementEmail.sendEmailToNewCaseOwner(evntBuilderSurveyId);
        }
    }     
}