objects/EB_Agent_Profile__c.object
<CustomObject>
    <fields>
        <fullName>of_Advanced_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Advanced Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Complex_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Complex Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Medium_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Medium Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Projects__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Projects Assigned</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EB/CC Agent Profile</label>
    <nameField>
        <label>EB Agent Profile</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EB/CC Agent Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EB_SB_Builder__c.object
<CustomObject>
    <fields>
        <fullName>AccountCustom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EB SB Projects</relationshipLabel>
        <relationshipName>EB_SB_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_s_To_Go__c</fullName>
        <formula>Expected_Launch_Date__c-TODAY()</formula>
        <label>Day(s) To Go</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EB_Agent_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EB Agent Profile</label>
        <referenceTo>EB_Agent_Profile__c</referenceTo>
        <relationshipLabel>EB SB Projects (EB Agent Profile)</relationshipLabel>
        <relationshipName>EB_SB_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Launch_Date__c</fullName>
        <label>Expected Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hrs_Pending_for_Completion__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hrs Pending for Completion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountCustom__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Account.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Contact_Associated__r.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EB SB Projects</relationshipLabel>
        <relationshipName>EB_SB_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSP_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSP ID</label>
        <referenceTo>Professional_Services_Project__c</referenceTo>
        <relationshipName>EB_SB_Builders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Complexity__c</fullName>
        <label>Project Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Simple</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>3-Advanced</fullName>
                </value>
                <value>
                    <fullName>4-Complex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Health__c</fullName>
        <label>Project Health</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Amber</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Launched_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Launched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Received_Date__c</fullName>
        <label>Project Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Reviewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Reviewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Stage__c</fullName>
        <label>Project Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Information Received</fullName>
                </value>
                <value>
                    <fullName>Setup Call Scheduled</fullName>
                </value>
                <value>
                    <fullName>Setup Call Done</fullName>
                </value>
                <value>
                    <fullName>Working on First Draft</fullName>
                </value>
                <value>
                    <fullName>First Draft Completed</fullName>
                </value>
                <value>
                    <fullName>First Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>First Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Second Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Second Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Third Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Third Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Fourth Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Fourth Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Additional Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>All the Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Event Testing</fullName>
                </value>
                <value>
                    <fullName>Event Launched</fullName>
                </value>
                <value>
                    <fullName>Sign Off Done</fullName>
                </value>
                <value>
                    <fullName>Premium Services - Post Launch Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yet to Start</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Status_del__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yet To Start</fullName>
                </value>
                <value>
                    <fullName>Information Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Post Launch Support</fullName>
                </value>
                <value>
                    <fullName>On Hold - Leadership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type_del__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abstract Management Build</fullName>
                </value>
                <value>
                    <fullName>Additional Changes</fullName>
                </value>
                <value>
                    <fullName>Affinity Partner Build</fullName>
                </value>
                <value>
                    <fullName>Affinity Partner Build - Premium</fullName>
                </value>
                <value>
                    <fullName>AllianceTech - EMT Build</fullName>
                </value>
                <value>
                    <fullName>Appointments Build</fullName>
                </value>
                <value>
                    <fullName>ARA - Active</fullName>
                </value>
                <value>
                    <fullName>ARA - Inactive</fullName>
                </value>
                <value>
                    <fullName>ARA Projects</fullName>
                </value>
                <value>
                    <fullName>Creative Services - EB</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Premium</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Regular</fullName>
                </value>
                <value>
                    <fullName>Creative Services - Rush</fullName>
                </value>
                <value>
                    <fullName>Custom Pages</fullName>
                </value>
                <value>
                    <fullName>Custom Task</fullName>
                </value>
                <value>
                    <fullName>Daily/Monthly Report</fullName>
                </value>
                <value>
                    <fullName>Dedicated Support</fullName>
                </value>
                <value>
                    <fullName>Demo eMarketing</fullName>
                </value>
                <value>
                    <fullName>Demo Event</fullName>
                </value>
                <value>
                    <fullName>Demo Survey</fullName>
                </value>
                <value>
                    <fullName>EB Mentoring</fullName>
                </value>
                <value>
                    <fullName>EMT Build</fullName>
                </value>
                <value>
                    <fullName>Enterprise Project</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Express</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Premium</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Premium Rush</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Regular</fullName>
                </value>
                <value>
                    <fullName>Event Builder - Rush</fullName>
                </value>
                <value>
                    <fullName>Event Builder - SU4</fullName>
                </value>
                <value>
                    <fullName>Event Quarterback Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Builder</fullName>
                    <default>true</default>
                    <label>Event Builder</label>
                </value>
                <value>
                    <fullName>Survey Builder</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Graphics</fullName>
                </value>
                <value>
                    <fullName>Demo Builder (for Harmeet's Team)</fullName>
                </value>
                <value>
                    <fullName>Creative Services</fullName>
                </value>
                <value>
                    <fullName>Scope Call</fullName>
                </value>
                <value>
                    <fullName>Internal Events</fullName>
                </value>
                <value>
                    <fullName>TPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains all EB/SB projects</description>
    <label>EB SB Project</label>
    <nameField>
        <displayFormat>Project-{YYYY}{MM}-{0000}</displayFormat>
        <label>EB/SB Builders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EB SB Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EBProjectCustomRelatedList_ContExt.cls
/*Author: Sandeep Kumar
* Date: 12 April 2017
* Description: Update Pending Hrs for Project Completion. 
* Class is used for displaing records on EBProjectCustomRelatedList_Page and EBProjectCapacityDashboard_Page.
* Test Class : EBProjectCustomRelatedList_ContExt_Test
* VF - EBProjectCustomRelatedList_Page and EBProjectCapacityDashboard_Page
*/
public class EBProjectCustomRelatedList_ContExt {
    
    public List<EB_SB_Builder__c> eBProjList;
    public Boolean showDashboard{get;set;} 
    public Boolean showChildRecords{get;set;} 
    public Map<Id,List<EB_SB_Builder__c>> agentIdToEBProjMap{get;set;} 
    public Map<EB_Agent_Profile__c,List<EB_SB_Builder__c>> agentProfileToEBProjMap{get;set;} 
    public String loggedUser{get;set;}
    // The extension constructor initializes the private member
    // variable writeOff by using the getRecord method from the standard
    // controller.
    public EBProjectCustomRelatedList_ContExt(ApexPages.StandardController stdController){
        loggedUser = UserInfo.getName();
        showChildRecords = false;
        showDashboard = false;
        string str = apexpages.currentpage().getparameters().get('id');
        /// Collection used for showing related records with agent on the agent profile.
        agentIdToEBProjMap = new Map<Id,List<EB_SB_Builder__c>>();
        // Collection used for showing all EB projects on PCS Capacity Dashboard to Leadership.
        agentProfileToEBProjMap = new Map<EB_Agent_Profile__c,List<EB_SB_Builder__c>>();
        if(str != null){
            for(EB_SB_Builder__c EbProj : [Select Id,Name,EB_Agent_Profile__c,Project__c,Project_Launched_del__c,
                                           Project_Stage__c,Project_Reviewed__c,Project_Health__c,Hrs_Pending_for_Completion__c,Day_s_To_Go__c,
                                           Project_Received_Date__c,Project_Type_del__c,Project_Status__c,
                                           Project_Complexity__c,PSP_ID__c,Opportunity__c,Project_Status_del__c,
                                           AccountCustom__c,Expected_Launch_Date__c
                                           from EB_SB_Builder__c where EB_Agent_Profile__c =:str AND Project_Status_del__c NOT IN ('Completed','Cancelled') Order By Expected_Launch_Date__c ASC])
            {
                //Instantiate List
                eBProjList = new List<EB_SB_Builder__c>();            
                // Prepare Opportunity Id to List of Opp Line Items.
                if(agentIdToEBProjMap.containsKey(EbProj.EB_Agent_Profile__c)){
                    eBProjList = agentIdToEBProjMap.get(EbProj.EB_Agent_Profile__c);
                    eBProjList.add(EbProj);
                    agentIdToEBProjMap.put(EbProj.EB_Agent_Profile__c, eBProjList);
                }else{
                    eBProjList.add(EbProj);
                    agentIdToEBProjMap.put(EbProj.EB_Agent_Profile__c, eBProjList);
                }
            }   
            if(agentIdToEBProjMap.size() > 0){
                showChildRecords =true;
            }
        }else{
            for(EB_Agent_Profile__c EbAgentProfile : [Select Id,Name,of_Advanced_Projects__c,of_Complex_Projects__c,of_Medium_Projects__c,of_Projects__c,of_Projects_Agent__c,of_Projects_Completed__c,of_Simple_Projects__c,
                                                      Agent_Name__c,Agent_Score__c,Agent_Shift__c,Agent_Skill_Group__c ,Agent_Status__c,Agent_Status_Indicator__c,Current_Assignment__c,Current_FY_Quality_Score__c,Current_Work_Load_hrs__c,
                                                      Max_Workload_Agent_Hrs__c,Process_Scores__c,Quality_Scores_Overall__c,VSAT_Current_FY__c,Max_of_Projects_Per_Week__c,VSAT_Overall__c,(Select Id,Name,EB_Agent_Profile__c,Project__c,Project_Launched_del__c,
                                                                                                                                                                Project_Stage__c,Project_Reviewed__c,Project_Health__c,Hrs_Pending_for_Completion__c,Day_s_To_Go__c,Project_Received_Date__c,Project_Type_del__c,Project_Status__c,Project_Complexity__c,PSP_ID__c,Opportunity__c,Project_Status_del__c,AccountCustom__c,Expected_Launch_Date__c
                                                                                                                                                                from EB_SB_Projects__r where EB_Agent_Profile__c !=null AND Project_Status_del__c NOT IN ('Completed','Cancelled') Order By Expected_Launch_Date__c ASC) from EB_Agent_Profile__c Order By Name ASC])
            {
                //Instantiate List
                eBProjList = new List<EB_SB_Builder__c>();           
                // Get all the projects with this Agent Profile.
                for(EB_SB_Builder__c EbProj : EbAgentProfile.EB_SB_Projects__r){
                    // Prepare Opportunity Id to List of Opp Line Items.
                    eBProjList.add(EbProj);
                } 
                agentProfileToEBProjMap.put(EbAgentProfile, eBProjList);
            }
            if(!agentProfileToEBProjMap.isEmpty()){
                showDashboard = true;
            }
        }     
    }        
}