objects/EB_SB_Builder__c.object
<CustomObject>
    <fields>
        <fullName>AccountCustom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EB SB Projects</relationshipLabel>
        <relationshipName>EB_SB_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <formula>PSP_ID__r.Account__r.Name</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N00000008IWSzEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.AccountCustom__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Account.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.Contact_Associated__r.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EB SB Projects</relationshipLabel>
        <relationshipName>EB_SB_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSP_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSP ID</label>
        <referenceTo>Professional_Services_Project__c</referenceTo>
        <relationshipName>EB_SB_Builders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Complexity__c</fullName>
        <label>Project Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Simple</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>3-Advanced</fullName>
                </value>
                <value>
                    <fullName>4-Complex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Stage__c</fullName>
        <label>Project Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Information Received</fullName>
                </value>
                <value>
                    <fullName>Setup Call Scheduled</fullName>
                </value>
                <value>
                    <fullName>Setup Call Done</fullName>
                </value>
                <value>
                    <fullName>Working on First Draft</fullName>
                </value>
                <value>
                    <fullName>First Draft Completed</fullName>
                </value>
                <value>
                    <fullName>First Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>First Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Second Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Second Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Third Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Third Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Fourth Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Fourth Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Additional Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>All the Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Event Testing</fullName>
                </value>
                <value>
                    <fullName>Event Launched</fullName>
                </value>
                <value>
                    <fullName>Sign Off Done</fullName>
                </value>
                <value>
                    <fullName>Premium Services - Post Launch Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Status_del__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yet To Start</fullName>
                </value>
                <value>
                    <fullName>Information Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Post Launch Support</fullName>
                </value>
                <value>
                    <fullName>On Hold - Leadership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Builder</fullName>
                    <default>true</default>
                    <label>Event Builder</label>
                </value>
                <value>
                    <fullName>Survey Builder</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Graphics</fullName>
                </value>
                <value>
                    <fullName>Demo Builder (for Harmeet's Team)</fullName>
                </value>
                <value>
                    <fullName>Creative Services</fullName>
                </value>
                <value>
                    <fullName>Scope Call</fullName>
                </value>
                <value>
                    <fullName>Internal Events</fullName>
                </value>
                <value>
                    <fullName>TPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains all EB/SB projects</description>
    <label>EB SB Project</label>
    <nameField>
        <displayFormat>Project-{YYYY}{MM}-{0000}</displayFormat>
        <label>EB/SB Builders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EB SB Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Professional_Services_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PSGs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PSPs</relationshipLabel>
        <relationshipName>PSPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>of_EB__c</fullName>
        <label># of EB</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>(List of all Additional Services)</description>
    <label>PSP</label>
    <nameField>
        <displayFormat>PSPs-{YYYY} #{0000}#</displayFormat>
        <label>PSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Plan_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Addnl_Info_Received_Expected_Date__c</fullName>
        <label>Addnl Info Received-Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Launch_Expected_Date__c</fullName>
        <label>Event Launch Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Setup_Call_Expected_Date__c</fullName>
        <label>Event Setup Call Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Testing_Expected_Date__c</fullName>
        <label>Event Testing Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FD_Completed_Expected_Date__c</fullName>
        <label>First Draft Completed Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_ROC_Completed_Expected_Date__c</fullName>
        <label>1st ROC Completed Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_ROC_Received_Expected_Date__c</fullName>
        <label>1st ROC Received Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2nd_ROC_Completed_Expected_Date__c</fullName>
        <label>2nd ROC Completed Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2nd_ROC_Received_Expected_Date__c</fullName>
        <label>2nd ROC Received Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3rd_ROC_Completed_Expected_Date__c</fullName>
        <label>3rd ROC Completed Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3rd_ROC_Received_Expected_Date__c</fullName>
        <label>3rd ROC Received Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Calculate Weekdays for Milestone based on Request Type and Complexity of a Case.</description>
    <label>Project Plan Milestone</label>
</CustomObject>

objects/Project_Plan_SOW_EB__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>EBSB_Builders_Name__r.Account__c</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Addnl_Info_Received_Expected_Date__c</fullName>
        <label>Addnl Info Received-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Launch_Expected_Date__c</fullName>
        <label>Event Launch Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Setup_Call_Expected_Date__c</fullName>
        <label>Event Setup Call Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Testing_Expected_Date__c</fullName>
        <label>Event Testing Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FD_Completed_Expected_Date__c</fullName>
        <label>FD Completed Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PSP_Id__c</fullName>
        <formula>EBSB_Builders_Name__r.PSP_ID__r.Name</formula>
        <label>PSP Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1st_ROC_Completed_Expected_Date__c</fullName>
        <label>1st ROC Completed-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X1st_ROC_Received_Expected_Date__c</fullName>
        <label>1st ROC Received-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X2nd_ROC_Completed_Expected_Date__c</fullName>
        <label>2nd ROC Completed-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X2nd_ROC_Received_Expected_Date__c</fullName>
        <label>2nd ROC Received-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X3rd_ROC_Completed_Expected_Date__c</fullName>
        <label>3rd ROC Completed Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X3rd_ROC_Received_Expected_Date__c</fullName>
        <label>3rd ROC Received Expected Date</label>
        <type>Date</type>
    </fields>
    <label>Project Plan/SOW EB</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Project Plan/SOW EB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Plan/SOW EB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EBProjUpdateExpLaunchDate_TrigAct_Test.cls
/**
* Author : Sandeep Kumar
* Date : 23 May 2017
* Description : It tests below mentioned class
* 1) EBProjUpdateExpLaunchDateFrmPP_TrigAct
*/
@isTest(seeAllData=false)
public class EBProjUpdateExpLaunchDate_TrigAct_Test {
    private static Opportunity opp;
    private static Account acc; 
    private static Contact con;
    private static Project_Plan_Milestone__c projPlanMilestone;
    private static Professional_Services_Project__c PSP;
    private static EB_SB_Builder__c EBSBRec;
    private static Project_Plan_SOW_EB__c projPlanObj;
    private static Id userProfieId = UserProfileUtil.getProfileIDByName('Customer Care Rep - Product Consultant EB Team');     
    private static User depUser = [Select Id, ProfileId from User where Name = 'CRM Deployment User'];   
    
    // Test for the manualShareRead method
    static testMethod void testExpectedLaunchDateUpdate(){
        system.runAs(depUser){
            Test.startTest();        
            User usr = TestUtil.createUser(userProfieId);          
            insert usr;  
            // Create Account Record.
            acc = TestUtil.createAccount('EB Account 1', 'Biz_Ac');
            insert acc;     
            
            // Create Contact Record.
            con = TestUtil.createContact(acc.id);
            insert con;   
            
            // Create PSP Record.
            Professional_Services_Project__c PSPRec = new Professional_Services_Project__c();
            PSPRec.Account__c = acc.Id;
            PSPRec.of_EB__c = 0;
            insert PSPRec;  
            
            Opportunity o2 = TestUtil.createOpportunity('testOpp','Event','Bid Phase');
            o2.Contact_Associated__c = con.Id;
            o2.AccountId = acc.Id;
            o2.CloseDate = Date.today().addDays(80);
            insert o2;
            
            projPlanMilestone = new Project_Plan_Milestone__c();
            projPlanMilestone.Name = 'Regular Simple';
            projPlanMilestone.Addnl_Info_Received_Expected_Date__c = 0;
            projPlanMilestone.Event_Launch_Expected_Date__c = 17;
            projPlanMilestone.Event_Setup_Call_Expected_Date__c = 0;
            projPlanMilestone.Event_Testing_Expected_Date__c = 16;
            projPlanMilestone.FD_Completed_Expected_Date__c = 3;
            projPlanMilestone.X1st_ROC_Completed_Expected_Date__c = 7;
            projPlanMilestone.X1st_ROC_Received_Expected_Date__c = 5;
            projPlanMilestone.X2nd_ROC_Completed_Expected_Date__c = 11;
            projPlanMilestone.X2nd_ROC_Received_Expected_Date__c = 9;
            projPlanMilestone.X3rd_ROC_Completed_Expected_Date__c = 15;
            projPlanMilestone.X3rd_ROC_Received_Expected_Date__c = 13;
            insert projPlanMilestone;
            
            // Create Eb Project.
            EBSBRec = new EB_SB_Builder__c();
            EBSBRec.PSP_ID__c = PSPRec.Id;
            EBSBRec.Contact__c = con.Id;
            EBSBRec.Opportunity__c = o2.Id;
            EBSBRec.AccountCustom__c = acc.Id;                 
            EBSBRec.Project__c = 'Event Builder';
            EBSBRec.Project_Status_del__c = 'In Progress';            
            EBSBRec.Project_Stage__c = 'Information Received';
            EBSBRec.Project_Complexity__c = '3-Advanced';
            EBSBRec.Project_Type_del__c = 'Event Builder - Regular';            
            EBSBRec.Event_Title__c = '';
            insert EBSBRec;
            
            projPlanObj = new Project_Plan_SOW_EB__c();
            projPlanObj.EBSB_Builders_Name__c = EBSBRec.Id;
            projPlanObj.Expected_Launch_Date__c = Date.today();
            projPlanObj.Project_Received_Date__c = Date.today();
            projPlanObj.Information_Received__c = Date.today();
            projPlanobj.Request_Type__c = 'Regular';
            projPlanobj.Project_Complexity__c = '1-Simple';
            projPlanobj.Project_Plan_Status__c = 'Generate Project plan';
            insert projPlanObj;
            
            // Assertion when Project Plan is created.
            EB_SB_Builder__c eBProject = [Select Id,Expected_Launch_Date__c from EB_SB_Builder__c where Id=:EBSBRec.Id];
            System.assertEquals(Date.today(), eBProject.Expected_Launch_Date__c);
            
            // Update Expected Launch Date on Project Plan Object.
            projPlanObj.Expected_Launch_Date__c = Date.today().addDays(30);
            update projPlanObj;
            
            // Assertion when Project Plan is updated with new Expected launch Date.
            eBProject = [Select Id,Expected_Launch_Date__c from EB_SB_Builder__c where Id=:EBSBRec.Id];
            System.assertEquals(Date.today().addDays(30), eBProject.Expected_Launch_Date__c);  
            
            // Update Expected Launch Date on Project Plan Object.
            projPlanObj.Event_Launch_Revised_Timeline__c = Date.today().addDays(50);
            update projPlanObj;
            
            // Assertion when Project Plan is updated with new Expected launch Date.
            eBProject = [Select Id,Expected_Launch_Date__c from EB_SB_Builder__c where Id=:EBSBRec.Id];
            System.assertEquals(Date.today().addDays(50), eBProject.Expected_Launch_Date__c);                      
            Test.stopTest();
        }        
    }    
}