objects/EB_SB_Builder__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Launch_Date__c</fullName>
        <label>Expected Launch Date</label>
        <type>Date</type>
    </fields>
    <description>Contains all EB/SB projects</description>
    <label>EB SB Project</label>
    <nameField>
        <displayFormat>Project-{YYYY}{MM}-{0000}</displayFormat>
        <label>EB/SB Builders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EB SB Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Project_Plan_SOW_EB__c.object
<CustomObject>
    <fields>
        <fullName>EBSB_Builders_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EB/SB Builders Name</label>
        <referenceTo>EB_SB_Builder__c</referenceTo>
        <relationshipLabel>Project Plan/SOW EB</relationshipLabel>
        <relationshipName>Project_Plan_SOW_EB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Launch_Revised_Timeline__c</fullName>
        <label>Event Launch-Revised Timeline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Launch_Date__c</fullName>
        <label>Expected Launch Date</label>
        <type>Date</type>
    </fields>
    <label>Project Plan/SOW EB</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Project Plan/SOW EB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Plan/SOW EB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EBProjUpdateExpLaunchDateFrmPP_TrigAct.cls
/*Author: Sandeep Kumar
* Date: 23 May 2017
* Description: EBProjUpdateExpLaunchDateFrmPP_TrigAct. 
* Class is reponsible for updating "Expected launch Date" from "Project Plan" object to associated EBSB Object.
* Test Class : EBProjectUpdateExpLaunchDate_TrigAct_Test
*/
public class EBProjUpdateExpLaunchDateFrmPP_TrigAct extends TriggerAction{
    public Map<Id,Date> projIdToExpectedLaunchDateMap;
    public List<EB_SB_Builder__c> ebProjList;   
    public EBProjUpdateExpLaunchDateFrmPP_TrigAct(){
        // Call super to set batch variables & context
        super();
        projIdToExpectedLaunchDateMap = new Map<Id,Date>();
        ebProjList = new List<EB_SB_Builder__c>();
    }
    
    public override Boolean shouldRun(){
        if(this.isAfter() && !this.hasRun()){
            if(this.isUpdate()){
                for(Project_Plan_SOW_EB__c newProjPlanObj: (List<Project_Plan_SOW_EB__c>)this.triggerMap.values()){
                    Project_Plan_SOW_EB__c oldProjPlanObj = (Project_Plan_SOW_EB__c)this.triggerOldMap.get(newProjPlanObj.Id);
                    if(newProjPlanObj.EBSB_Builders_Name__c != null){
                        // Below condition is satisfied whenever the Expected Launch Date is changed.
                        if(oldProjPlanObj.Expected_Launch_Date__c != newProjPlanObj.Expected_Launch_Date__c){
                            projIdToExpectedLaunchDateMap.put(newProjPlanObj.EBSB_Builders_Name__c, newProjPlanObj.Expected_Launch_Date__c);
                            // Below condition is satisfied whenever the Event Launch Revised Date is changed.    
                        }else if(oldProjPlanObj.Event_Launch_Revised_Timeline__c != newProjPlanObj.Event_Launch_Revised_Timeline__c) {
                            projIdToExpectedLaunchDateMap.put(newProjPlanObj.EBSB_Builders_Name__c, newProjPlanObj.Event_Launch_Revised_Timeline__c);
                        }
                    }                    
                } 
            }else if(this.isInsert()){
                for(Project_Plan_SOW_EB__c newProjPlanObj: (List<Project_Plan_SOW_EB__c>)this.triggerMap.values()){
                    if(newProjPlanObj.EBSB_Builders_Name__c != null)
                        projIdToExpectedLaunchDateMap.put(newProjPlanObj.EBSB_Builders_Name__c, newProjPlanObj.Expected_Launch_Date__c);                    
                } 
            }            
        }        
        return !projIdToExpectedLaunchDateMap.isEmpty();
    }
    
    public override void doAction(){
        
        EB_SB_Builder__c ebProjObj;
        for(Id projId  :projIdToExpectedLaunchDateMap.keySet()){
            ebProjObj = new EB_SB_Builder__c();            
            ebProjObj.Id = projId;
            ebProjObj.Expected_Launch_Date__c = projIdToExpectedLaunchDateMap.get(projId);
            ebProjList.add(ebProjObj);
        }
        if(!ebProjList.isEmpty()){
            update ebProjList;
        } 
    }    
}