objects/EB_SB_Builder__c.object
<CustomObject>
    <fields>
        <fullName>Hrs_Pending_for_Completion__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hrs Pending for Completion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Complexity__c</fullName>
        <label>Project Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Simple</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>3-Advanced</fullName>
                </value>
                <value>
                    <fullName>4-Complex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Stage__c</fullName>
        <label>Project Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Information Received</fullName>
                </value>
                <value>
                    <fullName>Setup Call Scheduled</fullName>
                </value>
                <value>
                    <fullName>Setup Call Done</fullName>
                </value>
                <value>
                    <fullName>Working on First Draft</fullName>
                </value>
                <value>
                    <fullName>First Draft Completed</fullName>
                </value>
                <value>
                    <fullName>First Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>First Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Second Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Second Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Third Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Third Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Fourth Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>Fourth Round of Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Additional Round of Changes Received</fullName>
                </value>
                <value>
                    <fullName>All the Changes Completed</fullName>
                </value>
                <value>
                    <fullName>Event Testing</fullName>
                </value>
                <value>
                    <fullName>Event Launched</fullName>
                </value>
                <value>
                    <fullName>Sign Off Done</fullName>
                </value>
                <value>
                    <fullName>Premium Services - Post Launch Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains all EB/SB projects</description>
    <label>EB SB Project</label>
    <nameField>
        <displayFormat>Project-{YYYY}{MM}-{0000}</displayFormat>
        <label>EB/SB Builders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EB SB Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/EBProjectStageToPendingHrsSetting__c.object
<CustomObject>
    <fields>
        <fullName>AdvancedPendingHrs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>AdvancedPendingHrs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ComplexPendingHrs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ComplexPendingHrs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MediumPendingHrs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MediumPendingHrs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SimplePendingHrs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SimplePendingHrs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>EBProjectStageToPendingHrsSetting</label>
</CustomObject>

classes/EBProjectUpdatePendingHrsForCompletion.cls
/*Author: Sandeep Kumar
* Date: 02 April 2017
* Description: Update Pending Hrs for Project Completion. 
* Class is reponsible for updating "EB_SB_Builder__c" field based on the project stage change.It is updating # of Pending Hrs for Completion.
* Test Class : EBProjectAssignmentRollup_TrigAct_Test
*/
public class EBProjectUpdatePendingHrsForCompletion extends TriggerAction{
    
    public List<EB_SB_Builder__c> EbProjList;  
    public Map<String,EBProjectStageToPendingHrsSetting__c> NameToHrsPendingMap;    
    
    public EBProjectUpdatePendingHrsForCompletion(){
        // Call super to set batch variables & context
        super();
        EbProjList = new List<EB_SB_Builder__c>();
        NameToHrsPendingMap = new Map<String,EBProjectStageToPendingHrsSetting__c>();        
    }
    
    public override Boolean shouldRun(){
        if(this.isUpdate() && this.isBefore() && !this.hasRun()){
            for(EB_SB_Builder__c newEBProj: (List<EB_SB_Builder__c>)this.triggerMap.values()){
                EB_SB_Builder__c oldEBProj = (EB_SB_Builder__c)this.triggerOldMap.get(newEBProj.Id);
                if(oldEBProj.Project_Stage__c != newEBProj.Project_Stage__c){
                    EbProjList.add(newEBProj);
                }
            }
        }        
        return !EbProjList.isEmpty();
    }
    
    public override void doAction(){
        
        for(EBProjectStageToPendingHrsSetting__c rec :EBProjectStageToPendingHrsSetting__c.getAll().Values()){
            NameToHrsPendingMap.put(rec.Name, rec);
        }
        
        for(EB_SB_Builder__c EBProj: EbProjList){
            if(EBProj.Project_Complexity__c == '1-Simple'){
                EBProj.Hrs_Pending_for_Completion__c = NameToHrsPendingMap.get(EBProj.Project_Stage__c).SimplePendingHrs__c;
            }else if(EBProj.Project_Complexity__c == '2-Medium'){
                EBProj.Hrs_Pending_for_Completion__c = NameToHrsPendingMap.get(EBProj.Project_Stage__c).MediumPendingHrs__c;
            }else if(EBProj.Project_Complexity__c == '3-Advanced'){
                EBProj.Hrs_Pending_for_Completion__c = NameToHrsPendingMap.get(EBProj.Project_Stage__c).AdvancedPendingHrs__c;
            }else if(EBProj.Project_Complexity__c == '4-Complex'){
                EBProj.Hrs_Pending_for_Completion__c = NameToHrsPendingMap.get(EBProj.Project_Stage__c).ComplexPendingHrs__c;
            }           
        }           
    }
}