objects/Execute_Function__mdt.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mark_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mark Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Execute Function</label>
    <pluralLabel>Execute Function</pluralLabel>
</CustomObject>

classes/ExecuteMethodHelper.cls
/***** CLass written to replace cutsom label turn ON/OFF functionality : Udita : 6/21/2019****/
/*** How to use : Boolean MethodIsActive = ExecuteMethodHelper.isActive('/ Label of record you’ve created in metadata');
                  If(MethodIsActive){
                  // execute code
                  }
*********/
public class ExecuteMethodHelper{
    public static Boolean isActive(string MethodName) {
      Execute_Function__mdt active = [select id,Mark_Active__c,Class_Name__c from Execute_Function__mdt where MasterLabel =: MethodName];
      return Boolean.ValueOf(active.Mark_Active__c);
    }
}