objects/GDPR_Central_Repository__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Firstname__c</fullName>
        <label>Firstname</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <description>This will hold the Contacts, Leads, Tasks, Cases which are being marked GDPR to validate if someone tries to create a new record with similar data.</description>
    <label>GDPR Central Repository</label>
    <nameField>
        <displayFormat>GDPR-{00000000}</displayFormat>
        <label>GDPR Central Repository Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDPR Central Repositories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GDPRCentralRepositoryHandler_Test.cls
@istest
public class GDPRCentralRepositoryHandler_Test{
    public static testMethod void testGDPRMethod(){
        
        User userObj = [SELECT Id,Firstname,ContactId,Email,LastName,MobilePhone,Phone,Name FROM User WHERE IsActive=TRUE AND IsPortalEnabled = TRUE LIMIT 1];

        Set<Id> userIdSet = new set<Id>();
        userIdSet.add(userObj.Id);

        Set<Id> contactIdSet = new set<Id>();
        contactIdSet.add(userObj.ContactId);
        
        GDPR_Central_Repository__c gdprObject = new GDPR_Central_Repository__c();
        gdprObject.Id__c = userObj.Id;
        gdprObject.Firstname__c = userObj.Firstname;
        gdprObject.Email__c = userObj.Email;
        gdprObject.LastName__c = userObj.LastName;
        gdprObject.MobilePhone__c = userObj.MobilePhone;
        gdprObject.Phone__c = userObj.Phone;
        gdprObject.Name__c = userObj.Name;
        
        insert gdprObject;
        Test.startTest();
        GDPRCentralRepositoryHandler.GDPRUser(userIdSet);
        Test.stopTest();
        GDPRCentralRepositoryHandler_User.updateGDPR_User(userIdSet,contactIdSet);
        
    }
    public static testMethod void testGDPRMethod1(){
        
        User userObj = [SELECT Id,Firstname,ContactId,Email,LastName,MobilePhone,Phone,Name FROM User WHERE IsActive=TRUE AND IsPortalEnabled = TRUE LIMIT 1];

        Set<Id> userIdSet = new set<Id>();
        userIdSet.add(userObj.Id);

        Set<Id> contactIdSet = new set<Id>();
        contactIdSet.add(userObj.ContactId);
        
        GDPR_Central_Repository__c gdprObject = new GDPR_Central_Repository__c();
        gdprObject.Id__c = userObj.Id;
        gdprObject.Firstname__c = userObj.Firstname;
        gdprObject.Email__c = userObj.Email;
        gdprObject.LastName__c = userObj.LastName;
        gdprObject.MobilePhone__c = userObj.MobilePhone;
        gdprObject.Phone__c = userObj.Phone;
        gdprObject.Name__c = userObj.Name;
        
        insert gdprObject;
        Test.startTest();
        GDPRCentralRepositoryHandler_User.updateGDPR_User(userIdSet,contactIdSet);        
        Test.stopTest();
        GDPRCentralRepositoryHandler.fakeMethod();
        
    }
}