objects/Mobile_Card__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Cards_CC</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Track Projects for Mobile App Builders in SF</description>
    <label>Mobile App</label>
    <nameField>
        <label>Mobile Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LMS_Groups__c</fullName>
        <description>Field to populate the tags for which automatic training can be assigned to users in LMS. This field can be populated from various sources. Currently, it's being populated from Product Mix and Mobile App.</description>
        <inlineHelpText>Field to populate the tags for which automatic training can be assigned to users in LMS. This field can be populated from various sources. Currently, it's being populated from Product Mix and Mobile App.</inlineHelpText>
        <label>LMS Groups</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LMS_Sync_Date__c</fullName>
        <description>Data to capture the last update date on LMS Synced Fields. Sync will happen for fields having current (today's) sync date. Currently being used for sync with Docebo LMS.</description>
        <inlineHelpText>Data to capture the last update date on LMS Synced Fields. Sync will happen for fields having current (today's) sync date. Currently being used for sync with Docebo LMS.</inlineHelpText>
        <label>LMS Sync Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/MobileAppTrgHandler.cls
/**** Written to update LMS Groups on User for Docebo : 4/15/2019****/
public class MobileAppTrgHandler{

   public void onAfterInsert(List<Mobile_Card__c > newValues){
    set<Id> ContactIds = new set<Id>();
    Map<id,User> userMap = new Map<id,User>();
    List<User> userUpdateList = new List<User>();
      for(Mobile_Card__c  mob : newValues){
        if((mob.RecordtypeId == Schema.SObjectType.Mobile_Card__c.getRecordTypeInfosByName().get('Mobile - Onboarding Lite').getRecordTypeId() || mob.RecordtypeId == Schema.SObjectType.Mobile_Card__c.getRecordTypeInfosByName().get('Mobile - Onboarding Standard').getRecordTypeId()) && mob.Primary_Contact__c != NULL){
           ContactIds.add(mob.Primary_Contact__c);
        }
      }    
      if(ContactIds.size() > 0){
        
         for(User u :[select id,LMS_Groups__c,ContactId from User where ContactID IN :ContactIds AND IsPortalEnabled = TRUE]){
            userMap.put(u.ContactId,u); 
         }
         for(Mobile_Card__c  mob : newValues){
           if((mob.RecordtypeId == Schema.SObjectType.Mobile_Card__c.getRecordTypeInfosByName().get('Mobile - Onboarding Lite').getRecordTypeId() || mob.RecordtypeId == Schema.SObjectType.Mobile_Card__c.getRecordTypeInfosByName().get('Mobile - Onboarding Standard').getRecordTypeId()) && mob.Primary_Contact__c != NULL){
               if(userMap.containsKey(mob.Primary_Contact__c)){
                   user u = userMap.get(mob.Primary_Contact__c);
                   if(u.LMS_Groups__c != NULL){
                     u.LMS_Groups__c = mob.RecordtypeId == Schema.SObjectType.Mobile_Card__c.getRecordTypeInfosByName().get('Mobile - Onboarding Lite').getRecordTypeId() ? u.LMS_Groups__c + ';' + 'CC Onboarding Lite'  : u.LMS_Groups__c + ';' + 'CC Onboarding Standard';}
                   else{
                     u.LMS_Groups__c = mob.RecordtypeId == Schema.SObjectType.Mobile_Card__c.getRecordTypeInfosByName().get('Mobile - Onboarding Lite').getRecordTypeId() ? 'CC Onboarding Lite'  : 'CC Onboarding Standard';
                     }
                     u.LMS_Sync_Date__c= system.today();
                     userUpdateList.add(u);
                   }
               }
           }
         } 
         if(userUpdateList.size() > 0){
           update userUpdateList;}   
      }       
   
}