objects/Onsite_Hardware_Request__c.object
<CustomObject>
    <label>Onsite Hardware Request</label>
    <nameField>
        <displayFormat>OHR - {0}</displayFormat>
        <label>Onsite Hardware Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onsite Hardware Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onsite_Hardware_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>Onsite_Hardware_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Onsite Hardware Request</label>
        <referenceTo>Onsite_Hardware_Request__c</referenceTo>
        <relationshipLabel>Onsite Hardware Request Items</relationshipLabel>
        <relationshipName>Onsite_Hardware_Request_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packlist_Quantity__c</fullName>
        <inlineHelpText>Entered by the Logistics Team. Might include buffers and spares.</inlineHelpText>
        <label>Packlist Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packlist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packlist</label>
        <referenceTo>Packlist__c</referenceTo>
        <relationshipLabel>Onsite Hardware Request Items</relationshipLabel>
        <relationshipName>Onsite_Hardware_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Onsite Hardware Request Item</label>
    <nameField>
        <displayFormat>OHRI - {0}</displayFormat>
        <label>Onsite Hardware Request Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onsite Hardware Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Packlist__c.object
<CustomObject>
    <fields>
        <fullName>Onsite_Hardware_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onsite Hardware Request</label>
        <referenceTo>Onsite_Hardware_Request__c</referenceTo>
        <relationshipLabel>Packlists</relationshipLabel>
        <relationshipName>Packlists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Packlist</label>
    <nameField>
        <label>Packlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packlists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CAM_PreparePacklist_Test.cls
@isTest

private class CAM_PreparePacklist_Test {

    @isTest static void test_newLine(){
        
        //get all the data into the database
        CAM_Test_PopulateData.populateData();
        
        //initiate the page
        PageReference PreparePacklist = new PageReference('/apex/CAM_PreparePacklist');
        Test.setCurrentPage(PreparePacklist);

        //initiate the controller
        ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(CAM_Test_PopulateData.ohri);
        CAM_PreparePacklist_Extension PreparePacklist_Extension = new CAM_PreparePacklist_Extension(stdController);

        
        System.debug ('TEST: newLine - positive outcome');
        System.AssertNotEquals (null, PreparePacklist_Extension.newLine, 'New Line should not be null');

    }//test_newLine

    @isTest static void test_splitItem(){
        
        //get all the data into the database
        CAM_Test_PopulateData.populateData();
        integer originalCount = CAM_Test_PopulateData.ohri.size();
        originalCount++;
        
        //initiate the page
        PageReference PreparePacklist = new PageReference('/apex/CAM_PreparePacklist');
        ApexPages.currentPage().getParameters().put('id', CAM_Test_PopulateData.ohr[0].id);
        Test.setCurrentPage(PreparePacklist);

        //set the parameters for the addItem method
        ApexPages.currentPage().getParameters().put('itemIdToBeSplit', CAM_Test_PopulateData.ohri[0].id);
        ApexPages.currentPage().getParameters().put('L1index', '0');
        ApexPages.currentPage().getParameters().put('L2index', '0');

        //initiate the controller
        ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(CAM_Test_PopulateData.ohri);
        CAM_PreparePacklist_Extension PreparePacklist_Extension = new CAM_PreparePacklist_Extension(stdController);

        

        //call the method
        PreparePacklist_Extension.pageID = CAM_Test_PopulateData.ohr[0].id;
        PreparePacklist_Extension.refreshTheRequest();
        PreparePacklist_Extension.refreshItems();
        PreparePacklist_Extension.getWarehouses();
        PreparePacklist_Extension.splitItem();

        //get the new count of items
        List<Onsite_Hardware_Request_Item__c> ohri_new = new List<Onsite_Hardware_Request_Item__c>();
        ohri_new = [SELECT id, Name FROM Onsite_Hardware_Request_Item__c WHERE Onsite_Hardware_Request__c =:CAM_Test_PopulateData.ohr[0].id];

        System.debug ('TEST: splitItem - positive outcome');
        System.AssertEquals (originalCount, ohri_new.size(), 'The item count did not increase by one as expected');

    }//test_splitItem

    @isTest static void test_createPacklists(){
        
        //get all the data into the database
        CAM_Test_PopulateData.populateData();
        integer originalCount = CAM_Test_PopulateData.packlists.size();
        originalCount++;
        
        //initiate the page
        PageReference PreparePacklist = new PageReference('/apex/CAM_PreparePacklist');
        ApexPages.currentPage().getParameters().put('id', CAM_Test_PopulateData.ohr[0].id);
        Test.setCurrentPage(PreparePacklist);

        //set the parameters for the addItem method
        ApexPages.currentPage().getParameters().put('itemIdToBeSplit', CAM_Test_PopulateData.ohri[0].id);
        ApexPages.currentPage().getParameters().put('L1index', '0');
        ApexPages.currentPage().getParameters().put('L2index', '0');

        //initiate the controller
        ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(CAM_Test_PopulateData.ohri);
        CAM_PreparePacklist_Extension PreparePacklist_Extension = new CAM_PreparePacklist_Extension(stdController);

        //initiate the Lists and imitate selecting the warehouses
        PreparePacklist_Extension.pageID = CAM_Test_PopulateData.ohr[0].id;
        PreparePacklist_Extension.refreshTheRequest();
        PreparePacklist_Extension.refreshItems();
        PreparePacklist_Extension.getWarehouses();
        for (integer i1=0; i1<PreparePacklist_Extension.assets.size(); i1++){
            for (integer i2=0; i2<PreparePacklist_Extension.assets[i1].lst.size(); i2++){
                PreparePacklist_Extension.assets[i1].lst[i2].warehouse = CAM_Test_PopulateData.warehouses[0].id;
                PreparePacklist_Extension.assets[i1].lst[i2].reqItem.Packlist_Quantity__c = 1;
            }
        }

        //call the method
        PreparePacklist_Extension.createPacklists();

        //get the new count of Packlists
        List<Packlist__c> packlists_new = new List<Packlist__c>();
        packlists_new = [SELECT id, Name FROM Packlist__c WHERE Onsite_Hardware_Request__c =:CAM_Test_PopulateData.ohr[0].id];

        System.debug ('TEST: createPacklists - positive outcome');
        System.AssertEquals (originalCount, packlists_new.size(), 'The packlist count did not increase by one as expected');

    }//test_createPacklists



}