objects/Project_Plan_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Addnl_Info_Received_Expected_Date__c</fullName>
        <label>Addnl Info Received-Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Launch_Expected_Date__c</fullName>
        <label>Event Launch Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Setup_Call_Expected_Date__c</fullName>
        <label>Event Setup Call Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Testing_Expected_Date__c</fullName>
        <label>Event Testing Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FD_Completed_Expected_Date__c</fullName>
        <label>First Draft Completed Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_ROC_Completed_Expected_Date__c</fullName>
        <label>1st ROC Completed Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X1st_ROC_Received_Expected_Date__c</fullName>
        <label>1st ROC Received Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2nd_ROC_Completed_Expected_Date__c</fullName>
        <label>2nd ROC Completed Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X2nd_ROC_Received_Expected_Date__c</fullName>
        <label>2nd ROC Received Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3rd_ROC_Completed_Expected_Date__c</fullName>
        <label>3rd ROC Completed Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X3rd_ROC_Received_Expected_Date__c</fullName>
        <label>3rd ROC Received Expected Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Calculate Weekdays for Milestone based on Request Type and Complexity of a Case.</description>
    <label>Project Plan Milestone</label>
</CustomObject>

objects/Project_Plan_Revised__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Timeline_API_Name__c</fullName>
        <label>Actual Timeline API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Timeline_API_Name__c</fullName>
        <label>Expected Timeline API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Sequence__c</fullName>
        <label>Field Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revised_Timeline_API_Name__c</fullName>
        <description>This field contains the name of Revised Milestone Date fields on EB SB project plan object.</description>
        <label>Revised Timeline API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeline_Reason_API_Name__c</fullName>
        <label>Timeline Reason API Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>It contains sequence of milestone dates and revised timeline fields.</description>
    <label>Project Plan Revised</label>
</CustomObject>

objects/Project_Plan_SOW_EB__c.object
<CustomObject>
    <fields>
        <fullName>Addnl_Info_Received_Actual_Timeline__c</fullName>
        <label>Addnl Info Received-Actual Timeline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Addnl_Info_Received_Expected_Date__c</fullName>
        <label>Addnl Info Received-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Addnl_Info_Received_Expected_Timeline__c</fullName>
        <label>Addnl Info Received-Expected Timeline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Addnl_Info_Received_Revised_Timeline__c</fullName>
        <label>Addnl Info Received-Revised Timeline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Addnl_Info_Recvd_Revised_Timeline_Reason__c</fullName>
        <label>Addnl Info Recvd-Revised Timeline Reason</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Launch_Expected_Date__c</fullName>
        <label>Event Launch Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Setup_Call_Actual_Timeline__c</fullName>
        <label>Event Setup Call-Actual Timeline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Setup_Call_Expected_Date__c</fullName>
        <label>Event Setup Call Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Setup_Call_Expected_Timeline__c</fullName>
        <label>Event Setup Call-Expected Timeline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Setup_Call_Revised_Timeline_Reason__c</fullName>
        <label>Event Setup Call Revised Timeline Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Setup_Call_Revised_Timeline__c</fullName>
        <label>Event Setup Call-Revised Timeline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Testing_Expected_Date__c</fullName>
        <label>Event Testing Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Launch_Date__c</fullName>
        <label>Expected Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FD_Completed_Expected_Date__c</fullName>
        <label>FD Completed Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Information_Received__c</fullName>
        <label>Setup Call</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Launch_Date_Revised__c</fullName>
        <inlineHelpText>Customer wants same/new launch date for Project Plan if any of the milestone date revised.</inlineHelpText>
        <label>Do you want to revise the launch date ?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Complexity__c</fullName>
        <label>Project Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1-Simple</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>3-Advanced</fullName>
                </value>
                <value>
                    <fullName>4-Complex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Plan_Status__c</fullName>
        <label>Project Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Generate Project Plan</fullName>
                </value>
                <value>
                    <fullName>Discard Project Plan</fullName>
                </value>
                <value>
                    <fullName>Project Plan Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Received_Date__c</fullName>
        <label>Project Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rush</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1st_ROC_Completed_Expected_Date__c</fullName>
        <label>1st ROC Completed-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X1st_ROC_Received_Expected_Date__c</fullName>
        <label>1st ROC Received-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X2nd_ROC_Completed_Expected_Date__c</fullName>
        <label>2nd ROC Completed-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X2nd_ROC_Received_Expected_Date__c</fullName>
        <label>2nd ROC Received-Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X3rd_ROC_Completed_Expected_Date__c</fullName>
        <label>3rd ROC Completed Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X3rd_ROC_Received_Expected_Date__c</fullName>
        <label>3rd ROC Received Expected Date</label>
        <type>Date</type>
    </fields>
    <label>Project Plan/SOW EB</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Project Plan/SOW EB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Plan/SOW EB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectPlanTrgHelperTest.cls
@isTest
Public Class ProjectPlanTrgHelperTest{

  @testsetup
  static void createTetsDataProjectPlan(){
      
      //Creating custom setting data (Project Plan Revised)
      Project_Plan_Revised__c pPlanRevised= new Project_Plan_Revised__c();
      pPlanRevised.Name = 'S1';
      pPlanRevised.Field_Sequence__c = 1 ;
      pPlanRevised.Expected_Timeline_API_Name__c = 'Event_Setup_Call_Expected_Timeline__c' ; 
      pPlanRevised.Revised_Timeline_API_Name__c = 'Event_Setup_Call_Revised_Timeline__c' ;
      pPlanRevised.Timeline_Reason_API_Name__c = 'Event_Setup_Call_Revised_Timeline_Reason__c' ;
      pPlanRevised.Actual_Timeline_API_Name__c =  'Event_Setup_Call_Actual_Timeline__c';
      insert pPlanRevised;
      
      
      //Creating custom setting data (Project Plan Revised)
      Project_Plan_Revised__c pPlanRevised2 = new Project_Plan_Revised__c();
      pPlanRevised2.Name = 'S2';
      pPlanRevised2.Field_Sequence__c = 2 ;
      pPlanRevised2.Expected_Timeline_API_Name__c = 'Addnl_Info_Received_Expected_Timeline__c' ; 
      pPlanRevised2.Revised_Timeline_API_Name__c = 'Addnl_Info_Received_Revised_Timeline__c' ;
      pPlanRevised.Timeline_Reason_API_Name__c = 'Addnl_Info_Recvd_Revised_Timeline_Reason__c' ;
      pPlanRevised2.Actual_Timeline_API_Name__c =  'Addnl_Info_Received_Actual_Timeline__c';
      insert pPlanRevised2;
      
      
      
      //Creating custom setting data (Project Plan Milestone)
      Decimal d = 3;
      Project_Plan_Milestone__c pPlanCustSetting = new Project_Plan_Milestone__c();
      pPlanCustSetting.Name = 'Regular Simple';
      pPlanCustSetting.Event_Launch_Expected_Date__c = d;
      pPlanCustSetting.Event_Setup_Call_Expected_Date__c = d;
      pPlanCustSetting.Event_Testing_Expected_Date__c = d;
      pPlanCustSetting.FD_Completed_Expected_Date__c = d;
      pPlanCustSetting.X1st_ROC_Completed_Expected_Date__c = d;
      pPlanCustSetting.X1st_ROC_Received_Expected_Date__c = d;
      pPlanCustSetting.X2nd_ROC_Received_Expected_Date__c = d;
      pPlanCustSetting.X2nd_ROC_Completed_Expected_Date__c = d;
      pPlanCustSetting.X3rd_ROC_Completed_Expected_Date__c = d;
      pPlanCustSetting.X3rd_ROC_Received_Expected_Date__c = d;     
      pPlanCustSetting.Addnl_Info_Received_Expected_Date__c = d;
      Insert pPlanCustSetting;
      
      
       //Creating Project Plan EB
      Project_Plan_SOW_EB__c pPlan = new Project_Plan_SOW_EB__c();
      pPlan.Information_Received__c = System.Today();
      pPlan.Project_Received_Date__c = System.Today();
      pPlan.Expected_Launch_Date__c = System.Today();
      pPlan.Request_Type__c = 'Regular' ;
      pPlan.Project_Complexity__c = '1-Simple';
      pPlan.Project_Plan_Status__c = 'Generate Project Plan';
      insert pPlan;   
  }
  
  @isTest Public static void beforeInsertTest(){
  
        Project_Plan_SOW_EB__c  pp = [Select Id,Event_Setup_Call_Expected_Timeline__c,Event_Setup_Call_Revised_Timeline__c,Event_Setup_Call_Revised_Timeline_Reason__c From Project_Plan_SOW_EB__c Limit 1];
        pp.Event_Setup_Call_Revised_Timeline__c =  pp.Event_Setup_Call_Expected_Timeline__c + 4;
        pp.Event_Setup_Call_Revised_Timeline_Reason__c = 'Test Reason';
        pp.Is_Launch_Date_Revised__c = 'No';
        Update pp;
  
  }
  
  

}