objects/PSA_Custom_Trigger_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Disable_Assignment_followProject__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables the trigger/method PSA_AssignmentTriggerHandler.followProject (causes resources to automatically follow Projects in Chatter when they are Assigned to a Project)</inlineHelpText>
        <label>Disable Assignment followProject</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Client_Meeting_deactivateMeeting__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disable trigger/method PSA_clientMeetingTriggerHandler.deactivateMeeting (unchecks Active on Client Meetings when they are edited to have a work end date in the past)</inlineHelpText>
        <label>Disable Client Meeting deactivateMeeting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_ER_handleNewExpenseReport__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_ExpenseReportTriggerHandler.handleNewExpenseReport (creates Integration Queue records from Approved Expense Reports for EBS integration)</inlineHelpText>
        <label>Disable ER handleNewExpenseReport</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_ER_populateApprover__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_ExpenseReportHeaderTriggerHandler.populateApprover (populates either Resource Manager or Project Manager in Approver field depending on project Expense Approval Method - WARNING-DISABLING WILL AFFECT APPROVAL PROCESS FUNCTION</inlineHelpText>
        <label>Disable ER populateApprover</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Expense_setExpenseType__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_expenseTriggerHandler.setExpenseType (sets Expense Type lookup on Expense records based on value in the Type field - used by EBS integration)</inlineHelpText>
        <label>Disable Expense setExpenseType</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Milestone_sumMilestoneWeight__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables the trigger/method PSA_MilestoneTriggerHandler.sumMilestoneWeight (sums total Milestone weight and weight of Approved Milestones onto the Project for a complete by weight %)</inlineHelpText>
        <label>Disable Milestone sumMilestoneWeight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Project_pendingCompletionPost__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables the trigger/method PSA_ProjectTriggerHandler.pendingCompletionPost (posts a message to Chatter to all assigned resources and PM's Manager when Project Status is set to "Pending Completion")</inlineHelpText>
        <label>Disable Project pendingCompletionPost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Project_populatePMsMgr__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables the trigger/method PSA_ProjectTriggerHandler.populatePMsMgr from executing (functionality that populates the PM's Manager on the Project for notification purposes)</inlineHelpText>
        <label>Disable Project populatePMsMgr</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_RR_setResourceManager__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_ResourceRequestTriggerHandler.setResourceManager (populates Resource Manager field on Resource Request with Resource Manager field from Project's Group)</inlineHelpText>
        <label>Disable RR setResourceManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Survey_Info_answerToNumber__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_surveyInfoTriggerHandler.answerToNumber (converts long text area Answer__c field to 1-5 numeric value if answer is Very Satisfied, Satisfied, Neutral, Dissatisfied, Very Dissatisfied)</inlineHelpText>
        <label>Disable Survey Info answerToNumber</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Survey_Info_sumTotalScore__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_surveyInfoTriggerHandler.sumTotalScore (sums total # of questions and total question score from Survey Info onto Project for Project Health Calculation)</inlineHelpText>
        <label>Disable Survey Info sumTotalScore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_TCHeader_nonBillableMilestone__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_TimecardHeaderTriggerHandler.nonBillableMilestone (unchecks Billable and checks Time Credited on Timecards against billable Projects where the Non-Billable Milestone field = TRUE on the related Milestone record)</inlineHelpText>
        <label>Disable TCHeader nonBillableMilestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_TCHeader_populateApprover__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_TimecardHeaderTriggerHandler.populateApprover (populates either Resource Manager or Project Manager in Approver field depending on project Time Approval Method - WARNING-DISABLING WILL AFFECT APPROVAL PROCESS FUNCTION</inlineHelpText>
        <label>Disable TCHeader populateApprover</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_TC_Split_populateTimePeriod__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disables trigger/method PSA_TimecardSplitTriggerHandler.populateTimePeriod (populates Quarter, Month and Year Time Period lookups on TC split for use in MBO Utilization Calculation batch).  Disabling this will affect Utilization Calculation function.</inlineHelpText>
        <label>Disable TC Split populateTimePeriod</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>PSA Custom Trigger Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Validation_Bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To bypass from Opp validations</description>
        <label>Validation Bypass</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PSA_Utils.cls
/****************************************************************************************
Name            : PSA_utils
Author(s)       : TOP Step Consulting - Andy Heidrich (aheidrich@topstepconsulting.com)
				:
Created Date    : 
Description     : Contains utility methods implemented for custom PSA code developed by
				: TOP Step Consulting.
				:
******************************************************************************************/

public without sharing class PSA_Utils {
    
    //This method checks to see if the currently logged in user has 'Validation Bypass' checked
    //on the User record.  This is used to bypass Apex code when loading data.
    public static Map<Id,User> DataLoadModeUsers
	{
		get
		{
			if(DataLoadModeUsers==null)
			{
				DataLoadModeUsers = new Map<Id,User>([SELECT Id FROM User WHERE UserType = 'Standard' AND IsActive = TRUE AND Validation_Bypass__c = TRUE]);				
			}
			return DataLoadModeUsers;
		}
	}
	public static boolean IsDataLoadMode
	{
		get
		{
			return DataLoadModeUsers.containsKey(UserInfo.getUserId());
		}
	}
    
    public static set<string> disabledTriggers
    {
        get{
            if(disabledTriggers == null) {
                disabledTriggers = new set<string>();
                PSA_Custom_Trigger_Settings__c pcts = 
                    [SELECT Disable_Assignment_followProject__c, Disable_Client_Meeting_deactivateMeeting__c,
                     Disable_ER_handleNewExpenseReport__c, Disable_ER_populateApprover__c, Disable_Expense_setExpenseType__c,
                     Disable_Milestone_sumMilestoneWeight__c, Disable_Project_pendingCompletionPost__c, Disable_Project_populatePMsMgr__c,
                     Disable_RR_setResourceManager__c, Disable_Survey_Info_answerToNumber__c, Disable_Survey_Info_sumTotalScore__c,
                     Disable_TCHeader_nonBillableMilestone__c, Disable_TCHeader_populateApprover__c, Disable_TC_Split_populateTimePeriod__c
                     FROM PSA_Custom_Trigger_Settings__c WHERE Name = 'Default'];
                
                if(pcts.Disable_Assignment_followProject__c) { disabledTriggers.add('followProject'); }
                if(pcts.Disable_Client_Meeting_deactivateMeeting__c) { disabledTriggers.add('deactivateMeeting'); }
                if(pcts.Disable_ER_handleNewExpenseReport__c) { disabledTriggers.add('handleNewExpenseReport'); }
                if(pcts.Disable_ER_populateApprover__c) { disabledTriggers.add('ERpopulateApprover'); }
                if(pcts.Disable_Expense_setExpenseType__c) { disabledTriggers.add('setExpenseType'); }
                if(pcts.Disable_Milestone_sumMilestoneWeight__c) { disabledTriggers.add('sumMilestoneWeight'); }
                if(pcts.Disable_Project_pendingCompletionPost__c) { disabledTriggers.add('pendingCompletionPost'); }
                if(pcts.Disable_Project_populatePMsMgr__c) { disabledTriggers.add('populatePMsMgr'); }
                if(pcts.Disable_RR_setResourceManager__c) { disabledTriggers.add('setResourceManager'); }
                if(pcts.Disable_Survey_Info_answerToNumber__c) { disabledTriggers.add('answerToNumber'); }
                if(pcts.Disable_Survey_Info_sumTotalScore__c) { disabledTriggers.add('sumTotalScore'); }
                if(pcts.Disable_TCHeader_nonBillableMilestone__c) { disabledTriggers.add('nonBillableMilestone'); }
                if(pcts.Disable_TCHeader_populateApprover__c) { disabledTriggers.add('TCpopulateApprover'); }
                if(pcts.Disable_TC_Split_populateTimePeriod__c) { disabledTriggers.add('populateTimePeriod'); }
            }
            return disabledTriggers;
        }
    }
    
    public static boolean isTriggerDisabled(string methodName)
	{
		return disabledTriggers.contains(methodName);	
	}
}