objects/Quality_Check_Done__c.object
<CustomObject>
    <fields>
        <fullName>Mobile_App__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mobile App</label>
        <referenceTo>Mobile_Card__c</referenceTo>
        <relationshipLabel>Quality Check Dones</relationshipLabel>
        <relationshipName>Quality_Check_Dones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QC_Done_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QC Done By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quality_Check_Dones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QC_Done_For__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QC Done For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quality_Check_Dones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quality_Checks__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quality Checks</label>
        <referenceTo>Quality_Checks__c</referenceTo>
        <relationshipLabel>Quality Check Dones</relationshipLabel>
        <relationshipName>Quality_Check_Dones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quality Check Done</label>
    <nameField>
        <displayFormat>QC-{00000000}</displayFormat>
        <label>Quality Check Done Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Check Dones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Check_Question__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Choices__c</fullName>
        <label>Answer Choices</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quality_Checks__c</fullName>
        <label>Quality Checks</label>
        <referenceTo>Quality_Checks__c</referenceTo>
        <relationshipLabel>Quality Check Questions</relationshipLabel>
        <relationshipName>Quality_Check_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question_Type_CC__c</fullName>
        <label>Question Type CC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Listing and Submission/Re-submission</fullName>
                </value>
                <value>
                    <fullName>Imports/Survey creation</fullName>
                </value>
                <value>
                    <fullName>CLI/LI</fullName>
                </value>
                <value>
                    <fullName>Graphics Upload</fullName>
                </value>
                <value>
                    <fullName>Mapping</fullName>
                </value>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>Download Numbers</fullName>
                </value>
                <value>
                    <fullName>Survey/Polling creation</fullName>
                </value>
                <value>
                    <fullName>HTML corrections</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Quality Check Question</label>
    <nameField>
        <displayFormat>QC Ques-{00000000}</displayFormat>
        <label>Quality Check Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Check Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quality_Check_Response__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quality_Check_Done__c</fullName>
        <label>Quality Check Done</label>
        <referenceTo>Quality_Check_Done__c</referenceTo>
        <relationshipLabel>Quality Check Response</relationshipLabel>
        <relationshipName>Quality_Check_Response</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quality_Check_Filled_Response__c</fullName>
        <label>Quality Check Filled Response</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quality_Check_Question__c</fullName>
        <label>Quality Check Question</label>
        <referenceTo>Quality_Check_Question__c</referenceTo>
        <relationshipLabel>Quality Check Response</relationshipLabel>
        <relationshipName>Quality_Check_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <formula>Quality_Check_Question__r.Question__c</formula>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <label>Quality Check Response</label>
    <nameField>
        <displayFormat>QC Resp-{000000000}</displayFormat>
        <label>Quality Check Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Check Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quality_Checks__c.object
<CustomObject>
    <description>Created for Quality Checks of Client Services</description>
    <label>Quality Checks</label>
    <nameField>
        <displayFormat>QC-{00000000}</displayFormat>
        <label>Quality Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/qualityCheckController.cls
public with sharing class qualityCheckController {
    
    public String quesType {get;set;}
    public String caseId {get; set;}
    public String userForId {get;set;}
    public String qcId {get;set;}
    public List<question> allQuestions {get;set;}
    public String selectedType {get;set;}
    public List<SelectOption> types;
    public String qcDoneId {get;set;}
    public Quality_Check_Done__c qcDone {get;set;}
    /*public String[] getquesType() {
        return quesType;
    }
    
    public void setquesType(String[] quesType) {
        this.quesType = quesType;
    }*/
    public qualityCheckController(ApexPages.StandardController stdController) {
        // Get url parameters
        qcId = Apexpages.currentPage().getParameters().get('id');
        qcDone = new Quality_Check_Done__c();
        system.debug('@@@@qcId: '+qcId);
        
        getallQuestions();
    }
     
    public void checkSelectedValue(){        
        system.debug('Selected value is: ' + quesType);
    } 
    
    public List<SelectOption> gettypes(){
        Schema.sObjectType sobject_type = Quality_Check_Question__c.getSObjectType();
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();
        List<Schema.PicklistEntry> pick_list_values = field_map.get('Question_Type_CC__c').getDescribe().getPickListValues();
        List<selectOption> options = new List<selectOption>();
        for (Schema.PicklistEntry a : pick_list_values) {
            options.add(new selectOption(a.getLabel(), a.getValue()));
        }
        return options;  
    }
    
    public PageReference submitValues(){
        system.debug('@@@@@allQuestions : '+allQuestions);
        system.debug('@@@@@quesType: '+quesType);
        caseId = qcDone.Mobile_App__c;
        userForId = qcDone.QC_Done_For__c;
        system.debug('@@@@caseId : '+caseId);
        system.debug('@@@@userForId : '+userForId);
        List <Quality_Check_Response__c> qcrList = new List<Quality_Check_Response__c>();
        Integer counter = 0;
        String lstQues='';
        for (question q : allQuestions){
            system.debug('@@@@@@Inside the for loop');
            Quality_Check_Response__c qcr = new Quality_Check_Response__c();
            system.debug('++++++222'+q.selectedOption);
            system.debug('++++++q.questionType'+q.questionType);
            if((q.selectedOption == null || q.selectedOption == '') && quesType== q.questionType){
                system.debug('++++++'+q.selectedOption);
                lstQues = lstQues + q.question +'\n\n\n\n\n\n';
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error,'**********Kindly complete the below questions**********'));
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error,q.question));
                qcr.Quality_Check_Filled_Response__c = '';
                counter++; 
            }  
        }
        //if(counter>0)
        //ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error,lstQues));
        if(counter==0){
            for (question q : allQuestions){
                if(quesType== q.questionType){
                    Quality_Check_Response__c qcr = new Quality_Check_Response__c();
                    qcr.Quality_Check_Filled_Response__c = q.singleOptions.get(Integer.valueOf(q.selectedOption)).getLabel();
                    qcr.Quality_Check_Question__c = q.Id;
                    qcr.Comments__c =  q.Comments;
                    qcrList.add(qcr);
                }
            }
        
            system.debug('@@@@@@Inside the submit method');
            if(addQCDone()){
                for(Quality_Check_Response__c qcr : qcrList){
                    qcr.Quality_Check_Done__c = qcDoneId;
                }
                if(qcrList.size()>0)
                    insert qcrList;
            }
            //PageReference pageRef = new PageReference('/apex/qcforCCDetailPage?id='+qcDoneId);
            PageReference pageRef = new PageReference('/'+qcDoneId);
            return pageRef;
        }else{
            return null;
        }
    }
    private Boolean addQCDone(){
        String userId;
        system.debug('@@@@qcId: '+qcId);
        if (qcId == null)
            return false;
        
        userId = UserInfo.getUserId();
        system.debug('@@@@userId: '+userId);
        //system.debug('@@@@qcDone.QC_Done_For__c: '+qcDone.QC_Done_For__c);
        //system.debug('@@@@qcDone.Mobile_App__c: '+qcDone.Mobile_App__c);
        List<Quality_Check_Done__c> check = [Select Mobile_App__c, QC_Done_By__c, QC_Done_For__c, Quality_Checks__c From Quality_Check_Done__c Where QC_Done_For__c=:userForId and Quality_Checks__c=:qcId and Mobile_App__c = :caseId];
           /* if(check != null && check.size()>0){
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This has already been done!!!'));
                return false;       
            }*/
        
        Quality_Check_Done__c qc = new Quality_Check_Done__c();
        qc.Mobile_App__c = qcDone.Mobile_App__c;
        qc.QC_Done_By__c = userId;
        qc.QC_Done_For__c = qcDone.QC_Done_For__c;
        qc.Quality_Checks__c = qcId;
        system.debug('@@@@qc: '+qc);
        insert qc;  
        qcDoneId = qc.Id;
        return true;    
    }
    
    @TestVisible public class question{
        public String name {get; set;}
        public String answerChoices {get; set;}
        public String question {get; set;}
        public String questionType {get; set;}
        public String id {get; set;}
        public List<SelectOption> singleOptions {get; set;}
        public List<String> strList {get; set;}
        public String singleOptionsForChart  {get; set;}
        public String selectedOption {get;set;}
        public String comments{get;set;}

        public question(Quality_Check_Question__c qc){
            name = qc.Name;
            answerChoices = qc.Answer_Choices__c;
            question = qc.Question__c;
            questionType = qc.Question_Type_CC__c;
            id = qc.id;
            this.comments = comments;
            singleOptions = stringToSelectOptions(answerChoices);
        }
        
        
        private List<SelectOption> stringToSelectOptions(String str){
            if (str == ''){
                return new List<SelectOption>();
            }
            strList = str.split('\n');
            List<SelectOption> returnVal = new List<SelectOption>();
            Integer i = 0;
            for(String s: strList){
                if (s!='') {    
                    if (s != 'null' && s!= null) {
                        String sBis = s.replace(' ', '%20');
                        singleOptionsForChart += s.trim()+'|';
                        returnVal.add(new SelectOption(String.valueOf(i),s));
                        System.debug('*****VALUES: ' + s);
                        i++;
                    }
                }
            }
            singleOptionsForChart = singleOptionsForChart.substring(0, singleOptionsForChart.length()-1);
            return returnVal;
        }
    }
    
    public List<question> getallQuestions() {
        List<Quality_Check_Question__c> allQuestionsObject = [Select id,Name,Question_Type_CC__c,Question__c,Answer_Choices__c From Quality_Check_Question__c s 
                                                              WHERE s.Quality_Checks__c =: qcId];
        allQuestions = new List<question>();
        for (Quality_Check_Question__c q : allQuestionsObject){ 
            question theQ = new question(q);
            allQuestions.add(theQ);
        }
        system.debug('allQuestions size'+allQuestions.size());
        return allQuestions;
    }
}