objects/Quota__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>DS</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>Task Force</fullName>
                </value>
                <value>
                    <fullName>SDR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quota Type</label>
    <nameField>
        <label>Quota Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quota Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quota_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Amount_for_Apr__c</fullName>
        <label>Amount for Apr</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_Aug__c</fullName>
        <label>Amount for Aug</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_Dec__c</fullName>
        <label>Amount for Dec</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_Feb__c</fullName>
        <label>Amount for Feb</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_Jan__c</fullName>
        <label>Amount for Jan</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_July__c</fullName>
        <label>Amount for July</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_June__c</fullName>
        <label>Amount for June</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_Mar__c</fullName>
        <label>Amount for Mar</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_May__c</fullName>
        <label>Amount for May</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_Nov__c</fullName>
        <label>Amount for Nov</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_Oct__c</fullName>
        <label>Amount for Oct</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_for_Sept__c</fullName>
        <label>Amount for Sept</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Apporved_New__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether New Quota is Approved...</description>
        <label>Is Apporved New</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Changes in Quota Allocation and New Amount is Approved</description>
        <label>Is Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Team__c</fullName>
        <label>Product / Team</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quota_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quota Type</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6 AND 7)</booleanFilter>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>contains</operation>
                <value>Pre Sales</value>
            </filterItems>
            <filterItems>
                <field>Quota__c.Role__c</field>
                <operation>equals</operation>
                <value>PS</value>
            </filterItems>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>contains</operation>
                <value>Direct Sales</value>
            </filterItems>
            <filterItems>
                <field>Quota__c.Role__c</field>
                <operation>equals</operation>
                <value>DS</value>
            </filterItems>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>startsWith</operation>
                <value>AM</value>
            </filterItems>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>notContain</operation>
                <value>Pre Sales</value>
            </filterItems>
            <filterItems>
                <field>Quota__c.Role__c</field>
                <operation>equals</operation>
                <value>AM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quota__c</referenceTo>
        <relationshipLabel>Quota Allocations</relationshipLabel>
        <relationshipName>Quota_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Role Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Members__c</fullName>
        <label>Sales Team Members</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quota_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                    <default>true</default>
                    <label>2016</label>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quota Allocation</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Quota Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quota_Management_Securtity_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Permission__c</fullName>
        <inlineHelpText>Please enter either "Read Only" or "Read/Write"</inlineHelpText>
        <label>Permission</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Quota Management Security Setting</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <formula>Profile.Name</formula>
        <label>Profile Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User Name/Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>User (Custom)</label>
    <nameField>
        <displayFormat>User# {00000000}</displayFormat>
        <label>User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuotaAllocation_Bulk_Update_Ext_Test.cls
@isTest
Public Class  QuotaAllocation_Bulk_Update_Ext_Test{
// ===============================
// AUTHOR     : Shanu Aggarwal    
// CREATED DATE     : 02/03/2016
// Class : QuotaAllocation_Bulk_Update_Extension
// SPECIAL NOTES:
// ===============================
// Change History:
//
//==================================
    static ApexPages.StandardController contr;
    
    static User managedUser ; 
    @testsetup
    public static void createquota(){
    
    
    User u = [Select Profile.Name , UserRole.Name from User Where ID =: UserInfo.GetUserId()];
    
    //inserting User
    System.runAs(u){
        
        Profile p = [SELECT Name FROM Profile WHERE Name = 'System Administrator']; 
        
        managedUser = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, ManagerId = UserInfo.getUserId(),
        TimeZoneSidKey='America/Los_Angeles', UserName='fUsercventtest@testorg.com');
        insert managedUser;
    }

    //Creating custom setting data to authorize current user to use Quota application
    Quota_Management_Securtity_Setting__c custSetting = new Quota_Management_Securtity_Setting__c ();
    custSetting.Name = 'Test123';
    custSetting.Profile_Name__c = u.Profile.Name ;
    custSetting.Role__c = u.UserRole.Name ;
    custSetting.Permission__c = 'Read/Write';
    insert custsetting ;
    
    
    //Inserting Quota Type
    Quota__c qType = new Quota__c();
    qType.Name = 'NBB Quota';
    qType.Comments__c = 'Test Comments';
    insert qType;
    
    
    //Inserting Quota Allocations
    Quota_Allocation__c qAllocation  = new Quota_Allocation__c ();
    qAllocation.Amount_for_Jan__c       = 6558; 
    qAllocation.Amount_for_Feb__c       = 5465;
    qAllocation.Amount_for_Mar__c       = 3545;
    qAllocation.Amount_for_Apr__c       = 3244;
    qAllocation.Amount_for_May__c       = 6544;
    qAllocation.Amount_for_June__c       = 2214;
    qAllocation.Amount_for_July__c       = 7988;
    qAllocation.Amount_for_Aug__c       = 6547;
    qAllocation.Amount_for_Sept__c       = 8987;
    qAllocation.Amount_for_Oct__c       = 1324;
    qAllocation.Amount_for_Nov__c       = 2146;
    qAllocation.Amount_for_Dec__c       = 6544;
    qAllocation.User__c                 = managedUser.Id;
    qAllocation.Quota_Type__c           = qType.Id;
    qAllocation.Sales_Team_Members__c   = 'Hemant Rana (Sops)';
    qAllocation.Product_Team__c         = 'Event';
    qAllocation.Role_Name__c            = 'Salesforce Developer T2';
    qAllocation.Is_Apporved_New__c      = true;
    qAllocation.Is_Approved__c          = true;
    qAllocation.Year__c                 = String.ValueOf(Date.Today().Year());
    Insert qAllocation;
   

    contr = new ApexPages.StandardController(qAllocation);
    
    }
    
    
    public static testmethod void TestForSaving1(){
    
        //Inserting Quota Type
        Quota__c qType2 = new Quota__c();
        qType2.Name = 'Power Score Quota';
        qType2.Comments__c = 'Test Comments';
        insert qType2;
        
        PageReference pgRef1 = Page.QuotaAllocation_Bulk_Update_Page;
        pgRef1.getParameters().put('index' , '1');
        Test.setCurrentPage(pgRef1);
        
        
        
        //Getting Allocation Record Created in Setup method
        Quota_Allocation__c qAllocation = [Select Id, Amount_for_Jan__c, Amount_for_Feb__c, Amount_for_Mar__c, Quota_Type__c,Quota_Type__r.Name, User__c From Quota_Allocation__c Limit 1 ];
        
        Quota_Allocation__c qAllocationCloned = qAllocation.clone(true,true,true,true);
        
        System.debug(   '******* qAllocation ***'  +  qAllocation );
       
        
        //Creating instance of Extension Class
        QuotaAllocation_Bulk_Update_Extension qExt = new QuotaAllocation_Bulk_Update_Extension(contr);
        qExt.TeamOrUsers = 'All Users';

        //Calling all methods
        qExt.CheckPermission();
        
        qExt.getUserResults();
        
        
        if( qExt.userWrappers!=null && qExt.userWrappers.size()>0 ){
            qExt.userWrappers[0].isSelected =true;
        }
        
        
        qExt.ManageAllocations();
        qExt.selectedUserIds.add(qAllocation.User__c);

        
        qExt.RedirectToAllocation();
        qExt.initializeQuotaData();
            
            
        qExt.DeleteRow();
        
        //Updating values
        qAllocationCloned.Quota_Type__c           = qType2.Id;
        qAllocationCloned.Amount_for_Jan__c       = 3445; 
        qAllocationCloned.Amount_for_Feb__c       = 4444;
        qAllocationCloned.Amount_for_Mar__c       = 2222;
        qAllocationCloned.Amount_for_Apr__c       = 1111;
        qAllocationCloned.Amount_for_May__c       = 1224;
        qAllocationCloned.Amount_for_June__c       = 4566;
        qAllocationCloned.Amount_for_July__c       = 4467;
        qAllocationCloned.Amount_for_Aug__c       = 6677;
        qAllocationCloned.Amount_for_Sept__c       = 6788;
        qAllocationCloned.Amount_for_Oct__c       = 5555;
        qAllocationCloned.Amount_for_Nov__c       = 3321;
        qAllocationCloned.Amount_for_Dec__c       = 2345;     
        
        update qAllocationCloned;
        
        System.debug(    '*******  qAllocationCloned *****' + qAllocationCloned );
       
        
        qExt.userIdForNewQuota = qAllocation.User__c ;
        qExt.AddNewQuota();
        
        
        if(qExt.newQuotaInsertList!=null && qExt.newQuotaInsertList.size()>0){
            qExt.newQuotaInsertList.get(0).Quota_Type__c = qAllocation.Quota_Type__c ;
        }
        
        qExt.SaveNewQuota();
        
        qExt.doSave();
        qExt.SelectAll();
        qExt.Cancel();
        
        QuotaAllocation_Bulk_Update_Extension.QuotaWrapper qwrapper = new QuotaAllocation_Bulk_Update_Extension.QuotaWrapper(qAllocationCloned);
        qwrapper.getTotalAmount();
                  
    }
    
    public static testmethod void TestForSaving2(){
        
        PageReference pgRef1 = Page.QuotaAllocation_Bulk_Update_Page;
        pgRef1.getParameters().put('index' , '1');
        Test.setCurrentPage(pgRef1);
        
        
        
        //Getting Allocation Record Created in Setup method
        Quota_Allocation__c qAllocation = [Select Id, Is_Approved__c,Amount_for_Jan__c, Amount_for_Feb__c, Amount_for_Mar__c, Quota_Type__c,Quota_Type__r.Name, User__c From Quota_Allocation__c Limit 1 ];
        qAllocation.Is_Approved__c = false;
        update qAllocation;
        
        Quota_Allocation__c qAllocationCloned = qAllocation.clone(true,true,true,true);
        
        System.debug(   '******* qAllocation ***'  +  qAllocation );
       
        
        //Creating instance of Extension Class
        QuotaAllocation_Bulk_Update_Extension qExt = new QuotaAllocation_Bulk_Update_Extension(contr);
        qExt.TeamOrUsers = 'All Users';
        qExt.userIdForNewQuota = qAllocation.User__c ;
        
        //Calling all methods
        qExt.CheckPermission();
        
        qExt.getUserResults();
        
        
        if( qExt.userWrappers!=null && qExt.userWrappers.size()>0 ){
            qExt.userWrappers[0].isSelected =true;
        }
        
        
        qExt.ManageAllocations();
        qExt.selectedUserIds.add(qAllocation.User__c);

        
        qExt.RedirectToAllocation();
        qExt.initializeQuotaData();
            
            
        qExt.DeleteRow();
        
        //Updating values
        qAllocationCloned.Amount_for_Jan__c       = 3445; 
        qAllocationCloned.Amount_for_Feb__c       = 4444;
        qAllocationCloned.Amount_for_Mar__c       = 2222;
        qAllocationCloned.Amount_for_Apr__c       = 1111;
        qAllocationCloned.Amount_for_May__c       = 1224;
        qAllocationCloned.Amount_for_June__c       = 4566;
        qAllocationCloned.Amount_for_July__c       = 4467;
        qAllocationCloned.Amount_for_Aug__c       = 6677;
        qAllocationCloned.Amount_for_Sept__c       = 6788;
        qAllocationCloned.Amount_for_Oct__c       = 5555;
        qAllocationCloned.Amount_for_Nov__c       = 3321;
        qAllocationCloned.Amount_for_Dec__c       = 2345;     
        
        update qAllocationCloned;
        
        System.debug(    '*******  qAllocationCloned *****' + qAllocationCloned );
        
        qExt.FetchUserData();
        qExt.doNext();
        qExt.doPrevious();
        qExt.RedirectToQuota();
        
        qExt.doSave();
        qExt.SelectAll();
        qExt.Cancel();
                  
    }
    
    public static testmethod void TestForSaving3(){
        
        PageReference pgRef1 = Page.QuotaAllocation_Bulk_Update_Page;
        pgRef1.getParameters().put('index' , '1');
        Test.setCurrentPage(pgRef1);
        
        
        
        //Getting Allocation Record Created in Setup method
        Quota_Allocation__c qAllocation = [Select Id, Is_Approved__c,Amount_for_Jan__c, Amount_for_Feb__c, Amount_for_Mar__c, Quota_Type__c,Quota_Type__r.Name, User__c From Quota_Allocation__c Limit 1 ];
        qAllocation.Is_Approved__c = false;
        update qAllocation;
        
        Quota_Allocation__c qAllocationCloned = qAllocation.clone(true,true,true,true);
        
        System.debug(   '******* qAllocation ***'  +  qAllocation );
       
        
        //Creating instance of Extension Class
        QuotaAllocation_Bulk_Update_Extension qExt = new QuotaAllocation_Bulk_Update_Extension(contr);
        qExt.TeamOrUsers = 'All Users';
        qExt.userIdForNewQuota = qAllocation.User__c ;
        qExt.nameSearchTxt='Testing';
        
        qExt.productSearchTxt='Event';
        qExt.roleSearchTxt='AM';
        
        qExt.qAllocationDelete = qAllocation;
        qExt.quotaDeleteId = qAllocation.Id;
        
        //Calling all methods
        qExt.CheckPermission();
        
        qExt.getUserResults();
        
        
        if( qExt.userWrappers!=null && qExt.userWrappers.size()>0 ){
            qExt.userWrappers[0].isSelected =true;
        }
        
        
        qExt.ManageAllocations();
        qExt.selectedUserIds.add(qAllocation.User__c);

        
        qExt.RedirectToAllocation();
        qExt.initializeQuotaData();
            
      
        
        qExt.FetchUserData();
        qExt.totalPages=15;
        qExt.pageNo=3;
        
        qExt.doNext();
        qExt.doPrevious();
        qExt.RedirectToQuota();
        
        
                  
    }
            
        
}