objects/Sales_Resources__c.object
<CustomObject>
    <fields>
        <fullName>Request_Received_Date__c</fullName>
        <label>Request Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_RFP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Resources</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestupdateSupervisorEmail.cls
@isTest
private class TestupdateSupervisorEmail {
   static testMethod void updateSupervisorEmailTest(){
       User u = [Select id from User where profile.name = 'System Administrator' limit 1];
       Sales_Resources__c s = new Sales_Resources__c(Name='test',
                                                                               Request_Received_Date__c = system.today(),
                                                                               recordtypeId = '0120000000099Kb',
                                                                               Sales_Requestor__c = u.id);
        insert s;
        
        s.Sales_Requestor__c = Userinfo.getUserId();
        update s;
   }
}