objects/Trigger_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Is_On__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is On</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Setting</label>
</CustomObject>

classes/SettingUtil.cls
/**
 * Name: SettingUtil
 * Author: Simplus
 * Created Date: 11 Dec 2019
 * Description: Utility class to retrieve Custom Setting values
 * History:[Author] [Modified Date] [Modification Reason]
**/
public Class SettingUtil {
    
    //Custom Setting API Name: Trigger_Setting__c
    //Custom Field: Is_On__c - Checkbox DataType - Default Value: Checked
    public static Boolean isTriggerOn(String triggerName) 
    {
        Boolean result = true; //If no setting, will return default value true;
        
        Trigger_Setting__c setting = Trigger_Setting__c.getInstance(triggerName);
        if(setting != null)
            result = setting.Is_On__c;
        
        return result;
    }
}