objects/User.object
<CustomObject>
    <fields>
        <fullName>Office_Location__c</fullName>
        <formula>IF(Email = "zmahmood@cvent.com", "USA", Country)</formula>
        <label>Office Location</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WriteOff__c.object
<CustomObject>
    <fields>
        <fullName>Amount_to_be_Written_Off__c</fullName>
        <label>Amount to be Written Off</label>
        <precision>17</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CVII_Link_for_Contract__c</fullName>
        <label>CVII Link for Contract</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Contract_Value__c</fullName>
        <label>Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_Conversion_Rate__c</fullName>
        <label>Currency Conversion Rate</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <referenceTo>BillingCase__c</referenceTo>
        <relationshipLabel>Write-Offs</relationshipLabel>
        <relationshipName>Write_Offs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office_Location__c</fullName>
        <label>Office Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>OA</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>UAE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CrowdCompass</fullName>
                </value>
                <value>
                    <fullName>CrowdTorch</fullName>
                </value>
                <value>
                    <fullName>CSN</fullName>
                </value>
                <value>
                    <fullName>Cvent CONNECT</fullName>
                </value>
                <value>
                    <fullName>Decision Street</fullName>
                </value>
                <value>
                    <fullName>Double Dutch</fullName>
                </value>
                <value>
                    <fullName>EMI</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Lanyon Events</fullName>
                </value>
                <value>
                    <fullName>Lanyon Group</fullName>
                </value>
                <value>
                    <fullName>Lanyon Meetings</fullName>
                </value>
                <value>
                    <fullName>Lanyon Passkey</fullName>
                </value>
                <value>
                    <fullName>Lanyon Transient</fullName>
                </value>
                <value>
                    <fullName>Lanyon Travel</fullName>
                </value>
                <value>
                    <fullName>OA-Enterprise</fullName>
                </value>
                <value>
                    <fullName>OA-Universal Leads</fullName>
                </value>
                <value>
                    <fullName>Onsite Solutions</fullName>
                </value>
                <value>
                    <fullName>Quick Mobile</fullName>
                </value>
                <value>
                    <fullName>SMM</fullName>
                </value>
                <value>
                    <fullName>Social Tables</fullName>
                </value>
                <value>
                    <fullName>SUFEVE</fullName>
                </value>
                <value>
                    <fullName>SUFMO1</fullName>
                </value>
                <value>
                    <fullName>SUFMOB</fullName>
                </value>
                <value>
                    <fullName>SUFSMM</fullName>
                </value>
                <value>
                    <fullName>SUFTPP</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>TPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shut_Down_Required__c</fullName>
        <label>Shut Down Required</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suggested_Shut_Down_Date__c</fullName>
        <label>Suggested Shut Down Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Billed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Contract Billed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Overage_Billed__c</fullName>
        <label>Total Overage Billed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tax_Billed__c</fullName>
        <label>Total Tax Billed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Shut_Down__c</fullName>
        <label>Type of Shut Down</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Blade/Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Write-Off</label>
    <nameField>
        <displayFormat>WO-{000}</displayFormat>
        <label>Case No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Write-Offs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CloneWriteOffObj_ControllerExt.cls
public class CloneWriteOffObj_ControllerExt{
    
    public WriteOff__c writeOffObj {get;set;} 
    private String errorMessage = '';
    // The extension constructor initializes the private member
    // variable writeOff by using the getRecord method from the standard
    // controller.
    public CloneWriteOffObj_ControllerExt(ApexPages.StandardController stdController){
        writeOffObj = new WriteOff__c();
        string str = apexpages.currentpage().getparameters().get('id');
        WriteOff__c[] writeOffArray = [select Id,
                                       Name,
                                       Product__c,
                                       Contract__c,
                                       OwnerId,
                                       Total_Contract_Billed__c,
                                       Total_Tax_Billed__c,
                                       Total_Overage_Billed__c,
                                       Office_Location__c,
                                       CurrencyIsoCode,
                                       Customer_Name__c,
                                       Shut_Down_Required__c,
                                       Type_of_Shut_Down__c,
                                       Suggested_Shut_Down_Date__c,
                                       CVII_Link_for_Contract__c,
                                       Contract_Value__c,
                                       Total_Paid__c,
                                       Amount_to_be_Written_Off__c,
                                       Currency_Conversion_Rate__c
                                       from WriteOff__c where Id =:str]; 
        
        if(writeOffArray != null && writeOffArray.size() > 0){
            this.writeOffObj.Product__c = writeOffArray[0].Product__c;
            this.writeOffObj.Total_Contract_Billed__c = writeOffArray[0].Total_Contract_Billed__c;
            this.writeOffObj.Contract__c = writeOffArray[0].Contract__c;
            this.writeOffObj.Total_Tax_Billed__c = writeOffArray[0].Total_Tax_Billed__c;
            this.writeOffObj.Total_Overage_Billed__c = writeOffArray[0].Total_Overage_Billed__c;
            this.writeOffObj.Office_Location__c = writeOffArray[0].Office_Location__c;
            this.writeOffObj.CurrencyIsoCode = writeOffArray[0].CurrencyIsoCode;
            this.writeOffObj.Customer_Name__c = writeOffArray[0].Customer_Name__c;
            this.writeOffObj.Shut_Down_Required__c = writeOffArray[0].Shut_Down_Required__c;
            this.writeOffObj.Type_of_Shut_Down__c = writeOffArray[0].Type_of_Shut_Down__c;
            this.writeOffObj.Suggested_Shut_Down_Date__c = writeOffArray[0].Suggested_Shut_Down_Date__c;
            this.writeOffObj.CVII_Link_for_Contract__c = writeOffArray[0].CVII_Link_for_Contract__c;
            this.writeOffObj.OwnerId = writeOffArray[0].OwnerId;
            this.writeOffObj.Contract_Value__c = writeOffArray[0].Contract_Value__c;
            this.writeOffObj.Total_Paid__c = writeOffArray[0].Total_Paid__c;
            this.writeOffObj.Amount_to_be_Written_Off__c = writeOffArray[0].Amount_to_be_Written_Off__c;
            this.writeOffObj.Currency_Conversion_Rate__c = writeOffArray[0].Currency_Conversion_Rate__c;
        }
    }
    
    // Declared pageReference Object.
    pageReference pr;
    
    // Creates new write off record and redirect user to the detail page of newly inserted record.
    public pageReference saveWriteOff(){
        pr = null;
        try{
            insert writeOffObj;
            pr = new pageReference('/'+writeOffObj.id);
            pr.setRedirect(true);            
        }Catch(Exception exp){
            if(exp.getMessage().indexOf('FIELD_CUSTOM_VALIDATION_EXCEPTION,')>=0){
                errorMessage = exp.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,');
                errorMessage = errorMessage.substringBeforeLast(': []');
            } else {
                errorMessage = exp.getMessage();
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,errorMessage,''));
        }
        return pr;
    }
    
    // Creates new write off record and redirect user for creating additional writeoff record.
    public pageReference saveAndNewWriteOff(){
        pr = null;
        try{
            insert writeOffObj; 
            pr = new pageReference('/apex/CloneWriteOffObj_Page');
            pr.getParameters().put('id',writeOffObj.id);
            pr.setRedirect(true);            
        }Catch(Exception exp){
            if(exp.getMessage().indexOf('FIELD_CUSTOM_VALIDATION_EXCEPTION,')>=0){
                errorMessage = exp.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,');
                errorMessage = errorMessage.substringBeforeLast(': []');
            } else {
                errorMessage = exp.getMessage();
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,errorMessage,''));
        }
        return pr;
    }
}